# -*- coding: utf-8 -*-
"""
Rule catalog, group 10: HotelArmor, BarArmor, FirearmArmor, CasinoArmor and
ShopArmor. Ten rules per industry, costliest first. None of these industries
has a detailed check yet, so no rule sets `method`.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 46. HOTELARMOR (hotels, motels and short-term lodging) ---
    46: [
        Rule(key="total_price_upfront", title="Total price shown with all fees",
             cost="Hidden resort and service fees draw FTC civil penalties and consumer class actions, and force refunds.",
             citation="FTC Rule on Unfair or Deceptive Fees, 16 CFR Part 464", kind="required",
             input="Does every rate you advertise or quote show the total price, including all mandatory fees, more prominently than other prices?",
             sample=False,
             action="Fold every mandatory fee into the displayed rate on your site, OTAs and quotes before taking more bookings."),
        Rule(key="accessible_booking", title="Accessible rooms bookable online",
             cost="Reservation systems that hide or release accessible rooms are a frequent basis for ADA lawsuits and DOJ settlements.",
             citation="ADA, 28 CFR 36.302(e)(1)", kind="required",
             input="Can guests book accessible rooms the same way as other rooms, with the accessibility features described and the room held once booked?",
             sample=True,
             action="Update the booking engine to list accessible features, hold booked accessible rooms and block them from general sale."),
        Rule(key="vgb_drain_covers", title="Pool and spa drain covers compliant",
             cost="Non-compliant drain covers force pool closures and expose the property to entrapment injury lawsuits.",
             citation="Virginia Graeme Baker Pool and Spa Safety Act, 15 U.S.C. 8003; 16 CFR Part 1450", kind="required",
             input="Does every pool and spa drain have a cover certified to the current VGB standard, within its expiration date?",
             sample=True,
             action="Close the pool or spa until the drain covers are replaced with certified ones."),
        Rule(key="pool_free_chlorine", title="Pool free chlorine level",
             cost="Low disinfectant is a common health-inspection closure and a source of illness claims from guests.",
             citation="State pool codes vary; CDC Model Aquatic Health Code common minimum", kind="min",
             input="Latest free chlorine reading in the pool", unit="ppm", limit=1.0, warn=1.5, policy=True,
             sample=0.8,
             action="Close the pool, raise free chlorine to at least the minimum and retest before reopening."),
        Rule(key="fire_alarm_annual_test", title="Fire alarm system tested yearly",
             cost="An overdue fire alarm test is a fire-marshal citation and can void insurance coverage after a fire.",
             citation="NFPA 72 as adopted by the local fire code", kind="max",
             input="Days since the fire alarm system's last annual inspection and test", unit="days", limit=365, warn=335, policy=True,
             sample=340,
             action="Book a licensed fire alarm contractor to inspect and test the system now."),
        Rule(key="guest_room_smoke_alarms", title="Smoke alarm in every guest room",
             cost="Missing guest-room smoke detection loses federal travel business and is a fire code violation with high liability after a fire.",
             citation="Hotel and Motel Fire Safety Act, 15 U.S.C. 2224(a); local fire code", kind="required",
             input="Does every guest room have a working hard-wired smoke alarm, checked on the room inspection schedule?",
             sample=True,
             action="Take rooms without a working smoke alarm out of service until one is installed and tested."),
        Rule(key="co_alarms", title="Carbon monoxide alarms installed",
             cost="Carbon monoxide incidents in guest rooms lead to wrongful-death lawsuits and state penalties where alarms are required.",
             citation="State law varies; many states require CO alarms in lodging with fuel-burning appliances", kind="required",
             input="Are carbon monoxide alarms installed and working wherever your state requires them (rooms near fuel-burning appliances or garages)?",
             sample=True, policy=True,
             action="Install and test CO alarms in every required area and move guests out of affected rooms until done."),
        Rule(key="no_card_data_stored", title="No card security codes stored",
             cost="Stored card data turns a breach into card-brand fines, forensic costs and loss of the ability to take cards.",
             citation="PCI DSS v4.0 Requirement 3.3.1", kind="forbidden",
             input="Are card security codes (CVV) or full magnetic-stripe data kept anywhere after authorization, including paper or email?",
             sample=False, policy=True,
             action="Purge stored security codes and stripe data now and stop collecting cards by email or paper forms."),
        Rule(key="legionella_plan", title="Legionella water management plan",
             cost="Legionnaires' disease outbreaks traced to hotel water systems lead to closures and large injury and wrongful-death claims.",
             citation="ANSI/ASHRAE Standard 188; CDC water management toolkit", kind="required",
             input="Is there a written water management plan for Legionella covering hot tubs, cooling towers and hot water, with logged checks?",
             sample=False, policy=True,
             action="Adopt a water management plan, set temperature and disinfectant checks, and log them starting today."),
        Rule(key="housekeeping_hazcom", title="Housekeeping chemical training",
             cost="Hazard communication is frequently cited by OSHA and exposes the property to penalties and injury claims.",
             citation="OSHA 29 CFR 1910.1200(h)", kind="required",
             input="Has every housekeeping and maintenance worker been trained on the chemicals they use before first working with them?",
             sample=True,
             action="Train untrained staff on the safety data sheets and labels for their chemicals before their next shift."),
    ],

    # --- 47. BARARMOR (bars, breweries and liquor retailers) ---
    47: [
        Rule(key="no_sales_under_21", title="No alcohol sold to minors",
             cost="Sales to minors bring license suspension or revocation, fines, and dram shop liability if the minor causes harm.",
             citation="State liquor law; minimum drinking age 21 under 23 U.S.C. 158", kind="forbidden",
             input="Was alcohol sold or served to anyone under 21, including in a compliance check?",
             sample=False,
             action="Retrain every server and cashier on ID checks, scan IDs at the door and report the incident as your state requires."),
        Rule(key="no_service_intoxicated", title="No service to intoxicated guests",
             cost="Overserving is the core of dram shop lawsuits after drunk-driving crashes and can cost the liquor license.",
             citation="State liquor and dram shop laws vary", kind="forbidden",
             input="Was alcohol served to a guest who was visibly intoxicated?",
             sample=False, policy=True,
             action="Cut the guest off, arrange a safe ride, write an incident report and review the shift with staff."),
        Rule(key="liquor_license_expiry", title="Liquor license renewed on time",
             cost="Selling on an expired license means closing the bar or paying penalties, with lost revenue every night it lapses.",
             citation="State liquor licensing law varies", kind="min",
             input="Days until the liquor license expires", unit="days", limit=0, warn=45, policy=True,
             sample=21,
             action="Stop alcohol sales until the license is renewed; file the renewal and fees with the state today."),
        Rule(key="server_training_current", title="Server alcohol training current",
             cost="Untrained servers raise dram shop exposure, can void liquor liability coverage and are cited in states that mandate training.",
             citation="State responsible beverage service laws vary", kind="max",
             input="Days since the oldest server certificate on staff was issued", unit="days", limit=1095, warn=1005, policy=True,
             sample=400,
             action="Schedule recertification for every server whose certificate is out of date before their next shift."),
        Rule(key="hours_of_sale", title="Alcohol sold only in legal hours",
             cost="After-hours sales are a common liquor-board citation leading to fines and license suspensions.",
             citation="State and local liquor law varies", kind="forbidden",
             input="Was alcohol sold or served outside the legal hours of sale?",
             sample=False, policy=True,
             action="Lock the POS for alcohol at last call and brief closing staff."),
        Rule(key="tip_pool_no_managers", title="Managers kept out of the tip pool",
             cost="Managers taking tips leads to back-wage and liquidated-damage lawsuits, often brought as collective actions.",
             citation="FLSA, 29 U.S.C. 203(m)(2)(B); 29 CFR 531.54", kind="forbidden",
             input="Did any owner, manager or supervisor keep part of employees' tips or the tip pool?",
             sample=False,
             action="Remove managers from the tip pool and repay the tips they received to the employees."),
        Rule(key="federal_excise_tax_filed", title="Federal excise tax filed on time",
             cost="Late excise tax returns and payments bring TTB penalties and interest and can put a brewer's permit at risk.",
             citation="26 U.S.C. 5051; 27 CFR Part 25 (brewers)", kind="required",
             input="For breweries: are federal excise tax returns filed and paid by each due date?",
             sample=True,
             action="File and pay the overdue excise tax return now and set reminders for each filing period."),
        Rule(key="label_approval_cola", title="Label approval before interstate sale",
             cost="Products shipped across state lines without label approval can be held or pulled, costing inventory and distribution.",
             citation="FAA Act, 27 U.S.C. 205(e); 27 CFR Parts 4, 5 and 7", kind="required",
             input="Does every label on product sold across state lines have an approved TTB Certificate of Label Approval (COLA)?",
             sample=True,
             action="Hold out-of-state shipments of that product and submit the label to TTB for approval."),
        Rule(key="licensed_wholesaler_only", title="Alcohol bought from licensed sources",
             cost="Buying from retail stores or unlicensed sellers breaks state three-tier rules and can lead to license loss.",
             citation="State three-tier distribution laws vary", kind="required",
             input="Is every bottle, keg and case bought from a licensed wholesaler or distributor?",
             sample=True, policy=True,
             action="Stop buying from unlicensed sources and pull any product bought outside licensed channels."),
        Rule(key="no_tied_house_inducements", title="No supplier inducements",
             cost="Taking free goods, equipment or cash from suppliers to push their brands violates trade practice rules for both sides.",
             citation="FAA Act, 27 U.S.C. 205(b); 27 CFR Part 6; state tied-house laws", kind="forbidden",
             input="Did a supplier give the business free goods, equipment, services or payments in exchange for carrying or promoting its brands?",
             sample=False,
             action="Decline or return the inducement and document it; check your state's tied-house rules before accepting anything."),
    ],

    # --- 48. FIREARMARMOR (federal firearms licensees / gun dealers) ---
    48: [
        Rule(key="form_4473_complete", title="Form 4473 fully completed",
             cost="Incomplete or wrong Forms 4473 are frequently cited at ATF inspections, and willful violations lead to license revocation.",
             citation="18 U.S.C. 923(g); 27 CFR 478.124(c)", kind="required",
             input="Was the Form 4473 fully completed, checked against the buyer's ID and signed by the buyer and dealer before the transfer?",
             sample=False,
             action="Hold the transfer and have the buyer and dealer complete and correct the form before handing over the firearm."),
        Rule(key="nics_before_transfer", title="Background check before transfer",
             cost="Transferring without a NICS check or after a denial is a serious violation that can end in license revocation and prosecution.",
             citation="Brady Act, 18 U.S.C. 922(t)(1)", kind="forbidden",
             input="Was a firearm transferred without a NICS 'proceed', without waiting the 3 business days after no response, or after a denial?",
             sample=False,
             action="Stop transfers without a proceed or elapsed wait, and report any transfer after a denial to ATF."),
        Rule(key="acquisition_entry", title="Acquisition logged next business day",
             cost="Late or missing acquisition entries are frequently cited at ATF inspections and make firearms untraceable.",
             citation="27 CFR 478.125(e)", kind="max",
             input="Business days since a firearm was received without an entry in the acquisition and disposition record",
             unit="business days", limit=1, warn=1, sample=0,
             action="Enter every unrecorded firearm in the A&D record now."),
        Rule(key="disposition_entry", title="Disposition logged within 7 days",
             cost="Missing disposition entries are a common ATF finding and can support a revocation case when repeated.",
             citation="27 CFR 478.125(e)", kind="max",
             input="Days since a firearm left inventory without a disposition entry", unit="days", limit=7, warn=5,
             sample=9,
             action="Record the disposition today with the buyer's name and address or the Form 4473 serial number."),
        Rule(key="multiple_handgun_report", title="Multiple handgun sale reported",
             cost="Unfiled multiple sales reports are a recurring ATF citation that counts toward willfulness in revocation cases.",
             citation="18 U.S.C. 923(g)(3)(A); 27 CFR 478.126a", kind="max",
             input="Business days since a sale of two or more handguns to one buyer within five business days, without filing ATF Form 3310.4",
             unit="business days", limit=0, sample=0,
             action="File ATF Form 3310.4 with ATF and the chief local law enforcement officer today."),
        Rule(key="theft_loss_48h", title="Theft or loss reported in 48 hours",
             cost="Late theft and loss reports are a violation ATF cites and delay recovery of guns that may be used in crimes.",
             citation="18 U.S.C. 923(g)(6); 27 CFR 478.39a", kind="max",
             input="Hours since a firearm theft or loss was discovered, without reporting to ATF and local police", unit="h",
             limit=48, warn=36, sample=12,
             action="Report the missing firearm to ATF (Form 3310.11) and local police now."),
        Rule(key="ffl_license_expiry", title="FFL renewed before it expires",
             cost="Selling on an expired license is illegal and forces the shop to stop firearm sales until renewed.",
             citation="18 U.S.C. 923; 27 CFR 478.45", kind="min",
             input="Days until the federal firearms license expires", unit="days", limit=0, warn=60,
             sample=45,
             action="Stop firearm sales until renewed; submit the renewal application to ATF now."),
        Rule(key="no_prohibited_transfer", title="No sale to a prohibited person",
             cost="Selling to someone the dealer has reason to believe is prohibited is a felony and grounds for revocation and civil suits.",
             citation="18 U.S.C. 922(d)", kind="forbidden",
             input="Did a buyer answer yes to a prohibited-person question, or show signs of a straw purchase, and still receive the firearm?",
             sample=False,
             action="Refuse the sale, document the reasons, and contact ATF about a suspected straw purchase."),
        Rule(key="safety_device_provided", title="Safety device with every handgun",
             cost="Selling a handgun without a storage or safety device is a violation that can bring license suspension and civil penalties.",
             citation="18 U.S.C. 922(z)(1)", kind="required",
             input="Does every handgun sale include a secure gun storage or safety device?",
             sample=True,
             action="Provide a lock or storage device with the handgun before the buyer leaves."),
        Rule(key="no_out_of_state_handgun", title="No handgun sales to other states",
             cost="Handgun sales to out-of-state residents are illegal and are treated as serious violations at inspection.",
             citation="18 U.S.C. 922(b)(3)", kind="forbidden",
             input="Was a handgun sold directly to a resident of another state?",
             sample=False,
             action="Stop the sale and ship the handgun to a licensed dealer in the buyer's state instead."),
    ],

    # --- 49. CASINOARMOR (casinos and card clubs) ---
    49: [
        Rule(key="ctr_filed_15_days", title="CTR filed within 15 days",
             cost="Missed CTRs are a core BSA failure that brings FinCEN penalties and enforcement actions against casinos.",
             citation="31 CFR 1021.311; 31 CFR 1010.306(a)(1)", kind="max",
             input="Days since a patron's cash in or cash out went over $10,000 in a gaming day, without filing a CTR", unit="days",
             limit=15, warn=12, sample=3,
             action="File the Currency Transaction Report with FinCEN now."),
        Rule(key="ctr_aggregation", title="Cash totals added up per patron",
             cost="Failing to aggregate a patron's cash transactions misses required CTRs and is a common finding in casino BSA exams.",
             citation="31 CFR 1021.313", kind="required",
             input="Are all cash transactions by the same patron in a gaming day added together (cage, pit, slots) to check the $10,000 threshold?",
             sample=True,
             action="Turn on cross-department aggregation in the casino management system and review today's gaming day."),
        Rule(key="sar_30_days", title="SAR filed within 30 days",
             cost="Late or missing suspicious activity reports are a common basis for FinCEN civil money penalties against casinos.",
             citation="31 CFR 1021.320(a)(2), (b)(3)", kind="max",
             input="Days since suspicious activity of $5,000 or more was detected, without filing a SAR", unit="days",
             limit=30, warn=25, sample=34,
             action="File the SAR with FinCEN today and document why it was late."),
        Rule(key="aml_independent_test", title="Independent AML test",
             cost="An overdue independent test is a standard BSA exam finding and weakens the casino's defense in an enforcement action.",
             citation="31 CFR 1021.210(b)(2)(ii); frequency is risk-based, commonly yearly", kind="max",
             input="Days since the last independent test of the AML program", unit="days", limit=365, warn=335, policy=True,
             sample=400,
             action="Engage an independent reviewer to test the AML program now."),
        Rule(key="aml_training", title="BSA training for gaming staff",
             cost="Untrained cage, pit and slot staff miss reportable activity, a frequent root cause cited in casino enforcement actions.",
             citation="31 CFR 1021.210(b)(2)(iii)", kind="required",
             input="Has every cage, pit, slot and host employee completed BSA/AML training?",
             sample=True,
             action="Train untrained employees before their next shift on the floor or cage."),
        Rule(key="w2g_issued", title="W-2G issued for reportable jackpots",
             cost="Missing W-2G forms bring IRS penalties per form and can trigger IRS gaming compliance examinations.",
             citation="26 U.S.C. 6041; 26 CFR 7.6041-1; IRS Instructions for Forms W-2G", kind="required",
             input="Is a Form W-2G issued for every slot, bingo, keno or other win at or above the current IRS reporting threshold?",
             sample=True,
             action="Issue the missing W-2Gs and update payout procedures to the current IRS thresholds."),
        Rule(key="ofac_screening", title="Patrons screened against OFAC",
             cost="Paying or extending credit to a sanctioned person brings OFAC penalties even without intent.",
             citation="31 CFR Part 501; OFAC sanctions regulations", kind="required",
             input="Are patrons screened against the OFAC sanctions list before large payouts, wires or markers?",
             sample=True,
             action="Screen the patron now and hold the payout if there is a possible match."),
        Rule(key="self_exclusion_honored", title="Self-excluded patrons kept out",
             cost="Letting self-excluded patrons gamble or sending them marketing brings state gaming fines and patron lawsuits.",
             citation="State gaming law and self-exclusion programs vary", kind="forbidden",
             input="Did a self-excluded patron gamble, receive comps or get marketing?",
             sample=False, policy=True,
             action="Remove the patron, forfeit winnings as state rules require, and purge them from marketing lists."),
        Rule(key="no_underage_gambling", title="No underage gambling",
             cost="Underage gambling is a serious state gaming violation that brings fines and puts the gaming license at risk.",
             citation="State gaming law sets the minimum age", kind="forbidden",
             input="Was anyone under the legal gambling age allowed to gamble or receive a payout?",
             sample=False, policy=True,
             action="Remove the minor, withhold winnings as state rules require, report to the regulator and retrain security."),
        Rule(key="bsa_records_5_years", title="BSA records kept five years",
             cost="Missing records leave the casino unable to prove compliance during exams and can support penalties.",
             citation="31 CFR 1010.430(d); 31 CFR 1021.410", kind="required",
             input="Are CTRs, SARs, patron identification and required transaction records kept for at least five years?",
             sample=True,
             action="Restore or rebuild missing records and set a five-year retention hold."),
    ],

    # --- 50. SHOPARMOR (e-commerce and online retailers) ---
    50: [
        Rule(key="ship_or_notify_30_days", title="Ship on time or offer cancellation",
             cost="Late shipments without notice break the FTC Mail Order Rule, leading to civil penalties, refunds and chargebacks.",
             citation="FTC Mail, Internet, or Telephone Order Merchandise Rule, 16 CFR 435.2", kind="max",
             input="Days since a paid order with no promised ship date, without shipping it or sending a delay notice with a cancellation option",
             unit="days", limit=30, warn=25, sample=33,
             action="Ship now or send a delay notice offering the right to cancel for a prompt refund."),
        Rule(key="rosca_subscriptions", title="Clear consent and easy cancel",
             cost="Subscriptions without clear consent or easy cancellation bring FTC actions, refunds and chargebacks.",
             citation="ROSCA, 15 U.S.C. 8403", kind="required",
             input="Do subscribers see all terms before paying, give express consent to recurring charges, and have a simple way to cancel?",
             sample=False,
             action="Add a clear recurring-charge disclosure and consent checkbox, and a one-step online cancel."),
        Rule(key="no_fake_reviews", title="No fake or suppressed reviews",
             cost="Fake, bought or suppressed reviews bring FTC civil penalties per violation and damage marketplace standing.",
             citation="FTC Rule on Consumer Reviews and Testimonials, 16 CFR Part 465", kind="forbidden",
             input="Does the store post fake reviews, pay only for positive reviews, or hide negative ones?",
             sample=False,
             action="Remove fake or incentivized-positive reviews and publish all genuine reviews."),
        Rule(key="endorsement_disclosure", title="Influencer ties disclosed",
             cost="Undisclosed paid endorsements lead to FTC actions against both the brand and its influencers.",
             citation="FTC Endorsement Guides, 16 CFR 255.5", kind="required",
             input="Do all paid influencers and affiliates clearly disclose their connection to the brand in each post?",
             sample=True,
             action="Require clear disclosures in every sponsored post and pause partners who do not comply."),
        Rule(key="childrens_product_certificate", title="Children's products certified",
             cost="Selling children's products without third-party testing and certificates leads to CPSC penalties, recalls and delisting.",
             citation="CPSIA; 15 U.S.C. 2063(a)(2); 16 CFR Parts 1107 and 1110", kind="required",
             input="Does every children's product have a Children's Product Certificate based on testing by a CPSC-accepted lab?",
             sample=True,
             action="Stop selling uncertified children's products until they are tested and certified."),
        Rule(key="prop65_warning", title="Prop 65 warning for California",
             cost="Missing Prop 65 warnings are a frequent target of private enforcement suits, with settlements and legal fees.",
             citation="Cal. Health and Safety Code 25249.6; Cal. Code Regs. tit. 27, 25602", kind="required",
             input="Do products sold to California that expose buyers to listed chemicals show a Prop 65 warning on the product page and package?",
             sample=True,
             action="Add the required warning to the product page and packaging before more California sales."),
        Rule(key="sales_tax_nexus", title="Sales tax registration by state",
             cost="Crossing a state's economic nexus threshold without collecting tax leaves the seller owing back taxes, penalties and interest.",
             citation="South Dakota v. Wayfair (2018); state economic nexus thresholds vary", kind="max",
             input="This year's sales into your largest unregistered state, as a percent of that state's economic nexus threshold",
             unit="%", limit=100, warn=85, policy=True, sample=94,
             action="Register with the state and start collecting sales tax on orders shipped there."),
        Rule(key="email_optout_10_days", title="Unsubscribes honored in 10 days",
             cost="Emailing people after they unsubscribe brings FTC penalties per email under CAN-SPAM.",
             citation="CAN-SPAM Act, 15 U.S.C. 7704(a)(4)", kind="max",
             input="Business days since an unsubscribe request while marketing emails are still being sent", unit="business days",
             limit=10, warn=8, sample=3,
             action="Suppress the address in every sending tool now."),
        Rule(key="made_in_usa_claims", title="Made in USA claims backed up",
             cost="Unqualified Made in USA claims on imported goods bring FTC civil penalties and relabeling costs.",
             citation="FTC Made in USA Labeling Rule, 16 CFR Part 323", kind="forbidden",
             input="Is any product labeled Made in USA without all or virtually all of it made in the United States?",
             sample=False,
             action="Remove or qualify the claim (for example, Assembled in USA) on labels and listings."),
        Rule(key="sms_marketing_consent", title="Marketing texts only with consent",
             cost="Texting without prior express written consent brings TCPA class actions with statutory damages per message.",
             citation="TCPA, 47 U.S.C. 227; 47 CFR 64.1200(a)(2)", kind="required",
             input="Do marketing texts go only to people who gave prior express written consent, with opt-outs honored?",
             sample=True,
             action="Stop texting contacts without documented written consent and process all opt-outs."),
    ],
}
