# -*- coding: utf-8 -*-
"""
OmniArmor rule catalog, group 5: industries 21-25.

21 FactoryArmor, 22 PharmaArmor, 23 MineArmor, 24 PortArmor, 25 GeneArmor.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 21. FACTORYARMOR (MANUFACTURING) ---
    21: [
        Rule(key="loto_isolation", title="Lockout/tagout before servicing",
             cost="Lockout/tagout is frequently cited by OSHA; failures bring citations, amputation and death lawsuits, and line shutdowns.",
             citation="29 CFR 1910.147(d)(6) and (f)(3)", kind="required",
             input="Has energy isolation been verified and has every worker on the job applied a personal lock?",
             sample=True,
             action="Stop servicing; verify isolation and have every worker apply a personal lock first.",
             method="factory_armor_loto_gate"),
        Rule(key="hazcom_training", title="Hazard communication training",
             cost="Hazard communication is frequently cited by OSHA, and untrained workers lead to citations, chemical injuries and claims.",
             citation="29 CFR 1910.1200(h)(1)", kind="required",
             input="Has every worker exposed to hazardous chemicals been trained on them before starting that work?",
             sample=False,
             action="Keep untrained workers away from the chemicals and train them on labels, SDSs and hazards now."),
        Rule(key="machine_guarding", title="Machine guards in place",
             cost="Missing guards are frequently cited by OSHA and cause amputations, bringing penalties, lawsuits and lost production.",
             citation="29 CFR 1910.212(a)(1) and (a)(3)(ii)", kind="forbidden",
             input="Is any machine running with its point-of-operation guard removed or bypassed?",
             sample=True,
             action="Stop the machine and lock it out until the guard is reinstalled and working."),
        Rule(key="forklift_evaluation", title="Forklift operator evaluation",
             cost="Powered industrial truck violations are frequently cited by OSHA, and forklift crashes cause serious injuries, claims and damage.",
             citation="29 CFR 1910.178(l)(4)(iii)", kind="max",
             input="Days since the operator's last forklift performance evaluation",
             unit="days", limit=1095, warn=1000, sample=1040,
             action="Remove the operator from forklift duty until a performance evaluation is completed."),
        Rule(key="respirator_fit_test", title="Respirator fit test",
             cost="Respiratory protection is frequently cited by OSHA, and poorly fitted respirators expose workers to illness claims.",
             citation="29 CFR 1910.134(f)(2)", kind="max",
             input="Days since the worker was last fit tested on the respirator they wear",
             unit="days", limit=365, warn=330, sample=400,
             action="Keep the worker out of areas needing a respirator until a new fit test is passed."),
        Rule(key="fall_protection", title="Fall protection at 4 feet",
             cost="Walking-working surface violations are commonly cited by OSHA, and falls cause serious injuries, penalties and lawsuits.",
             citation="29 CFR 1910.28(b)(1)(i)", kind="forbidden",
             input="Is any worker exposed to an unprotected side or edge 4 feet or more above a lower level?",
             sample=False,
             action="Move the worker back and install guardrails, a safety net or personal fall protection before work resumes."),
        Rule(key="electrical_working_space", title="Clear space at electrical panels",
             cost="Electrical violations are frequently cited by OSHA, and blocked panels delay shutoff and worsen shock and arc injuries.",
             citation="29 CFR 1910.303(g)(1)", kind="forbidden",
             input="Is the working space in front of any electrical panel or equipment blocked or used for storage?",
             sample=False,
             action="Clear the working space in front of the panel now and mark it to keep it clear."),
        Rule(key="noise_exposure", title="Noise exposure limit",
             cost="Noise violations bring OSHA citations, and hearing loss is a common and costly workers' compensation claim.",
             citation="29 CFR 1910.95(b)(1) and (c)(1)", kind="max",
             input="Worker's 8-hour time-weighted average noise exposure",
             unit="dBA", limit=90, warn=85, sample=87,
             action="Use engineering or administrative controls, require hearing protection and enroll workers in hearing conservation."),
        Rule(key="severe_injury_report", title="Severe injury report to OSHA",
             cost="Late or missing reports bring OSHA penalties and often trigger a full inspection of the plant.",
             citation="29 CFR 1904.39(a)(2)", kind="max",
             input="Hours since learning of a work-related hospitalization, amputation or eye loss, without reporting it to OSHA",
             unit="h", limit=24, warn=12, sample=30,
             action="Report to OSHA now by phone or online. A work-related death must be reported within 8 hours."),
        Rule(key="osha_300_log", title="Record injury on OSHA 300 log",
             cost="Late or missing 300 log entries are commonly cited by OSHA and can add recordkeeping penalties to any inspection.",
             citation="29 CFR 1904.29(b)(3)", kind="max",
             input="Calendar days since learning of a recordable injury or illness, without entering it on the OSHA 300 log",
             unit="days", limit=7, warn=5, sample=9,
             action="Enter the case on the OSHA 300 log and complete the 301 incident report now."),
    ],

    # --- 22. PHARMAARMOR (PHARMACEUTICALS) ---
    22: [
        Rule(key="part11_signature", title="Part 11 electronic signatures",
             cost="Part 11 and data integrity gaps are common in FDA warning letters and can hold up batch release and product approvals.",
             citation="21 CFR 11.50 and 11.200(a)(1)", kind="required",
             input="Does every electronic signature show the signer's name, date/time and meaning, and use two distinct ID components?",
             sample=False,
             action="Do not release the record; fix the signature so name, date/time and meaning show and two ID components are used.",
             method="pharma_armor_cfr_signature"),
        Rule(key="oos_investigation", title="OOS results investigated",
             cost="Inadequate OOS investigations are frequently cited in FDA 483s and warning letters and can lead to recalls.",
             citation="21 CFR 211.192", kind="required",
             input="Has every out-of-specification result or unexplained discrepancy been fully investigated and documented before batch release?",
             sample=True,
             action="Hold the batch; complete and document the investigation, extend it to related batches, and record conclusions."),
        Rule(key="audit_trail", title="Lab data audit trail",
             cost="Deleted or altered data is a frequent basis for FDA warning letters, import alerts and consent decrees.",
             citation="21 CFR 11.10(e); 21 CFR 211.68(b) and 211.194(a)", kind="forbidden",
             input="Can any user delete or overwrite laboratory or production data without an audit trail record?",
             sample=True,
             action="Lock down user rights, turn on audit trails, and review affected data before relying on it."),
        Rule(key="instrument_calibration", title="Instrument calibration due",
             cost="Overdue calibration is a common FDA 483 finding and can put every result from the instrument, and the batches they released, in doubt.",
             citation="21 CFR 211.68(a) and 211.160(b)(4)", kind="min",
             input="Days until the instrument's next calibration due date under the written program (negative if overdue)",
             unit="days", limit=0, warn=14, sample=7,
             action="Tag the instrument out of use, calibrate it, and assess results produced since the due date."),
        Rule(key="equipment_cleaning", title="Equipment cleaning procedures",
             cost="Cleaning failures cause cross-contamination, recalls and FDA warning letters.",
             citation="21 CFR 211.67(b) and 211.182", kind="required",
             input="Are written equipment cleaning procedures in place, followed, and recorded for each cleaning?",
             sample=True,
             action="Quarantine product made on the equipment and clean it under a written, recorded procedure."),
        Rule(key="annual_product_review", title="Annual product quality review",
             cost="Skipped annual reviews are a routine FDA 483 finding and let quality trends go unnoticed until they cause recalls.",
             citation="21 CFR 211.180(e)", kind="max",
             input="Days since the last annual review of each product's quality records",
             unit="days", limit=365, warn=330, sample=345,
             action="Complete the review of batches, complaints, recalls and investigations and record any corrective actions."),
        Rule(key="dscsa_illegitimate_notice", title="DSCSA illegitimate product notice",
             cost="Late notice of illegitimate product violates DSCSA, can bring FDA enforcement, and lets harmful product reach patients.",
             citation="21 U.S.C. 360eee-1(b)(4)(B) (FD&C Act 582(b)(4)(B))", kind="max",
             input="Hours since determining a product is illegitimate, without notifying FDA and affected trading partners",
             unit="h", limit=24, warn=18, sample=10,
             action="Notify FDA (Form 3911) and affected trading partners now, and quarantine the product."),
        Rule(key="adverse_event_15_day", title="15-day adverse event report",
             cost="Late safety reports draw FDA warning letters and raise product liability exposure.",
             citation="21 CFR 314.80(c)(1)(i)", kind="max",
             input="Calendar days since receiving a serious and unexpected adverse drug experience, without a report to FDA",
             unit="days", limit=15, warn=10, sample=12,
             action="Submit the 15-day alert report to FDA now and document the follow-up investigation."),
        Rule(key="field_alert_report", title="Field alert report",
             cost="Late field alerts draw FDA enforcement and let defective drugs stay on the market, raising recall and liability costs.",
             citation="21 CFR 314.81(b)(1)", kind="max",
             input="Working days since learning of a distributed product quality problem (e.g., contamination, label mix-up), without a field alert",
             unit="days", limit=3, warn=2, sample=4,
             action="File the field alert report with the FDA district office now, even if the investigation is still open."),
        Rule(key="dea_biennial_inventory", title="DEA biennial inventory",
             cost="Controlled substance recordkeeping failures bring DEA civil penalties and can cost the company its registration.",
             citation="21 CFR 1304.11(c)", kind="max",
             input="Days since the last complete controlled substance inventory",
             unit="days", limit=730, warn=670, sample=500,
             action="Take a complete inventory of all controlled substances now and keep the record for DEA inspection."),
    ],

    # --- 23. MINEARMOR (MINING & MINERALS) ---
    23: [
        Rule(key="part46_new_miner", title="New miner training",
             cost="Untrained miners draw MSHA citations and withdrawal orders that remove them from work, and raise accident risk.",
             citation="30 CFR 46.5", kind="min",
             input="Hours of new-miner training completed (4 h before starting work, 24 h within 90 days)",
             unit="h", limit=4, warn=23, sample=2,
             action="Keep the miner off the job until 4 hours of training are done; finish all 24 hours within 90 days.",
             method="mine_armor_part46_gate"),
        Rule(key="annual_refresher", title="Annual refresher training",
             cost="Missed refresher training brings MSHA citations and orders to withdraw the miner from the mine.",
             citation="30 CFR 46.8 (Part 48 mines: 30 CFR 48.8 and 48.28)", kind="max",
             input="Days since the miner's last 8-hour annual refresher training",
             unit="days", limit=365, warn=330, sample=380,
             action="Remove the miner from work until the 8-hour refresher training is completed."),
        Rule(key="workplace_exam", title="Workplace exam each shift",
             cost="Missed workplace exams are frequently cited by MSHA and let hazards go unfixed until someone is hurt.",
             citation="30 CFR 56.18002(a)", kind="required",
             input="Was each working place examined for hazards by a competent person before work began this shift?",
             sample=True,
             action="Stop work in the area until a competent person examines it and records the exam."),
        Rule(key="accident_notice", title="Call MSHA within 15 minutes",
             cost="Late accident notice brings MSHA penalties, and disturbing the scene before MSHA arrives can lead to further enforcement.",
             citation="30 CFR 50.10", kind="max",
             input="Minutes since a reportable accident was known, without calling MSHA",
             unit="min", limit=15, warn=10, sample=8,
             action="Call MSHA now at its toll-free accident number and preserve the scene."),
        Rule(key="fire_extinguisher_inspection", title="Monthly fire extinguisher check",
             cost="Uninspected extinguishers are a common MSHA citation and may fail when a mobile equipment or plant fire starts.",
             citation="30 CFR 56.4201(a)(1)", kind="max",
             input="Days since the fire extinguisher's last monthly visual inspection",
             unit="days", limit=31, warn=25, sample=20,
             action="Inspect the extinguisher now; replace or recharge it if it is not fully charged and operable."),
        Rule(key="noise_exposure", title="Noise exposure limit",
             cost="Noise overexposure brings MSHA citations, and hearing loss leads to compensation claims.",
             citation="30 CFR 62.130 (action level 30 CFR 62.120)", kind="max",
             input="Miner's 8-hour time-weighted average noise exposure",
             unit="dBA", limit=90, warn=85, sample=92,
             action="Use engineering and administrative controls, provide hearing protection and enroll the miner in hearing conservation."),
        Rule(key="machine_guarding", title="Moving machine parts guarded",
             cost="Guarding is frequently cited by MSHA, and unguarded conveyors and pulleys cause amputations and deaths.",
             citation="30 CFR 56.14107(a)", kind="forbidden",
             input="Is any exposed moving machine part that could injure a person missing its guard?",
             sample=False,
             action="Stop and lock out the machine until the guard is installed."),
        Rule(key="preshift_equipment", title="Mobile equipment pre-shift check",
             cost="Skipped pre-shift checks are frequently cited by MSHA, and defective haul trucks and loaders cause fatal accidents.",
             citation="30 CFR 56.14100(a)", kind="required",
             input="Was every piece of self-propelled mobile equipment checked for safety defects before use this shift?",
             sample=False,
             action="Park the equipment until the operator completes the check and any safety defects are fixed."),
        Rule(key="ground_control", title="Loose ground scaled or supported",
             cost="Ground falls cause serious injuries and deaths, bringing MSHA orders that close the area and penalties.",
             citation="30 CFR 56.3200", kind="forbidden",
             input="Is anyone working or traveling where hazardous loose or unstable ground has not been taken down or supported?",
             sample=False,
             action="Clear people from the area and post it until the ground is scaled or supported."),
        Rule(key="grounding_test", title="Electrical grounding test",
             cost="Untested grounding brings MSHA citations and can lead to fatal electrocutions.",
             citation="30 CFR 56.12028", kind="max",
             input="Days since grounding systems were tested for continuity and resistance",
             unit="days", limit=365, warn=330, sample=340,
             action="Test grounding continuity and resistance now and record the results."),
    ],

    # --- 24. PORTARMOR (PORT AUTHORITIES) ---
    24: [
        Rule(key="twic_access", title="TWIC for secure areas",
             cost="Access control failures draw Coast Guard civil penalties and can lead to orders suspending facility operations.",
             citation="33 CFR 101.514; 33 CFR 105.255", kind="required",
             input="Does every person entering a secure area hold a valid TWIC or have a TWIC-holding escort?",
             sample=False,
             action="Stop the person at the gate; allow entry only with a valid TWIC or an escort who holds one.",
             method="port_armor_twic_check"),
        Rule(key="security_drill", title="Quarterly security drill",
             cost="Missed drills are a common Coast Guard deficiency that can bring penalties and operating restrictions.",
             citation="33 CFR 105.220(b)", kind="max",
             input="Months since the last facility security drill",
             unit="months", limit=3, warn=2.5, sample=2,
             action="Run and record a security drill now covering an element of the facility security plan."),
        Rule(key="security_exercise", title="Annual security exercise",
             cost="Missing exercises is a Coast Guard deficiency that can bring penalties and operating restrictions.",
             citation="33 CFR 105.220(c)", kind="max",
             input="Months since the last facility security exercise (at least once each calendar year, never more than 18 months apart)",
             unit="months", limit=18, warn=15, sample=16,
             action="Schedule and hold a security exercise now and record it."),
        Rule(key="fsp_audit", title="Facility security plan audit",
             cost="An unaudited security plan draws Coast Guard enforcement and leaves gaps that can lead to breaches and suspended operations.",
             citation="33 CFR 105.415(b)", kind="max",
             input="Days since the facility security plan was last audited",
             unit="days", limit=365, warn=330, sample=200,
             action="Have the facility security officer complete the audit and submit any needed plan amendments."),
        Rule(key="marsec_change", title="MARSEC level change measures",
             cost="Failing to raise security when MARSEC rises can bring Coast Guard penalties and orders to stop cargo or vessel operations.",
             citation="33 CFR 105.230", kind="max",
             input="Hours since notice of a MARSEC level increase, without all of the new level's measures in place",
             unit="h", limit=12, warn=9, sample=4,
             action="Put the higher MARSEC measures in place now and report status to the Captain of the Port."),
        Rule(key="declaration_of_security", title="Declaration of Security",
             cost="Missing Declarations of Security draw Coast Guard penalties and can delay vessel operations.",
             citation="33 CFR 105.245", kind="required",
             input="When a Declaration of Security is required, was it signed before the vessel-facility interface began?",
             sample=True,
             action="Hold cargo or passenger operations until the vessel and facility security officers sign the Declaration."),
        Rule(key="nrc_security_report", title="Report security breaches",
             cost="Unreported breaches and suspicious activity bring Coast Guard penalties and harm the facility's standing with regulators.",
             citation="33 CFR 101.305", kind="required",
             input="Has every breach of security and suspicious activity been reported to the National Response Center without delay?",
             sample=False,
             action="Call the National Response Center now and record the report."),
        Rule(key="declaration_of_inspection", title="Declaration of Inspection",
             cost="Starting an oil transfer without a Declaration of Inspection brings Coast Guard penalties and raises spill cleanup and liability costs.",
             citation="33 CFR 156.150", kind="required",
             input="Before this oil transfer with a vessel began, was a Declaration of Inspection completed and signed by both persons in charge?",
             sample=True,
             action="Stop or hold the transfer until both persons in charge complete and sign the Declaration of Inspection."),
        Rule(key="oil_spill_plan", title="Oil spill response plan",
             cost="Handling oil without a response plan brings Coast Guard penalties and can stop transfers; spills add cleanup and liability costs.",
             citation="33 U.S.C. 1321(j)(5); 33 CFR Part 154, Subpart F", kind="required",
             input="Does the facility have a current oil spill response plan submitted to the Coast Guard and kept at the facility?",
             sample=True,
             action="Stop oil transfers until a compliant response plan is submitted and in place."),
        Rule(key="crane_exam", title="Crane annual examination",
             cost="Uncertified cranes draw OSHA citations and cannot be used, delaying vessel work; crane failures cause injuries and damage.",
             citation="29 CFR 1917.50", kind="max",
             input="Days since the crane's last annual certification examination",
             unit="days", limit=365, warn=330, sample=390,
             action="Take the crane out of service until an accredited agency examines and certifies it."),
    ],

    # --- 25. GENEARMOR (BIOTECH & GENETICS) ---
    25: [
        Rule(key="ibc_approval", title="IBC approval before research",
             cost="Noncompliance with the NIH Guidelines can lead NIH to suspend or end funding for the project or the whole institution.",
             citation="NIH Guidelines, Section III (III-A to III-D)", kind="required",
             input="For work under NIH Guidelines Sections III-A to III-D, did the IBC approve it before it began?",
             sample=False,
             action="Stop the experiment and submit it to the Institutional Biosafety Committee for approval.",
             method="gene_armor_nih_monitor"),
        Rule(key="select_agent_registration", title="Select agent registration",
             cost="Unregistered select agent work brings civil penalties, criminal charges and loss of the right to hold select agents.",
             citation="42 CFR 73.7; 7 CFR 331.7; 9 CFR 121.7", kind="forbidden",
             input="Is any select agent or toxin held, used or transferred outside a current registration?",
             sample=False,
             action="Secure the material, stop work, and contact the Federal Select Agent Program right away."),
        Rule(key="select_agent_loss_report", title="Select agent theft or loss",
             cost="Unreported theft, loss or release brings penalties and can lead to suspension or revocation of registration.",
             citation="42 CFR 73.19; 7 CFR 331.19; 9 CFR 121.19", kind="required",
             input="Has every theft, loss or release of a select agent or toxin been reported to CDC or APHIS right away?",
             sample=True,
             action="Report to CDC or APHIS now, and to law enforcement for theft, then file the written report."),
        Rule(key="bbp_training", title="Bloodborne pathogens training",
             cost="Missed training is a frequently cited part of the bloodborne pathogens standard, and untrained staff raise exposure and claim costs.",
             citation="29 CFR 1910.1030(g)(2)(ii)", kind="max",
             input="Days since the worker's last bloodborne pathogens training",
             unit="days", limit=365, warn=330, sample=150,
             action="Keep the worker from tasks with exposure risk until annual training is completed."),
        Rule(key="bbp_exposure_plan", title="Bloodborne exposure control plan",
             cost="Bloodborne pathogens is a frequently cited OSHA standard, and exposures lead to medical costs and claims.",
             citation="29 CFR 1910.1030(c)(1)(iv)", kind="max",
             input="Days since the exposure control plan was reviewed and updated",
             unit="days", limit=365, warn=330, sample=350,
             action="Review and update the exposure control plan now, including safer sharps devices."),
        Rule(key="chemical_hygiene_plan", title="Chemical hygiene plan review",
             cost="An outdated lab chemical hygiene plan draws OSHA citations and leaves staff exposed to chemical injuries.",
             citation="29 CFR 1910.1450(e)(4)", kind="max",
             input="Days since the chemical hygiene plan was reviewed",
             unit="days", limit=365, warn=330, sample=120,
             action="Review the chemical hygiene plan's effectiveness now and update it as needed."),
        Rule(key="bsc_certification", title="Biosafety cabinet certification",
             cost="Uncertified cabinets can expose staff and ruin samples, putting at risk inspections, grants and select agent registration.",
             citation="NSF/ANSI 49 standard; CDC/NIH BMBL (annual field certification)", kind="max",
             input="Days since the biosafety cabinet was field-certified",
             unit="days", limit=365, warn=330, policy=True, sample=400,
             action="Stop work in the cabinet and have it field-certified before use."),
        Rule(key="infectious_shipping", title="Infectious substance packaging",
             cost="Improper shipments bring DOT civil penalties, carrier refusals and lost samples.",
             citation="49 CFR 173.196 (Category A); 49 CFR 173.199 (Category B)", kind="required",
             input="Is every infectious substance shipment in the required triple packaging and marked and labeled correctly?",
             sample=True,
             action="Hold the shipment and repack it in compliant packaging with correct marks and labels."),
        Rule(key="hipaa_risk_analysis", title="HIPAA risk analysis",
             cost="Missing risk analyses are a frequent finding in HIPAA enforcement settlements, and genetic data breaches also bring lawsuits.",
             citation="45 CFR 164.308(a)(1)(ii)(A)", kind="required",
             input="Has a current security risk analysis been done for systems holding patients' genetic and health data?",
             sample=False,
             action="Complete a risk analysis of all systems with patient data and start fixing the risks it finds."),
        Rule(key="irb_approval", title="IRB approval for human research",
             cost="Research without IRB approval can lead to suspended federal funding, unusable data and lawsuits from participants.",
             citation="45 CFR 46.103 and 46.109", kind="required",
             input="Did an IRB approve this human subjects research before any participant was enrolled?",
             sample=True,
             action="Stop enrolling participants and submit the study to the IRB for review."),
    ],
}
