# -*- coding: utf-8 -*-
"""
Rule catalog, group 3: industries 11-15.

11 LuxuryArmor, 12 AgriArmor, 13 CopArmor, 14 FireArmor, 15 ParkArmor.
Each list holds the ten compliance failures that cost organizations in that
industry the most money. Rule 1 of each list matches the industry's detailed
check in OmniArmorPortal (see `method`).
"""

from omni_armor_rules.rule import Rule

RULES = {
    # ------------------------------------------------------------------
    # 11. LUXURYARMOR - luxury goods brands and retailers
    # ------------------------------------------------------------------
    11: [
        Rule(key="cites_permit", title="CITES permit for exotic materials",
             cost="Wildlife inspectors seize shipments of listed-species goods without permits, and the goods can be forfeited with civil or criminal penalties.",
             citation="CITES; 50 CFR Parts 14 and 23 (CITES permits plus USFWS Form 3-177 declaration)",
             kind="required",
             input="If this shipment contains a CITES-listed species (e.g. crocodile, python, ostrich, coral), are the CITES permits and Form 3-177 on file? (Yes if none.)",
             sample=False,
             action="Hold the shipment; do not import, export or sell it until valid CITES permits and the USFWS declaration are on file.",
             method="luxury_armor_cites_gate"),
        Rule(key="lacey_plant_declaration", title="Lacey Act plant declaration",
             cost="Goods made with illegally sourced wood or plants can be seized and forfeited even if the importer did not know, plus civil and criminal penalties.",
             citation="Lacey Act, 16 U.S.C. 3372(a) and 3372(f) (plant product import declaration)",
             kind="required",
             input="For imported goods with covered plant material (e.g. wood cases, handles, paper), was a Lacey Act declaration filed and legal harvest documented?",
             sample=True,
             action="Stop entry of the goods; file the plant declaration (PPQ 505 or electronic) and gather proof of species and country of harvest."),
        Rule(key="origin_marking", title="Country-of-origin marking",
             cost="CBP holds unmarked imports until they are marked or exported and can assess additional marking duties and penalties.",
             citation="19 U.S.C. 1304; 19 CFR Part 134",
             kind="required",
             input="Is every imported article (or its container, where allowed) legibly and permanently marked in English with its country of origin?",
             sample=False,
             action="Hold the goods; mark each article with its country of origin under CBP supervision before release or sale."),
        Rule(key="precious_metal_marking", title="Gold and silver quality marks",
             cost="Overstated karat or silver marks bring FTC deceptive-practice actions, Stamping Act penalties, refunds and consumer class actions.",
             citation="FTC Jewelry Guides, 16 CFR Part 23 (gold and silver sections); National Gold and Silver Stamping Act, 15 U.S.C. 291-300",
             kind="forbidden",
             input="Is any piece marked or described with a higher gold karat or silver fineness than assay testing shows?",
             sample=False,
             action="Pull the pieces from sale; correct the stamps and descriptions to the tested fineness and review supplier assays."),
        Rule(key="lab_grown_disclosure", title="Lab-grown and treated stone disclosure",
             cost="Selling lab-grown or treated stones as natural brings FTC actions, refunds, lost trade accounts and fraud claims.",
             citation="FTC Jewelry Guides, 16 CFR Part 23 (e.g. 23.12 on diamonds and the laboratory-created stone and treatment sections)",
             kind="required",
             input="Is every laboratory-grown or treated stone clearly and prominently disclosed as such in tags, listings and invoices?",
             sample=True,
             action="Stop selling the item; add a clear lab-grown or treatment disclosure to tags, listings and invoices before relisting."),
        Rule(key="fur_label", title="Fur product labeling",
             cost="Mislabeled or unlabeled fur brings FTC enforcement, civil penalties and retailer chargebacks or recalls from sale.",
             citation="Fur Products Labeling Act, 15 U.S.C. 69-69k; 16 CFR Part 301",
             kind="required",
             input="Does every fur or fur-trimmed product carry a label with the animal name, country of origin and any dyeing or other processing?",
             sample=True,
             action="Pull unlabeled fur items from sale; attach compliant labels and fix any matching ads or invoices."),
        Rule(key="dpms_aml_program", title="AML program for dealers",
             cost="FinCEN civil money penalties apply to covered dealers that lack an AML program, and gaps invite criminal money-laundering exposure.",
             citation="Bank Secrecy Act; 31 CFR 1027.210 (dealers in precious metals, precious stones or jewels)",
             kind="required",
             input="If you are a covered dealer, do you have a written AML program with a compliance officer, risk-based procedures, training and independent testing?",
             sample=False,
             action="Adopt a written AML program now: name a compliance officer, set risk-based procedures, train staff and schedule independent testing."),
        Rule(key="form_8300", title="Form 8300 cash report filing",
             cost="Late or missing Form 8300 filings bring IRS civil penalties per return, higher penalties for intentional disregard, and possible criminal charges.",
             citation="26 U.S.C. 6050I; 31 U.S.C. 5331; 31 CFR 1010.330 (file within 15 days)",
             kind="max",
             input="Days since receiving over $10,000 in cash (one or related transactions) with Form 8300 not yet filed",
             unit="days", limit=15, warn=10, sample=12,
             action="File Form 8300 with the IRS/FinCEN today and send the buyer the required written notice by January 31."),
        Rule(key="prop65_warning", title="California Prop 65 warning",
             cost="Private enforcers send 60-day notices and sue for civil penalties, attorney fees and forced relabeling of products sold in California.",
             citation="Cal. Health & Safety Code 25249.6; 27 CCR 25600 et seq. (businesses with 10 or more employees)",
             kind="required",
             input="For products sold in California that expose buyers to a listed chemical (e.g. lead, DEHP) above safe-harbor levels, is a clear Prop 65 warning given?",
             sample=True,
             action="Stop California sales of the product until a compliant Prop 65 warning is on the product, shelf or web listing."),
        Rule(key="uflpa_tracing", title="Forced labor supply-chain tracing",
             cost="CBP detains and excludes goods tied to Xinjiang or listed entities, stranding inventory and missing selling seasons.",
             citation="Uyghur Forced Labor Prevention Act, Pub. L. 117-78; 19 U.S.C. 1307",
             kind="required",
             input="Is supply-chain tracing on file showing no input (e.g. cotton, leather, gold, polysilicon) came from Xinjiang or a UFLPA Entity List supplier?",
             sample=False,
             action="Hold the shipment; assemble tracing documents back to raw materials and replace any Xinjiang or listed-entity source."),
    ],

    # ------------------------------------------------------------------
    # 12. AGRIARMOR - farms and growers
    # ------------------------------------------------------------------
    12: [
        Rule(key="phi_met", title="Pesticide pre-harvest interval",
             cost="Residues over tolerance lead to rejected loads, crop destruction, buyer delistings and FIFRA misuse penalties.",
             citation="FIFRA 12(a)(2)(G), 7 U.S.C. 136j - use must follow the label, including its pre-harvest interval",
             kind="required",
             input="Has the full label pre-harvest interval (PHI) passed since the last pesticide application to this crop?",
             sample=False,
             action="Do not harvest; wait until the label PHI has fully passed since the last application.",
             method="agri_armor_withholding_clock"),
        Rule(key="rei_entry", title="Restricted-entry interval",
             cost="Worker poisonings bring WPS penalties, medical and workers' compensation costs, and lawsuits.",
             citation="EPA Worker Protection Standard, 40 CFR 170.405 and 170.407; FIFRA 12(a)(2)(G)",
             kind="forbidden",
             input="Did any worker enter a treated area during its label restricted-entry interval without a permitted early-entry exception and PPE?",
             sample=False,
             action="Remove workers from the treated area now, post or tell the REI, and provide decontamination and medical help if exposed."),
        Rule(key="wps_training", title="WPS pesticide safety training",
             cost="Untrained workers and handlers bring WPS violations counted per worker and higher risk of poisoning claims.",
             citation="EPA Worker Protection Standard, 40 CFR 170.401 (workers) and 170.501 (handlers) - every 12 months",
             kind="max",
             input="Days since this worker's or handler's last WPS pesticide safety training",
             unit="days", limit=365, warn=335, sample=350,
             action="Keep this person out of treated areas and handling tasks until retrained, and record the training."),
        Rule(key="rup_record", title="Restricted-use pesticide record",
             cost="Missing application records bring USDA and state civil penalties and weaken the farm's defense in drift or residue claims.",
             citation="7 U.S.C. 136i-1; 7 CFR Part 110 (record within 14 days, keep 2 years; some states stricter)",
             kind="max",
             input="Days since a restricted-use pesticide application that still has no application record",
             unit="days", limit=14, warn=10, sample=20,
             action="Write the application record now (product, EPA reg. no., amount, site, date, applicator) and file it for 2 years."),
        Rule(key="certified_applicator", title="Certified applicator for RUPs",
             cost="Applying restricted-use pesticides without certification brings FIFRA penalties, loss of dealer access and liability for any harm.",
             citation="FIFRA 3(d), 7 U.S.C. 136a(d); 40 CFR Part 171",
             kind="required",
             input="Is every restricted-use pesticide applied by, or under the direct supervision of, a currently certified applicator?",
             sample=True,
             action="Stop the application; use a currently certified applicator or one supervising directly before continuing."),
        Rule(key="ag_water_ecoli", title="Harvest and post-harvest water",
             cost="Contaminated wash water can cause outbreaks, recalls, FDA warning letters and loss of buyer contracts.",
             citation="FSMA Produce Safety Rule, 21 CFR 112.44(a) - no detectable generic E. coli in 100 mL",
             kind="max",
             input="Generic E. coli found in water used for washing produce, contact surfaces or handwashing",
             unit="CFU/100 mL", limit=0, sample=0,
             action="Stop using this water for produce contact or handwashing; switch to a safe source or treat it and retest."),
        Rule(key="field_toilets", title="Field toilets and handwashing",
             cost="Missing field sanitation brings OSHA citations, worker illness and food-safety failures that buyers audit for.",
             citation="OSHA 29 CFR 1928.110(c)(2) - one toilet and handwashing facility per 20 workers (farms with 11+ hand laborers)",
             kind="max",
             input="Field hand laborers per toilet and handwashing facility (within a quarter-mile walk)",
             unit="workers", limit=20, warn=18, sample=22,
             action="Bring in more toilets and handwashing stations today so each serves 20 or fewer workers within a quarter-mile walk."),
        Rule(key="h2a_wage", title="H-2A required wage rate",
             cost="Underpaying H-2A or corresponding workers brings DOL back wages, civil money penalties and debarment from the H-2A program.",
             citation="20 CFR 655.120(a) and 655.122(l); 29 CFR Part 501",
             kind="required",
             input="Are H-2A workers and workers in corresponding employment paid at least the highest of the AEWR, prevailing wage, agreed rate, or federal or state minimum wage?",
             sample=True,
             action="Raise pay to the highest required rate now and pay back wages owed for all hours already worked."),
        Rule(key="decon_supplies", title="Pesticide decontamination supplies",
             cost="Missing wash water, soap and towels near treated areas bring WPS violations and worsen worker poisonings and injury claims.",
             citation="EPA Worker Protection Standard, 40 CFR 170.411 (workers) and 170.509 (handlers)",
             kind="required",
             input="Are water, soap and single-use towels in place within a quarter mile of workers in treated areas (plus eye-flush and clean clothes for handlers)?",
             sample=True,
             action="Set out decontamination water, soap, towels and eye-flush supplies before workers or handlers continue."),
        Rule(key="flc_registration", title="Farm labor contractor registration",
             cost="Using an unregistered labor contractor brings MSPA civil money penalties and joint liability for the crew's wages and housing.",
             citation="Migrant and Seasonal Agricultural Worker Protection Act, 29 U.S.C. 1842; 29 CFR Part 500",
             kind="required",
             input="Have you checked that every farm labor contractor you use holds a valid DOL certificate covering the work they do for you?",
             sample=False,
             action="Verify the contractor's DOL certificate before the crew works again; stop using any unregistered contractor."),
    ],

    # ------------------------------------------------------------------
    # 13. COPARMOR - police departments
    # ------------------------------------------------------------------
    13: [
        Rule(key="evidence_inspection", title="Evidence room inspection",
             cost="Lost or tampered evidence breaks chain of custody, gets cases dismissed and can cost CALEA accreditation.",
             citation="CALEA Standard 84.1.6 - semiannual property/evidence inspections (accredited agencies) or agency policy",
             kind="max",
             input="Days since the last property and evidence room inspection",
             unit="days", limit=183, warn=153, policy=True, sample=160,
             action="Inspect the evidence room now and reconcile records before releasing more evidence to court.",
             method="cop_armor_evidence_timer"),
        Rule(key="cjis_training", title="CJIS security awareness training",
             cost="Failed CJIS audits can suspend the agency's access to NCIC and state criminal history systems.",
             citation="FBI CJIS Security Policy, awareness and training (AT) controls - before access and annually (FBI policy, applied through state CSA agreements)",
             kind="max",
             input="Days since this person's last CJIS security awareness training",
             unit="days", limit=365, warn=335, policy=True, sample=300,
             action="Suspend this person's CJI access until they complete CJIS security awareness training."),
        Rule(key="cjis_mfa", title="Multi-factor login for CJI",
             cost="Weak authentication fails CJIS audits, risks losing NCIC access and exposes the agency to breach costs.",
             citation="FBI CJIS Security Policy, identification and authentication (IA) controls - multi-factor authentication",
             kind="required",
             input="Is multi-factor authentication required for every login that can reach criminal justice information?",
             sample=False,
             action="Turn on multi-factor authentication for all CJI systems, or block access from accounts and devices without it."),
        Rule(key="bwc_retention", title="Body-worn camera retention",
             cost="Deleted or missing footage leads to lost cases, adverse-inference rulings, public-records suits and settlements.",
             citation="State law varies (state body-worn camera and records retention laws); agency retention policy",
             kind="required",
             input="Is body-worn camera footage kept for your state's required period, with longer holds for use of force, arrests, complaints and litigation?",
             policy=True, sample=True,
             action="Place a hold on all footage at risk of deletion and fix retention settings to match state law and open cases."),
        Rule(key="use_of_force_report", title="Use-of-force reporting and review",
             cost="Unreported or unreviewed force drives civil rights verdicts, pattern-or-practice investigations and loss of state grants.",
             citation="State law and agency policy; CALEA standards, Chapter 4 (use of force reporting and review)",
             kind="required",
             input="Is every reportable use of force documented and reviewed by a supervisor as state law and agency policy require?",
             sample=True,
             action="Get the officer's written report and a supervisor review completed now, and submit any report state law requires."),
        Rule(key="comp_time_cap", title="Compensatory time 480-hour cap",
             cost="Comp time banked over the cap must be paid as overtime, with FLSA back pay, equal liquidated damages and attorney fees.",
             citation="FLSA 7(o)(3)(A), 29 U.S.C. 207(o)(3)(A); 29 CFR 553.24 - 480 hours for law enforcement",
             kind="max",
             input="Hours of compensatory time this officer has banked",
             unit="h", limit=480, warn=440, sample=455,
             action="Pay cash overtime for further overtime hours instead of adding comp time until the balance drops below 480."),
        Rule(key="probable_cause_48h", title="Probable cause review within 48 hours",
             cost="Holding a warrantless arrestee past 48 hours without a judicial probable cause finding brings civil rights suits and release orders.",
             citation="County of Riverside v. McLaughlin, 500 U.S. 44 (1991); Gerstein v. Pugh, 420 U.S. 103 (1975); state rules may be shorter",
             kind="max",
             input="Hours since a warrantless arrest with no judicial probable cause determination yet",
             unit="h", limit=48, warn=36, sample=20,
             action="Get the arrestee before a judge for a probable cause determination now, or release them."),
        Rule(key="firearms_qualification", title="Firearms qualification",
             cost="Officers carrying without current qualification expose the agency to failure-to-train liability and breach state POST rules.",
             citation="State POST standards vary; annual qualification is common policy; City of Canton v. Harris, 489 U.S. 378 (1989)",
             kind="max",
             input="Days since this officer last passed firearms qualification with the duty weapon",
             unit="days", limit=365, warn=335, policy=True, sample=400,
             action="Remove the officer from armed duty until they pass firearms qualification with the duty weapon."),
        Rule(key="flsa_7k_overtime", title="Police overtime (7(k) period)",
             cost="Unpaid overtime brings FLSA back pay, equal liquidated damages and attorney fees, often in group lawsuits.",
             citation="FLSA 7(k), 29 U.S.C. 207(k); 29 CFR 553.230 - 171 hours per 28-day law enforcement work period",
             kind="max",
             input="Hours an officer has worked at straight-time pay in the current 28-day 7(k) work period",
             unit="h", limit=171, warn=160, sample=165,
             action="Pay overtime (or allowed comp time) at time and a half for every hour over 171 in this 28-day period."),
        Rule(key="ada_communication", title="ADA communication with deaf people",
             cost="Failing to provide interpreters brings DOJ settlements, damages suits and suppressed statements.",
             citation="ADA Title II, 42 U.S.C. 12132; 28 CFR 35.160 (effective communication)",
             kind="required",
             input="Are qualified interpreters or other auxiliary aids provided to deaf or hard-of-hearing people in interviews, interrogations and arrests?",
             sample=True,
             action="Get a qualified interpreter or other auxiliary aid before continuing the interview, and document it."),
    ],

    # ------------------------------------------------------------------
    # 14. FIREARMOR - fire departments
    # ------------------------------------------------------------------
    14: [
        Rule(key="scba_pressure", title="SCBA inspected and charged",
             cost="A low or unchecked SCBA can fail inside a fire, causing injury or death, OSHA citations and wrongful-death suits.",
             citation="OSHA 29 CFR 1910.134(h)(3) - SCBA checked before and after use and monthly; recharge below 90% of rated pressure",
             kind="min",
             input="SCBA cylinder pressure as a percent of rated full pressure at this shift's check",
             unit="%", limit=90, warn=92, sample=88,
             action="Take the SCBA out of service and recharge the cylinder before assigning it.",
             method="fire_armor_scba_verification"),
        Rule(key="fit_test", title="Annual SCBA facepiece fit test",
             cost="Untested facepieces let smoke in, leading to OSHA citations (in State Plan states) and exposure-related claims.",
             citation="OSHA 29 CFR 1910.134(f)(2) - fit test before use and at least annually (public departments in OSHA State Plan states)",
             kind="max",
             input="Days since this firefighter's last SCBA facepiece fit test",
             unit="days", limit=365, warn=335, sample=200,
             action="Keep the firefighter off respirator duty until fit tested with the facepiece model and size they use."),
        Rule(key="medical_evaluation", title="Annual firefighter medical exam",
             cost="Missed medicals raise line-of-duty cardiac risk, respirator-standard citations and costly workers' compensation claims.",
             citation="NFPA 1582 standard or its successor (annual medical evaluation); OSHA 29 CFR 1910.134(e) medical clearance for respirator use",
             kind="max",
             input="Days since this firefighter's last occupational medical evaluation",
             unit="days", limit=365, warn=335, policy=True, sample=340,
             action="Restrict the firefighter from fireground and respirator duty until the medical evaluation is done and cleared."),
        Rule(key="gear_retirement", title="Turnout gear 10-year retirement",
             cost="Over-age gear may not protect against heat and flame, creating burn injury claims and failed audits or grant reviews.",
             citation="NFPA 1851 standard or its successor NFPA 1850 - retire structural ensembles 10 years after manufacture",
             kind="max",
             input="Years since this turnout gear was manufactured",
             unit="years", limit=10, warn=9, policy=True, sample=11,
             action="Retire this gear from firefighting use now and issue a compliant replacement set."),
        Rule(key="gear_advanced_inspection", title="Turnout gear advanced cleaning",
             cost="Contaminated or damaged gear raises cancer-exposure and burn risk and fails NFPA-based audits.",
             citation="NFPA 1851 standard or its successor NFPA 1850 - advanced inspection and advanced cleaning at least every 12 months",
             kind="max",
             input="Days since this turnout gear's last advanced inspection and advanced cleaning",
             unit="days", limit=365, warn=335, policy=True, sample=150,
             action="Pull the gear for advanced cleaning and inspection and issue a spare set meanwhile."),
        Rule(key="hose_test", title="Annual fire hose service test",
             cost="A hose that bursts on the fireground endangers crews and property and weakens the department's liability defense.",
             citation="NFPA 1962 standard or its successor NFPA 1910 - in-service hose tested at least annually",
             kind="max",
             input="Days since this hose length's last service test",
             unit="days", limit=365, warn=335, policy=True, sample=380,
             action="Take the hose out of service until it passes a service pressure test."),
        Rule(key="ladder_test", title="Annual ground ladder test",
             cost="Ladder failures cause falls, serious injury claims and OSHA or insurer findings.",
             citation="NFPA 1932 standard or its successor NFPA 1910 - ground ladders service tested at least annually",
             kind="max",
             input="Days since this ground ladder's last service test",
             unit="days", limit=365, warn=335, policy=True, sample=350,
             action="Remove the ladder from the apparatus until it passes its service test."),
        Rule(key="pump_test", title="Annual fire pump service test",
             cost="A pump that fails to deliver rated flow can lose structures and lives and lower ISO ratings and insurance outcomes.",
             citation="NFPA 1911 standard or its successor NFPA 1910 - apparatus fire pump service tested at least annually",
             kind="max",
             input="Days since this apparatus's last fire pump service test",
             unit="days", limit=365, warn=335, policy=True, sample=100,
             action="Schedule the pump service test now and put the apparatus in reserve if it cannot pass."),
        Rule(key="two_in_two_out", title="Two-in, two-out entry",
             cost="Entering without a standby team leaves no rescue option, causing line-of-duty deaths, OSHA citations and lawsuits.",
             citation="OSHA 29 CFR 1910.134(g)(4) - two in, two out for interior structural firefighting (known-rescue exception)",
             kind="forbidden",
             input="Did any interior structural firefighting entry into an IDLH atmosphere happen without two properly equipped firefighters standing by outside?",
             sample=False,
             action="Hold interior entry until two equipped firefighters are outside, and review the incident with the crews."),
        Rule(key="hbv_vaccine", title="Hepatitis B vaccine offered",
             cost="Unvaccinated responders face infection risk, OSHA bloodborne pathogens citations and workers' compensation claims.",
             citation="OSHA 29 CFR 1910.1030(f)(2) - offer within 10 working days of assignment (public departments in OSHA State Plan states)",
             kind="max",
             input="Working days since this responder was assigned exposure duties without being offered the hepatitis B vaccine",
             unit="working days", limit=10, warn=8, sample=3,
             action="Offer the hepatitis B vaccine series at no cost now, or get a signed declination."),
    ],

    # ------------------------------------------------------------------
    # 15. PARKARMOR - amusement and water parks
    # ------------------------------------------------------------------
    15: [
        Rule(key="daily_ride_inspection", title="Daily pre-opening ride inspection",
             cost="Opening an uninspected ride risks rider injury, state shutdown orders and negligence lawsuits.",
             citation="ASTM F770 - daily pre-opening inspection by the owner/operator; state ride laws adopt or add to it",
             kind="required",
             input="Has today's pre-opening inspection been completed and signed off for this ride?",
             sample=True,
             action="Keep the ride closed until today's pre-opening inspection is completed and signed.",
             method="park_armor_ride_clearance"),
        Rule(key="state_ride_permit", title="State ride permit current",
             cost="Operating without a current state permit or inspection brings shutdown orders, fines and weaker insurance and legal defense.",
             citation="State amusement ride laws vary (permits and periodic state or third-party inspections)",
             kind="min",
             input="Days until this ride's state permit or inspection certificate expires (negative if expired)",
             unit="days", limit=0, warn=30, policy=True, sample=-5,
             action="Close the ride until the state inspection is passed and the permit is current and posted."),
        Rule(key="incident_reporting", title="Ride incident reporting",
             cost="Late or missing incident reports bring state fines and shutdowns and undercut the park's position in injury lawsuits.",
             citation="State amusement ride laws vary (reporting deadlines for serious injuries; ride held for inspection)",
             kind="required",
             input="Was every ride incident with serious injury reported to the state agency within its deadline, with the ride held as required?",
             policy=True, sample=True,
             action="Report the incident to the state agency now and keep the ride closed and unaltered until it is released."),
        Rule(key="operator_training", title="Ride operator training",
             cost="Untrained operators cause rider injuries and negligence verdicts, and training gaps are cited in state inspections.",
             citation="ASTM F770 (operator training and training records); state ride laws",
             kind="required",
             input="Has every operator completed and documented training for the specific ride they run, including its rider restrictions?",
             policy=True, sample=True,
             action="Remove the operator from the ride until ride-specific training is completed and recorded."),
        Rule(key="lifeguard_certification", title="Lifeguard certification current",
             cost="An uncertified lifeguard on duty can void insurance, bring health-department closure and weaken drowning-lawsuit defense.",
             citation="State pool and bathing codes vary; CDC Model Aquatic Health Code (lifeguard qualification)",
             kind="min",
             input="Days until this lifeguard's certification expires (negative if already expired)",
             unit="days", limit=0, warn=30, policy=True, sample=12,
             action="Take the lifeguard off the stand until recertified; replace them with a certified guard."),
        Rule(key="free_chlorine", title="Pool free chlorine level",
             cost="Low chlorine spreads waterborne illness, leading to health-department closure, outbreak lawsuits and lost admissions.",
             citation="State pool codes vary; CDC Model Aquatic Health Code minimum 1.0 ppm free chlorine (higher with stabilizer and in spas)",
             kind="min",
             input="Free chlorine level at the latest pool test",
             unit="ppm", limit=1.0, warn=1.5, policy=True, sample=0.6,
             action="Clear the pool, raise free chlorine to the required level and retest before reopening."),
        Rule(key="vgb_drain_covers", title="VGB-compliant drain covers",
             cost="Drain entrapment causes catastrophic injuries or death, CPSC enforcement and large lawsuits.",
             citation="Virginia Graeme Baker Pool and Spa Safety Act, 15 U.S.C. 8003; 16 CFR Part 1450",
             kind="required",
             input="Does every pool and spa drain have a VGB-compliant cover within its rated service life, plus required anti-entrapment systems?",
             sample=True,
             action="Close the pool or spa until noncompliant or expired drain covers are replaced and anti-entrapment protection is in place."),
        Rule(key="pool_ph", title="Pool pH upper limit",
             cost="High pH weakens chlorine, spreading waterborne illness and bringing health-department closures and lost admissions.",
             citation="State pool codes vary; CDC Model Aquatic Health Code pH range 7.2 to 7.8",
             kind="max",
             input="pH at the latest pool water test",
             unit="pH", limit=7.8, warn=7.7, policy=True, sample=7.5,
             action="Adjust pH into range and retest before letting swimmers back in."),
        Rule(key="child_labor_hours", title="Teen work hours (14-15)",
             cost="Child labor violations bring DOL civil money penalties per minor and bad publicity with families.",
             citation="FLSA child labor rules, 29 CFR 570.35(a) - 18 hours in a school week for 14- and 15-year-olds",
             kind="max",
             input="Hours a 14- or 15-year-old employee worked this school week",
             unit="h", limit=18, warn=16, sample=14,
             action="Take the minor off the schedule for the rest of the week and fix scheduling to FLSA hour limits."),
        Rule(key="lockout_tagout", title="Lockout/tagout for ride maintenance",
             cost="Unexpected startup during maintenance causes amputations and deaths, OSHA citations and workers' compensation costs.",
             citation="OSHA 29 CFR 1910.147 (control of hazardous energy)",
             kind="required",
             input="Are written lockout/tagout procedures used every time workers service or maintain ride machinery that could start or move?",
             sample=True,
             action="Stop the maintenance work; lock out all energy sources under written procedures before anyone resumes."),
    ],
}
