# -*- coding: utf-8 -*-
"""
Rule catalog, group 7: PrivacyArmor, PayArmor, CryptoArmor, MortgageArmor and
CollectArmor. Ten rules per industry, costliest first.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 31. PRIVACYARMOR (software/SaaS and data-driven companies) ---
    31: [
        Rule(key="gdpr_breach_72h", title="Breach notice to authority in 72 hours",
             cost="Late breach notice draws GDPR fines from supervisory authorities on top of the breach costs and follow-on claims.",
             citation="GDPR Art. 33(1)", kind="max",
             input="Hours since becoming aware of a personal data breach, without notifying the supervisory authority",
             unit="h", limit=72, warn=48, sample=50,
             action="Notify the lead supervisory authority now; explain the reasons for any delay and send what facts you have."),
        Rule(key="lawful_basis", title="Lawful basis for processing",
             cost="Processing without a valid legal basis, such as invalid consent for ads, is the ground for many of the largest GDPR fines and orders to stop processing.",
             citation="GDPR Art. 6(1); Art. 7", kind="required",
             input="Is a lawful basis documented for every processing activity, with valid consent where consent is the basis?",
             sample=True,
             action="Stop the processing that lacks a lawful basis until a valid basis is identified and documented."),
        Rule(key="international_transfers", title="Lawful transfers outside the EEA",
             cost="Unlawful transfers of EU personal data can bring large GDPR fines and orders to suspend transfers that the product depends on.",
             citation="GDPR Chapter V (Art. 44-49)", kind="required",
             input="Is every transfer of personal data out of the EEA covered by an adequacy decision, standard contractual clauses or another Chapter V tool?",
             sample=False,
             action="Pause the uncovered transfer; put SCCs with a transfer risk assessment in place or use an adequacy-covered recipient."),
        Rule(key="gdpr_dsar_one_month", title="Answer data subject requests",
             cost="Ignored or late access and erasure requests are among the most common complaints to regulators and lead to orders, fines and damages claims.",
             citation="GDPR Art. 12(3) (one month, treated here as 30 days; extendable by two months with notice)", kind="max",
             input="Days since the data subject request was received, with no response and no extension notice",
             unit="days", limit=30, warn=21, sample=12,
             action="Respond now, or tell the person within the month why you are extending and by how long."),
        Rule(key="ccpa_request_45_days", title="Answer CCPA consumer requests",
             cost="Missed consumer request deadlines draw California enforcement with civil penalties per violation and injunctive terms.",
             citation="Cal. Civ. Code 1798.130(a)(2)", kind="max",
             input="Days since the verifiable consumer request was received, with no response and no extension notice",
             unit="days", limit=45, warn=35, sample=38,
             action="Respond now; the 45 days may be extended once by 45 more only if the consumer was told within the first 45."),
        Rule(key="do_not_sell_gpc", title="Do Not Sell or Share and GPC honored",
             cost="Failing to offer or honor opt-outs of sale or sharing, including Global Privacy Control signals, has led to California settlements and penalties.",
             citation="Cal. Civ. Code 1798.120, 1798.135; 11 CCR 7025", kind="required",
             input="Does the site show a Do Not Sell or Share link and treat Global Privacy Control signals as opt-out requests?",
             sample=False,
             action="Add the opt-out link and configure tags and ad tools to stop selling or sharing when a GPC signal is received."),
        Rule(key="coppa_parental_consent", title="Parental consent for kids under 13",
             cost="Collecting children's data without verifiable parental consent brings FTC civil penalties per violation and data deletion orders.",
             citation="15 U.S.C. 6502; 16 CFR 312.5", kind="required",
             input="For a service directed to children or with known users under 13, is verifiable parental consent obtained before collecting their data?",
             sample=True,
             action="Stop collecting data from users under 13 until verifiable parental consent is in place; delete data collected without it."),
        Rule(key="state_breach_notice", title="Breach notice to affected residents",
             cost="Late notice to affected people draws state attorney general penalties and strengthens class action claims after a breach.",
             citation="State breach laws vary (policy); 30 days is the shortest common deadline, e.g., Colo. Rev. Stat. 6-1-716, Fla. Stat. 501.171", kind="max",
             input="Days since the breach was discovered, without notifying affected residents",
             unit="days", limit=30, warn=20, policy=True, sample=34,
             action="Send notices to affected residents now and file any required state attorney general notices."),
        Rule(key="hipaa_baa", title="HIPAA business associate agreements",
             cost="Handling protected health information without a signed business associate agreement is a HIPAA violation cited in OCR settlements and lost contracts.",
             citation="45 CFR 164.502(e), 164.504(e), 164.308(b)", kind="required",
             input="Is a signed business associate agreement in place with every client and subcontractor for which you handle PHI?",
             sample=True,
             action="Stop receiving PHI from, or sending it to, any party without a signed business associate agreement."),
        Rule(key="gdpr_dpia", title="DPIA before high-risk processing",
             cost="Launching high-risk processing without a data protection impact assessment draws GDPR fines and can force a product feature to be withdrawn.",
             citation="GDPR Art. 35(1)", kind="required",
             input="Was a data protection impact assessment completed before starting processing likely to be high risk?",
             sample=False,
             action="Complete the DPIA before continuing; consult the supervisory authority if high risk remains after mitigation."),
    ],

    # --- 32. PAYARMOR (merchants and payment processors) ---
    32: [
        Rule(key="no_sad_storage", title="No CVV or track data after auth",
             cost="Storing sensitive authentication data turns a breach into card-brand assessments, forensic costs, higher fees and possible loss of card acceptance.",
             citation="PCI DSS v4.0.1 Req. 3.3.1 (industry standard)", kind="forbidden",
             input="Is CVV, full track data or PIN data stored anywhere after authorization?",
             policy=True, sample=False,
             action="Find and securely delete the stored data, fix the capture flow, and report to your acquirer if a compromise is suspected."),
        Rule(key="ofac_screening", title="OFAC sanctions screening",
             cost="Processing payments for sanctioned parties brings strict-liability OFAC civil penalties and bank de-risking of the business.",
             citation="31 CFR Part 501; 31 CFR Chapter V sanctions programs", kind="required",
             input="Are merchants, customers and payment parties screened against the OFAC SDN list at onboarding and when the list changes?",
             sample=True,
             action="Hold transactions with unscreened parties; screen them now and block and report any match to OFAC."),
        Rule(key="ach_unauthorized_returns", title="ACH unauthorized return rate",
             cost="Exceeding the Nacha unauthorized return threshold leads to ODFI inquiries, fines under the Nacha rules and loss of ACH origination.",
             citation="Nacha Operating Rules Subsection 2.17.2 (unauthorized entry return rate, industry rule)", kind="max",
             input="Unauthorized ACH debit return rate over the last 60 days",
             unit="%", limit=0.5, warn=0.4, policy=True, sample=0.62,
             action="Stop origination for the high-return originators, fix authorization capture and give your ODFI a reduction plan."),
        Rule(key="chargeback_ratio", title="Chargeback ratio under program limit",
             cost="Crossing card-brand dispute program thresholds brings monthly fines, higher processing costs and possible termination of the merchant account.",
             citation="Card brand dispute monitoring programs (policy setting; set to your acquirer's current Visa and Mastercard thresholds)", kind="max",
             input="Chargebacks as a percent of settled card transactions last month",
             unit="%", limit=1.0, warn=0.75, policy=True, sample=0.8,
             action="Tighten fraud screening, fix billing descriptors and refund policies, and contact your acquirer about a remediation plan."),
        Rule(key="mfa_into_cde", title="MFA for access into the CDE",
             cost="Password-only access to cardholder data systems is a common breach path that leads to card-brand assessments and failed PCI validation.",
             citation="PCI DSS v4.0.1 Req. 8.4.2 (industry standard)", kind="required",
             input="Is multi-factor authentication required for all access into the cardholder data environment?",
             policy=True, sample=False,
             action="Turn on MFA for every account that can reach the cardholder data environment before further access."),
        Rule(key="quarterly_asv_scan", title="Quarterly external ASV scan",
             cost="Missing passing ASV scans puts the business out of PCI compliance, raising non-compliance fees and breach liability.",
             citation="PCI DSS v4.0.1 Req. 11.3.2 (industry standard; once every three months)", kind="max",
             input="Days since the last passing external vulnerability scan by an Approved Scanning Vendor",
             unit="days", limit=90, warn=75, policy=True, sample=64,
             action="Run an ASV scan now, fix failing findings and rescan until it passes."),
        Rule(key="annual_pci_validation", title="Annual PCI validation (SAQ/ROC)",
             cost="Lapsed PCI validation brings monthly non-compliance fees from the acquirer and weakens the defense after a breach.",
             citation="Card brand compliance programs (policy; annual SAQ or ROC with AOC)", kind="max",
             input="Days since the last completed SAQ or Report on Compliance and Attestation of Compliance",
             unit="days", limit=365, warn=330, policy=True, sample=342,
             action="Complete the SAQ or ROC and submit the Attestation of Compliance to your acquirer."),
        Rule(key="pan_unreadable", title="Stored card numbers unreadable",
             cost="Stored card numbers in clear text make a breach far more costly through card-brand assessments, card reissue costs and lawsuits.",
             citation="PCI DSS v4.0.1 Req. 3.5.1 (industry standard)", kind="required",
             input="Is every stored primary account number rendered unreadable (encryption, tokenization, truncation or hashing)?",
             policy=True, sample=True,
             action="Encrypt or tokenize the stored card numbers now and delete any you do not need."),
        Rule(key="reg_e_error_resolution", title="Reg E error investigation timing",
             cost="Slow handling of consumer disputes on transfers, prepaid or P2P accounts has led to CFPB consent orders with restitution and penalties.",
             citation="12 CFR 1005.11(c)", kind="max",
             input="Business days since the consumer reported the error, without finishing the investigation or giving provisional credit",
             unit="business days", limit=10, warn=8, sample=6,
             action="Finish the investigation now or give provisional credit and notify the consumer."),
        Rule(key="surcharge_cap", title="Credit card surcharge within cap",
             cost="Surcharges over card-brand caps or in states that restrict them lead to card-brand fines, state enforcement and refund claims.",
             citation="Card brand surcharge rules (policy; Visa U.S. cap is 3%); state law varies; no surcharges on debit or prepaid cards", kind="max",
             input="Surcharge charged on credit card transactions, as a percent of the sale",
             unit="%", limit=3, warn=2.75, policy=True, sample=3.5,
             action="Lower the surcharge to the cap, confirm your state allows it, disclose it and stop surcharging debit cards."),
    ],

    # --- 33. CRYPTOARMOR (crypto exchanges and money services businesses) ---
    33: [
        Rule(key="aml_program", title="Effective AML program",
             cost="AML program failures are the basis of the largest FinCEN and DOJ crypto settlements, with monitorships and forced exits from the U.S. market.",
             citation="31 U.S.C. 5318(h); 31 CFR 1022.210", kind="required",
             input="Is there a written, risk-based AML program with a compliance officer, training and working transaction monitoring?",
             sample=True,
             action="Fix the program gaps now: name a qualified compliance officer, turn on monitoring and document the risk assessment."),
        Rule(key="sar_30_days", title="SAR filed within 30 days",
             cost="Late or missing SARs are cited in almost every FinCEN enforcement action against money services businesses and draw civil penalties.",
             citation="31 CFR 1022.320(a)(2), (b)(3) ($2,000 threshold)", kind="max",
             input="Days since initial detection of facts that may require a SAR, without filing",
             unit="days", limit=30, warn=20, sample=33,
             action="File the SAR with FinCEN now and document why it was late."),
        Rule(key="ofac_screening", title="OFAC sanctions screening",
             cost="Serving sanctioned users or wallets brings strict-liability OFAC civil penalties, often alongside AML enforcement.",
             citation="31 CFR Part 501; 31 CFR Chapter V sanctions programs", kind="required",
             input="Are customers, IP locations and counterparty wallet addresses screened against OFAC sanctions lists?",
             sample=False,
             action="Block activity for unscreened accounts, screen them now and report any blocked property to OFAC."),
        Rule(key="state_mtl", title="State money transmitter licenses",
             cost="Transmitting money without required state licenses brings cease-and-desist orders, state fines and federal criminal exposure under 18 U.S.C. 1960.",
             citation="State money transmitter laws (policy; requirements vary by state); 18 U.S.C. 1960", kind="required",
             input="Does the business hold a license, or a documented exemption, in every state where it serves customers?",
             policy=True, sample=True,
             action="Stop onboarding customers in unlicensed states and apply for the license or confirm the exemption."),
        Rule(key="msb_registration", title="FinCEN MSB registration current",
             cost="Operating as an unregistered MSB draws FinCEN civil penalties and is a federal crime.",
             citation="31 CFR 1022.380; 18 U.S.C. 1960", kind="required",
             input="Is the business registered with FinCEN as an MSB, with renewal filed on its two-year cycle?",
             sample=True,
             action="File or renew the FinCEN MSB registration (Form 107) now."),
        Rule(key="customer_verification", title="Customer identity verified",
             cost="Letting unverified customers transact is a core finding in crypto AML enforcement and leads to penalties and costly account lookbacks.",
             citation="31 CFR 1022.210(d)(1)(i)(A)", kind="required",
             input="Is each customer's identity verified under the AML program before the account can send or receive funds?",
             sample=False,
             action="Restrict unverified accounts from transacting until identity verification is complete."),
        Rule(key="travel_rule", title="Travel Rule for $3,000+ transmittals",
             cost="Missing originator and beneficiary information on transmittals is a recurring FinCEN finding that draws civil penalties.",
             citation="31 CFR 1010.410(e), (f)", kind="required",
             input="For transmittals of $3,000 or more, is the required sender and recipient information recorded and passed to the next institution?",
             sample=True,
             action="Hold qualifying transmittals until the required information is recorded and can be sent with the transfer."),
        Rule(key="ctr_15_days", title="CTR for cash over $10,000",
             cost="Failing to file currency transaction reports draws FinCEN civil penalties and can support structuring charges.",
             citation="31 CFR 1022.310; 31 CFR 1010.311; 31 CFR 1010.306(a)(1)", kind="max",
             input="Days since a cash transaction (or same-day aggregate) over $10,000, without filing a CTR",
             unit="days", limit=15, warn=10, sample=4,
             action="File the CTR with FinCEN now."),
        Rule(key="independent_aml_review", title="Independent AML review",
             cost="A missing or stale independent review is a common exam finding that leads to FinCEN and state penalties and remediation orders.",
             citation="31 CFR 1022.210(d)(4) (frequency is risk-based; annual is a common policy setting)", kind="max",
             input="Days since the last independent review of the AML program was completed",
             unit="days", limit=365, warn=330, policy=True, sample=410,
             action="Engage a qualified independent reviewer now and track the findings to closure."),
        Rule(key="record_retention_5y", title="BSA records kept five years",
             cost="Destroyed or missing BSA records draw civil penalties and leave the business unable to defend itself in exams and investigations.",
             citation="31 CFR 1010.430(d)", kind="required",
             input="Are BSA records (SARs, CTRs, transmittal and identity records) kept for at least five years?",
             sample=True,
             action="Stop any deletion of BSA records and set retention to at least five years."),
    ],

    # --- 34. MORTGAGEARMOR (mortgage lenders and servicers) ---
    34: [
        Rule(key="fair_lending", title="No unexplained lending disparities",
             cost="Pricing, underwriting or redlining disparities by race or other protected traits lead to DOJ and CFPB settlements with penalties and loan subsidy funds.",
             citation="15 U.S.C. 1691; 12 CFR 1002.4(a); Fair Housing Act 42 U.S.C. 3605", kind="forbidden",
             input="Has a fair lending review found pricing, underwriting or marketing disparities on a prohibited basis that remain unexplained?",
             sample=False,
             action="Investigate the disparity now, fix the policy causing it and review affected borrowers for remediation."),
        Rule(key="respa_kickbacks", title="No RESPA referral kickbacks",
             cost="Paying or taking anything of value for settlement service referrals brings CFPB penalties, disgorgement and class actions.",
             citation="12 U.S.C. 2607; 12 CFR 1024.14", kind="forbidden",
             input="Is anything of value given or received for referrals of settlement service business (including disguised marketing deals)?",
             sample=False,
             action="Stop the payments, end the arrangement and have counsel review any marketing services agreements."),
        Rule(key="trid_loan_estimate", title="Loan Estimate in 3 business days",
             cost="Late Loan Estimates are a leading exam finding and can force the lender to cover fee increases and pay borrower damages.",
             citation="12 CFR 1026.19(e)(1)(iii)(A)", kind="max",
             input="Business days since the application was received, without delivering or mailing the Loan Estimate",
             unit="business days", limit=3, warn=2, sample=2,
             action="Deliver or mail the Loan Estimate today."),
        Rule(key="trid_closing_disclosure", title="Closing Disclosure 3 days before close",
             cost="Closing before the waiting period ends is a TRID violation that forces delayed closings, cures and borrower damages.",
             citation="12 CFR 1026.19(f)(1)(ii)(A)", kind="min",
             input="Business days between the consumer's receipt of the Closing Disclosure and consummation",
             unit="business days", limit=3, warn=3, sample=2,
             action="Move the closing date so the consumer has the Closing Disclosure at least three business days before."),
        Rule(key="foreclosure_120_days", title="No foreclosure before 120 days late",
             cost="Filing foreclosure too early violates Regulation X, bringing borrower lawsuits, CFPB penalties and wrongful foreclosure costs.",
             citation="12 CFR 1024.41(f)(1)", kind="min",
             input="Days the loan will be delinquent on the date of the first foreclosure notice or filing (must be more than 120)",
             unit="days", limit=121, warn=121, sample=150,
             action="Do not file; wait until the loan is more than 120 days delinquent and check for pending loss mitigation."),
        Rule(key="ecoa_adverse_action", title="Adverse action notice in 30 days",
             cost="Missing or late adverse action notices are frequent exam findings and support ECOA lawsuits and CFPB enforcement.",
             citation="12 CFR 1002.9(a)(1)(i)", kind="max",
             input="Days since a completed application was denied or decided, without sending the adverse action notice",
             unit="days", limit=30, warn=25, sample=31,
             action="Send the adverse action notice with the specific principal reasons now."),
        Rule(key="safe_act_licensing", title="Loan originators licensed (NMLS)",
             cost="Unlicensed originators draw state fines and license actions, and loans they originate can face repurchase demands.",
             citation="12 U.S.C. 5103; 12 CFR Part 1007 and 1008", kind="required",
             input="Is every loan originator state-licensed through NMLS, or federally registered, before taking applications?",
             sample=True,
             action="Stop the originator from taking applications until the license or registration is active in NMLS."),
        Rule(key="servicing_error_notice", title="Resolve notices of error",
             cost="Ignoring or slow-walking borrower error notices violates RESPA, bringing actual and statutory damages and CFPB enforcement.",
             citation="12 CFR 1024.35(e)(3)(i)(C) (30 business days for most errors; shorter for payoff and foreclosure errors)", kind="max",
             input="Business days since a notice of error was received, without correcting it or responding in writing",
             unit="business days", limit=30, warn=25, sample=12,
             action="Correct the error or send the written determination now."),
        Rule(key="hmda_lar_filing", title="HMDA LAR filed by March 1",
             cost="Late or inaccurate HMDA data draws civil money penalties and required resubmission.",
             citation="12 CFR 1003.5(a)(1)(i)", kind="required",
             input="Was last year's HMDA loan application register submitted accurately by March 1?",
             sample=True,
             action="Submit the LAR now and correct and resubmit any data errors."),
        Rule(key="flood_insurance", title="Flood insurance in flood zones",
             cost="Missing flood insurance on loans in special flood hazard areas brings civil money penalties per violation and uninsured flood losses.",
             citation="42 U.S.C. 4012a; 12 CFR 22.3 (OCC), 12 CFR 339.3 (FDIC), 12 CFR 208.25 (Fed)", kind="required",
             input="For a property in a special flood hazard area, is required flood insurance in place at or before closing?",
             sample=False,
             action="Do not close until flood insurance is in place; send the borrower notice and force-place coverage if it lapses."),
    ],

    # --- 35. COLLECTARMOR (debt collectors and collection agencies) ---
    35: [
        Rule(key="tcpa_consent", title="Consent for autodialed cell calls",
             cost="TCPA class actions carry statutory damages per call with no cap, so calls to cell phones without consent can bring very large judgments.",
             citation="47 U.S.C. 227(b)(1)(A)(iii); 47 CFR 64.1200(a)(1)", kind="required",
             input="Is there prior express consent for every autodialed or prerecorded-voice call to a cell phone number?",
             sample=True,
             action="Stop autodialed and prerecorded calls to numbers without documented consent; dial them manually or not at all."),
        Rule(key="call_frequency_7in7", title="Call frequency 7 in 7 days",
             cost="Calling more than the Reg F presumption allows supports FDCPA harassment claims, class actions and CFPB enforcement.",
             citation="12 CFR 1006.14(b)(2)(i)(A)", kind="max",
             input="Call attempts to the consumer about this debt in the last 7 days",
             unit="calls", limit=7, warn=6, sample=6,
             action="Stop calling on this debt until the 7-day window allows another attempt."),
        Rule(key="validation_notice", title="Validation notice within 5 days",
             cost="A missing or late validation notice is a common FDCPA lawsuit claim and draws CFPB and state enforcement.",
             citation="15 U.S.C. 1692g(a); 12 CFR 1006.34(a)(1)", kind="max",
             input="Days since the initial communication, without sending the validation notice",
             unit="days", limit=5, warn=4, sample=7,
             action="Send the validation notice now and pause collection until the validation period is set."),
        Rule(key="call_hours", title="No calls before 8 a.m. or after 9 p.m.",
             cost="Calls at inconvenient hours are an FDCPA violation that supports individual and class lawsuits.",
             citation="15 U.S.C. 1692c(a)(1); 12 CFR 1006.6(b)(1)(i)", kind="forbidden",
             input="Were any calls placed before 8 a.m. or after 9 p.m. in the consumer's local time?",
             sample=False,
             action="Restrict the dialer to 8 a.m.-9 p.m. in the consumer's time zone, using all known time zones if unsure."),
        Rule(key="third_party_disclosure", title="No debt disclosure to third parties",
             cost="Telling employers, family or others about a debt brings FDCPA lawsuits, privacy claims and regulator actions.",
             citation="15 U.S.C. 1692c(b); 12 CFR 1006.6(d)(1)", kind="forbidden",
             input="Was the debt discussed with anyone other than the consumer, their spouse or attorney, or another permitted party?",
             sample=True,
             action="Stop the contact, retrain staff and review voicemail and letter templates that can reveal the debt."),
        Rule(key="time_barred_suits", title="No suits on time-barred debt",
             cost="Suing or threatening to sue on debt past the statute of limitations brings FDCPA liability, fee awards and enforcement.",
             citation="12 CFR 1006.26(b)", kind="forbidden",
             input="Has a lawsuit been filed, or threatened, on a debt past its statute of limitations?",
             sample=False,
             action="Dismiss or withdraw the suit or threat, and flag the account as time-barred."),
        Rule(key="cease_communication", title="Honor cease-communication requests",
             cost="Contacting a consumer after a written request to stop is an FDCPA violation that supports lawsuits and enforcement.",
             citation="15 U.S.C. 1692c(c); 12 CFR 1006.6(c)(1)", kind="forbidden",
             input="Was the consumer contacted after a written cease-communication request, other than a permitted final notice?",
             sample=False,
             action="Stop all contact on the account now except the notices the rule permits."),
        Rule(key="fcra_dispute_30_days", title="Credit report disputes in 30 days",
             cost="Failing to investigate credit reporting disputes brings FCRA lawsuits with actual, statutory and punitive damages and CFPB enforcement.",
             citation="15 U.S.C. 1681s-2(b), 1681i(a)(1); 12 CFR 1022.43(e)", kind="max",
             input="Days since the credit reporting dispute was received, without completing the investigation",
             unit="days", limit=30, warn=25, sample=26,
             action="Finish the investigation now and correct or delete inaccurate data with every bureau it was reported to."),
        Rule(key="no_debt_parking", title="No credit reporting before contact",
             cost="Reporting a debt before contacting the consumer (passive debt collection) violates Reg F and invites lawsuits and enforcement.",
             citation="12 CFR 1006.30(a)(1)", kind="forbidden",
             input="Was the debt reported to a credit bureau before speaking to the consumer or sending a notice and waiting for undeliverability?",
             sample=False,
             action="Pull the tradeline, contact the consumer, and wait a reasonable time (such as 14 days) for any undeliverable notice."),
        Rule(key="state_collection_license", title="State collection agency license",
             cost="Collecting without a required state license brings state fines, license denials and can void collections or support consumer suits.",
             citation="State collection agency licensing laws (policy; requirements vary by state)", kind="required",
             input="Does the agency hold a license, or a documented exemption, in every state where it collects from consumers?",
             policy=True, sample=True,
             action="Stop collecting from consumers in unlicensed states and apply for the license or confirm the exemption."),
    ],
}
