# -*- coding: utf-8 -*-
"""
Rule catalog, group 2: industries 6-10.

6  AIArmor       companies building or deploying AI systems
7  LibraryArmor  public libraries
8  SchoolArmor   K-12 schools
9  PropArmor     residential property managers and landlords
10 AutoArmor     new and used car dealerships
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 6. AIARMOR ---
    6: [
        Rule(key="post_market_drift", title="Post-market drift monitoring",
             cost="Unchecked drift in a high-risk AI system can lead to regulator orders to withdraw it from the market, fines and claims from people it harmed.",
             citation="EU AI Act Art. 15 (accuracy, robustness) and Art. 72 (post-market monitoring); threshold is your own policy",
             kind="max", input="Current model drift score from post-market monitoring",
             unit="", limit=0.15, warn=0.12, policy=True, sample=0.18,
             action="Pause the release and re-validate accuracy before redeploying.",
             method="ai_armor_eu_act_monitor"),
        Rule(key="bipa_biometric_consent", title="Written consent for biometrics",
             cost="Collecting face, voice or fingerprint data in Illinois without written consent brings class actions with statutory damages per violation.",
             citation="Illinois BIPA, 740 ILCS 14/15(a)-(b)",
             kind="required",
             input="Before collecting face, voice, fingerprint or other biometric data from Illinois residents, is signed written consent on file?",
             sample=True,
             action="Stop collecting biometric data from that person until written consent is signed; publish a retention policy."),
        Rule(key="gdpr_breach_72h", title="Report data breach within 72 hours",
             cost="Late breach reports to the data protection authority are a common GDPR finding and bring fines on top of the breach costs.",
             citation="GDPR Art. 33(1) (no later than 72 hours after becoming aware, unless the breach is unlikely to result in risk)",
             kind="max", input="Hours since becoming aware of a personal data breach not yet reported to the supervisory authority",
             unit="h", limit=72, warn=48, sample=60,
             action="Notify the supervisory authority now with what is known and send the rest in phases."),
        Rule(key="gdpr_access_request", title="Answer data requests in a month",
             cost="Late or missing replies to access and deletion requests are among the most common GDPR complaints and lead to fines and orders.",
             citation="GDPR Art. 12(3) (within one month; extendable by two months if the person is told); 30 days used here",
             kind="max", input="Days since a data subject request (access, deletion, objection) was received without a reply",
             unit="days", limit=30, warn=25, sample=12,
             action="Reply to the person today, or tell them of the extension and the reason if the request is complex."),
        Rule(key="gdpr_dpia", title="DPIA before high-risk processing",
             cost="Deploying AI that profiles or monitors people without a data protection impact assessment breaks GDPR and draws fines and stop orders.",
             citation="GDPR Art. 35(1) and 35(3)",
             kind="required",
             input="Was a data protection impact assessment completed before deploying AI that profiles, scores or monitors people?",
             sample=False,
             action="Pause the deployment until the impact assessment is done and signed off by the data protection officer."),
        Rule(key="nyc_candidate_notice", title="Notify candidates of hiring AI",
             cost="Using an automated hiring tool in NYC without advance candidate notice brings civil penalties for each violation.",
             citation="NYC Admin. Code 20-871(b) (at least 10 business days before use); 6 RCNY 5-303",
             kind="required",
             input="Were NYC candidates told at least 10 business days before the automated hiring tool was used on them?",
             sample=True,
             action="Hold the tool for these candidates until 10 business days after notice is given."),
        Rule(key="gdpr_processor_contract", title="Data contract with each AI vendor",
             cost="Sharing personal data with AI vendors or model hosts without a processor contract breaks GDPR and is a frequent audit finding.",
             citation="GDPR Art. 28(3)",
             kind="required",
             input="Is a signed data processing agreement in place with every vendor that processes personal data for your AI system?",
             sample=True,
             action="Stop sending personal data to the vendor until a data processing agreement is signed."),
        Rule(key="nyc_bias_audit", title="Annual bias audit for hiring AI",
             cost="Using an automated hiring tool in NYC without a current bias audit brings civil penalties for each day of use and each violation.",
             citation="NYC Admin. Code 20-871; 6 RCNY 5-300 et seq. (Local Law 144 of 2021)",
             kind="max", input="Days since the last independent bias audit of the automated hiring tool",
             unit="days", limit=365, warn=335, sample=380,
             action="Stop using the tool for NYC candidates until a new independent bias audit is done and its summary is published."),
        Rule(key="gdpr_automated_decision", title="Human review of automated decisions",
             cost="Solely automated decisions without safeguards break GDPR, bringing data protection fines, orders to stop processing and claims.",
             citation="GDPR Art. 22(3) (right to human intervention and to contest) and Art. 13(2)(f)",
             kind="required",
             input="Can people subject to solely automated decisions with legal or similar effects get human review and contest the decision?",
             sample=True,
             action="Route affected decisions to a human reviewer and tell people how to contest them before deciding more cases."),
        Rule(key="ai_claims_substantiated", title="No unproven AI marketing claims",
             cost="Unsupported claims about what an AI product can do are deceptive under the FTC Act, leading to FTC orders, redress and lawsuits.",
             citation="FTC Act Section 5, 15 U.S.C. 45(a)",
             kind="forbidden",
             input="Do any marketing materials make claims about the AI's accuracy or abilities that you cannot back with testing evidence?",
             sample=True,
             action="Pull the unsupported claims from all marketing now and keep only claims backed by documented testing."),
    ],

    # --- 7. LIBRARYARMOR ---
    7: [
        Rule(key="cipa_filter", title="CIPA internet filter active",
             cost="Libraries without a working filter lose E-rate and LSTA internet funding and may have to repay funds already received.",
             citation="CIPA, 47 U.S.C. 254(h)(6); 47 CFR 54.520; 20 U.S.C. 9134(f) (LSTA)",
             kind="required",
             input="Is a technology protection measure (filter) active on every public computer and on public Wi-Fi?",
             sample=True,
             action="Turn the filter back on for all public devices and Wi-Fi before patrons use them again.",
             method="library_armor_cipa_filter"),
        Rule(key="internet_safety_policy", title="Internet safety policy adopted",
             cost="Without an internet safety policy adopted after public notice and a hearing, the library cannot certify CIPA and loses E-rate discounts.",
             citation="CIPA, 47 U.S.C. 254(h)(6) and 254(l); 47 CFR 54.520",
             kind="required",
             input="Has the board adopted an internet safety policy after public notice and at least one public hearing or meeting?",
             sample=True,
             action="Give public notice, hold a hearing and adopt the policy before certifying CIPA on the next E-rate form."),
        Rule(key="erate_form470_wait", title="Wait 28 days after Form 470",
             cost="Signing a service contract before the bidding window closes breaks E-rate competitive bidding rules, and USAC denies or recovers the funding.",
             citation="47 CFR 54.503(c)(4) (wait at least 28 days after FCC Form 470 is posted)",
             kind="min", input="Days between posting FCC Form 470 and signing the service contract",
             unit="days", limit=28, warn=30, sample=21,
             action="Do not sign the contract; wait until 28 full days after the Form 470 posting and evaluate all bids received."),
        Rule(key="erate_record_retention", title="Keep E-rate records 10 years",
             cost="Missing E-rate records during an audit lets USAC recover funding the library already received.",
             citation="47 CFR 54.516(a) (10 years after the last day of service or the service delivery deadline)",
             kind="required",
             input="Are all E-rate bidding, contract, invoice and CIPA records kept for at least 10 years after the funding year?",
             sample=True,
             action="Stop any disposal of E-rate files and gather the missing records from vendors and USAC now."),
        Rule(key="erate_invoice_deadline", title="File E-rate invoice on time",
             cost="Missing the invoice deadline forfeits E-rate discounts the library was already approved for.",
             citation="47 CFR 54.514(a) (120 days after the last day to receive service, or later notice date)",
             kind="max", input="Days since the last day to receive service without filing the E-rate invoice (BEAR or SPI)",
             unit="days", limit=120, warn=90, sample=100,
             action="File the BEAR form or confirm the vendor filed its SPI invoice today; request an extension if still allowed."),
        Rule(key="exits_clear", title="Exits unlocked and clear",
             cost="Blocked or locked exits are among the most common fire inspection citations and bring fines and orders to close until fixed.",
             citation="NFPA 101 Life Safety Code or IFC Chapter 10, as adopted by the local fire code; adoption varies",
             kind="forbidden",
             input="Is any exit door, exit path or exit sign blocked, locked or out during open hours?",
             sample=False,
             action="Clear or unlock the exit now and check every exit before opening."),
        Rule(key="copier_copyright_notice", title="Copyright notice on copiers",
             cost="Without the notice the library can lose its protection and be held liable for infringing copies patrons make.",
             citation="17 U.S.C. 108(f)(1)",
             kind="required",
             input="Is a copyright warning notice posted on every public copier, scanner and printer?",
             sample=False,
             action="Post the copyright warning notice on each unsupervised copying device today."),
        Rule(key="film_public_performance", title="License for public film showings",
             cost="Showing films at public programs without a license is copyright infringement and can bring statutory damages and legal fees.",
             citation="17 U.S.C. 106(4) and 501; statutory damages under 17 U.S.C. 504(c)",
             kind="forbidden",
             input="Are films shown at public library programs without a public performance license?",
             sample=False,
             action="Cancel the showing until a public performance license covers the title."),
        Rule(key="patron_record_privacy", title="Patron records kept confidential",
             cost="Releasing patron records without the legal process state law requires brings lawsuits, penalties and loss of public trust.",
             citation="State library-records confidentiality law varies (e.g., N.Y. CPLR 4509, Cal. Gov. Code 7927.105)",
             kind="forbidden",
             input="Were any patron circulation or use records released without the consent, subpoena or court order your state law requires?",
             sample=False,
             action="Stop further release, send all requests to the director and legal counsel, and document what was disclosed."),
        Rule(key="fire_extinguisher_service", title="Annual fire extinguisher service",
             cost="Out-of-date extinguishers are a common fire inspection citation and can bring fines and orders to close rooms until fixed.",
             citation="NFPA 10 (annual maintenance) as adopted by the local fire code; adoption varies",
             kind="max", input="Days since the last annual fire extinguisher maintenance",
             unit="days", limit=365, warn=335, policy=True, sample=350,
             action="Book a licensed extinguisher service now and tag every unit after maintenance."),
    ],

    # --- 8. SCHOOLARMOR ---
    8: [
        Rule(key="ferpa_disclosure", title="FERPA consent before disclosure",
             cost="Improper release of student records can end federal education funding and brings complaints, corrective orders and lawsuits under state law.",
             citation="FERPA, 20 U.S.C. 1232g; 34 CFR 99.30 and 99.31",
             kind="required",
             input="Is every disclosure of student records covered by written consent or a 34 CFR 99.31 exception?",
             sample=False,
             action="Withhold the records until written consent is on file or a 99.31 exception is documented.",
             method="school_armor_ferpa_block"),
        Rule(key="ferpa_access_45_days", title="Give parents records in 45 days",
             cost="Missing the access deadline is a FERPA violation that leads to Department of Education complaints and corrective orders.",
             citation="FERPA, 34 CFR 99.10(b) (no more than 45 days after the request)",
             kind="max", input="Days since a parent or eligible student asked to inspect records",
             unit="days", limit=45, warn=35, sample=38,
             action="Schedule the records review with the parent immediately."),
        Rule(key="idea_initial_evaluation", title="IDEA evaluation within 60 days",
             cost="Late special education evaluations lead to due process claims, compensatory services, attorney fee awards and state findings.",
             citation="IDEA, 34 CFR 300.301(c)(1) (60 days from consent, or the state's own timeframe)",
             kind="max", input="Days since parent consent for an initial special education evaluation",
             unit="days", limit=60, warn=50, sample=64,
             action="Finish the evaluation now and hold the eligibility meeting; tell the parent of the delay in writing."),
        Rule(key="iep_annual_review", title="Review each IEP every year",
             cost="Expired IEPs deny required services, leading to due process claims, compensatory education and state monitoring findings.",
             citation="IDEA, 34 CFR 300.324(b)(1)(i) (at least annually)",
             kind="max", input="Days since the student's last IEP team review",
             unit="days", limit=365, warn=335, sample=340,
             action="Schedule the IEP meeting with the parent now and keep providing current services."),
        Rule(key="title_ix_coordinator", title="Title IX coordinator named",
             cost="No designated coordinator or notice of nondiscrimination is a Title IX violation that risks federal funding and lawsuits.",
             citation="Title IX, 34 CFR 106.8(a)-(b)",
             kind="required",
             input="Is a Title IX coordinator designated, with contact details published to students, parents and staff?",
             sample=True,
             action="Designate a coordinator and publish their contact details in the nondiscrimination notice today."),
        Rule(key="idea_reevaluation", title="IDEA reevaluation every 3 years",
             cost="Overdue reevaluations are a common state monitoring finding and lead to due process claims and compensatory services.",
             citation="IDEA, 34 CFR 300.303(b)(2) (at least once every three years unless parent and school agree it is unnecessary)",
             kind="max", input="Days since the student's last special education evaluation",
             unit="days", limit=1095, warn=1005, sample=1020,
             action="Get parent consent and start the reevaluation now, or document the agreement that it is not needed."),
        Rule(key="staff_background_check", title="Staff background checks cleared",
             cost="Hiring staff without the required checks exposes the district to negligent hiring lawsuits and state licensing penalties.",
             citation="State law varies (fingerprint-based state and FBI checks are common)",
             kind="required",
             input="Has every employee, volunteer and contractor with student contact cleared the background check your state requires?",
             sample=True,
             action="Remove the person from student contact until the background check clears."),
        Rule(key="edtech_student_data", title="Ed-tech apps vetted for privacy",
             cost="Apps that collect student data without proper authorization and limits bring FTC and state privacy actions and FERPA problems.",
             citation="COPPA, 16 CFR Part 312; FERPA, 34 CFR 99.31(a)(1)(i)(B)",
             kind="required",
             input="Does every ed-tech tool that collects student data have school approval and a signed agreement limiting data use to school purposes?",
             sample=False,
             action="Stop student use of unapproved tools until the vendor signs a data agreement."),
        Rule(key="ahera_reinspection", title="AHERA asbestos reinspection",
             cost="Missed asbestos reinspections are a frequent EPA citation and bring civil penalties plus costly cleanup if materials are disturbed.",
             citation="AHERA, 40 CFR 763.85(b) (reinspection at least once every three years)",
             kind="max", input="Days since the last accredited AHERA asbestos reinspection",
             unit="days", limit=1095, warn=1005, sample=1050,
             action="Hire an accredited inspector to reinspect now and update the management plan."),
        Rule(key="food_safety_inspections", title="Two food safety inspections",
             cost="Missing required inspections is a USDA review finding that can lead to corrective action and withheld meal reimbursements.",
             citation="42 U.S.C. 1758(h); 7 CFR 210.13(b) (two inspections each school year)",
             kind="required",
             input="Has each school kitchen had two state or local food safety inspections this school year?",
             sample=True,
             action="Request the missing inspection from the local health department and post the latest report."),
    ],

    # --- 9. PROPARMOR ---
    9: [
        Rule(key="deposit_separate_account", title="Deposits in a separate account",
             cost="Mixing tenant deposits with operating cash can forfeit the right to keep any deposit and brings damages, penalties and license action.",
             citation="State trust-account and security-deposit law varies (e.g., N.Y. Gen. Oblig. Law 7-103, Fla. Stat. 83.49)",
             kind="required",
             input="Are all tenant security deposits held in a separate trust or escrow account?",
             sample=False,
             action="Move tenant deposits to the separate trust or escrow account now.",
             method="prop_armor_escrow_isolation"),
        Rule(key="deposit_return_deadline", title="Return deposit on time",
             cost="Late deposit returns or missing itemized statements can forfeit deductions and bring statutory penalties and attorney fees.",
             citation="State law varies (e.g., Cal. Civ. Code 1950.5(g): 21 days); set the limit to your state's deadline",
             kind="max", input="Days since move-out without returning the deposit or an itemized list of deductions",
             unit="days", limit=21, warn=17, policy=True, sample=10,
             action="Send the deposit balance and an itemized statement of deductions today."),
        Rule(key="lead_disclosure", title="Lead paint disclosure before lease",
             cost="Missing lead disclosures for pre-1978 housing bring EPA and HUD civil penalties and damages lawsuits from tenants.",
             citation="42 U.S.C. 4852d; 24 CFR 35.88-35.92; 40 CFR 745.107 and 745.113(b)",
             kind="required",
             input="For pre-1978 units, are the lead disclosure form and EPA lead pamphlet given and signed before the tenant is bound by the lease?",
             sample=True,
             action="Do not sign or renew the lease until the tenant receives and signs the lead disclosure and pamphlet."),
        Rule(key="lead_safe_renovation", title="Certified firm for paint work",
             cost="Paint-disturbing work in pre-1978 housing by uncertified crews is a common EPA violation bringing civil penalties per violation.",
             citation="EPA Renovation, Repair and Painting Rule, 40 CFR 745.81, 745.85 and 745.89",
             kind="required",
             input="Is repair work that disturbs paint in pre-1978 units done by an EPA-certified firm using lead-safe practices?",
             sample=False,
             action="Stop the work until an EPA-certified firm and renovator take over with lead-safe practices."),
        Rule(key="fha_advertising", title="No discriminatory ads",
             cost="Ads showing a preference based on a protected class break the Fair Housing Act, bringing HUD charges, DOJ suits and damages.",
             citation="Fair Housing Act, 42 U.S.C. 3604(c); 24 CFR 100.75",
             kind="forbidden",
             input="Do any listings or ads state a preference or limit based on race, color, religion, sex, disability, familial status or national origin?",
             sample=False,
             action="Take down the listing and rewrite it to describe the unit, not the tenant."),
        Rule(key="reasonable_accommodation", title="Answer accommodation requests",
             cost="Denying or ignoring disability accommodation requests, including assistance animals, is a top source of fair housing complaints and damages.",
             citation="Fair Housing Act, 42 U.S.C. 3604(f)(3)(B); 24 CFR 100.204",
             kind="required",
             input="Is every accommodation request, including for assistance animals, reviewed and answered without charging pet fees or deposits?",
             sample=False,
             action="Review the pending request now, refund any pet fee charged for an assistance animal and reply in writing."),
        Rule(key="fcra_adverse_action", title="Adverse action notice to applicant",
             cost="Denying an applicant based on a screening report without the required notice brings FCRA lawsuits, damages and CFPB or FTC action.",
             citation="FCRA, 15 U.S.C. 1681m(a)",
             kind="required",
             input="Does every applicant denied or charged more because of a screening report get an adverse action notice?",
             sample=True,
             action="Send the adverse action notice with the screening company's details and dispute rights today."),
        Rule(key="deposit_cap", title="Security deposit within legal cap",
             cost="Charging more than the state deposit cap brings refunds, statutory penalties and tenant lawsuits.",
             citation="State law varies (e.g., Cal. Civ. Code 1950.5(c), N.Y. Gen. Oblig. Law 7-108(1-a)(a): one month); set to your state's cap",
             kind="max", input="Security deposit charged, as months of rent",
             unit="months", limit=1, policy=True, sample=1.5,
             action="Refund the amount over the cap to the tenant now and fix the lease template."),
        Rule(key="smoke_co_alarms", title="Working smoke and CO alarms",
             cost="Missing or dead alarms are a common code citation and expose the owner to fines and injury or death lawsuits after a fire.",
             citation="State law and locally adopted fire code vary (e.g., IFC Sections 907.2.11 and 915)",
             kind="required",
             input="Does every unit have working smoke alarms, and carbon monoxide alarms where fuel-burning appliances or attached garages exist?",
             sample=True,
             action="Install or replace the missing alarms today and test each one."),
        Rule(key="no_self_help_eviction", title="No lockouts or utility shutoffs",
             cost="Evicting without a court order through lockouts or shutoffs brings statutory damages, penalties and tenant lawsuits.",
             citation="State landlord-tenant law varies (e.g., Cal. Civ. Code 789.3, Fla. Stat. 83.67)",
             kind="forbidden",
             input="Has any tenant been locked out, had utilities shut off or had belongings removed without a court order?",
             sample=False,
             action="Restore access and utilities immediately and use the court eviction process instead."),
    ],

    # --- 10. AUTOARMOR ---
    10: [
        Rule(key="used_car_buyers_guide", title="Buyers Guide on every used car",
             cost="Missing Buyers Guides are a top FTC Used Car Rule citation and bring civil penalties per vehicle.",
             citation="FTC Used Car Rule, 16 CFR 455.2",
             kind="required",
             input="Is a completed Buyers Guide posted on every used vehicle offered for sale?",
             sample=False,
             action="Hold the vehicle from sale and post a completed Buyers Guide before showing it.",
             method="auto_armor_ftc_sticker_check"),
        Rule(key="safeguards_mfa", title="Multi-factor login for customer data",
             cost="Weak access controls on customer data break the FTC Safeguards Rule and invite FTC orders, breach costs and lawsuits.",
             citation="FTC Safeguards Rule, 16 CFR 314.4(c)(5)",
             kind="required",
             input="Is multi-factor authentication required for everyone who accesses customer information systems?",
             sample=False,
             action="Turn on multi-factor authentication for all DMS, CRM and email accounts before further access."),
        Rule(key="safeguards_ftc_breach_notice", title="Notify FTC of data breach",
             cost="Failing to report a breach of 500 or more customers breaks the Safeguards Rule and raises FTC enforcement risk.",
             citation="FTC Safeguards Rule, 16 CFR 314.4(j) (no later than 30 days after discovery)",
             kind="max", input="Days since discovering a breach affecting 500 or more customers that is not yet reported to the FTC",
             unit="days", limit=30, warn=20, sample=24,
             action="File the notification through the FTC's online form today."),
        Rule(key="red_flags_program", title="Identity theft program in place",
             cost="Dealers that arrange financing without a written identity theft program break the Red Flags Rule and risk FTC penalties and fraud losses.",
             citation="FTC Red Flags Rule, 16 CFR 681.1(d)",
             kind="required",
             input="Does the dealership have a written, board-approved Identity Theft Prevention Program that staff follow on credit deals?",
             sample=True,
             action="Adopt a written Red Flags program and train F&I staff before taking more credit applications."),
        Rule(key="odometer_disclosure", title="Odometer disclosure on transfer",
             cost="Missing or false odometer statements bring federal civil penalties and damages suits from buyers.",
             citation="49 U.S.C. 32705; 49 CFR 580.5 (see 580.17 for exempt vehicles)",
             kind="required",
             input="Is a signed odometer disclosure statement completed for every non-exempt vehicle transfer?",
             sample=True,
             action="Hold the title transfer until the odometer disclosure is completed and signed."),
        Rule(key="form_8300_cash", title="File Form 8300 for cash over $10,000",
             cost="Late or missing Form 8300 filings bring IRS penalties, and intentional disregard carries much larger penalties.",
             citation="26 U.S.C. 6050I; 26 CFR 1.6050I-1 (file within 15 days of receiving more than $10,000 in cash)",
             kind="max", input="Days since receiving more than $10,000 in cash in one or related transactions without filing Form 8300",
             unit="days", limit=15, warn=10, sample=16,
             action="File Form 8300 today and send the buyer the required written statement by January 31."),
        Rule(key="reg_z_credit_ads", title="Complete terms in credit ads",
             cost="Ads that give a payment or down payment without the APR and terms break Truth in Lending and bring CFPB, FTC and state action.",
             citation="TILA, Regulation Z, 12 CFR 1026.24(d)",
             kind="forbidden",
             input="Does any credit ad state a payment, down payment or number of payments without also stating the APR and repayment terms?",
             sample=True,
             action="Pull the ad and add the down payment, repayment terms and APR before it runs again."),
        Rule(key="tila_disclosures", title="TILA disclosures before signing",
             cost="Missing or wrong credit disclosures bring TILA lawsuits, statutory damages, attorney fees and regulator action.",
             citation="TILA, Regulation Z, 12 CFR 1026.17(b) and 1026.18",
             kind="required",
             input="Does every credit buyer get written APR, finance charge, amount financed and total of payments disclosures before signing?",
             sample=True,
             action="Stop the deal and give the buyer the correct TILA disclosures before they sign."),
        Rule(key="new_car_open_recall", title="No new car sold with open recall",
             cost="Selling a new vehicle with an unrepaired safety recall breaks federal law, bringing NHTSA civil penalties and injury lawsuits.",
             citation="49 U.S.C. 30120(i)",
             kind="forbidden",
             input="Is any new vehicle with an open safety recall being sold or delivered before the recall repair is done?",
             sample=False,
             action="Hold delivery until the recall repair is completed and documented."),
        Rule(key="safeguards_pen_test", title="Annual penetration test",
             cost="Skipping required security testing breaks the FTC Safeguards Rule and leaves customer data open to costly breaches.",
             citation="FTC Safeguards Rule, 16 CFR 314.4(d)(2)(i) (annual); 314.6 exempts institutions with under 5,000 consumers",
             kind="max", input="Days since the last penetration test of customer information systems",
             unit="days", limit=365, warn=335, sample=400,
             action="Book a qualified penetration test now and track fixes for every finding."),
    ],
}
