# -*- coding: utf-8 -*-
"""
Rule catalog, group 6: SeniorArmor, DentalArmor, PharmacyArmor, BuildArmor
and HRArmor. Ten rules per industry, costliest first. None of these
industries has a detailed check yet, so no rule sets `method`.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 26. SENIORARMOR (nursing homes and assisted living) ---
    26: [
        Rule(key="abuse_report_2_hours", title="Abuse allegation reported in 2 hours",
             cost="Late abuse reporting is cited as immediate jeopardy, bringing civil money penalties, payment denials and possible loss of Medicare certification.",
             citation="42 CFR 483.12(c)(1); Elder Justice Act, 42 U.S.C. 1320b-25(b)", kind="max",
             input="Hours since staff learned of an allegation involving abuse or serious bodily injury, without reporting it to the administrator and state agency",
             unit="h", limit=2, warn=1.5, sample=3,
             action="Report now to the administrator and the state survey agency (and law enforcement if a crime is suspected); protect the resident."),
        Rule(key="abuse_investigation_5_days", title="Abuse investigation results filed",
             cost="Incomplete or late investigations are cited under abuse and neglect tags, which draw civil money penalties and lawsuits from families.",
             citation="42 CFR 483.12(c)(4)", kind="max",
             input="Working days since the incident without reporting investigation results to the administrator and state survey agency",
             unit="working days", limit=5, warn=4, sample=2,
             action="Finish the investigation and send the results to the administrator and state survey agency today."),
        Rule(key="fall_supervision", title="Fall prevention and supervision",
             cost="Falls from missing supervision or devices are frequently cited deficiencies and a common cause of wrongful-death and injury lawsuits.",
             citation="42 CFR 483.25(d)", kind="required",
             input="Does every resident assessed as a fall risk have care-planned interventions and supervision that staff are actually carrying out?",
             sample=False,
             action="Reassess each fall-risk resident, update the care plan with supervision and devices, and brief every shift."),
        Rule(key="pressure_injury_prevention", title="Pressure injury prevention",
             cost="Avoidable pressure injuries are cited as harm or immediate jeopardy and are a common basis for neglect lawsuits and penalties.",
             citation="42 CFR 483.25(b)(1)", kind="required",
             input="Is every resident at risk for pressure injuries on a documented skin-check and repositioning plan that staff follow?",
             sample=True,
             action="Assess skin for all at-risk residents now, start repositioning and support surfaces, and notify the physician of any wound."),
        Rule(key="infection_preventionist", title="Infection preventionist on staff",
             cost="Infection control is a frequently cited nursing home deficiencies and can lead to civil money penalties and outbreak lawsuits.",
             citation="42 CFR 483.80(a)-(b)", kind="required",
             input="Is a specially trained infection preventionist designated and working at least part-time at the facility?",
             sample=True,
             action="Designate a qualified infection preventionist who has completed specialized training, and document the assignment."),
        Rule(key="prn_psychotropic_14_days", title="PRN psychotropic 14-day limit",
             cost="Unnecessary or open-ended psychotropic orders are cited as chemical restraint and unnecessary drugs, drawing penalties and lawsuits.",
             citation="42 CFR 483.45(e)(4)-(5)", kind="max",
             input="Days an as-needed (PRN) psychotropic order has been in effect without a prescriber's documented renewal",
             unit="days", limit=14, warn=12, sample=13,
             action="Stop using the PRN order until the prescriber evaluates the resident and documents the rationale and duration."),
        Rule(key="rn_8_hours_daily", title="RN on duty 8 hours every day",
             cost="Missing RN coverage is cited as a staffing deficiency, can lower star ratings and draws civil money penalties.",
             citation="42 U.S.C. 1395i-3(b)(4)(C)(i); 42 CFR 483.35(b)", kind="required",
             input="Is a registered nurse on duty for at least 8 consecutive hours today?",
             sample=True,
             action="Schedule or call in a registered nurse to cover at least 8 consecutive hours today."),
        Rule(key="mds_admission_14_days", title="Admission MDS within 14 days",
             cost="Late MDS assessments are cited in surveys and can delay or reduce Medicare and Medicaid payment for the stay.",
             citation="42 CFR 483.20(b)(2)(i)", kind="max",
             input="Calendar days since admission without a completed comprehensive admission assessment (MDS)",
             unit="days", limit=14, warn=12, sample=9,
             action="Complete and sign the comprehensive admission assessment today and transmit it as required."),
        Rule(key="pbj_submission", title="Payroll-Based Journal submitted",
             cost="Missing or late PBJ staffing data lowers the facility's Care Compare staffing rating, which cuts referrals, and can be cited.",
             citation="42 CFR 483.70 (PBJ staffing data); CMS PBJ deadline 45 days after quarter end", kind="max",
             input="Days since the end of the quarter without submitting Payroll-Based Journal staffing data",
             unit="days", limit=45, warn=35, sample=38,
             action="Submit the quarter's payroll-based staffing data to CMS now and confirm it was accepted."),
        Rule(key="emergency_plan_annual", title="Emergency plan reviewed yearly",
             cost="An outdated emergency plan is cited in surveys, and poor disaster response can bring penalties, evacuations and lawsuits.",
             citation="42 CFR 483.73(a)", kind="max",
             input="Days since the emergency preparedness plan was last reviewed and updated",
             unit="days", limit=365, warn=335, sample=400,
             action="Review and update the emergency plan, risk assessment and communication plan now, and document the review."),
    ],

    # --- 27. DENTALARMOR (dental and small medical practices) ---
    27: [
        Rule(key="no_false_claims", title="No false or unsupported claims",
             cost="Billing for services not provided or not documented brings False Claims Act damages, penalties and exclusion from Medicare and Medicaid.",
             citation="31 U.S.C. 3729; 42 U.S.C. 1320a-7a", kind="forbidden",
             input="Did a chart audit find claims billed at a higher code, or for services not provided or not documented?",
             sample=False,
             action="Stop billing the affected codes, correct the documentation process, and refund any overpayments."),
        Rule(key="overpayment_60_days", title="Overpayments returned in 60 days",
             cost="Keeping an identified Medicare or Medicaid overpayment past the deadline turns it into a False Claims Act liability.",
             citation="42 U.S.C. 1320a-7k(d); 42 CFR 401.305", kind="max",
             input="Days since an overpayment was identified without reporting and returning it",
             unit="days", limit=60, warn=45, sample=50,
             action="Report and return the overpayment to the payer now, with a written explanation of the reason."),
        Rule(key="hipaa_risk_analysis", title="HIPAA security risk analysis",
             cost="A missing risk analysis is the most common finding in HIPAA enforcement, leading to settlements, penalties and ransomware losses.",
             citation="45 CFR 164.308(a)(1)(ii)(A)", kind="required",
             input="Has the practice completed and documented a current security risk analysis covering all systems with patient data?",
             sample=False,
             action="Complete a documented risk analysis of all electronic patient data and start a plan to fix the risks found."),
        Rule(key="breach_notice_60_days", title="Breach notice within 60 days",
             cost="Late breach notices draw HHS civil money penalties, state attorney general actions and patient lawsuits.",
             citation="45 CFR 164.404(b)", kind="max",
             input="Calendar days since a breach of unsecured patient information was discovered without notifying affected patients",
             unit="days", limit=60, warn=45, sample=20,
             action="Send written notice to every affected patient now, and notify HHS (and media if 500+ in a state) as required."),
        Rule(key="hepb_vaccine_offer", title="Hepatitis B vaccine offered",
             cost="Not offering the vaccine is a frequently cited OSHA bloodborne pathogens violation and raises workers' compensation exposure.",
             citation="29 CFR 1910.1030(f)(2)(i)", kind="max",
             input="Working days since a new employee with blood exposure was assigned without being offered the hepatitis B vaccine",
             unit="working days", limit=10, warn=8, sample=4,
             action="Offer the hepatitis B vaccine series at no cost now, or get a signed declination form."),
        Rule(key="exposure_control_plan", title="Exposure control plan annual review",
             cost="An outdated bloodborne pathogens exposure control plan is among the OSHA citations most often issued to dental and medical offices.",
             citation="29 CFR 1910.1030(c)(1)(iv)", kind="max",
             input="Days since the written exposure control plan was last reviewed and updated",
             unit="days", limit=365, warn=335, sample=350,
             action="Review and update the exposure control plan now, including safer sharps devices and staff input."),
        Rule(key="hazard_communication", title="Chemical hazard communication",
             cost="Missing safety data sheets or chemical training is frequently cited by OSHA and draws per-violation penalties.",
             citation="29 CFR 1910.1200(e), (g), (h)", kind="required",
             input="Is there a written hazard communication program, a safety data sheet for every chemical used, and trained staff?",
             sample=True,
             action="Collect missing safety data sheets, update the written program and chemical list, and train staff."),
        Rule(key="sterilizer_spore_test", title="Weekly sterilizer spore test",
             cost="A failed or untested sterilizer can force patient notification and testing, board discipline and infection lawsuits.",
             citation="CDC Guidelines for Infection Control in Dental Health-Care Settings (2003); common policy", kind="max",
             input="Days since each sterilizer last had a biological (spore) test",
             unit="days", limit=7, warn=6, policy=True, sample=9,
             action="Run a spore test on the sterilizer today and hold instruments until results are negative."),
        Rule(key="dea_registration_current", title="DEA registration current",
             cost="Prescribing or storing controlled substances without a valid DEA registration is unlawful and can bring DEA penalties and board discipline.",
             citation="21 U.S.C. 822; 21 CFR 1301.13", kind="min",
             input="Days until the practitioner's DEA registration for this location expires",
             unit="days", limit=0, warn=60, sample=45,
             action="Stop prescribing controlled substances and renew the DEA registration online now."),
        Rule(key="amalgam_separator", title="Amalgam separator in use",
             cost="Discharging amalgam without a compliant separator violates Clean Water Act pretreatment rules and can bring enforcement by the local sewer authority.",
             citation="40 CFR 441.30; 40 CFR 441.40; 40 CFR 441.50", kind="required",
             input="If the office places or removes amalgam, is an ISO 11143-compliant amalgam separator installed, maintained and on file?",
             sample=True,
             action="Install or repair a compliant amalgam separator, follow the best management practices, and file the compliance report."),
    ],

    # --- 28. PHARMACYARMOR (retail and independent pharmacies) ---
    28: [
        Rule(key="corresponding_responsibility", title="Controlled Rx red flags resolved",
             cost="Filling illegitimate controlled-substance prescriptions brings DEA registration loss, civil penalties and opioid lawsuits.",
             citation="21 CFR 1306.04(a); 21 CFR 1306.06", kind="required",
             input="Are red flags on controlled-substance prescriptions resolved and documented before dispensing?",
             sample=True,
             action="Do not dispense until the red flag is resolved with the prescriber and documented; refuse if it cannot be."),
        Rule(key="biennial_inventory", title="Biennial controlled-drug inventory",
             cost="Missing inventories are recordkeeping violations under the Controlled Substances Act and carry civil penalties per violation.",
             citation="21 CFR 1304.11(c)", kind="max",
             input="Days since the last complete controlled-substance inventory",
             unit="days", limit=730, warn=670, sample=700,
             action="Take a complete inventory of all controlled substances now and keep it on file for DEA inspection."),
        Rule(key="theft_loss_report", title="Theft or loss reported to DEA",
             cost="Unreported theft or significant loss of controlled substances draws DEA civil penalties and can put the pharmacy's registration at risk.",
             citation="21 CFR 1301.76(b)", kind="max",
             input="Business days since discovering a theft or significant loss of controlled substances without notifying DEA in writing",
             unit="business days", limit=1, warn=1, sample=2,
             action="Notify the DEA field division in writing now, then complete DEA Form 106 and notify police as appropriate."),
        Rule(key="emergency_cii_7_days", title="Emergency C-II follow-up in 7 days",
             cost="Dispensing an emergency oral Schedule II prescription without the follow-up prescription is a Controlled Substances Act violation.",
             citation="21 CFR 1306.11(d)(4)", kind="max",
             input="Days since dispensing an emergency oral Schedule II prescription without receiving the prescriber's follow-up prescription",
             unit="days", limit=7, warn=5, sample=3,
             action="Notify the nearest DEA Diversion office that the follow-up prescription was not received."),
        Rule(key="ciii_iv_refill_limit", title="C-III/IV refill limit",
             cost="Refilling Schedule III or IV prescriptions past legal limits is a Controlled Substances Act violation that draws DEA penalties.",
             citation="21 CFR 1306.22(a)", kind="max",
             input="Refill number about to be dispensed on this Schedule III or IV prescription (also must be within 6 months of issue)",
             unit="refills", limit=5, warn=5, sample=6,
             action="Do not refill; get a new prescription from the prescriber."),
        Rule(key="dscsa_trading_partners", title="DSCSA supplier and product checks",
             cost="Buying from unauthorized sources or without transaction data violates the DSCSA and risks counterfeit drugs, FDA action and lawsuits.",
             citation="21 U.S.C. 360eee-1(d)", kind="required",
             input="Does the pharmacy buy only from authorized trading partners, keep transaction data, and quarantine suspect product?",
             sample=True,
             action="Stop buying from the unverified source, quarantine the product, investigate, and notify FDA if it is illegitimate."),
        Rule(key="sterile_compounding_cert", title="Sterile compounding room certified",
             cost="Uncertified cleanrooms can lead to state board shutdown of compounding, FDA action and contamination lawsuits.",
             citation="USP <797> (every 6 months); enforced through state boards, state law varies", kind="max",
             input="Days since the sterile compounding hoods and cleanroom were last certified",
             unit="days", limit=180, warn=160, policy=True, sample=150,
             action="Stop sterile compounding in the affected area until it is recertified by a qualified certifier."),
        Rule(key="exclusion_screening", title="Staff checked for exclusion",
             cost="Employing an excluded person makes claims they touch unpayable and brings OIG civil money penalties.",
             citation="42 U.S.C. 1320a-7a(a)(6); OIG guidance; monthly screening is common policy", kind="max",
             input="Days since all staff were last checked against the OIG exclusion list",
             unit="days", limit=31, warn=25, policy=True, sample=40,
             action="Screen all staff against the OIG exclusion list now and remove any excluded person from covered work."),
        Rule(key="patient_counseling_offer", title="Counseling offered to patients",
             cost="Failing to offer counseling violates state pharmacy rules and Medicaid standards, and missed counseling is cited in malpractice claims.",
             citation="42 U.S.C. 1396r-8(g)(2)(A)(ii); state law varies", kind="required",
             input="Is every patient offered pharmacist counseling on new prescriptions, with refusals documented?",
             sample=False,
             action="Offer counseling at pickup for every new prescription and document the offer or refusal."),
        Rule(key="license_current", title="Pharmacy staff licenses current",
             cost="Working with an expired pharmacist, technician or pharmacy license brings state board discipline and makes claims unpayable.",
             citation="State pharmacy practice acts; renewal cycles vary by state", kind="min",
             input="Days until the earliest pharmacist, technician or pharmacy permit expiration",
             unit="days", limit=0, warn=60, policy=True, sample=90,
             action="Remove the unlicensed person from duty or stop operating under the expired permit until it is renewed."),
    ],

    # --- 29. BUILDARMOR (construction contractors) ---
    29: [
        Rule(key="fall_protection_6ft", title="Fall protection at 6 feet",
             cost="Fall protection is frequently cited by OSHA, and falls lead to serious penalties, stop-work orders and injury lawsuits.",
             citation="29 CFR 1926.501(b)(1)", kind="required",
             input="Are all workers 6 feet or more above a lower level protected by guardrails, safety nets or personal fall arrest systems?",
             sample=False,
             action="Stop work at height until guardrails, nets or personal fall arrest systems are in place."),
        Rule(key="trench_protection_5ft", title="Trench protection at 5 feet",
             cost="Unprotected trenches cause fatal cave-ins and draw willful OSHA citations, possible criminal referral and wrongful-death suits.",
             citation="29 CFR 1926.652(a)(1)", kind="required",
             input="Is every trench 5 feet or deeper that workers enter protected by sloping, shoring or a trench box (unless in stable rock)?",
             sample=True,
             action="Get everyone out of the trench now; do not re-enter until a protective system is installed."),
        Rule(key="trench_daily_inspection", title="Daily trench inspection",
             cost="Skipping competent-person inspections is a common OSHA excavation citation and leaves hazards unnoticed before cave-ins.",
             citation="29 CFR 1926.651(k)(1)", kind="required",
             input="Did a competent person inspect each open excavation today before work and after any rain or other hazard-increasing event?",
             sample=True,
             action="Keep workers out until a competent person inspects the excavation and protective system."),
        Rule(key="scaffold_fall_protection", title="Scaffold fall protection over 10 ft",
             cost="Scaffold violations are frequently cited by OSHA, and scaffold falls lead to penalties and injury lawsuits.",
             citation="29 CFR 1926.451(g)(1)", kind="required",
             input="Are workers on scaffolds more than 10 feet above a lower level protected by guardrails or personal fall arrest systems?",
             sample=True,
             action="Clear the scaffold until guardrails or personal fall arrest systems are installed."),
        Rule(key="ladder_extension_3ft", title="Ladder extends 3 ft above landing",
             cost="Ladder violations are frequently cited by OSHA and a frequent cause of injury claims.",
             citation="29 CFR 1926.1053(b)(1)", kind="min",
             input="Feet the portable ladder's side rails extend above the upper landing (if no grab rail is provided)",
             unit="ft", limit=3, warn=3, sample=2,
             action="Reposition or replace the ladder so the rails extend 3 feet above the landing, or secure it and add a grab device."),
        Rule(key="silica_exposure", title="Silica exposure limit",
             cost="Silica overexposure is a frequently cited OSHA health standard and leads to occupational disease claims.",
             citation="29 CFR 1926.1153(d) (PEL); action level 25 in 1926.1153(b)", kind="max",
             input="Measured respirable crystalline silica exposure, 8-hour average (if not following Table 1 controls)",
             unit="µg/m³", limit=50, warn=25, sample=30,
             action="Add dust controls such as water or vacuum, provide respirators, and restrict access until exposure is below the limit."),
        Rule(key="crane_operator_certified", title="Crane operator certified",
             cost="Uncertified operators draw OSHA citations, and crane incidents lead to deaths, property damage and very large lawsuits.",
             citation="29 CFR 1926.1427(a)", kind="required",
             input="Is every crane operator on site certified or qualified for the equipment type and evaluated by the employer?",
             sample=True,
             action="Do not operate the crane until a certified and evaluated operator is assigned."),
        Rule(key="prevailing_wage", title="Davis-Bacon prevailing wages paid",
             cost="Underpaying prevailing wages brings back-wage orders, withheld contract payments and possible debarment from federal work.",
             citation="40 U.S.C. 3142; 29 CFR 5.5(a)(1)", kind="forbidden",
             input="Is any worker on a federally funded job paid less than the prevailing wage and fringe benefits for their classification?",
             sample=False,
             action="Pay back wages to affected workers now and correct their classification and rates on the next payroll."),
        Rule(key="certified_payroll", title="Weekly certified payroll",
             cost="Late or missing certified payrolls let the agency withhold contract payments and can lead to debarment.",
             citation="29 CFR 5.5(a)(3)(ii); 29 CFR 3.4(a)", kind="max",
             input="Days since the regular pay date for a Davis-Bacon payroll week without submitting its certified payroll",
             unit="days", limit=7, warn=5, sample=6,
             action="Submit the signed certified payroll and statement of compliance for the week now."),
        Rule(key="rrp_lead_safe", title="EPA lead-safe certification",
             cost="Disturbing paint in pre-1978 homes without RRP certification brings EPA civil penalties and lead-poisoning lawsuits.",
             citation="40 CFR 745.81(a); 40 CFR 745.89", kind="required",
             input="For work disturbing paint in pre-1978 homes or child-occupied facilities, is the firm EPA-certified with a certified renovator assigned?",
             sample=True,
             action="Stop paint-disturbing work until the firm is certified and a certified renovator directs lead-safe practices."),
    ],

    # --- 30. HRARMOR (every employer) ---
    30: [
        Rule(key="overtime_pay", title="Overtime paid over 40 hours",
             cost="Unpaid overtime brings back wages plus equal liquidated damages, attorney fees and class or collective action lawsuits.",
             citation="29 U.S.C. 207(a)(1)", kind="required",
             input="Is every non-exempt employee paid 1.5 times the regular rate for all hours over 40 in a workweek?",
             sample=False,
             action="Pay the unpaid overtime on the next payroll and fix timekeeping so all hours over 40 are paid at 1.5x."),
        Rule(key="exempt_salary_level", title="Exempt salary threshold",
             cost="Misclassified exempt employees are owed back overtime plus liquidated damages and attorney fees.",
             citation="29 CFR 541.600(a); higher state thresholds may apply", kind="min",
             input="Weekly salary paid to an employee classified as exempt (executive, administrative or professional)",
             unit="$", limit=684, warn=720, sample=650,
             action="Reclassify the employee as non-exempt and pay overtime, or raise the salary to at least the threshold."),
        Rule(key="minimum_wage", title="Federal minimum wage paid",
             cost="Minimum wage violations bring back wages plus equal liquidated damages and Department of Labor penalties for repeat violations.",
             citation="29 U.S.C. 206(a)(1)(C); higher state or local minimums may apply", kind="min",
             input="Lowest hourly rate paid to any non-exempt employee",
             unit="$", limit=7.25, warn=7.25, sample=12.0,
             action="Raise the rate to at least the federal minimum (or higher state or local rate) and pay the difference owed."),
        Rule(key="i9_section_2", title="Form I-9 done within 3 business days",
             cost="Missing or late I-9s are the most common immigration audit finding and bring per-form civil penalties.",
             citation="8 CFR 274a.2(b)(1)(ii)", kind="max",
             input="Business days since the new hire's first day of work without a completed I-9 Section 2",
             unit="business days", limit=3, warn=2, sample=2,
             action="Examine the employee's documents and complete Section 2 of Form I-9 today."),
        Rule(key="hours_records", title="Hours worked records kept",
             cost="Without accurate time records, courts accept employee estimates of hours owed, making wage lawsuits hard to defend.",
             citation="29 CFR 516.2(a)(7); 29 CFR 516.5-516.6", kind="required",
             input="Are hours worked each day and each week recorded and kept for every non-exempt employee?",
             sample=True,
             action="Start recording daily and weekly hours for every non-exempt employee and keep payroll records for 3 years."),
        Rule(key="aca_coverage_offer", title="ACA coverage offer (50+ FTEs)",
             cost="Large employers that do not offer coverage to enough full-time employees owe IRS employer shared responsibility payments.",
             citation="26 U.S.C. 4980H(a); 26 CFR 54.4980H-4(a)", kind="min",
             input="Percent of full-time employees (and dependents) offered minimum essential coverage this month",
             unit="%", limit=95, warn=97, sample=96,
             action="Offer coverage to uncovered full-time employees at the next enrollment opportunity and review full-time tracking."),
        Rule(key="cobra_election_notice", title="COBRA election notice sent",
             cost="Late COBRA notices bring ERISA statutory penalties, liability for medical claims and lawsuits from former employees.",
             citation="29 CFR 2590.606-4(b)(2)", kind="max",
             input="Days since a qualifying event without sending the COBRA election notice (employer is plan administrator, 20+ employees)",
             unit="days", limit=44, warn=35, sample=50,
             action="Send the COBRA election notice to the employee and dependents now by a trackable method."),
        Rule(key="fmla_notice_5_days", title="FMLA notice within 5 business days",
             cost="Late FMLA notices can be treated as interference, bringing lost wages, damages and attorney fees in employee lawsuits.",
             citation="29 CFR 825.300(b)(1), (c)", kind="max",
             input="Business days since the employee requested leave or the employer learned of a possible FMLA reason, without a notice",
             unit="business days", limit=5, warn=4, sample=3,
             action="Send the eligibility notice and rights and responsibilities notice to the employee today."),
        Rule(key="hospitalization_report_24h", title="Report hospitalization in 24 hours",
             cost="Failing to report a work-related hospitalization, amputation or eye loss to OSHA is cited and can trigger an inspection.",
             citation="29 CFR 1904.39(a)(2)", kind="max",
             input="Hours since learning of a work-related in-patient hospitalization, amputation or eye loss without reporting to OSHA",
             unit="h", limit=24, warn=20, sample=6,
             action="Report the incident to OSHA now by phone, in person or online."),
        Rule(key="fatality_report_8h", title="Report a work fatality in 8 hours",
             cost="Failing to report a work-related death to OSHA on time is cited, and the fatality inspection that follows can bring major penalties.",
             citation="29 CFR 1904.39(a)(1)", kind="max",
             input="Hours since learning of a work-related fatality without reporting it to OSHA",
             unit="h", limit=8, warn=6, sample=2,
             action="Report the fatality to OSHA now by phone or in person, and preserve the scene."),
    ],
}
