# -*- coding: utf-8 -*-
"""
Rule catalog, group 1: FleetArmor, RestoArmor, YachtArmor, AeroArmor and
HospitalArmor. Ten rules per industry; rule 1 of each is the topic of the
existing detailed check in omni_armor_platform.py.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 1. FLEETARMOR (FMCSA motor carriers) ---
    1: [
        Rule(key="hos_11_hour", title="11-hour driving limit",
             cost="Out-of-service orders idle the truck and load, and HOS violations raise CSA scores and insurance costs.",
             citation="49 CFR 395.3(a)(3)", kind="max",
             input="Hours driven since last 10 consecutive hours off duty",
             unit="h", limit=11, warn=10, sample=11.5,
             action="Stop driving; 10 consecutive hours off duty required.",
             method="fleet_armor_hos_timer"),
        Rule(key="eld_in_use", title="Electronic logging device in use",
             cost="Drivers without a required ELD are placed out of service, and missing records are cited in audits and raise CSA scores.",
             citation="49 CFR 395.8(a); 49 CFR Part 395 Subpart B", kind="required",
             input="Is the driver recording hours of service on a registered ELD (or covered by a listed exemption)?",
             sample=True,
             action="Do not dispatch; install a registered ELD or document the exemption that applies."),
        Rule(key="medical_certificate", title="Driver medical certificate current",
             cost="A driver without a valid medical card is placed out of service, and using unqualified drivers draws audit penalties.",
             citation="49 CFR 391.41(a); 49 CFR 391.45", kind="min",
             input="Days until the driver's medical examiner's certificate expires",
             unit="days", limit=0, warn=30, sample=12,
             action="Pull the driver from duty until a certified medical examiner issues a new certificate."),
        Rule(key="cdl_valid", title="Valid CDL for the vehicle",
             cost="Letting a driver operate without a valid CDL of the right class draws civil penalties, out-of-service orders and crash liability.",
             citation="49 CFR 383.23(a); 49 CFR 383.37", kind="required",
             input="Does the driver hold a valid CDL with the class and endorsements this vehicle and load need?",
             sample=True,
             action="Do not let this driver operate the vehicle; assign a properly licensed driver."),
        Rule(key="annual_mvr_review", title="Annual driving record review",
             cost="Missing annual reviews are cited in compliance reviews and weaken the carrier's defense in negligent-retention lawsuits.",
             citation="49 CFR 391.25", kind="max",
             input="Days since the driver's last annual motor vehicle record inquiry and review",
             unit="days", limit=365, warn=335, sample=380,
             action="Order the driver's MVR from each state now, review it and file it in the qualification file."),
        Rule(key="pre_employment_drug_test", title="Pre-employment drug test",
             cost="Using a driver before a negative drug result is an acute audit violation that can lead to penalties and an unsatisfactory rating.",
             citation="49 CFR 382.301(a)", kind="required",
             input="Has a verified negative pre-employment drug test been received for this driver?",
             sample=False,
             action="Keep the driver off all safety-sensitive work until a verified negative result is on file."),
        Rule(key="clearinghouse_annual_query", title="Annual Clearinghouse query",
             cost="Skipping required Drug and Alcohol Clearinghouse queries is cited in audits and can leave a prohibited driver on the road.",
             citation="49 CFR 382.701(b)", kind="max",
             input="Days since the last Drug and Alcohol Clearinghouse query on this driver",
             unit="days", limit=365, warn=335, sample=200,
             action="Run a Clearinghouse query on this driver today and keep the record."),
        Rule(key="annual_vehicle_inspection", title="Annual vehicle inspection",
             cost="Vehicles without a current periodic inspection are cited at roadside and in audits, and raise vehicle maintenance CSA scores.",
             citation="49 CFR 396.17", kind="max",
             input="Days since the vehicle's last annual (periodic) inspection",
             unit="days", limit=365, warn=335, sample=345,
             action="Take the vehicle out of service until a qualified inspector completes the annual inspection."),
        Rule(key="steer_tire_tread", title="Steer tire tread depth",
             cost="Worn steer tires are an out-of-service condition that idles the truck, and tire violations raise vehicle maintenance CSA scores.",
             citation="49 CFR 393.75(b)", kind="min",
             input="Shallowest tread depth on any steering-axle tire, in 32nds of an inch",
             unit="32nds of an inch", limit=4, warn=5, sample=6,
             action="Do not dispatch; replace the steer tire before the vehicle moves."),
        Rule(key="hos_70_hour_8_day", title="70-hour/8-day on-duty limit",
             cost="Driving past the 60/70-hour limit brings out-of-service orders and is a frequently cited HOS violations in audits.",
             citation="49 CFR 395.3(b)(2) (60 h/7 days in 395.3(b)(1) if not operating every day)", kind="max",
             input="On-duty hours in the last 8 consecutive days (carrier on the 70-hour/8-day schedule)",
             unit="h", limit=70, warn=63, sample=66,
             action="No more driving until on-duty hours fall under 70, or take a 34-hour restart."),
    ],

    # --- 2. RESTOARMOR (restaurants) ---
    2: [
        Rule(key="cold_holding", title="Cold holding at 41°F or below",
             cost="Out-of-temperature food is discarded, is a priority violation at inspection and can cause outbreaks and lawsuits.",
             citation="FDA Food Code 3-501.16(A)(2)", kind="max",
             input="Current temperature of TCS food in cold holding",
             unit="°F", limit=41, warn=40, sample=43,
             action="Hold the food; check how long it was above 41°F and discard it if safe time cannot be shown.",
             method="resto_armor_temp_check"),
        Rule(key="hot_holding", title="Hot holding at 135°F or above",
             cost="Food held below 135°F must be reheated or discarded, is a priority violation and can cause outbreaks.",
             citation="FDA Food Code 3-501.16(A)(1)", kind="min",
             input="Current temperature of TCS food in hot holding",
             unit="°F", limit=135, warn=140, sample=138,
             action="Reheat the food to 165°F within 2 hours if allowed, or discard it; fix the holding unit."),
        Rule(key="cooling_first_stage", title="Cooling 135°F to 70°F in 2 hours",
             cost="Improper cooling is a common cause of foodborne outbreaks and requires the batch to be reheated or thrown out.",
             citation="FDA Food Code 3-501.14(A)(1)", kind="max",
             input="Hours taken to cool cooked TCS food from 135°F to 70°F",
             unit="h", limit=2, warn=1.5, sample=1.25,
             action="Reheat to 165°F and restart cooling, or discard; use shallow pans or ice baths."),
        Rule(key="date_marking", title="Ready-to-eat food 7-day limit",
             cost="Food past its date mark must be thrown out and is cited at inspection; it raises Listeria risk.",
             citation="FDA Food Code 3-501.17(A); 3-501.18", kind="max",
             input="Days this ready-to-eat TCS food has been held at 41°F, counting the prep or opening day as day 1",
             unit="days", limit=7, warn=6, sample=8,
             action="Discard the food now and check date labels on the rest of the cooler."),
        Rule(key="no_bare_hand_rte", title="No bare-hand contact with RTE food",
             cost="Bare-hand contact with ready-to-eat food is a priority violation and a main route for norovirus outbreaks.",
             citation="FDA Food Code 3-301.11(B)", kind="forbidden",
             input="Did staff touch ready-to-eat food with bare hands?",
             sample=False,
             action="Discard the food touched, have staff wash hands and use gloves, tongs or deli tissue."),
        Rule(key="handwashing_sink", title="Hand sinks accessible and stocked",
             cost="Blocked or unstocked hand sinks are frequently cited inspection items and lead to repeat inspections.",
             citation="FDA Food Code 5-205.11; 6-301.11; 6-301.12", kind="required",
             input="Is every handwashing sink clear, used only for handwashing and stocked with soap and paper towels?",
             sample=True,
             action="Clear the sink and restock soap and towels now."),
        Rule(key="sick_employee_excluded", title="Sick employees kept off work",
             cost="Ill food workers cause outbreaks that bring closures, lawsuits and lost customers.",
             citation="FDA Food Code 2-201.11; 2-201.12(A)", kind="forbidden",
             input="Is any employee with vomiting or diarrhea working in the establishment?",
             sample=False,
             action="Send the employee home, clean and sanitize affected areas and log the exclusion."),
        Rule(key="no_pests", title="Premises free of pests",
             cost="Evidence of rodents or insects can close the restaurant on the spot and forces food discards.",
             citation="FDA Food Code 6-501.111", kind="forbidden",
             input="Are there signs of rodents or insects (droppings, live or dead pests)?",
             sample=True,
             action="Call a licensed pest control operator, discard contaminated food and clean affected areas."),
        Rule(key="certified_food_manager", title="Certified food protection manager",
             cost="Having no certified food protection manager is cited at inspection and can hold up permits.",
             citation="FDA Food Code 2-102.12(A) (as adopted by state or local code)", kind="required",
             input="Is at least one manager with authority over food prep a certified food protection manager?",
             sample=True,
             action="Enroll a manager in an accredited food protection manager exam now."),
        Rule(key="overtime_pay", title="Overtime paid over 40 hours",
             cost="Unpaid overtime leads to back wages, equal liquidated damages and class or collective lawsuits.",
             citation="Fair Labor Standards Act, 29 U.S.C. 207(a)(1)", kind="required",
             input="Are nonexempt employees paid 1.5 times their regular rate for hours over 40 in a workweek?",
             sample=False,
             action="Correct the payroll and pay back overtime owed; review how the regular rate is figured for tipped staff."),
    ],

    # --- 3. YACHTARMOR (superyachts / commercial yachts) ---
    3: [
        Rule(key="sewage_discharge_distance", title="Untreated sewage 12 nm from land",
             cost="Illegal sewage discharge draws Coast Guard and port state fines and can lead to detention of the yacht.",
             citation="MARPOL Annex IV reg. 11.1.1", kind="min",
             input="Distance from nearest land for a planned untreated sewage discharge",
             unit="nm", limit=12, warn=13, sample=8,
             action="Do not discharge; hold sewage until the yacht is over 12 nm out and en route at 4 knots or more.",
             method="yacht_armor_marpol_sentry"),
        Rule(key="oily_water_15ppm", title="Oily bilge discharge under 15 ppm",
             cost="Oily discharges bring pollution fines, detention and criminal prosecution of the owner, operator and crew.",
             citation="MARPOL Annex I reg. 15; 33 CFR 151.10", kind="max",
             input="Oil content of bilge effluent from the oily-water separator",
             unit="ppm", limit=15, warn=12, sample=9,
             action="Stop the discharge and keep oily water on board for delivery ashore."),
        Rule(key="oil_record_book", title="Oil Record Book kept complete",
             cost="Missing or false Oil Record Book entries are a main basis for U.S. criminal pollution cases and port state detentions.",
             citation="MARPOL Annex I reg. 17; 33 U.S.C. 1908 (Act to Prevent Pollution from Ships)", kind="required",
             input="Is every bilge, sludge and oily-waste operation entered accurately in the Oil Record Book?",
             sample=True,
             action="Bring the Oil Record Book up to date with accurate entries and receipts; never alter past entries."),
        Rule(key="stcw_certificate_valid", title="Officer STCW certificates valid",
             cost="Expired certificates of competency are a common port state control deficiency and can detain the yacht until replaced.",
             citation="STCW Convention reg. I/2 and reg. I/11 (revalidation)", kind="min",
             input="Days until the officer's STCW certificate of competency or endorsement expires",
             unit="days", limit=0, warn=90, sample=150,
             action="Take the officer off watch in that role until the certificate is revalidated; arrange a qualified relief."),
        Rule(key="eca_fuel_sulfur", title="ECA fuel sulfur 0.10% or less",
             cost="Burning high-sulfur fuel in an Emission Control Area draws EPA and port state penalties and forced fuel changes.",
             citation="MARPOL Annex VI reg. 14.4", kind="max",
             input="Sulfur content of fuel in use inside an Emission Control Area, by mass",
             unit="%", limit=0.10, warn=0.09, sample=0.08,
             action="Change over to compliant fuel now and log the changeover time and position."),
        Rule(key="crew_hours_of_rest", title="Crew rest 10 hours in 24",
             cost="Hours of rest breaches are a common port state control deficiency, can detain the yacht and create crew injury claims.",
             citation="MLC 2006 Standard A2.3.5(b); STCW Code A-VIII/1", kind="min",
             input="Hours of rest the crew member had in the last 24 hours",
             unit="h", limit=10, warn=11, sample=9,
             action="Relieve the crew member now and adjust the watch schedule; record rest hours accurately."),
        Rule(key="crew_medical_certificate", title="Crew medical certificate valid",
             cost="Crew without a valid medical certificate is a port state control deficiency that can delay departure.",
             citation="MLC 2006 Regulation 1.2; Standard A1.2", kind="min",
             input="Days until the crew member's medical fitness certificate expires",
             unit="days", limit=0, warn=30, sample=20,
             action="Book a medical exam with a recognized practitioner before the crew member works again."),
        Rule(key="abandon_ship_fire_drills", title="Monthly abandon-ship and fire drills",
             cost="Missed drills are a frequent port state control deficiency and weaken the defense after a casualty.",
             citation="SOLAS Ch. III reg. 19.3 (every crew member, every month)", kind="max",
             input="Days since the crew's last abandon-ship drill and fire drill",
             unit="days", limit=31, warn=25, sample=27,
             action="Hold abandon-ship and fire drills before the next voyage and log them."),
        Rule(key="liferaft_servicing", title="Liferaft annual service",
             cost="Overdue liferaft servicing is a port state control deficiency that can detain the yacht and void insurance cover.",
             citation="SOLAS Ch. III reg. 20.8 (12 months; flag state may extend to 17)", kind="max",
             input="Days since each inflatable liferaft was last serviced at an approved station",
             unit="days", limit=365, warn=335, sample=400,
             action="Send the liferaft to an approved service station or fit a serviced replacement before sailing."),
        Rule(key="garbage_record_book", title="Garbage Record Book kept",
             cost="Missing or incomplete Garbage Record Book entries are a frequent port state control deficiency and support pollution fines.",
             citation="MARPOL Annex V reg. 10.3 (400 GT and above, or certified for 15 or more persons)", kind="required",
             input="Is every garbage discharge, incineration and delivery ashore entered in the Garbage Record Book with receipts?",
             sample=True,
             action="Bring the Garbage Record Book up to date and file shore reception receipts."),
    ],

    # --- 4. AEROARMOR (Part 135 air charter) ---
    4: [
        Rule(key="inspection_100_hour", title="100-hour inspection",
             cost="Flying for hire past the 100-hour inspection grounds the aircraft and draws FAA civil penalties per flight.",
             citation="14 CFR 91.409(b); 14 CFR 135.411(a)(1)", kind="max",
             input="Hours in service since the last 100-hour inspection",
             unit="h", limit=100, warn=90, sample=94,
             action="Ground the aircraft for hire; complete the 100-hour inspection (up to 10 h over allowed only to reach it).",
             method="aero_armor_faa_logger"),
        Rule(key="single_pilot_flight_time", title="Single-pilot 8-hour flight time",
             cost="Scheduling pilots past flight time limits draws FAA civil penalties and raises accident risk and liability.",
             citation="14 CFR 135.267(b)(1) (unscheduled one- and two-pilot crews)", kind="max",
             input="Flight time assigned to a single-pilot crew in the last 24 consecutive hours",
             unit="h", limit=8, warn=7, sample=6.5,
             action="Do not assign more flying; use a two-pilot crew or a rested pilot."),
        Rule(key="pilot_rest_10_hours", title="10 hours rest before assignment",
             cost="Assigning a pilot without required rest draws FAA civil penalties and fatigue-related accident liability.",
             citation="14 CFR 135.267(d)", kind="min",
             input="Consecutive hours of rest in the 24 hours before the planned end of the assignment",
             unit="h", limit=10, warn=11, sample=9,
             action="Do not dispatch this pilot; reschedule so the pilot gets 10 consecutive hours of rest."),
        Rule(key="pilot_competency_check", title="Pilot competency check current",
             cost="Using a pilot with a lapsed competency check draws FAA civil penalties and can put the certificate at risk.",
             citation="14 CFR 135.293(b)", kind="max",
             input="Calendar months since the pilot's last Part 135 competency check",
             unit="months", limit=12, warn=11, sample=11,
             action="Remove the pilot from Part 135 flights until a competency check is passed."),
        Rule(key="pilot_medical_current", title="Pilot medical certificate current",
             cost="Flying with an expired or wrong-class medical is a certificate action for the pilot and a civil penalty for the operator.",
             citation="14 CFR 61.3(c); 14 CFR 61.23", kind="required",
             input="Does each pilot hold a current medical certificate of the class this flight requires?",
             sample=True,
             action="Replace the pilot with one holding a current medical certificate of the required class."),
        Rule(key="drug_alcohol_program", title="Drug and alcohol testing program",
             cost="Gaps in the FAA drug and alcohol program are a common basis for FAA civil penalties against charter operators.",
             citation="14 CFR Part 120 (120.105, 120.215); 49 CFR Part 40", kind="required",
             input="Is every safety-sensitive employee in the FAA drug and alcohol testing program, with a pre-employment test on file?",
             sample=False,
             action="Keep untested employees off safety-sensitive work and enroll them in the program now."),
        Rule(key="ifr_proficiency_check", title="IFR proficiency check in 6 months",
             cost="Using a pilot for IFR flights with a lapsed instrument check draws FAA civil penalties and increases liability after an incident.",
             citation="14 CFR 135.297(a)", kind="max",
             input="Calendar months since the pilot in command's last instrument proficiency check",
             unit="months", limit=6, warn=5, sample=7,
             action="Remove the pilot from IFR flights for hire until an instrument proficiency check is passed."),
        Rule(key="airworthiness_directives", title="No overdue airworthiness directives",
             cost="Flying with an overdue airworthiness directive makes the aircraft unairworthy and draws FAA civil penalties.",
             citation="14 CFR 39.7", kind="forbidden",
             input="Is any applicable airworthiness directive overdue on this aircraft?",
             sample=False,
             action="Ground the aircraft until the directive is complied with and recorded."),
        Rule(key="ifr_fuel_reserve", title="IFR fuel reserve 45 minutes",
             cost="Fuel planning violations draw FAA enforcement and fuel exhaustion accidents bring hull loss and liability.",
             citation="14 CFR 135.223(a)(3) (airplanes)", kind="min",
             input="Minutes of fuel at normal cruise planned to remain after reaching the IFR alternate",
             unit="min", limit=45, warn=50, sample=60,
             action="Add fuel, reduce load or pick a closer alternate before departure."),
        Rule(key="altimeter_static_check", title="Altimeter and static test (IFR)",
             cost="Flying IFR with an overdue altimeter and static system test makes the flight illegal and draws FAA penalties.",
             citation="14 CFR 91.411(a)", kind="max",
             input="Calendar months since the last altimeter and static system test",
             unit="months", limit=24, warn=22, sample=25,
             action="Restrict the aircraft to VFR until the altimeter and static system test is done and logged."),
    ],

    # --- 5. HOSPITALARMOR (hospitals) ---
    5: [
        Rule(key="nurse_staffing_ratio", title="Med-surg nurse staffing ratio",
             cost="Short staffing leads to survey citations, state penalties where ratios are law, and patient harm lawsuits.",
             citation="Cal. Code Regs. tit. 22, 70217 (California 1:5 med-surg; policy elsewhere); 42 CFR 482.23(b)",
             kind="max",
             input="Patients per licensed nurse on a medical-surgical unit",
             unit="patients per nurse", limit=5, warn=5, sample=5.5, policy=True,
             action="Call in nursing staff or hold admissions until the ratio is back within limit.",
             method="hospital_armor_patient_gate"),
        Rule(key="emtala_screening", title="EMTALA medical screening exam",
             cost="EMTALA violations bring OIG civil penalties, possible loss of Medicare participation and patient lawsuits.",
             citation="42 U.S.C. 1395dd(a); 42 CFR 489.24(a) and (d)(4)", kind="required",
             input="Does every person who comes to the ED asking for care get a medical screening exam, not delayed by payment questions?",
             sample=True,
             action="Screen the patient now and stop any payment or insurance questions that delay the exam."),
        Rule(key="breach_notification_60_days", title="HIPAA breach notice within 60 days",
             cost="Late breach notices draw OCR penalties and state attorney general actions, and add to class action exposure.",
             citation="45 CFR 164.404(b)", kind="max",
             input="Days since a breach of unsecured PHI was discovered without notifying affected patients",
             unit="days", limit=60, warn=45, sample=50,
             action="Send notices to affected patients now, without further delay, and prepare the HHS report."),
        Rule(key="hipaa_risk_analysis", title="HIPAA security risk analysis",
             cost="A missing or outdated risk analysis is among the most common findings in OCR settlements and penalties.",
             citation="45 CFR 164.308(a)(1)(ii)(A)", kind="required",
             input="Is there a current, organization-wide risk analysis covering all systems that hold electronic PHI?",
             sample=False,
             action="Start an enterprise-wide security risk analysis and document the risk management plan."),
        Rule(key="records_access_30_days", title="Patient records within 30 days",
             cost="Slow responses to patient records requests have led to many OCR right-of-access settlements.",
             citation="45 CFR 164.524(b)(2)", kind="max",
             input="Days since the patient's request for their records, with no extension notice sent",
             unit="days", limit=30, warn=25, sample=12,
             action="Provide the records now, or send the patient a written notice of the one 30-day extension allowed."),
        Rule(key="restraint_order_4_hours", title="Violent restraint order 4 hours",
             cost="Restraint violations are cited in CMS surveys, can threaten Medicare participation and lead to injury lawsuits.",
             citation="42 CFR 482.13(e)(8)(ii)(A) (adults 18 and older)", kind="max",
             input="Hours since the current restraint order for an adult's violent or self-destructive behavior was written",
             unit="h", limit=4, warn=3.5, sample=4.5,
             action="Have a physician or authorized practitioner assess the patient and renew or end the order now."),
        Rule(key="surgical_informed_consent", title="Informed consent before surgery",
             cost="Surgery without documented informed consent is cited in CMS surveys and is a common basis for malpractice claims.",
             citation="42 CFR 482.51(b)(2); 42 CFR 482.24(c)(4)(v)", kind="required",
             input="Is a properly executed informed consent form in the chart before this non-emergency procedure?",
             sample=True,
             action="Hold the procedure until informed consent is obtained and documented."),
        Rule(key="fire_drills_each_shift", title="Quarterly fire drill on every shift",
             cost="Life safety deficiencies are frequently cited in CMS and accreditation surveys and require costly corrective plans.",
             citation="42 CFR 482.41(b); NFPA 101 (2012) 18.7.1.6 / 19.7.1.6", kind="required",
             input="Has a fire drill been held on every shift in the current quarter?",
             sample=False,
             action="Schedule and hold fire drills on each shift missing one this quarter and document them."),
        Rule(key="physician_agreements_current", title="Physician agreements signed and current",
             cost="Expired or unsigned physician agreements can make Medicare claims false, leading to refunds and False Claims Act settlements.",
             citation="42 U.S.C. 1395nn (Stark Law); 42 CFR 411.357", kind="required",
             input="Is every paid arrangement with a referring physician covered by a signed agreement still in effect (or in an allowed holdover)?",
             sample=False,
             action="Stop referral-linked billing under the lapsed arrangement and have counsel renew it and review past claims."),
        Rule(key="price_transparency_update", title="Standard charges file updated yearly",
             cost="Hospitals without a current price transparency file face CMS warning notices, corrective action plans and daily civil penalties.",
             citation="45 CFR 180.50(e)", kind="max",
             input="Days since the machine-readable standard charges file was last updated",
             unit="days", limit=365, warn=335, sample=200,
             action="Update and repost the complete machine-readable standard charges file now."),
    ],
}
