# -*- coding: utf-8 -*-
"""
Rule catalog, group 8: DefenseArmor, FoodArmor, DeviceArmor, ChemArmor and
WasteArmor. Ten rules per industry, costliest first.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 36. DEFENSEARMOR (defense contractors) ---
    36: [
        Rule(key="nist_800_171_safeguarding", title="CUI safeguarded per NIST SP 800-171",
             cost="Claiming cyber compliance that is not in place exposes the contractor to False Claims Act suits, lost awards and contract termination.",
             citation="DFARS 252.204-7012(b); NIST SP 800-171", kind="required",
             input="Do all company systems that process, store or send CUI meet NIST SP 800-171, with any open gaps tracked in a current plan of action?",
             sample=False,
             action="Stop representing full compliance; document gaps in a plan of action, fix them and correct any inaccurate SPRS score."),
        Rule(key="tina_certified_data", title="Certified cost or pricing data",
             cost="Defective pricing data leads to government price reductions with interest, and knowing errors can bring False Claims Act liability.",
             citation="10 U.S.C. 3702; FAR 15.403-4; FAR 52.215-10", kind="required",
             input="For each negotiated action over the TINA threshold with no exception, was current, accurate and complete cost or pricing data submitted and certified?",
             sample=True,
             action="Hold the price agreement; update the cost or pricing data to the agreed date and certify it before award."),
        Rule(key="itar_unauthorized_export", title="No ITAR export without authorization",
             cost="Unlicensed exports of defense articles or technical data draw civil penalties, consent agreements, debarment from exports and criminal charges.",
             citation="22 CFR 123.1; 22 CFR 125.2; 22 CFR 127.1", kind="forbidden",
             input="Has ITAR-controlled technical data or hardware been shared with a foreign person (including employees) without a DDTC license or exemption?",
             sample=False,
             action="Stop further access, preserve records and consider a voluntary disclosure to DDTC under 22 CFR 127.12 with export counsel."),
        Rule(key="mandatory_disclosure", title="Mandatory disclosure made",
             cost="Failing to disclose credible evidence of fraud or False Claims Act violations is a cause for suspension and debarment from federal contracts.",
             citation="FAR 52.203-13(b)(3)(i); FAR 9.406-2(b)(1)(vi)", kind="forbidden",
             input="Is there credible evidence of contract-related fraud, bribery, conflict of interest, gratuity or False Claims Act violations not yet disclosed?",
             sample=False,
             action="Disclose in writing to the agency Office of Inspector General now, with a copy to the contracting officer."),
        Rule(key="cmmc_level_met", title="CMMC level required by contract",
             cost="Without the CMMC status the contract requires, the company is ineligible for award and can lose new work and options.",
             citation="32 CFR Part 170; DFARS 252.204-7021", kind="required",
             input="Does the company hold a current CMMC status, at the level the solicitation or contract requires, for each system handling FCI or CUI?",
             sample=True,
             action="Do not bid or process FCI/CUI on the system; complete the required CMMC assessment and affirmation."),
        Rule(key="sprs_assessment_current", title="SPRS assessment current",
             cost="Without a current NIST SP 800-171 assessment in SPRS, the contractor cannot be awarded contracts that require one.",
             citation="DFARS 252.204-7019; DFARS 252.204-7020", kind="max",
             input="Days since the NIST SP 800-171 assessment score was posted in SPRS",
             unit="days", limit=1095, warn=1005, sample=1030,
             action="Perform a new NIST SP 800-171 assessment and post the score and summary in SPRS now."),
        Rule(key="cyber_incident_72h", title="Cyber incident reported to DoD",
             cost="Late cyber incident reports breach DFARS clauses, can support termination or False Claims Act claims, and hurt past performance.",
             citation="DFARS 252.204-7012(c)(1)", kind="max",
             input="Hours since the cyber incident affecting covered defense information was discovered, without reporting to DoD",
             unit="h", limit=72, warn=48, sample=80,
             action="Report now at dibnet.dod.mil with a medium assurance certificate and preserve images of affected systems for 90 days."),
        Rule(key="section_889_telecom", title="No prohibited telecom equipment",
             cost="Using or supplying covered Huawei, ZTE, Hytera, Hikvision or Dahua telecom or video gear breaches FAR clauses and risks contract loss.",
             citation="FAR 52.204-25; FAR 52.204-24", kind="forbidden",
             input="Is any covered telecommunications or video surveillance equipment or service used or provided by the company?",
             sample=False,
             action="Report it to the contracting officer within one business day and plan removal or replacement of the equipment."),
        Rule(key="counterfeit_parts_system", title="Counterfeit parts detection system",
             cost="Counterfeit electronic parts make rework and replacement costs unallowable and can lead to purchasing system disapproval and withholds.",
             citation="DFARS 252.246-7007; DFARS 252.246-7008; DFARS 231.205-71", kind="required",
             input="Does the company run a counterfeit electronic part detection and avoidance system and buy parts from original makers or authorized sources?",
             sample=True,
             action="Quarantine suspect parts, report them to the contracting officer and GIDEP, and fix sourcing and inspection procedures."),
        Rule(key="itar_registration_current", title="DDTC ITAR registration current",
             cost="Manufacturing or exporting defense articles without a current DDTC registration is an ITAR violation and blocks license approvals.",
             citation="22 CFR 122.1; 22 CFR 122.3", kind="min",
             input="Days until the company's DDTC registration expires",
             unit="days", limit=0, warn=60, sample=45,
             action="Submit the registration renewal and fee in DECCS now; do not export until the registration is current."),
    ],

    # --- 37. FOODARMOR (food and beverage manufacturers) ---
    37: [
        Rule(key="environmental_monitoring", title="Environmental pathogen monitoring",
             cost="Listeria or Salmonella in ready-to-eat food leads to recalls, outbreak lawsuits, plant shutdowns and FDA warning letters.",
             citation="21 CFR 117.165(a)(3); 21 CFR 117.150", kind="required",
             input="For ready-to-eat food exposed to the environment before packaging, is environmental pathogen monitoring done, recorded and acted on?",
             sample=True,
             action="Start swabbing food-contact and nearby zones now, hold affected product and document corrective actions."),
        Rule(key="undeclared_allergen", title="No undeclared major allergens",
             cost="Undeclared allergens are a common cause of food recalls and bring lost product, retailer chargebacks and injury lawsuits.",
             citation="21 U.S.C. 343(w) (FD&C Act 403(w), FALCPA and FASTER Act)", kind="forbidden",
             input="Does any label omit a major allergen the product contains (milk, egg, fish, shellfish, tree nuts, peanuts, wheat, soy, sesame)?",
             sample=True,
             action="Stop shipping, hold and relabel the product, and assess whether a recall and a Reportable Food Registry report are needed."),
        Rule(key="food_safety_plan", title="Written food safety plan by a PCQI",
             cost="Operating without a written food safety plan is a common FDA warning letter finding and can lead to registration suspension.",
             citation="21 CFR 117.126; 21 CFR 117.180", kind="required",
             input="Does the facility have a written food safety plan prepared or overseen by a preventive controls qualified individual?",
             sample=True,
             action="Have a PCQI prepare the hazard analysis and written food safety plan now and review production against it."),
        Rule(key="pest_control", title="Pests excluded from the plant",
             cost="Pest activity makes food adulterated under insanitary conditions, bringing warning letters, product destruction and shutdowns.",
             citation="21 CFR 117.35(c); 21 U.S.C. 342(a)(4)", kind="forbidden",
             input="Has pest activity been found in any food handling, processing or storage area and not yet corrected?",
             sample=False,
             action="Hold exposed product, call pest control, seal entry points and document cleaning and corrective action."),
        Rule(key="reportable_food_registry", title="Reportable food reported in 24 h",
             cost="Late Reportable Food Registry reports are a prohibited act under the FD&C Act and increase recall scope and outbreak liability.",
             citation="21 U.S.C. 350f(d)(1) (FD&C Act 417)", kind="max",
             input="Hours since determining a food is a reportable food, without submitting a Reportable Food Registry report",
             unit="h", limit=24, warn=18, sample=6,
             action="Submit the report through the FDA Safety Reporting Portal now and investigate the cause."),
        Rule(key="supplier_verification", title="Supplier verification in place",
             cost="Using unverified suppliers for hazards they control is cited in FDA inspections and passes contaminated ingredients into product.",
             citation="21 CFR 117.410; 21 CFR 117.430", kind="required",
             input="For each ingredient whose hazard the supplier controls, is the supplier approved and verified (for example, audits, sampling, records review)?",
             sample=False,
             action="Hold the ingredient; approve the supplier and complete and document a verification activity before use."),
        Rule(key="food_safety_plan_reanalysis", title="Food safety plan reanalysis",
             cost="An outdated food safety plan is cited in FDA inspections and leaves new hazards uncontrolled, raising recall risk.",
             citation="21 CFR 117.170(a)", kind="max",
             input="Days since the last full reanalysis of the food safety plan",
             unit="days", limit=1095, warn=1000, sample=1150,
             action="Have a PCQI reanalyze the whole food safety plan now and document the result."),
        Rule(key="recall_plan", title="Written recall plan",
             cost="Without a recall plan, recalls are slower and wider, raising product losses, retailer costs and liability.",
             citation="21 CFR 117.139", kind="required",
             input="For food with a hazard requiring a preventive control, is there a written recall plan with steps and assigned responsibilities?",
             sample=True,
             action="Write the recall plan now, covering notice to consignees, the public, effectiveness checks and disposal."),
        Rule(key="fsvp_in_place", title="Foreign supplier verification (FSVP)",
             cost="Importing without an FSVP draws FDA warning letters and import alerts that stop shipments at the border.",
             citation="21 CFR 1.502; 21 CFR Part 1 Subpart L", kind="required",
             input="As the importer, does the company have a Foreign Supplier Verification Program for each imported food and foreign supplier?",
             sample=True,
             action="Do not import the food; develop the FSVP hazard analysis and supplier verification for it first."),
        Rule(key="facility_registration", title="FDA facility registration renewed",
             cost="Food from a facility that failed to register or renew is a prohibited act, and imports from it are held at the port.",
             citation="21 CFR 1.230(b); 21 U.S.C. 350d", kind="required",
             input="Was the FDA food facility registration renewed in the most recent October 1 to December 31 even-year renewal period?",
             sample=True,
             action="Renew or re-register the facility in FDA's FURLS system now."),
    ],

    # --- 38. DEVICEARMOR (medical device manufacturers) ---
    38: [
        Rule(key="capa_effective", title="CAPA process working",
             cost="CAPA failures are frequently cited FDA inspection findings and lead to warning letters, import holds and consent decrees.",
             citation="21 CFR 820.10 (ISO 13485:2016 clauses 8.5.2, 8.5.3)", kind="required",
             input="Are quality problems investigated to root cause, with corrective and preventive actions documented and verified as effective?",
             sample=False,
             action="Open CAPAs for the open quality problems, find root causes, fix them and verify effectiveness in writing."),
        Rule(key="premarket_authorization", title="510(k) or PMA before marketing",
             cost="Selling a device or changed device without required clearance or approval makes it adulterated and misbranded, risking seizure and recall.",
             citation="21 U.S.C. 360(k); 21 CFR 807.81; 21 U.S.C. 360e; 21 CFR Part 814", kind="forbidden",
             input="Is any device, or significant change to a device, being marketed without the required 510(k), De Novo or PMA?",
             sample=False,
             action="Stop distributing the device and file the required submission; consult regulatory counsel on product in the field."),
        Rule(key="complaint_handling", title="Complaints handled and evaluated",
             cost="Weak complaint handling is a top FDA inspection finding, hides reportable events and leads to warning letters and recalls.",
             citation="21 CFR 820.10 (ISO 13485:2016 clause 8.2.2); 21 CFR 820.35(a)", kind="required",
             input="Is every complaint recorded, evaluated for MDR reportability, and investigated where needed, with records kept?",
             sample=True,
             action="Log and review all open complaints now, document the MDR decision for each and start needed investigations."),
        Rule(key="mdr_30_day", title="MDR report within 30 days",
             cost="Late or missing Medical Device Reports are cited in warning letters and can support civil money penalties and misbranding charges.",
             citation="21 CFR 803.50(a)", kind="max",
             input="Calendar days since becoming aware of a reportable death, serious injury or malfunction, without filing an MDR",
             unit="days", limit=30, warn=25, sample=27,
             action="File the MDR (Form 3500A) through eMDR now and document why it was late."),
        Rule(key="design_controls", title="Design controls followed",
             cost="Design control gaps lead to warning letters, field failures and recalls of devices already sold.",
             citation="21 CFR 820.10 (ISO 13485:2016 clause 7.3)", kind="required",
             input="For each device under design controls, are design inputs, verification, validation and risk management complete before transfer?",
             sample=True,
             action="Hold design transfer until design verification, validation and risk analysis are complete and approved."),
        Rule(key="supplier_controls", title="Suppliers evaluated and controlled",
             cost="Uncontrolled suppliers let defective components into devices, leading to recalls, warning letters and production stops.",
             citation="21 CFR 820.10 (ISO 13485:2016 clause 7.4)", kind="required",
             input="Are all suppliers of product and services evaluated, approved, monitored and bound by documented purchasing requirements?",
             sample=False,
             action="Hold incoming parts from unapproved suppliers; evaluate and approve them and document purchasing requirements."),
        Rule(key="correction_removal_report", title="Correction or removal reported",
             cost="Unreported corrections and removals to reduce health risk make devices misbranded and draw warning letters.",
             citation="21 CFR 806.10(b)", kind="max",
             input="Working days since starting a correction or removal to reduce a health risk, without reporting it to FDA",
             unit="working days", limit=10, warn=8, sample=3,
             action="Submit the Part 806 correction or removal report to FDA now."),
        Rule(key="mdr_5_day", title="5-day MDR report",
             cost="Missing a 5-day report on an event needing remedial action is cited in warning letters and can support civil money penalties.",
             citation="21 CFR 803.53", kind="max",
             input="Work days since becoming aware of an event needing remedial action to prevent substantial harm (or an FDA 5-day request), without reporting",
             unit="work days", limit=5, warn=4, sample=6,
             action="File the 5-day MDR report through eMDR now."),
        Rule(key="registration_listing", title="Annual registration and listing",
             cost="Devices from an unregistered or unlisted establishment are misbranded and can be refused at import or held from sale.",
             citation="21 CFR 807.22(b); 21 U.S.C. 360", kind="required",
             input="Was establishment registration renewed (with the user fee paid) and device listing reviewed between October 1 and December 31 last year?",
             sample=True,
             action="Pay the registration user fee and complete registration and listing in FURLS now."),
        Rule(key="udi_labeling", title="UDI on labels and in GUDID",
             cost="Devices without a required UDI or GUDID record are misbranded and can be refused by hospitals, distributors and at import.",
             citation="21 CFR 801.20; 21 CFR 830.300", kind="required",
             input="Does each device label and package carry a UDI, with device data submitted to GUDID, unless an exception applies?",
             sample=True,
             action="Stop shipping unlabeled units; apply UDIs and submit the GUDID records."),
    ],

    # --- 39. CHEMARMOR (chemical plants and facilities) ---
    39: [
        Rule(key="mechanical_integrity_overdue", title="No overdue equipment inspections",
             cost="Mechanical integrity failures cause fires and explosions and are frequently cited PSM items, bringing OSHA and EPA penalties.",
             citation="29 CFR 1910.119(j)(4); 40 CFR 68.73", kind="forbidden",
             input="Is any covered process equipment overdue for an inspection or test set by the manufacturer or good engineering practice?",
             sample=True,
             action="Perform the overdue inspections and tests now; correct deficiencies before further use or add interim safeguards."),
        Rule(key="pha_revalidation", title="PHA revalidated every 5 years",
             cost="Out-of-date process hazard analyses are a frequent PSM and RMP citation and leave hazards unaddressed before incidents.",
             citation="29 CFR 1910.119(e)(6); 40 CFR 68.67(f)", kind="max",
             input="Days since the process hazard analysis for this process was last updated and revalidated",
             unit="days", limit=1825, warn=1640, sample=1700,
             action="Schedule the PHA revalidation with a qualified team now and track recommendations to closure."),
        Rule(key="management_of_change", title="Management of change completed",
             cost="Unreviewed process changes are a common cause of chemical incidents and draw PSM citations and incident liability.",
             citation="29 CFR 1910.119(l); 40 CFR 68.75", kind="required",
             input="Was every change to process chemicals, technology, equipment or procedures reviewed under written management of change before startup?",
             sample=False,
             action="Stop using the changed process until the MOC review, pre-startup safety review and training are complete."),
        Rule(key="rmp_five_year_update", title="RMP updated every 5 years",
             cost="An outdated risk management plan is an EPA Clean Air Act violation that leads to civil penalties and consent agreements.",
             citation="40 CFR 68.190(b)(1)", kind="max",
             input="Days since the risk management plan was last updated and resubmitted to EPA",
             unit="days", limit=1825, warn=1640, sample=900,
             action="Update the RMP, including hazard review and emergency response data, and resubmit it through RMP*eSubmit now."),
        Rule(key="psm_compliance_audit", title="PSM compliance audit every 3 years",
             cost="Missed compliance audits are cited by OSHA and EPA and let program gaps grow unnoticed until an incident.",
             citation="29 CFR 1910.119(o)(1); 40 CFR 68.79(a)", kind="max",
             input="Days since the last PSM compliance audit was certified",
             unit="days", limit=1095, warn=1000, sample=1120,
             action="Schedule and certify a PSM compliance audit now and respond to findings in writing."),
        Rule(key="sds_available", title="SDS available for every chemical",
             cost="Hazard communication is frequently cited by OSHA, and missing SDSs draw citations and worker injury claims.",
             citation="29 CFR 1910.1200(g)(8)", kind="required",
             input="Is a current safety data sheet for every hazardous chemical readily accessible to employees in their work area on every shift?",
             sample=True,
             action="Get missing SDSs from suppliers and place them where workers on every shift can reach them."),
        Rule(key="tier_ii_submitted", title="Tier II report filed by March 1",
             cost="Missing or late EPCRA Tier II reports draw EPA civil penalties and leave fire departments unaware of stored hazards.",
             citation="40 CFR 370.45", kind="required",
             input="Was the Tier II inventory for last year submitted to the SERC, LEPC and local fire department by March 1?",
             sample=True,
             action="File the Tier II report with the SERC, LEPC and fire department now."),
        Rule(key="tri_form_r", title="TRI Form R filed by July 1",
             cost="Failing to file Toxics Release Inventory reports is an EPCRA violation that draws EPA civil penalties for each chemical and year.",
             citation="40 CFR 372.30", kind="required",
             input="Was each required TRI Form R (or Form A) for last calendar year submitted to EPA by July 1?",
             sample=False,
             action="Prepare and submit the missing TRI reports through TRI-MEweb now."),
        Rule(key="spcc_five_year_review", title="SPCC plan 5-year review",
             cost="An unreviewed spill prevention plan is a Clean Water Act violation cited by EPA and raises cleanup costs after a spill.",
             citation="40 CFR 112.5(b)", kind="max",
             input="Days since the last documented review and evaluation of the SPCC plan",
             unit="days", limit=1825, warn=1640, sample=600,
             action="Complete and document the SPCC plan review now and amend the plan within 6 months if changes are needed."),
        Rule(key="dot_hazmat_training", title="DOT hazmat training every 3 years",
             cost="Untrained hazmat employees draw DOT civil penalties per violation and raise the risk of shipping incidents.",
             citation="49 CFR 172.704(c)(2)", kind="max",
             input="Days since the employee's last DOT hazmat training (general, function-specific, safety and security)",
             unit="days", limit=1095, warn=1000, sample=1010,
             action="Keep the employee off hazmat work until recurrent training is completed and recorded."),
    ],

    # --- 40. WASTEARMOR (hazardous waste generators and environmental services) ---
    40: [
        Rule(key="lqg_90_day_limit", title="LQG 90-day accumulation limit",
             cost="Holding waste past 90 days makes a large quantity generator an unpermitted storage facility, bringing large RCRA penalties.",
             citation="40 CFR 262.17(a)", kind="max",
             input="Days hazardous waste has been in the central accumulation area",
             unit="days", limit=90, warn=80, sample=95,
             action="Ship the waste to a permitted facility now, or request an extension from the regulator if allowed."),
        Rule(key="waste_determination", title="Hazardous waste determination made",
             cost="Skipping waste determinations is a top RCRA citation and leads to illegal disposal, penalties and cleanup liability.",
             citation="40 CFR 262.11", kind="required",
             input="Has a hazardous waste determination been made and recorded for every solid waste the site generates?",
             sample=False,
             action="Characterize the waste now by knowledge or testing, record the result and manage it as hazardous until done."),
        Rule(key="manifest_shipments", title="Manifested shipments only",
             cost="Shipping waste without a manifest or to an unpermitted site brings RCRA penalties and cleanup liability for where it ends up.",
             citation="40 CFR 262.20(a); 40 CFR 262.18(c)", kind="forbidden",
             input="Has any hazardous waste left the site without a manifest, or with a transporter or facility lacking an EPA ID number?",
             sample=False,
             action="Find the shipment, confirm where it went, and report to the regulator; use only manifests and EPA ID holders."),
        Rule(key="container_labeling", title="Containers marked and dated",
             cost="Unlabeled or undated containers are frequently cited RCRA violations and can cost the generator its accumulation exemption.",
             citation="40 CFR 262.17(a)(5)", kind="required",
             input="Is every container in the central accumulation area marked 'Hazardous Waste', with its hazards and accumulation start date?",
             sample=True,
             action="Label each container with 'Hazardous Waste', its hazards and the start date now."),
        Rule(key="weekly_inspection", title="Weekly container area inspection",
             cost="Missed weekly inspections are frequently cited in RCRA inspections and let leaks go unnoticed until cleanup is needed.",
             citation="40 CFR 262.17(a)(1)(v)", kind="max",
             input="Days since the last recorded inspection of the central accumulation area",
             unit="days", limit=7, warn=6, sample=9,
             action="Inspect the area for leaks and deterioration today and record the inspection."),
        Rule(key="satellite_accumulation", title="Satellite area 55-gallon limit",
             cost="Exceeding satellite limits is a common RCRA citation and turns the area into one that must meet full storage rules.",
             citation="40 CFR 262.15(a)", kind="max",
             input="Gallons of non-acute hazardous waste at this satellite accumulation area",
             unit="gal", limit=55, warn=50, sample=40,
             action="Date the excess and move it to the central accumulation area within 3 consecutive calendar days."),
        Rule(key="sqg_180_day_limit", title="SQG 180-day accumulation limit",
             cost="Holding waste past the limit makes a small quantity generator an unpermitted storage facility subject to RCRA penalties.",
             citation="40 CFR 262.16(b)(1); 40 CFR 262.16(d)", kind="max",
             input="Days hazardous waste has been accumulated on site (180-day limit; 270 days only if the TSDF is over 200 miles away)",
             unit="days", limit=180, warn=160, sample=165,
             action="Ship the waste to a permitted facility now, or request an extension from the regulator if allowed."),
        Rule(key="annual_training_review", title="Annual RCRA training review",
             cost="Missing training records are a common RCRA citation and untrained staff mishandle waste, raising spill and penalty risk.",
             citation="40 CFR 262.17(a)(7)(iii)", kind="max",
             input="Days since the employee's last annual review of hazardous waste training",
             unit="days", limit=365, warn=335, sample=200,
             action="Complete the annual training review with the employee now and record it."),
        Rule(key="exception_report", title="Manifest exception report",
             cost="Not following up on unconfirmed shipments is a RCRA violation and leaves the generator liable if waste is misdelivered.",
             citation="40 CFR 262.42(a)", kind="max",
             input="Days since the initial transporter took the waste, without receiving the signed manifest copy from the destination facility",
             unit="days", limit=45, warn=35, sample=20,
             action="Contact the transporter and facility, and file an exception report with the EPA Region or state now."),
        Rule(key="biennial_report", title="Biennial report filed by March 1",
             cost="Missing biennial reports is a RCRA reporting violation that draws penalties and triggers closer inspection.",
             citation="40 CFR 262.41(a)", kind="required",
             input="If the site was a large quantity generator in any month of the last odd year, was its biennial report filed by March 1?",
             sample=True,
             action="Prepare and file the biennial hazardous waste report through RCRAInfo now."),
    ],
}
