# -*- coding: utf-8 -*-
"""
Rule catalog, group 9: GridArmor, WaterArmor, LawArmor, CampusArmor and
ChildArmor. Ten rules per industry, costliest first.
"""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 41. GRIDARMOR (electric utilities and grid operators, NERC) ---
    41: [
        Rule(key="cip007_patch_evaluation", title="Security patch evaluation cycle",
             cost="Late patch evaluations are frequently cited CIP violations and draw NERC civil penalties and mitigation plans.",
             citation="NERC CIP-007 R2.2", kind="max",
             input="Days since the last evaluation of security patches for applicability",
             unit="days", limit=35, warn=28, sample=38,
             action="Evaluate all released security patches now and document the result for each applicable BES Cyber Asset."),
        Rule(key="cip004_access_revocation", title="Access removed after termination",
             cost="Former staff who keep unescorted physical or remote access are a frequent CIP finding that draws NERC penalties.",
             citation="NERC CIP-004 R5.1", kind="max",
             input="Hours since a termination action without removing unescorted physical and Interactive Remote Access",
             unit="h", limit=24, warn=16, sample=6,
             action="Remove the person's badge access and Interactive Remote Access now and record the time removed."),
        Rule(key="fac003_vegetation_clearance", title="Vegetation inside clearance distance",
             cost="Vegetation encroachment on covered transmission lines can cause outages and draws some of the largest NERC penalties.",
             citation="NERC FAC-003", kind="forbidden",
             input="Has vegetation been found inside the Minimum Vegetation Clearance Distance of an applicable line?",
             sample=False,
             action="Dispatch crews to clear the encroachment, notify the Reliability Coordinator if required, and log the event."),
        Rule(key="cip008_incident_notice", title="1-hour cyber incident notice",
             cost="Missing the notice deadline for a reportable cyber incident is a CIP-008 violation that draws NERC penalties and scrutiny.",
             citation="NERC CIP-008 R4.2", kind="max",
             input="Hours since a Reportable Cyber Security Incident was determined, without notice to E-ISAC and CISA",
             unit="h", limit=1, warn=0.5, sample=0.25,
             action="Send the initial notification to E-ISAC and CISA now with the attributes known so far."),
        Rule(key="cip010_baseline_update", title="Configuration baseline updated",
             cost="Out-of-date baselines are a common CIP-010 finding that leads to NERC penalties and costly re-baselining.",
             citation="NERC CIP-010 R1.3", kind="max",
             input="Days since a change that deviates from the baseline, without updating the baseline",
             unit="days", limit=30, warn=21, sample=24,
             action="Update the baseline configuration for the changed asset and record the authorization for the change."),
        Rule(key="prc005_maintenance_interval", title="Protection system maintenance",
             cost="Overdue relay, battery and communication tests are a frequent PRC-005 finding and can lead to misoperations and penalties.",
             citation="NERC PRC-005", kind="required",
             input="Is every Protection System component within its maximum maintenance interval in the PRC-005 tables?",
             sample=False,
             action="Schedule the overdue component tests now and document completion against the program's interval tables."),
        Rule(key="cip004_training_interval", title="CIP security training current",
             cost="Staff with authorized access and lapsed training are a common CIP-004 finding that draws NERC penalties.",
             citation="NERC CIP-004 R2.3", kind="max",
             input="Months since the person with authorized access last completed the cyber security training program",
             unit="months", limit=15, warn=13, sample=14,
             action="Complete the training now or suspend the person's authorized access until it is done."),
        Rule(key="cip002_categorization_review", title="BES Cyber System review",
             cost="A missed review of BES Cyber System identifications is a CIP-002 violation that can leave assets without required controls.",
             citation="NERC CIP-002 R2", kind="max",
             input="Months since BES Cyber System identifications were reviewed and approved by the CIP Senior Manager",
             unit="months", limit=15, warn=13, sample=9,
             action="Review the impact ratings and have the CIP Senior Manager or delegate approve them now."),
        Rule(key="cip003_policy_review", title="Cyber security policy approval",
             cost="Policies not reviewed and approved on time are a CIP-003 violation that NERC auditors cite and penalize.",
             citation="NERC CIP-003 R1", kind="max",
             input="Months since the CIP Senior Manager last reviewed and approved the cyber security policies",
             unit="months", limit=15, warn=13, sample=16,
             action="Have the CIP Senior Manager review and approve the documented cyber security policies now."),
        Rule(key="eop004_event_report", title="Reportable event filed in 24 h",
             cost="Late reports of reportable events such as physical attacks or load loss are an EOP-004 violation that draws penalties.",
             citation="NERC EOP-004 R2 and Attachment 1", kind="max",
             input="Hours since recognizing an EOP-004 reportable event without submitting the report",
             unit="h", limit=24, warn=18, sample=3,
             action="Submit the EOP-004 Attachment 2 or DOE OE-417 form to the required parties now."),
    ],

    # --- 42. WATERARMOR (drinking water and wastewater utilities) ---
    42: [
        Rule(key="lead_action_level", title="Lead 90th percentile action level",
             cost="A lead action level exceedance triggers public education, treatment changes and lead service line replacement, plus lawsuits.",
             citation="40 CFR 141.80(c) (current 15 ppb action level)", kind="max",
             input="90th percentile lead level from the latest round of tap samples",
             unit="ppb", limit=15, warn=12, sample=13,
             action="Notify the state, start public education within the required time, and begin the required treatment steps."),
        Rule(key="tier1_public_notice", title="Tier 1 notice within 24 hours",
             cost="Late notice of acute risks such as E. coli or a boil-water event brings state enforcement, penalties and liability suits.",
             citation="40 CFR 141.202(b)", kind="max",
             input="Hours since learning of a Tier 1 violation or situation without issuing public notice",
             unit="h", limit=24, warn=12, sample=30,
             action="Issue public notice now by broadcast or hand delivery and consult the state primacy agency."),
        Rule(key="rtcr_repeat_samples", title="Repeat samples after TC-positive",
             cost="Missing repeat samples after a total coliform-positive result is a violation that can trigger assessments and public notice.",
             citation="40 CFR 141.858(a)", kind="max",
             input="Hours since notice of a total coliform-positive routine sample without collecting the repeat samples",
             unit="h", limit=24, warn=16, sample=8,
             action="Collect at least three repeat samples now at the required locations and have them tested."),
        Rule(key="disinfectant_residual_entry", title="Residual entering distribution",
             cost="Low disinfectant residual at the entry point is a treatment technique violation that requires public notice and enforcement.",
             citation="40 CFR 141.72 (surface water systems)", kind="min",
             input="Lowest disinfectant residual in water entering the distribution system",
             unit="mg/L", limit=0.2, warn=0.3, sample=0.45,
             action="Raise the disinfectant dose now; the residual may not stay below 0.2 mg/L for more than 4 hours. Notify the state."),
        Rule(key="turbidity_max", title="Filtered water turbidity",
             cost="A combined filter effluent turbidity spike is a treatment technique violation that can require public notice and a boil order.",
             citation="40 CFR 141.173(a) (conventional or direct filtration)", kind="max",
             input="Highest combined filter effluent turbidity reading this month",
             unit="NTU", limit=1, warn=0.3, sample=0.2,
             action="Take the filter offline or adjust treatment now, consult the state, and prepare public notice."),
        Rule(key="npdes_effluent_limit", title="NPDES permit effluent limit",
             cost="Discharges over permit limits bring Clean Water Act penalties, consent decrees and citizen suits.",
             citation="40 CFR 122.41(a); Clean Water Act 309", kind="max",
             input="Highest effluent result this period as a percent of its NPDES permit limit",
             unit="%", limit=100, warn=90, sample=104,
             action="Report the exceedance as the permit requires, find the cause, and adjust treatment before the next sample."),
        Rule(key="npdes_dmr_submitted", title="Discharge Monitoring Report on time",
             cost="Late or missing DMRs are among the most common NPDES violations and lead to enforcement and penalties.",
             citation="40 CFR 122.41(l)(4); 40 CFR Part 127 (electronic reporting)", kind="required",
             input="Were all Discharge Monitoring Reports for the last period submitted by the permit's due date?",
             sample=True,
             action="Submit the missing DMR electronically now and explain the delay to the permitting authority."),
        Rule(key="consumer_confidence_report", title="Consumer Confidence Report by July 1",
             cost="A late or missing annual water quality report is a reporting violation that requires public notice and draws enforcement.",
             citation="40 CFR 141.152(b)", kind="required",
             input="Was this year's Consumer Confidence Report delivered to customers by July 1?",
             sample=False,
             action="Deliver the report to customers now and send the state the certification of delivery."),
        Rule(key="awia_risk_assessment", title="AWIA risk and resilience review",
             cost="Systems serving over 3,300 people that miss the 5-year review and certification face EPA enforcement.",
             citation="SDWA 1433(a) (42 U.S.C. 300i-2)", kind="max",
             input="Months since the risk and resilience assessment was last reviewed and certified to EPA",
             unit="months", limit=60, warn=54, sample=56,
             action="Complete the review, certify it to EPA, and update the emergency response plan within 6 months."),
        Rule(key="certified_operator", title="Certified operator in charge",
             cost="Running a plant without an operator of the required certification grade draws state penalties and weakens defense after incidents.",
             citation="State operator certification rules under SDWA 1419 (42 U.S.C. 300g-8) (vary by state)", kind="required",
             input="Is the treatment plant and distribution system under an operator holding the certification grade the state requires?",
             sample=True, policy=True,
             action="Assign a properly certified operator now and notify the state of the change."),
    ],

    # --- 43. LAWARMOR (law firms) ---
    43: [
        Rule(key="deadline_docketing", title="Limitations deadlines docketed",
             cost="Missed statutes of limitations and court deadlines are a common cause of malpractice claims and discipline.",
             citation="ABA Model Rule 1.3 (state versions vary); docketing is firm policy", kind="required",
             input="Is every open matter's statute of limitations and court deadline entered in the docket with reminders?",
             sample=False, policy=True,
             action="Enter the missing deadlines now, have a second person verify them, and set advance reminders."),
        Rule(key="trust_reconciliation", title="Three-way trust reconciliation",
             cost="Unreconciled trust accounts hide shortfalls that lead to disbarment, restitution and client security fund claims.",
             citation="ABA Model Rule 1.15 (state versions vary; monthly is common)", kind="max",
             input="Days since the last three-way reconciliation of the client trust account",
             unit="days", limit=31, warn=25, sample=27, policy=True,
             action="Reconcile the bank statement, trust ledger and client ledgers now and fix any difference."),
        Rule(key="no_commingling", title="No commingling of client funds",
             cost="Mixing firm and client money is a common cause of lawyer discipline, including suspension and disbarment.",
             citation="ABA Model Rule 1.15(a) (state versions vary)", kind="forbidden",
             input="Are any firm funds (beyond allowed bank fees) held in trust, or any client funds held in a firm account?",
             sample=False, policy=True,
             action="Move the funds to the correct account now and document each transfer in the ledger."),
        Rule(key="conflict_check", title="Conflict check before engagement",
             cost="Unchecked conflicts lead to disqualification, fee forfeiture and malpractice claims.",
             citation="ABA Model Rules 1.7, 1.9 and 1.10 (state versions vary)", kind="required",
             input="Was a conflict check run on the client and all adverse parties before accepting the matter?",
             sample=True, policy=True,
             action="Stop work on the matter and run the conflict check before doing anything further."),
        Rule(key="conflict_waiver_written", title="Conflict waiver confirmed in writing",
             cost="A waiver not confirmed in writing may be unenforceable, risking disqualification and fee loss.",
             citation="ABA Model Rule 1.7(b)(4) (state versions vary)", kind="required",
             input="For each waived conflict, is the client's informed consent confirmed in writing?",
             sample=True, policy=True,
             action="Send the client a written confirmation of the informed consent before continuing the representation."),
        Rule(key="contingency_fee_writing", title="Signed contingency fee agreement",
             cost="Without a signed writing, contingency fees can be reduced or forfeited and draw discipline.",
             citation="ABA Model Rule 1.5(c) (state versions vary)", kind="required",
             input="Does every contingency fee matter have a fee agreement signed by the client?",
             sample=False, policy=True,
             action="Get the written fee agreement signed now, stating the percentage and how expenses are handled."),
        Rule(key="unearned_fee_refund", title="Unearned fees refunded",
             cost="Holding unearned fees after a representation ends is a frequent grievance that leads to discipline and fee disputes.",
             citation="ABA Model Rule 1.16(d) (state versions vary)", kind="forbidden",
             input="Is the firm still holding unearned fees or client files for any representation that has ended?",
             sample=False, policy=True,
             action="Refund the unearned fees and return the client's file promptly, and record the date."),
        Rule(key="client_data_mfa", title="Client data security controls",
             cost="Breaches and wire fraud involving client data bring malpractice claims, discipline and breach-response costs.",
             citation="ABA Model Rule 1.6(c) (state versions vary); ABA Formal Opinion 477R", kind="required",
             input="Are email, document systems and remote access protected by multi-factor authentication and encryption?",
             sample=True, policy=True,
             action="Turn on multi-factor authentication for all users now and encrypt devices that hold client data."),
        Rule(key="cle_deadline", title="CLE hours by the deadline",
             cost="Lawyers who miss CLE deadlines face late fees and administrative suspension, which stops billable work.",
             citation="State CLE rules (vary by state)", kind="min",
             input="Days left before the CLE deadline for any lawyer still short of required hours",
             unit="days", limit=0, warn=60, sample=45, policy=True,
             action="Enroll the lawyer in approved courses now or request an extension from the state bar."),
        Rule(key="nonlawyer_supervision", title="Staff and vendor supervision",
             cost="Firms are responsible for staff and vendor errors with client funds and data, leading to discipline and malpractice claims.",
             citation="ABA Model Rule 5.3 (state versions vary)", kind="required",
             input="Have all non-lawyer staff and outside vendors been trained on confidentiality and trust handling this year?",
             sample=True, policy=True,
             action="Train the untrained staff now and restrict their access to client funds and data until done."),
    ],

    # --- 44. CAMPUSARMOR (colleges and universities) ---
    44: [
        Rule(key="r2t4_return_funds", title="Return of Title IV funds in 45 days",
             cost="Late returns of Title IV funds are a top program review finding, bringing liabilities, fines and risk to aid eligibility.",
             citation="34 CFR 668.22(j)(1)", kind="max",
             input="Days since the date of determination that a student withdrew, without returning unearned Title IV funds",
             unit="days", limit=45, warn=35, sample=48,
             action="Return the unearned funds now and document the calculation and return date in the student file."),
        Rule(key="clery_asr_oct1", title="Annual Security Report by Oct 1",
             cost="A late or incomplete Annual Security Report brings Clery Act fines per violation and program review findings.",
             citation="34 CFR 668.41(e); 34 CFR 668.46(b)", kind="required",
             input="Was this year's Annual Security Report published and distributed to students and staff by October 1?",
             sample=True,
             action="Publish and distribute the report now and notify prospective students and employees of it."),
        Rule(key="clery_timely_warning", title="Clery timely warnings issued",
             cost="Failing to warn the campus of a Clery crime that is a serious or continuing threat brings fines and lawsuits.",
             citation="34 CFR 668.46(e)", kind="required",
             input="Was a timely warning issued for every reported Clery crime considered a serious or continuing threat?",
             sample=True,
             action="Issue the warning now and record who decided, when, and how it was distributed."),
        Rule(key="credit_balance_14_days", title="Credit balance paid in 14 days",
             cost="Late Title IV credit balance payments are a common program review finding that leads to liabilities and fines.",
             citation="34 CFR 668.164(h)(2)", kind="max",
             input="Days since a Title IV credit balance occurred without paying it to the student or parent",
             unit="days", limit=14, warn=10, sample=12,
             action="Pay the credit balance to the student or parent now unless a valid written authorization to hold it is on file."),
        Rule(key="glba_safeguards", title="GLBA safeguards for aid data",
             cost="Missing safeguards for student financial data can bring Federal Student Aid findings, breach costs and lawsuits.",
             citation="16 CFR 314.4", kind="required",
             input="Is student financial data covered by a written security program, a qualified individual, a risk assessment, MFA and encryption?",
             sample=False,
             action="Name a qualified individual, complete the risk assessment, and turn on MFA and encryption for aid systems now."),
        Rule(key="ferpa_disclosure_consent", title="FERPA consent before disclosure",
             cost="Improper release of education records brings Department of Education investigations and can put federal funding at risk.",
             citation="34 CFR 99.30; 34 CFR 99.31", kind="required",
             input="Is written consent or a documented FERPA exception on file before each disclosure of education records?",
             sample=True,
             action="Stop the disclosure until signed consent or a documented exception is on file, and log the request."),
        Rule(key="title_ix_training", title="Title IX personnel trained",
             cost="Untrained Title IX staff lead to flawed grievance outcomes, OCR findings and lawsuits from both parties.",
             citation="34 CFR 106.45(b)(1)(iii); 34 CFR 106.45(b)(10)(i)(D)", kind="required",
             input="Have the Title IX Coordinator, investigators, decision-makers and facilitators completed required training posted on the website?",
             sample=True,
             action="Train the staff before they handle any case and post the training materials on the institution's website."),
        Rule(key="ninety_ten_revenue", title="90/10 federal revenue limit",
             cost="A for-profit school over the limit two years in a row loses Title IV eligibility.",
             citation="34 CFR 668.28; HEA 487(a)(24)", kind="max",
             input="Percent of revenue from federal education assistance funds this fiscal year (for-profit institutions)",
             unit="%", limit=90, warn=85, sample=87,
             action="Notify the Department within the required time and plan to raise non-federal revenue before year end."),
        Rule(key="sap_before_disbursement", title="Academic progress checked",
             cost="Paying aid to students not meeting academic progress rules creates repayment liabilities in program reviews.",
             citation="34 CFR 668.34", kind="required",
             input="Was satisfactory academic progress evaluated at the policy's required interval before the next aid disbursement?",
             sample=False,
             action="Hold further disbursements until SAP is evaluated and warning or probation status is applied."),
        Rule(key="dfsca_biennial_review", title="Drug and alcohol biennial review",
             cost="Missing the biennial review is a common finding that can lead to fines and risk to federal funding.",
             citation="34 CFR 86.100(b)", kind="max",
             input="Months since the last biennial review of the drug and alcohol prevention program",
             unit="months", limit=24, warn=20, sample=18,
             action="Complete and document the biennial review now and keep the report available on request."),
    ],

    # --- 45. CHILDARMOR (child care centers) ---
    45: [
        Rule(key="background_checks", title="Background checks before access",
             cost="Staff working without cleared checks lead to license actions, loss of subsidy funding and abuse lawsuits.",
             citation="45 CFR 98.43; state licensing rules", kind="required",
             input="Has every staff member cleared the required background checks before any unsupervised time with children?",
             sample=False, policy=True,
             action="Remove the staff member from unsupervised contact with children until all checks are cleared."),
        Rule(key="supervision_headcount", title="Headcount at every transition",
             cost="Children left behind, wandering off or left in vehicles lead to lawsuits, license suspension and closure.",
             citation="State child care licensing rules (vary by state)", kind="required",
             input="Was a name-to-face headcount recorded at every transition, outing and vehicle unload today?",
             sample=True, policy=True,
             action="Do a headcount now against the sign-in sheet and check all rooms, outdoor areas and vehicles."),
        Rule(key="safe_sleep", title="Infants placed on backs to sleep",
             cost="Unsafe sleep deaths bring wrongful death suits, license revocation and closure.",
             citation="45 CFR 98.41(a)(1)(ii)(B); state licensing rules", kind="forbidden",
             input="Was any infant placed to sleep on the stomach or side, or with soft bedding or objects in the crib?",
             sample=False, policy=True,
             action="Place the infant on the back in a bare crib now and retrain the caregiver on safe sleep."),
        Rule(key="infant_ratio", title="Infant staff-to-child ratio",
             cost="Ratio violations are frequently cited licensing violations and lead to fines, probation and liability.",
             citation="State licensing rules (vary by state; 1:4 for infants is common)", kind="max",
             input="Infants per caregiver in the infant room right now",
             unit="children per caregiver", limit=4, warn=4, sample=5, policy=True,
             action="Bring in another qualified caregiver now or move children so the ratio is met."),
        Rule(key="mandated_reporting", title="Suspected abuse reported",
             cost="Failing to report suspected abuse is a crime for mandated reporters and leads to license revocation and lawsuits.",
             citation="State mandated reporter laws (vary by state); CAPTA (42 U.S.C. 5106a); 45 CFR 98.41", kind="required",
             input="Has every suspected case of abuse or neglect been reported to the state hotline or police right away?",
             sample=True, policy=True,
             action="Call the state child abuse hotline now and document the report; do not investigate on your own."),
        Rule(key="cpr_first_aid", title="Pediatric CPR and first aid",
             cost="Having no certified staff on site during an emergency brings licensing citations and liability suits.",
             citation="45 CFR 98.41 (pediatric first aid and CPR); state licensing rules (vary)", kind="required",
             input="Is at least one caregiver with current pediatric CPR and first aid on site with each group at all times?",
             sample=True, policy=True,
             action="Reassign certified staff now and schedule CPR and first aid courses for staff with lapsed cards."),
        Rule(key="medication_authorization", title="Signed medication authorization",
             cost="Medication given without parent authorization or in error leads to licensing violations and injury claims.",
             citation="45 CFR 98.41 (medication administration with parental consent); state licensing rules", kind="required",
             input="Is signed parent authorization on file for every medication given to a child today?",
             sample=False, policy=True,
             action="Do not give the medication until the parent signs the authorization with drug, dose and times."),
        Rule(key="immunization_records", title="Immunization records on file",
             cost="Missing immunization records are a common licensing citation and increase outbreak liability.",
             citation="45 CFR 98.41(a)(1)(i); state licensing rules (vary)", kind="required",
             input="Does every enrolled child have a current immunization record or valid exemption on file?",
             sample=True, policy=True,
             action="Get the record or exemption from the parent by the state deadline or exclude the child as the state requires."),
        Rule(key="fire_drills", title="Fire evacuation drill",
             cost="Missed drills are a common licensing and fire inspection citation and raise liability if a fire occurs.",
             citation="State licensing rules and fire codes (vary by state; monthly is common)", kind="max",
             input="Days since the last fire evacuation drill",
             unit="days", limit=31, warn=25, sample=26, policy=True,
             action="Hold a fire evacuation drill now and log the date, time, evacuation time and children present."),
        Rule(key="cacfp_meal_pattern", title="CACFP meal pattern met",
             cost="Meals that miss the meal pattern are disallowed, and repeat problems lead to serious deficiency and termination.",
             citation="7 CFR 226.20", kind="required",
             input="Did every meal claimed for CACFP reimbursement meet the required meal pattern components?",
             sample=True,
             action="Do not claim the noncompliant meals; fix the menu and train kitchen staff on the meal pattern."),
    ],
}
