# -*- coding: utf-8 -*-
"""Rule catalog, group 4: industries 16-20 (JailArmor, InsureArmor, BankArmor,
FintechArmor, PetroArmor). Rule 1 of each industry mirrors the detailed check
in omni_armor_platform.py named by its `method`."""

from omni_armor_rules.rule import Rule

RULES = {
    # --- 16. JAILARMOR (JAILS AND PRISONS) ---
    16: [
        Rule(key="welfare_check_interval", title="Restrictive housing welfare checks",
             cost="Missed checks are central to in-custody death lawsuits and settlements, and can cost a facility its accreditation.",
             citation="Corrections standards (e.g., ACA): checks at least every 30 minutes at irregular times; common policy, set to yours",
             kind="max", input="Minutes since the last welfare check of the person in restrictive housing",
             unit="min", limit=30, warn=24, policy=True, sample=34,
             action="Check the cell now and log the time; use 15-minute or constant watch for anyone at risk of suicide.",
             method="jail_armor_wellness_timer"),
        Rule(key="prea_intake_screening", title="PREA intake risk screening",
             cost="Unscreened housing assignments lead to sexual abuse, civil rights suits and failed PREA audits.",
             citation="28 CFR 115.41(a)-(b)", kind="max",
             input="Hours since the inmate arrived without a sexual victimization and abusiveness risk screening",
             unit="h", limit=72, warn=60, sample=48,
             action="Complete the PREA risk screening now and review the housing assignment against the result."),
        Rule(key="prea_audit_cycle", title="PREA audit every three years",
             cost="States that cannot certify PREA compliance lose part of certain DOJ grant funds, and a lapsed audit weakens the defense in abuse suits.",
             citation="28 CFR 115.93; 28 CFR 115.401(a)-(b); 34 U.S.C. 30307(e)", kind="max",
             input="Months since the facility's last completed PREA audit",
             unit="months", limit=36, warn=32, sample=33,
             action="Schedule a DOJ-certified PREA auditor now so the audit is completed within the current three-year cycle."),
        Rule(key="prea_staffing_plan_review", title="Annual staffing plan review",
             cost="Documented understaffing is cited in consent decrees and abuse lawsuits against jails and prisons.",
             citation="28 CFR 115.13(a), (d)", kind="max",
             input="Months since the staffing and video monitoring plan was last assessed and documented",
             unit="months", limit=12, warn=11, sample=9,
             action="Assess the staffing plan now, document needed adjustments, and record any deviations from it."),
        Rule(key="suicide_risk_screening", title="Suicide risk screening at intake",
             cost="Suicides after missed screening bring deliberate indifference lawsuits, large settlements and federal oversight.",
             citation="Eighth and Fourteenth Amendments (deliberate indifference); Farmer v. Brennan, 511 U.S. 825 (1994); NCCHC and ACA standards",
             kind="required", input="Was every person booked today screened for suicide risk by trained staff?",
             sample=True,
             action="Screen the person now; place anyone who screens positive on observation and refer to mental health."),
        Rule(key="sick_call_triage", title="Health requests reviewed in 24 hours",
             cost="Delayed or denied medical care is a leading source of Eighth Amendment lawsuits and court-ordered monitoring.",
             citation="NCCHC standards (nonemergency requests reviewed within 24 hours; common policy); Estelle v. Gamble, 429 U.S. 97 (1976)",
             kind="max", input="Hours since the oldest unreviewed health care request was submitted",
             unit="h", limit=24, warn=20, policy=True, sample=30,
             action="Have qualified health staff triage all pending requests now and see urgent cases immediately."),
        Rule(key="prea_refresher_training", title="PREA staff refresher training",
             cost="Training gaps are common PREA audit findings, can fail the audit and weaken the defense in sexual abuse lawsuits.",
             citation="28 CFR 115.31(a), (c) (refresher training every two years; refresher information in other years)",
             kind="max", input="Months since the staff member last completed PREA refresher training",
             unit="months", limit=24, warn=22, sample=26,
             action="Schedule the staff member for PREA training now and keep the signed acknowledgment on file."),
        Rule(key="ada_effective_communication", title="Interpreters for deaf inmates",
             cost="Denying interpreters at medical, disciplinary and classification encounters is a common basis for ADA suits and DOJ settlements.",
             citation="28 CFR 35.160; 28 CFR 35.152; 42 U.S.C. 12132", kind="required",
             input="Was a qualified interpreter or other effective aid provided to deaf or hard of hearing inmates at every medical or disciplinary encounter?",
             sample=False,
             action="Postpone the encounter until a qualified interpreter (on-site or video) is provided, and log the request."),
        Rule(key="fire_alarm_testing", title="Fire alarm system testing",
             cost="Failed fire inspections can force housing units closed, and fire deaths in locked units bring major liability.",
             citation="NFPA 72 annual inspection and testing; NFPA 101 Ch. 22-23; as adopted by state or local fire code (policy)",
             kind="max", input="Days since the fire alarm and smoke detection system was last inspected and tested",
             unit="days", limit=365, warn=330, policy=True, sample=300,
             action="Schedule a qualified inspection and test of the fire alarm system now and post a fire watch if any part is down."),
        Rule(key="grievance_response", title="Grievance response deadline",
             cost="Unanswered grievances can make remedies unavailable under the PLRA, letting inmate lawsuits go forward.",
             citation="Facility grievance policy sets the deadline (common policy: 30 days); PLRA 42 U.S.C. 1997e(a); Ross v. Blake, 578 U.S. 632 (2016)",
             kind="max", input="Days since the oldest open inmate grievance was filed without a written response",
             unit="days", limit=30, warn=25, policy=True, sample=12,
             action="Issue a written response to the grievance now and log the date it was delivered to the inmate."),
    ],

    # --- 17. INSUREARMOR (INSURANCE) ---
    17: [
        Rule(key="tcpa_written_consent", title="TCPA consent for marketing calls",
             cost="Each unlawful call or text carries statutory damages, and TCPA class actions against insurers and lead buyers settle for large sums.",
             citation="47 U.S.C. 227(b)-(c); 47 CFR 64.1200(a)(2)-(3), (c)(1)-(2)", kind="required",
             input="For autodialed or prerecorded marketing calls or texts, is prior express written consent on file?",
             sample=False,
             action="Do not dial; get prior express written consent first and scrub the number against the Do Not Call Registry.",
             method="insure_armor_tcpa_filter"),
        Rule(key="producer_license_active", title="Producer licensed and CE current",
             cost="Unlicensed sales bring state fines, license revocation and commission forfeiture, and can void coverage placed.",
             citation="State insurance producer licensing laws based on the NAIC Producer Licensing Model Act; state CE rules for renewal",
             kind="required",
             input="Is every producer selling to this customer licensed in the customer's state for the line, with CE complete?",
             sample=True,
             action="Stop the producer from selling in that state or line until the license is active and CE hours are complete."),
        Rule(key="claim_acknowledgment", title="Claim acknowledged on time",
             cost="Late claim handling is a top finding in market conduct exams, leading to fines and bad-faith lawsuits.",
             citation="State unfair claims practices laws vary; NAIC model regulation and e.g. Cal. Code Regs. tit. 10, 2695.5(e) use 15 days",
             kind="max", input="Days since notice of claim was received without acknowledging it",
             unit="days", limit=15, warn=12, policy=True, sample=13,
             action="Acknowledge the claim in writing now, tell the claimant what is needed, and begin the investigation."),
        Rule(key="claim_decision", title="Claim accepted or denied on time",
             cost="Slow claim decisions draw regulator fines, interest penalties and bad-faith verdicts that can exceed policy limits.",
             citation="State law varies (e.g., 40 days after proof of claim, Cal. Code Regs. tit. 10, 2695.7(b)); set to your state",
             kind="max", input="Days since proof of claim was received without accepting or denying the claim",
             unit="days", limit=40, warn=32, policy=True, sample=45,
             action="Accept or deny the claim in writing now; if more time is needed, give written notice of what is needed and why."),
        Rule(key="cyber_event_notice", title="Cybersecurity event notice",
             cost="Late notice of a data breach to the insurance regulator brings penalties, consent orders and costly remediation plans.",
             citation="NAIC Insurance Data Security Model Law (#668) Sec. 6 as adopted by states; 23 NYCRR 500.17(a); state versions vary",
             kind="max", input="Hours since the company determined a reportable cybersecurity event occurred",
             unit="h", limit=72, warn=48, policy=True, sample=20,
             action="Notify the insurance commissioner now with the facts known, and update the notice as more is learned."),
        Rule(key="mfa_remote_access", title="Multi-factor authentication",
             cost="Missing MFA is a frequently cited failings in NYDFS cybersecurity consent orders and a common path to costly breaches.",
             citation="23 NYCRR 500.12 (NYDFS licensees); NAIC Insurance Data Security Model Law (#668) Sec. 4 as adopted by states",
             kind="required",
             input="Is multi-factor authentication required for all remote access and all access to systems holding customer data?",
             sample=True,
             action="Turn on multi-factor authentication for the account or system now, or disable remote access until it is on."),
        Rule(key="glba_privacy_notice", title="Privacy notice to customers",
             cost="Missing privacy notices are cited in market conduct exams and lead to fines and required corrective mailings.",
             citation="15 U.S.C. 6803(a), 6805(a)(6); state insurance privacy rules based on NAIC Model Regulation #672",
             kind="required",
             input="Was a privacy notice given to the customer when the customer relationship began?",
             sample=True,
             action="Deliver the privacy notice now, including opt-out rights, before sharing information with nonaffiliated parties."),
        Rule(key="hipaa_breach_notice", title="HIPAA breach notice to members",
             cost="Late breach notices bring HHS OCR civil money penalties, resolution agreements and class action lawsuits.",
             citation="45 CFR 164.404(b)", kind="max",
             input="Days since a breach of unsecured protected health information was discovered without notifying members",
             unit="days", limit=60, warn=45, sample=64,
             action="Send breach notices to affected individuals now, and notify HHS and media as 45 CFR 164.406-164.408 require."),
        Rule(key="ofac_screening", title="OFAC sanctions screening",
             cost="OFAC penalties apply on a strict liability basis to policies issued or claims paid to sanctioned parties.",
             citation="31 CFR Chapter V (OFAC regulations); blocked property reports, 31 CFR 501.603", kind="required",
             input="Were the policyholder, insureds and claim payees screened against the OFAC SDN list?",
             sample=True,
             action="Hold the policy or payment and screen all parties now; block and report any confirmed match to OFAC."),
        Rule(key="life_insurer_sar", title="SAR filing for covered products",
             cost="Late or missing SARs bring FinCEN civil money penalties and AML consent orders for life insurers.",
             citation="31 CFR 1025.320(b)(3)", kind="max",
             input="Days since suspicious activity on a covered life or annuity product was first detected",
             unit="days", limit=30, warn=25, sample=27,
             action="File the SAR with FinCEN now and keep the supporting records for five years."),
    ],

    # --- 18. BANKARMOR (BANKS AND CREDIT UNIONS) ---
    18: [
        Rule(key="ctr_cash_threshold", title="Currency Transaction Report",
             cost="Missed CTRs and ignored structuring bring FinCEN and bank regulator penalties and BSA consent orders.",
             citation="31 CFR 1010.311, 1010.313 (aggregation); filed within 15 days, 31 CFR 1010.306(a)(1); structuring, 31 U.S.C. 5324",
             kind="max", input="Customer's total cash in or out today, aggregated across transactions",
             unit="$", limit=10000, warn=9000, sample=9600,
             action="File a FinCEN CTR within 15 calendar days; the transaction may proceed. Review recent activity for structuring.",
             method="bank_armor_ctr_monitor"),
        Rule(key="sar_filing_deadline", title="SAR filed within 30 days",
             cost="Late or missing SARs are frequently cited BSA failures, leading to civil money penalties and consent orders.",
             citation="31 CFR 1020.320(b)(3) (30 days; up to 60 if no suspect is identified)", kind="max",
             input="Days since suspicious activity was first detected without a SAR filed",
             unit="days", limit=30, warn=25, sample=34,
             action="File the SAR with FinCEN now; call law enforcement first if the activity needs immediate attention."),
        Rule(key="cip_identity_collected", title="Customer identification (CIP)",
             cost="CIP gaps are cited in BSA exams and lead to penalties, consent orders and limits on opening new accounts.",
             citation="31 CFR 1020.220(a)(2)", kind="required",
             input="Were name, date of birth, address and ID number collected before the account was opened?",
             sample=True,
             action="Restrict the account until the missing identity information is collected and verified."),
        Rule(key="beneficial_ownership", title="Beneficial owners identified",
             cost="Missing beneficial ownership records are a frequent BSA exam finding behind penalties and consent orders.",
             citation="31 CFR 1010.230(a)-(b)", kind="required",
             input="For a legal entity customer, were beneficial owners identified and verified at account opening?",
             sample=False,
             action="Collect the beneficial ownership certification and verify each owner's identity before further activity."),
        Rule(key="ofac_screening", title="OFAC sanctions screening",
             cost="OFAC penalties apply on a strict liability basis to payments for sanctioned parties and can be very large.",
             citation="31 CFR Chapter V (OFAC regulations); blocked property reports, 31 CFR 501.603", kind="required",
             input="Were all parties to the account or payment screened against the OFAC SDN list?",
             sample=True,
             action="Hold the transaction and screen all parties now; block and report any confirmed match to OFAC."),
        Rule(key="reg_e_error_resolution", title="Reg E error investigation",
             cost="Mishandled EFT disputes bring CFPB and regulator enforcement, required restitution and class actions.",
             citation="12 CFR 1005.11(c)(1)-(2)", kind="max",
             input="Business days since the customer reported an EFT error without a decision or provisional credit",
             unit="business days", limit=10, warn=8, sample=7,
             action="Finish the investigation or give provisional credit now, and tell the customer the result in writing."),
        Rule(key="trid_closing_disclosure", title="Closing Disclosure 3 days early",
             cost="Late Closing Disclosures force closing delays, and TRID errors lead to restitution and TILA liability.",
             citation="12 CFR 1026.19(f)(1)(ii)(A)", kind="min",
             input="Business days before consummation that the borrower received the Closing Disclosure",
             unit="business days", limit=3, warn=3, sample=2,
             action="Reschedule consummation so the borrower has the Closing Disclosure at least 3 business days beforehand."),
        Rule(key="ecoa_adverse_action", title="Adverse action notice in 30 days",
             cost="Missing or late adverse action notices are common fair lending findings behind restitution and CFPB orders.",
             citation="12 CFR 1002.9(a)(1)(i)", kind="max",
             input="Days since a completed credit application was received without a decision notice",
             unit="days", limit=30, warn=25, sample=18,
             action="Send the decision now; if denied, give specific reasons or the right to request them, plus the ECOA notice."),
        Rule(key="flood_insurance", title="Flood insurance at loan closing",
             cost="Flood insurance violations carry mandatory civil money penalties per violation and are regularly cited in exams.",
             citation="42 U.S.C. 4012a(b), (f); 12 CFR 339.3 (FDIC), 12 CFR 22.3 (OCC), 12 CFR 208.25 (Fed), 12 CFR 760.3 (NCUA)",
             kind="required",
             input="For a building in a special flood hazard area, is flood insurance in place at or before loan closing?",
             sample=True,
             action="Do not close, extend or renew the loan until required flood insurance is in place."),
        Rule(key="billing_error_acknowledgment", title="Billing error acknowledged in 30 days",
             cost="Mishandled credit card billing disputes lead to CFPB enforcement, customer restitution and forfeited disputed amounts.",
             citation="12 CFR 1026.13(c)(1) (resolve within two billing cycles, no later than 90 days, under 1026.13(c)(2))",
             kind="max", input="Days since a credit card billing error notice was received without a written acknowledgment or resolution",
             unit="days", limit=30, warn=25, sample=12,
             action="Send the written acknowledgment now and do not collect the disputed amount until the error is resolved."),
    ],

    # --- 19. FINTECHARMOR (ADVISERS, BROKER-DEALERS, FINTECH) ---
    19: [
        Rule(key="form_adv_annual_amendment", title="Form ADV annual amendment",
             cost="Late Form ADV filings draw SEC or state deficiency findings and fines, and a long lapse can end registration.",
             citation="17 CFR 275.204-1(a)(1) (within 90 days of fiscal year-end)", kind="max",
             input="Days since the adviser's fiscal year-end without the annual Form ADV amendment filed",
             unit="days", limit=90, warn=75, sample=82,
             action="File the annual updating amendment on IARD now and deliver the brochure or summary of changes to clients.",
             method="fintech_armor_adv_countdown"),
        Rule(key="marketing_net_performance", title="Net performance in advertising",
             cost="Marketing Rule violations are an SEC enforcement priority and lead to settled orders and civil penalties.",
             citation="17 CFR 275.206(4)-1(d)(1)", kind="forbidden",
             input="Does any advertisement show gross performance without net performance shown with at least equal prominence?",
             sample=True,
             action="Pull the advertisement and reissue it with net performance for the same periods, shown as prominently."),
        Rule(key="custody_audit_delivery", title="Private fund audit delivery",
             cost="Late fund audits break the custody rule, a frequent SEC exam finding that leads to settled orders and penalties.",
             citation="17 CFR 275.206(4)-2(b)(4) (120 days; 180 days for funds of funds)", kind="max",
             input="Days since the private fund's fiscal year-end without audited financials delivered to investors",
             unit="days", limit=120, warn=100, sample=95,
             action="Press the auditor to finish now and deliver the audited financials; report any delay on Form ADV as required."),
        Rule(key="reg_sp_breach_notice", title="Reg S-P customer breach notice",
             cost="Late breach notices bring SEC enforcement, customer lawsuits and loss of client trust and assets.",
             citation="17 CFR 248.30(a)(4) (Reg S-P as amended in 2024)", kind="max",
             input="Days since learning sensitive customer information was, or likely was, accessed without authorization",
             unit="days", limit=30, warn=24, sample=10,
             action="Send notices to affected customers now, as required by the incident response program."),
        Rule(key="off_channel_communications", title="Business texts captured and kept",
             cost="Unrecorded texting on personal devices has led to large SEC and CFTC recordkeeping penalties against firms.",
             citation="17 CFR 240.17a-4(b)(4) (broker-dealers); 17 CFR 275.204-2(a)(7) (advisers)", kind="forbidden",
             input="Do staff use personal texting or messaging apps for business that the firm does not capture and retain?",
             sample=True,
             action="Stop off-channel business messaging, move staff to an archived tool, and collect the messages that were missed."),
        Rule(key="form_crs_delivery", title="Form CRS delivered to retail clients",
             cost="Missed Form CRS delivery is a common SEC and FINRA exam finding that leads to fines and required remediation.",
             citation="17 CFR 240.17a-14(c) (broker-dealers); 17 CFR 275.204-5(b) (advisers)", kind="required",
             input="Was Form CRS delivered to the retail investor before or at the first recommendation, order, account opening or advisory contract?",
             sample=True,
             action="Deliver the current Form CRS now and record the delivery date before taking further action on the account."),
        Rule(key="ecoa_adverse_action", title="Adverse action notice in 30 days",
             cost="Missing or late adverse action notices from fintech lenders lead to CFPB orders, restitution and penalties.",
             citation="12 CFR 1002.9(a)(1)(i)", kind="max",
             input="Days since a completed credit application was received without a decision notice",
             unit="days", limit=30, warn=25, sample=31,
             action="Send the decision now; if denied, give the specific principal reasons, not just model outputs."),
        Rule(key="money_transmitter_license", title="Money transmitter licenses",
             cost="Unlicensed money transmission brings state cease-and-desist orders and fines, and criminal exposure under federal law.",
             citation="State money transmitter laws; 18 U.S.C. 1960; FinCEN MSB registration, 31 CFR 1022.380", kind="required",
             input="Is the company licensed, or exempt, as a money transmitter in every state where it serves customers?",
             sample=True,
             action="Stop onboarding customers in the unlicensed state until a license is obtained or an exemption is confirmed."),
        Rule(key="sar_filing_deadline", title="SAR filed within 30 days",
             cost="Late or missing SARs bring FinCEN, SEC and FINRA penalties and AML consent orders.",
             citation="31 CFR 1023.320(b)(3) (broker-dealers); 31 CFR 1022.320(b)(3) (money services businesses)", kind="max",
             input="Days since suspicious activity was first detected without a SAR filed",
             unit="days", limit=30, warn=25, sample=14,
             action="File the SAR with FinCEN now and keep the supporting documentation for five years."),
        Rule(key="net_capital_minimum", title="Broker-dealer net capital",
             cost="A broker-dealer below its net capital minimum must stop doing business, and violations bring SEC and FINRA fines.",
             citation="17 CFR 240.15c3-1; notice to regulators, 17 CFR 240.17a-11 (early warning at 120% of the minimum)", kind="min",
             input="Net capital as a percent of the firm's required minimum",
             unit="%", limit=100, warn=120, sample=115,
             action="Stop business that uses capital, notify the SEC and FINRA the same day, and add capital before resuming."),
    ],

    # --- 20. PETROARMOR (OIL AND GAS PRODUCTION AND PIPELINES) ---
    20: [
        Rule(key="valve_inspection_interval", title="Transmission valve inspection",
             cost="Missed valve inspections are common PHMSA findings that lead to civil penalties and orders to fix or shut in lines.",
             citation="49 CFR 192.745(a) (at least once each calendar year, not over 15 months apart)", kind="max",
             input="Months since the transmission valve was last inspected and partially operated",
             unit="months", limit=15, warn=13, sample=16,
             action="Inspect and partially operate the valve now; if it does not work, fix it or designate an alternative valve.",
             method="petro_armor_valve_sentry"),
        Rule(key="ldar_leak_repair", title="Methane leak repair deadline",
             cost="LDAR failures are a frequent EPA Clean Air Act case, leading to civil penalties and consent decrees.",
             citation="40 CFR 60.5397a(h) (OOOOa); 40 CFR 60.5397b(h) (OOOOb): first repair attempt within 30 days of detection",
             kind="max", input="Days since a fugitive emissions leak was detected without a repair attempt",
             unit="days", limit=30, warn=24, sample=12,
             action="Attempt the repair now, resurvey to confirm it holds, and record the repair and resurvey dates."),
        Rule(key="spcc_plan_review", title="SPCC plan five-year review",
             cost="Out-of-date SPCC plans are routine EPA inspection findings with civil penalties, and worsen spill liability.",
             citation="40 CFR 112.5(b)", kind="max",
             input="Months since the SPCC plan was last reviewed and evaluated",
             unit="months", limit=60, warn=54, sample=58,
             action="Complete and document the SPCC plan review now, and amend the plan if technology or the facility has changed."),
        Rule(key="psm_pha_revalidation", title="Process hazard analysis update",
             cost="Out-of-date hazard analyses are frequently cited PSM items, bringing OSHA penalties and raising explosion risk.",
             citation="29 CFR 1910.119(e)(6)", kind="max",
             input="Months since the process hazard analysis was last updated and revalidated",
             unit="months", limit=60, warn=54, sample=40,
             action="Assemble a qualified team and update and revalidate the process hazard analysis now."),
        Rule(key="h2s_exposure", title="Hydrogen sulfide exposure",
             cost="H2S overexposure can kill workers within minutes, leading to OSHA citations, shutdowns and wrongful death suits.",
             citation="29 CFR 1910.1000 Table Z-2 (ceiling 20 ppm; 50 ppm peak up to 10 minutes once per shift if no other exposure)",
             kind="max", input="Highest H2S concentration measured in the worker's breathing zone",
             unit="ppm", limit=20, warn=10, sample=25,
             action="Move workers upwind out of the area now; re-enter only with supplied-air respirators after the source is found."),
        Rule(key="pipeline_incident_call", title="Pipeline incident phone report",
             cost="Late incident reports to the National Response Center draw PHMSA civil penalties and heavier scrutiny after an accident.",
             citation="49 CFR 191.5(a) (gas); 49 CFR 195.52(a) (hazardous liquid): no later than one hour after confirmed discovery",
             kind="max", input="Hours since a reportable pipeline incident was confirmed without calling the National Response Center",
             unit="h", limit=1, warn=0.75, sample=0.5,
             action="Call the National Response Center at 1-800-424-8802 now, then file the written report on time."),
        Rule(key="operator_qualification", title="Operator qualification for tasks",
             cost="Unqualified workers on covered tasks are common PHMSA findings that lead to civil penalties and raise accident risk.",
             citation="49 CFR 192.805 (gas); 49 CFR 195.505 (hazardous liquid)", kind="required",
             input="Is every person performing covered pipeline tasks today qualified under the written OQ program?",
             sample=False,
             action="Stop the task until a qualified person performs it or directly observes and directs the unqualified worker."),
        Rule(key="sems_audit", title="Offshore SEMS audit",
             cost="Missed SEMS audits bring BSEE incidents of noncompliance, civil penalties and possible shut-in of operations.",
             citation="30 CFR 250.1920(a)", kind="max",
             input="Months since the last independent SEMS audit of the offshore facility",
             unit="months", limit=36, warn=32, sample=30,
             action="Engage an accredited audit service provider now and submit the audit report to BSEE on time."),
        Rule(key="cathodic_protection_survey", title="Cathodic protection annual survey",
             cost="Missed corrosion control tests are frequent PHMSA findings that lead to civil penalties and raise the risk of leaks and ruptures.",
             citation="49 CFR 192.465(a) (gas); 49 CFR 195.573(a)(1) (hazardous liquid): each calendar year, not over 15 months apart",
             kind="max", input="Months since cathodic protection test readings were last taken on the pipeline",
             unit="months", limit=15, warn=13, sample=11,
             action="Take the cathodic protection readings now and correct any deficiency found."),
        Rule(key="oil_sheen_reporting", title="Oil spill reported immediately",
             cost="Failing to report an oil discharge brings Clean Water Act civil and criminal penalties on top of cleanup costs.",
             citation="33 U.S.C. 1321(b)(5); 40 CFR 110.3, 110.6", kind="required",
             input="Was every oil discharge that caused a sheen on water reported to the National Response Center immediately?",
             sample=True,
             action="Call the National Response Center at 1-800-424-8802 now and start containment and cleanup."),
    ],
}
