"""Academy question bank: the Big Picture unit."""

WORLDS = [
    {
        "key": "startup",
        "title": "Start a Business",
        "tagline": "From idea to open for business",
        "icon": "flag",
        "cards": [
            ("Solve a real problem", "Great businesses start by fixing a problem people really have, like a busy street with no place to fix a flat bike tire."),
            ("Test it small first", "Before spending a lot, try a tiny version. Sell 20 cookies at a school fair and see if people come back for more."),
            ("Know your startup costs", "Startup costs are what you spend before you earn: tools, supplies, a sign, permits. List them all so there are no surprises."),
            ("Follow the rules", "In many places a business needs permits or licenses, and food sellers must follow safety rules. Ask the local town office what you need."),
            ("Listen to early customers", "Your first customers are your best teachers. Ask what they liked and what to fix, then improve a little every week."),
        ],
        "questions": [
            ("What is the best first step for a new business idea?", "Check that real people want it",
             "Buy lots of supplies right away", "Rent a big store downtown",
             "Testing whether people want it first saves money if the idea needs changes.", 1),
            ("What does it mean when a business 'solves a problem'?", "It makes something easier or better for people",
             "It sells the most expensive item in town", "It copies whatever another shop is selling",
             "People pay for things that fix a need, like a bakery on a street with no fresh bread.", 1),
            ("Which is an example of a startup cost for a lemonade stand?", "Buying lemons, cups and a pitcher",
             "The money a customer pays for a cup", "The tip a neighbor gives you",
             "Startup costs are what you spend before you can sell anything. Customer payments are money coming in, not going out.", 1),
            ("What is a permit?", "Official permission to do something, like sell food",
             "A coupon that gives customers a discount", "A list of the prices on your menu",
             "Permits come from the local government and show you are allowed to run that kind of business safely.", 1),
            ("Why does a business need a good name?", "So customers can remember and find it",
             "So it can charge double the price", "So it never has to pay any taxes",
             "A clear, easy name helps people tell friends and find you again. It does not change prices or taxes.", 1),
            ("Who are your first customers often likely to be?", "Friends, family and neighbors nearby",
             "Big companies in other countries", "People who have never heard of you",
             "People who already know you are most likely to try something new first. Their feedback helps you improve.", 1),
            ("What is customer feedback?", "What customers tell you about your product",
             "The money you pay to your suppliers", "A sign you hang outside your shop",
             "Feedback is comments from customers, good or bad. It tells you what to keep and what to fix.", 1),
            ("You sold 10 cupcakes on Saturday and 15 on Sunday. How many did you sell in all?", "25 cupcakes",
             "20 cupcakes", "30 cupcakes",
             "10 plus 15 equals 25. Keeping count of sales each day shows if your business is growing.", 1),
            ("Why is starting small a smart idea?", "You can learn and fix mistakes cheaply",
             "Small businesses never have to work hard", "It means you never need customers",
             "Small mistakes cost little money. Once you know what works, you can grow with more confidence.", 1),
            ("Which name is best for a dog-walking business?", "Happy Paws Dog Walking",
             "Business Number 4217", "Xqzt Services Group",
             "A good name is easy to say and tells people what you do. A random code or jumble is hard to remember.", 1),
            ("Your pet-sitting flyers cost $5 and a leash costs $10. What are your startup costs?", "$15",
             "$5", "$50",
             "$5 plus $10 equals $15. Adding up every startup cost tells you how much money you need before you begin.", 1),
            ("A customer says your cookies are too salty. What should you do?", "Thank them and try less salt next batch",
             "Tell them they are wrong about taste", "Stop making cookies forever",
             "Feedback is a gift. A small change based on what customers say can make your product much better.", 1),

            ("You want to open a bakery. What is a smart way to test the idea small?", "Sell at a weekend market for a month",
             "Sign a ten-year lease on a big shop", "Buy five ovens before baking anything",
             "A market stall costs little and shows if people buy your bread and come back, before you risk lots of money.", 2),
            ("Before choosing a business name, what should you check?", "That no nearby business already uses it",
             "That it is the longest name possible", "That it uses as many numbers as it can",
             "Using another business's name confuses customers and can break rules in many places. Checking first avoids trouble.", 2),
            ("A food truck owner wants to start selling. Which should she get first?", "The food safety permits her area needs",
             "A huge billboard on the highway", "A second food truck for later",
             "Selling food without the right permits can mean fines or being shut down. Rules come before advertising.", 2),
            ("What is a 'minimum viable product'?", "The simplest version that still solves the problem",
             "The most expensive version you can build", "A product made only for your family",
             "Starting with a simple version lets you test with real customers fast, then add features they actually want.", 2),
            ("Startup costs for a bike repair stand: tools $120, sign $30, permit $50. What is the total?", "$200",
             "$170", "$150",
             "$120 plus $30 is $150, plus $50 is $200. Listing every cost keeps you from running out of money.", 2),
            ("Ten people tried your new smoothie. Eight said it was too sweet. What does this tell you?", "Most testers want it less sweet",
             "Your smoothie is perfect as it is", "Smoothies are a bad business idea",
             "When most testers say the same thing, it is a clear pattern worth fixing. One complaint is less clear than eight.", 2),
            ("Why should you ask your local town or city office before opening?", "They explain which permits and rules apply",
             "They will run the business for you", "They pay your first month of rent",
             "Rules differ from place to place. The local office can tell you what licenses, safety checks and zoning rules apply.", 2),
            ("Which is the best way to find a business idea?", "Notice problems people complain about",
             "Pick whatever sounds the most fancy", "Choose the idea with the highest price",
             "Complaints point to needs. If neighbors keep saying there is nowhere to fix bikes, that is a possible business.", 2),
            ("You have $60 saved. Startup costs are $85. How much more do you need?", "$25",
             "$15", "$35",
             "$85 minus $60 is $25. Knowing the gap helps you plan, like saving longer or starting with fewer supplies.", 2),
            ("Your first 20 customers loved your brownies but said the price was too high. What is a smart move?", "Test a smaller size at a lower price",
             "Raise the price even more right away", "Ignore them since they liked the taste",
             "A smaller size can keep your profit while fitting what customers want to pay. Testing shows if it works.", 2),
            ("What does 'zoning' mean for a business?", "Rules about what can be built or run in each area",
             "The way a store arranges items on shelves", "A special sale that happens once a year",
             "In many places, some streets are for homes and others for shops. Zoning rules say where a business can operate.", 2),
            ("What is a good reason to keep a notebook during your first months?", "To track what sells and what customers say",
             "To write down only your favorite colors", "To hide your costs from your family",
             "Notes show patterns over time, like which flavor sells best, so your choices are based on facts, not memory.", 2),

            ("Idea A: a candle shop with 3 candle shops nearby. Idea B: a shoe repair stand with none nearby. Which is likely easier to start?", "Idea B, since the need is not being met",
             "Idea A, since buyers already shop there", "Idea A, since more rivals means more fun",
             "When a need is not being met, you face less competition. A crowded market is harder for a brand new business.", 3),
            ("You made $90 in sales and spent $40 on supplies in your first week. What was your profit?", "$50",
             "$130", "$40",
             "Profit is sales minus costs: $90 minus $40 equals $50. Sales alone do not show if you made money.", 3),
            ("Why might a new owner start with a cart instead of a full store?", "Lower costs while proving people will buy",
             "Carts never need any permits at all", "Customers only trust businesses with carts",
             "A cart costs far less than a store. If sales are strong, you can grow with proof instead of hope.", 3),
            ("A survey says 50 people 'would buy' your snack, but only 5 bought it at a test sale. What should you trust more?", "The 5 real sales",
             "The 50 survey answers", "Neither one tells you anything",
             "What people do matters more than what they say. Real purchases show true demand; surveys can be too hopeful.", 3),
            ("Your craft kits cost $4 each to make. You sell 30 at $10 each. What is your profit?", "$180",
             "$300", "$120",
             "Sales are 30 times $10, or $300. Costs are 30 times $4, or $120. Profit is $300 minus $120, which is $180.", 3),
            ("A friend says to skip the permit because 'nobody checks'. What is the best choice?", "Get the permit and follow the rules",
             "Skip it to save time and money", "Open first and get it only if caught",
             "Rules protect customers and your business. Getting caught without a permit can bring fines or closing, and it breaks trust.", 3),
            ("What is a 'pivot' for a startup?", "Changing direction based on what you learned",
             "Spinning the shop sign so more people see it", "Closing the business at the first problem",
             "If testing shows customers want something a bit different, a pivot lets you adjust instead of giving up.", 3),
            ("You must cut startup costs. Which cut is wisest?", "Buy used tools that are in good shape",
             "Skip the required safety permit", "Use old ingredients that are past their date",
             "Used tools can save a lot and still work well. Skipping permits or safety is risky, unfair to customers and can end your business.", 3),
            ("Week 1 you had 12 customers, week 2 had 18, week 3 had 24. If the pattern continues, how many in week 4?", "30",
             "28", "36",
             "Customers went up by 6 each week: 12, 18, 24. Adding 6 more gives 30.", 3),
            ("Why is it smart to set some money aside when you start?", "Surprise costs often show up early",
             "Saving money is against business rules", "Customers pay you before you buy anything",
             "New businesses often find costs they did not expect, like a broken tool. A cushion keeps you open while you fix it.", 3),
            ("Early feedback is mixed: some love your spicy salsa, some say it is too hot. What is a smart test?", "Offer a mild and a hot version",
             "Make it even hotter for everyone", "Stop asking customers what they think",
             "Offering two choices lets both groups buy. Sales of each version will show which one people really want.", 3),
            ("Which is the strongest sign your idea is ready to grow?", "Customers keep coming back and telling friends",
             "Your best friend said it sounded cool once", "You spent a lot of money on a fancy logo",
             "Repeat customers and word of mouth show real demand. Opinions and spending do not prove people will buy.", 3),
        ],
        "facts": [
            ("Many successful businesses start by solving a simple, everyday problem.", True,
             "Fixing a common need, like quick bike repairs, gives people a clear reason to buy."),
            ("A business idea should always be tested with a big, expensive launch.", False,
             "Testing small first, like a market stall, costs less and shows what customers really want."),
            ("In many places, businesses that sell food must follow special safety rules.", True,
             "Food rules protect people from getting sick, so inspectors may check kitchens and storage."),
            ("Startup costs are the money customers pay you on your first day.", False,
             "Startup costs are what you spend before opening, like tools and supplies. Customer payments are sales."),
            ("Negative feedback from customers can help a business improve.", True,
             "Complaints show what to fix. Owners who listen and improve often keep customers longer."),
            ("A business name can be anything, even if another nearby shop already uses it.", False,
             "Using a name that is already taken confuses customers and can break rules in many places."),
            ("Many big businesses started out very small.", True,
             "Lots of companies began in a kitchen, garage or market stall before they grew."),
            ("If friends say they like your idea, you can be sure it will succeed.", False,
             "Friends want to be kind. Real sales to strangers are much stronger proof that people want it."),
            ("Changing your product based on what you learn is a normal part of starting.", True,
             "Most startups adjust their idea several times as they learn what customers want."),
            ("Permits and licenses are the same in every town and country.", False,
             "Rules differ by place, so owners should ask their local office what their business needs."),
            ("Saving extra money for surprise costs is a smart startup habit.", True,
             "Unexpected costs, like a repair, are common early on. A cushion keeps the business running."),
            ("Your first customers do not matter much because the business is still small.", False,
             "First customers spread the word and give feedback. Treating them well helps the business grow."),
        ],
    },
    {
        "key": "plan",
        "title": "Business Plans",
        "tagline": "Map out where you're going",
        "icon": "map",
        "cards": [
            ("What is a business plan?", "A business plan is a written map of your business: what you sell, who buys it, how you will make money and what your goals are."),
            ("Mission and vision", "Your mission says what you do and why, today. Your vision describes the bigger future you are working toward."),
            ("Know customers and rivals", "Describe who your customers are and what they need. Then study competitors so you know how to be different or better."),
            ("Costs, sales and goals", "Estimate what you will spend and sell each month. Set clear goals with numbers and dates, like 40 customers by June."),
            ("Keep the plan alive", "A plan is never really finished. Update it as you learn, and use it to explain your idea to a bank or a partner."),
        ],
        "questions": [
            ("What is a business plan?", "A written map of how a business will work",
             "A list of your favorite snacks", "A drawing of the store's front door",
             "A business plan explains what you sell, who buys it and how you will make money, so you can make smart choices.", 1),
            ("What does a mission statement tell people?", "What the business does and why",
             "How much the owner earns each year", "The address of every customer",
             "A mission explains your purpose, like 'We bake fresh, healthy bread for our neighborhood every morning.'", 1),
            ("Who are a business's customers?", "The people who buy its products",
             "The people who build its shelves", "The people who own other shops",
             "Customers are the people who pay for what you sell. Knowing them well helps you make the right products.", 1),
            ("What is a competitor?", "Another business selling similar things",
             "A customer who buys a lot from you", "A worker who helps in your shop",
             "Competitors offer customers a similar choice. Two pizza shops on one street are competitors.", 1),
            ("Which is an example of a clear business goal?", "Sell 50 cupcakes each week by May",
             "Be kind of good at stuff someday", "Try to do some things soon",
             "Clear goals have a number and a date, so you can check if you reached them.", 1),
            ("Why do business owners write down their plans?", "To think clearly and stay on track",
             "To make the shop look more crowded", "Because plans replace the need to work",
             "Writing a plan helps you spot problems early and remember your goals when you get busy.", 1),
            ("Each cup of lemonade costs $1 to make. You plan to sell 20 cups. What will the 20 cups cost to make?", "$20",
             "$10", "$40",
             "20 cups times $1 each equals $20. Plans use simple math like this to predict costs.", 1),
            ("What is a 'vision' for a business?", "A picture of what it hopes to become",
             "The glasses the owner wears at work", "The list of today's prices",
             "A vision is a big future goal, like 'Every kid in town can get a bike fixed fast and fairly.'", 1),
            ("Who might want to read your business plan?", "A bank deciding whether to lend money",
             "A shopper looking for a free snack", "A neighbor walking a dog past the shop",
             "Banks and partners read plans to see if your idea is well thought out before they help with money.", 1),
            ("What should a plan say about your product?", "What it is and why people will want it",
             "Only the color of the packaging", "Nothing, since products are not important",
             "The plan should explain what you sell and the problem it solves, so readers see why customers will buy.", 1),
            ("You plan to sell 10 bracelets a day for 5 days. How many bracelets is that?", "50",
             "15", "40",
             "10 times 5 equals 50. Sales forecasts often multiply a daily number by the number of days.", 1),
            ("How often should you look at your business plan?", "Regularly, to check progress and update it",
             "Never again once it is written", "Only if the business closes",
             "Checking your plan often shows if you are meeting goals and what to change as things happen.", 1),

            ("You want to open a bike shop. Which question belongs in the 'customers' part of your plan?", "Who in town rides bikes and what do they need?",
             "What color should the shop floor be?", "How tall is the building next door?",
             "The customer section describes who will buy and what they want, so you stock the right bikes and services.", 2),
            ("A competitor sells cookies for $2. Yours cost more to make. What could make your cookies worth more?", "Special flavors or fresher ingredients",
             "Hiding your price from customers", "Saying bad things about the other shop",
             "Being different in a way customers value, like quality or unique flavors, can honestly justify a higher price.", 2),
            ("What is a sales forecast?", "A careful guess of future sales",
             "A report about tomorrow's weather", "A list of past customers' names",
             "A forecast predicts how much you will sell, using facts like past sales and the number of likely customers.", 2),
            ("Your plan expects $300 in sales and $180 in costs each month. What is the expected profit?", "$120",
             "$480", "$180",
             "Profit equals sales minus costs. $300 minus $180 is $120.", 2),
            ("Which goal is the most useful for a plan?", "Get 30 new customers by the end of March",
             "Get lots of customers at some point", "Become famous without a set time",
             "Specific, measurable goals with a deadline let you track progress. Vague goals are hard to check.", 2),
            ("Why should a plan describe competitors?", "To show how your business will stand out",
             "To copy everything they do exactly", "To prove you have no rivals at all",
             "Knowing rivals helps you find a gap, like longer hours or better service, that gives customers a reason to choose you.", 2),
            ("What is a 'fixed cost' in a plan?", "A cost that stays the same each month, like rent",
             "A cost for something that got repaired", "A cost that changes with every sale",
             "Fixed costs, like rent, stay the same even if sales go up or down. Ingredients are variable costs that change with sales.", 2),
            ("What is a 'variable cost' for a bakery?", "Flour, which rises when you bake more",
             "Monthly rent for the shop", "The yearly cost of a permit",
             "Variable costs grow with how much you make. More loaves need more flour, but rent stays the same.", 2),
            ("Rent is $400 a month. How much is rent for a year?", "$4,800",
             "$4,000", "$400",
             "There are 12 months in a year. 12 times $400 equals $4,800.", 2),
            ("Halfway through the year, sales are lower than your plan expected. What should you do?", "Find out why and update the plan",
             "Throw the plan away for good", "Pretend sales are fine on paper",
             "Plans are guesses. When results differ, learn the reason and adjust, like changing prices or marketing.", 2),
            ("Which belongs in a plan's 'marketing' section?", "How customers will hear about you",
             "The owner's favorite movie", "The recipe for every cookie",
             "Marketing explains how you will reach customers, like flyers, a website or signs, and how much it will cost.", 2),
            ("Your mission is 'healthy snacks for kids.' Which new product fits best?", "Fruit cups with no added sugar",
             "Giant candy bars with extra sugar", "Car parts for local garages",
             "Products that match your mission keep the business focused and help customers trust what you stand for.", 2),

            ("A bank asks how you will repay a $1,000 loan. Which plan answer is strongest?", "Show monthly profit and when it covers payments",
             "Say you feel very sure it will work", "Promise to pay when you get lucky",
             "Banks want numbers. Showing expected profit and a repayment schedule proves you thought it through.", 3),
            ("Each smoothie costs $2 to make and sells for $5. How many must you sell to earn $60 in profit?", "20",
             "12", "30",
             "Each smoothie earns $5 minus $2, which is $3 profit. $60 divided by $3 is 20 smoothies.", 3),
            ("What is a 'break-even point'?", "When sales just cover all costs, with no profit or loss",
             "When the shop's equipment breaks down", "When you sell half of your products",
             "At break-even, money in equals money out. Every sale after that adds profit.", 3),
            ("Fixed costs are $200 a month. Each cake earns $10 after ingredients. How many cakes to break even?", "20",
             "10", "200",
             "You need $200 to cover fixed costs. Each cake adds $10, so $200 divided by $10 is 20 cakes.", 3),
            ("You are presenting your plan to a possible partner. What should you do?", "Explain clearly and share real numbers and risks",
             "Hide the risks so it sounds perfect", "Talk only about how fun it will be",
             "Partners trust honest plans. Sharing risks and how you will handle them shows you are prepared.", 3),
            ("A new rival opens across the street with lower prices. How should your plan respond?", "Review what makes you special and adjust",
             "Copy their prices without checking costs", "Do nothing and hope they leave",
             "Check your costs before cutting prices. Often better service, quality or new ideas work better than a price war.", 3),
            ("Why is it smart to plan for a 'slow month'?", "Sales often change with the seasons",
             "Slow months never really happen", "Banks require a slow month every year",
             "Many businesses sell less at certain times, like ice cream in winter. Planning ahead keeps enough money to pay bills.", 3),
            ("Your forecast: 100 customers in January, growing by 10 each month. How many in April?", "130",
             "140", "110",
             "January 100, February 110, March 120, April 130. Each month adds 10.", 3),
            ("Which is the best example of a vision statement?", "Every family in our town can eat fresh bread daily",
             "We open at 7 a.m. on weekdays", "Our bread costs $3 per loaf",
             "A vision describes the big future you want. Hours and prices are details, not a vision.", 3),
            ("You need $500 to start. You have $200 and a partner adds $150. How much is still missing?", "$150",
             "$300", "$350",
             "$200 plus $150 is $350. $500 minus $350 leaves $150 still needed.", 3),
            ("Why should a plan include a 'what if things go wrong' section?", "It prepares you to act fast when problems come",
             "It guarantees that nothing will go wrong", "It makes the plan longer so it looks better",
             "Thinking ahead about risks, like a broken oven, lets you respond calmly instead of panicking.", 3),
            ("Your goal was 40 customers a month. You reached 52. What is a smart next step?", "Set a new goal and plan how to reach it",
             "Stop setting goals since you won", "Lower the goal so it is easier",
             "Beating a goal shows your plan works. Raising the bar keeps the business growing.", 3),
        ],
        "facts": [
            ("A business plan can help an owner get a loan from a bank.", True,
             "Banks read plans to see if the owner understands costs, sales and how the loan will be paid back."),
            ("Once a business plan is written, it should never be changed.", False,
             "Good plans are updated as owners learn new things about customers, costs and competitors."),
            ("A good business goal includes a number and a deadline.", True,
             "Goals like 'sell 100 pies by July' are easy to measure, so you know if you reached them."),
            ("A business with no competitors at all is always a great idea.", False,
             "Sometimes no competitors means nobody wants the product. It is worth checking for real demand."),
            ("Rent is usually a fixed cost for a shop.", True,
             "Rent stays the same each month whether you sell a lot or a little, so it is fixed."),
            ("A mission statement is the same thing as a price list.", False,
             "A mission explains what the business does and why. A price list just shows what things cost."),
            ("Sales forecasts are educated guesses, not promises.", True,
             "Forecasts use facts to predict sales, but real results can be higher or lower, so owners check them."),
            ("Business plans are only useful for very large companies.", False,
             "Even a small lemonade stand gains from a simple plan of costs, prices and goals."),
            ("Knowing your customers helps you decide what to sell.", True,
             "If your customers are busy parents, quick and healthy meals might sell better than fancy ones."),
            ("A plan should hide risks so that banks will say yes.", False,
             "Honest plans build trust. Banks and partners want to see risks and how you will handle them."),
            ("A vision statement describes what a business hopes to become in the future.", True,
             "A vision is the big dream, like being the friendliest bike shop in the region."),
            ("Ingredients for a bakery are a fixed cost.", False,
             "Ingredients are variable costs, because baking more bread uses more flour and butter."),
        ],
    },
    {
        "key": "data",
        "title": "Read the Numbers",
        "tagline": "Charts, trends and smart decisions",
        "icon": "graph",
        "cards": [
            ("Tables and charts", "A table lists numbers in rows and columns. A bar chart shows them as bars, so you can see at a glance which is biggest."),
            ("Spot the trend", "A trend is the direction numbers move over time. Sales of 40, 50 and 60 over three months show an upward trend."),
            ("Averages", "To find an average, add the numbers and divide by how many there are. Sales of 4, 6 and 8 cups have an average of 6."),
            ("Percentages", "Percent means 'out of 100.' If 25 of 100 visitors buy, that is 25 percent. Half is 50 percent, a quarter is 25 percent."),
            ("Data beats guesses", "Check the numbers before deciding. Watch key numbers like sales, costs and customers, and double-check anything that looks odd."),
        ],
        "questions": [
            ("A table shows lemonade sold: Monday 5 cups, Tuesday 8 cups, Wednesday 3 cups. Which day sold the most?", "Tuesday",
             "Monday", "Wednesday",
             "8 is the biggest number in the table, so Tuesday had the most sales.", 1),
            ("Sales were $100 in May and $150 in June. How much did they go up?", "$50",
             "$150", "$250",
             "$150 minus $100 equals $50. Subtracting the earlier month from the later one shows the change.", 1),
            ("What does a bar chart help you do?", "Compare amounts by the height of bars",
             "Count the words on a page", "Draw a map of your town",
             "Taller bars mean bigger numbers, so you can quickly see which item, day or month is highest.", 1),
            ("Customers per month were 20, 25, 30, then 35. What is the trend?", "Going up",
             "Going down", "Staying the same",
             "Each month has more customers than the one before, so the trend is upward.", 1),
            ("What does 'percent' mean?", "Out of 100",
             "Out of 10", "Out of 1,000",
             "Percent comes from words meaning 'per hundred.' 30 percent means 30 out of every 100.", 1),
            ("A bike shop sold 4 bikes, 6 bikes and 8 bikes over three days. What is the average per day?", "6 bikes",
             "18 bikes", "4 bikes",
             "Add them: 4 plus 6 plus 8 is 18. Divide by 3 days: 18 divided by 3 is 6.", 1),
            ("Why should owners use data instead of guesses?", "Numbers show what is really happening",
             "Guesses are always more exciting", "Data makes the shop look nicer",
             "Feelings can trick us. Real numbers, like sales records, show what customers actually do.", 1),
            ("Which is a key number every business should watch?", "Total sales each week",
             "The number of clouds in the sky", "How many pens the owner owns",
             "Sales show how much money comes in. Along with costs and customers, it tells you how the business is doing.", 1),
            ("Half of your 40 customers bought muffins. How many bought muffins?", "20",
             "10", "40",
             "Half means divide by 2. 40 divided by 2 is 20.", 1),
            ("A line on a chart goes down from left to right over the months. What does this usually mean?", "The number is falling over time",
             "The number is rising over time", "The number never changes",
             "Charts usually show time from left to right. A line sloping down means the number is getting smaller.", 1),
            ("Costs were $80 in March and $60 in April. Did costs go up or down, and by how much?", "Down by $20",
             "Up by $20", "Down by $140",
             "$80 minus $60 is $20, and April is lower, so costs went down by $20.", 1),
            ("What is a 'trend' in business numbers?", "The direction numbers move over time",
             "A single number from one day", "A brand new style of clothing",
             "A trend shows a pattern, like sales rising for several months, not just one day's result.", 1),

            ("A table shows cookie sales: chocolate 30, oatmeal 10, sugar 20. What percent of the 60 cookies were chocolate?", "50 percent",
             "30 percent", "60 percent",
             "30 out of 60 is one half, and one half is 50 percent.", 2),
            ("Weekly visitors were 50, 52, 49 and 51. What is the best description?", "About the same each week",
             "Rising fast every week", "Falling fast every week",
             "The numbers move only a little up and down, so visitors are fairly steady.", 2),
            ("Sales by month: January $200, February $220, March $240. If this trend continues, what might April be?", "$260",
             "$240", "$300",
             "Sales rose by $20 each month. Adding $20 to $240 gives $260, though real results can differ.", 2),
            ("Your sales log says 3 + 4 + 5 cups = 15 cups. What should the total be?", "12 cups",
             "15 cups", "9 cups",
             "3 plus 4 plus 5 equals 12. Checking totals catches mistakes before they lead to bad decisions.", 2),
            ("Out of 200 shop visitors, 50 bought something. What percent bought?", "25 percent",
             "50 percent", "20 percent",
             "50 out of 200 is the same as 25 out of 100, which is 25 percent.", 2),
            ("A chart shows ice cream sales high in summer and low in winter, every year. What is this called?", "A seasonal pattern",
             "A one-time mistake", "A random accident",
             "When numbers rise and fall at the same times each year, it is seasonal. Owners plan stock and staff around it.", 2),
            ("You think blue cupcakes sell best, but your records show pink sold twice as many. What should you do?", "Trust the records and make more pink",
             "Ignore the records and make more blue", "Stop keeping sales records",
             "Records show what customers actually bought. Following data instead of hunches leads to better choices.", 2),
            ("Three days of sales were $10, $20 and $30. What is the average daily sales?", "$20",
             "$60", "$30",
             "Add them: $10 plus $20 plus $30 is $60. Divide by 3 days to get $20.", 2),
            ("A shop's costs went from $500 to $700 while sales stayed at $800. What happened to profit?", "It fell by $200",
             "It rose by $200", "It stayed the same",
             "Profit was $800 minus $500, or $300. Now it is $800 minus $700, or $100. That is $200 less.", 2),
            ("Which number tells you if customers like you enough to return?", "How many customers come back again",
             "How many chairs are in the shop", "How many hours the sign is lit",
             "Repeat customers show loyalty. If that number drops, it may mean something needs fixing.", 2),
            ("A pie chart shows how a whole is split up. If one slice is half the pie, what percent is it?", "50 percent",
             "25 percent", "100 percent",
             "The whole pie is 100 percent, so half of it is 50 percent.", 2),
            ("Why compare this June to last June, and not just to this May?", "It removes seasonal effects from the comparison",
             "June always has more days than May", "Last year never matters in business",
             "Comparing the same month across years shows real growth, since both months share the same season.", 2),

            ("Sales went from $200 to $250. By what percent did they grow?", "25 percent",
             "50 percent", "20 percent",
             "The increase is $50. $50 out of the starting $200 is one quarter, which is 25 percent.", 3),
            ("Daily customers were 10, 12, 11, 90 and 12. What should you do first about the 90?", "Check if it was a typing mistake",
             "Assume every day will now have 90", "Delete all the other numbers",
             "A number far off the pattern is often a mistake, like 9 typed as 90. If it is real, learn what caused it.", 3),
            ("May: 400 visitors and 100 buyers. June: 500 visitors and 100 buyers. What happened?", "A smaller share of visitors bought",
             "A bigger share of visitors bought", "The buying share stayed the same",
             "May: 100 of 400 is 25 percent. June: 100 of 500 is 20 percent. More people came, but fewer of them bought.", 3),
            ("Four weeks of sales were $40, $60, $50 and $50. What is the weekly average?", "$50",
             "$200", "$60",
             "Add them to get $200. Divide by 4 weeks: $200 divided by 4 is $50.", 3),
            ("Sales are rising, but profit is falling. Which is the most likely cause?", "Costs are growing faster than sales",
             "Customers are buying more items", "The prices are exactly right",
             "Profit is sales minus costs. If costs climb faster than sales, profit can shrink even as sales grow.", 3),
            ("A friend says 'Everyone loves our new drink!' Data shows 3 of 30 buyers chose it. What percent is that?", "10 percent",
             "30 percent", "3 percent",
             "3 out of 30 is the same as 10 out of 100, or 10 percent. The data shows most buyers chose something else.", 3),
            ("A bar chart's scale starts at 90 instead of 0, so a small change looks huge. Why does this matter?", "It can make differences look bigger than they are",
             "It makes the chart more accurate", "It does not change how it looks at all",
             "Starting the scale above zero stretches small gaps. Always read the numbers on the axis, not just bar sizes.", 3),
            ("Your bakery sells 120 loaves a week and 25 percent are rye. How many rye loaves is that?", "30",
             "25", "40",
             "25 percent is one quarter. 120 divided by 4 is 30.", 3),
            ("Lemonade sales: a hot week sold 80 cups, a rainy week sold 20 cups. What is the best conclusion?", "Weather likely affects sales",
             "Lemonade is no longer popular", "The prices must have doubled",
             "The big drop came with rain. One example is not proof, but tracking weather with sales can confirm the link.", 3),
            ("Monthly costs were $300, $300, then $360. By what percent did they rise in the last month?", "20 percent",
             "60 percent", "36 percent",
             "The rise is $60. $60 out of $300 is the same as 20 out of 100, or 20 percent.", 3),
            ("You asked only your 5 best friends about a new flavor. Why is this data weak?", "The group is tiny and may not match customers",
             "Five is far too many people to ask", "Friends always give wrong answers",
             "A small group of friends may be kind and similar to you. Asking many real customers gives a truer picture.", 3),
            ("Sales were $500 and costs were $350. What percent of sales was profit?", "30 percent",
             "35 percent", "15 percent",
             "Profit is $500 minus $350, or $150. $150 out of $500 is 30 out of 100, which is 30 percent.", 3),
        ],
        "facts": [
            ("An average can be found by adding numbers and dividing by how many there are.", True,
             "For 2, 4 and 6: add to get 12, then divide by 3 to get an average of 4."),
            ("If sales go up for one day, that always means a long-term upward trend.", False,
             "One day can be a fluke. A trend needs a pattern over several days, weeks or months."),
            ("50 percent is the same as one half.", True,
             "Percent means out of 100, and 50 out of 100 is one half."),
            ("A chart can never be misleading.", False,
             "Charts can mislead if scales are stretched or parts are left out. Always check the numbers and labels."),
            ("Comparing the same month in different years can help spot real growth.", True,
             "It removes season effects, like more ice cream sales every summer."),
            ("Gut feelings are always more reliable than sales records.", False,
             "Records show what really happened. Feelings are useful for ideas but should be checked with data."),
            ("Typing mistakes in sales records can lead to bad business decisions.", True,
             "A 9 typed as 90 could make you order far too much stock. Double-checking numbers prevents this."),
            ("If sales rise, profit always rises too.", False,
             "If costs rise even faster than sales, profit can fall. Owners watch both numbers."),
            ("Tracking the number of customers helps an owner understand the business.", True,
             "Customer counts show if more people are finding you and whether they come back."),
            ("25 percent of 80 is 25.", False,
             "25 percent is one quarter. 80 divided by 4 is 20, not 25."),
            ("A line chart is a good way to show how something changes over time.", True,
             "Points joined by a line make it easy to see rises, drops and steady periods."),
            ("Asking three friends is enough data to know what all customers want.", False,
             "A tiny, similar group may not match your real customers. Bigger, varied groups are more trustworthy."),
        ],
    },
    {
        "key": "world",
        "title": "Business Around the World",
        "tagline": "Trade, currencies and cultures",
        "icon": "globe",
        "cards": [
            ("Imports and exports", "An export is something a country sells to another country. An import is something it buys from another country."),
            ("Why countries trade", "Places are good at making different things because of weather, skills or resources. Trade lets everyone get more variety."),
            ("Money around the world", "Many countries use their own money, called currency. An exchange rate tells how much of one currency you get for another."),
            ("Shipping and time zones", "Goods sent overseas can take weeks to arrive. When it is morning for you, it may be night for a partner far away."),
            ("Respect every culture", "Customs differ around the world, like greetings, holidays and gifts. Learn and respect them to build trust with partners."),
        ],
        "questions": [
            ("What is an export?", "A product sold to another country",
             "A product bought from another country", "A product made and sold at home only",
             "Exports leave the country to be sold abroad. A farm selling its fruit overseas is exporting.", 1),
            ("What is an import?", "A product bought from another country",
             "A product sold to another country", "A product thrown away as waste",
             "Imports come into a country from abroad, like a bike shop buying parts made in another country.", 1),
            ("What is a currency?", "The kind of money a country uses",
             "A type of shipping container", "A map of trade routes",
             "Many countries have their own money. When you trade abroad, you may need to change one currency into another.", 1),
            ("Why do countries trade with each other?", "To get things they cannot easily make",
             "Because trading is required every day", "To make all prices the same everywhere",
             "Some places cannot grow certain foods or make certain goods. Trade lets people get them from places that can.", 1),
            ("It is 9 a.m. where you live. Your partner is 3 hours ahead. What time is it for them?", "12 p.m.",
             "6 a.m.", "3 p.m.",
             "Ahead means later in the day. 9 a.m. plus 3 hours is 12 p.m., which is noon.", 1),
            ("What is a 'local business'?", "One that mainly serves people nearby",
             "One that sells in every country", "One that only works at night",
             "A local business, like a neighborhood bakery, mostly serves its own community.", 1),
            ("What is a 'global business'?", "One that sells or works in many countries",
             "One that only sells globes", "One that has just one customer",
             "Global businesses buy, sell or operate in many countries around the world.", 1),
            ("Why might shipping from another country take longer than buying locally?", "Goods travel far by ship, plane or truck",
             "Faraway stores are always closed", "Boxes get heavier as they travel",
             "Long distances, border checks and transfers between ships and trucks all add time.", 1),
            ("You meet a partner from another country who greets people differently. What should you do?", "Learn their custom and greet respectfully",
             "Insist they only use your greeting", "Make jokes about how they greet",
             "Respecting other customs shows you care and builds trust, which is key to good business.", 1),
            ("What is a 'trading partner'?", "A country or business you buy from or sell to",
             "A friend you swap stickers with at lunch", "A worker who cleans the shop",
             "Trading partners exchange goods or services, like a shop that buys fabric from a mill in another country.", 1),
            ("A shipment leaves on day 1 and takes 14 days to travel. On what day does it arrive?", "Day 15",
             "Day 14", "Day 13",
             "Starting on day 1 and adding 14 days brings you to day 15.", 1),
            ("Which is an example of an export?", "A coffee farm selling beans overseas",
             "A family buying bread at a corner shop", "A child saving coins in a jar",
             "The farm sends its product to buyers in another country, which makes it an export.", 1),

            ("What is an exchange rate?", "How much of one currency you get for another",
             "The price of a bus ticket abroad", "How fast a cargo ship can travel",
             "Exchange rates tell you how money converts. If 1 unit of your money gets 2 of theirs, 10 units get 20 of theirs.", 2),
            ("If 1 of your dollars equals 4 coins of another currency, how many coins do you get for 5 dollars?", "20 coins",
             "9 coins", "4 coins",
             "Multiply: 5 dollars times 4 coins each equals 20 coins.", 2),
            ("Fabric takes 6 weeks to ship to you. You need it in 8 weeks. When should you order?", "Within the next 2 weeks",
             "In 7 weeks", "The day before you need it",
             "8 weeks minus 6 weeks of shipping leaves 2 weeks. Ordering early adds a safety cushion for delays.", 2),
            ("Your partner is 8 hours behind you. It is 4 p.m. for you. What time is it for them?", "8 a.m.",
             "12 a.m.", "8 p.m.",
             "Behind means earlier. 4 p.m. minus 8 hours is 8 a.m.", 2),
            ("A partner's country has a big holiday next week. What is the respectful choice?", "Plan around it and avoid urgent requests",
             "Demand they work through the holiday", "Ignore it since it is not your holiday",
             "Respecting partners' holidays builds goodwill. Planning ahead keeps your orders on time too.", 2),
            ("Why might a toy shop import some of its toys?", "Another country makes them well at a good price",
             "Imports never need to be shipped", "Local toys are not allowed in shops",
             "Different places specialize in different products. Importing can give customers more choice at fair prices.", 2),
            ("What is a tariff?", "A tax on some goods coming from another country",
             "A ship that carries cargo overseas", "A free gift for new trading partners",
             "Many countries charge tariffs on some imports. It adds to the cost, so importers include it in their prices.", 2),
            ("A product costs $10 to make and $3 to ship from abroad. What is the total cost to get it?", "$13",
             "$7", "$30",
             "Add making and shipping costs: $10 plus $3 is $13. Shipping is part of the real cost.", 2),
            ("Your business sells online to buyers in many countries. What should your website do?", "Show clear prices, shipping costs and times",
             "Hide shipping costs until after payment", "Use only words that are hard to read",
             "Clear information builds trust with buyers everywhere and prevents surprise costs.", 2),
            ("A partner in another country prefers formal emails. What should you do?", "Write politely and formally to them",
             "Use slang because it feels friendly", "Stop emailing and wait for them",
             "Matching a partner's preferred style shows respect and helps your messages be understood.", 2),
            ("Which is the best reason a small shop might choose to stay local?", "It knows its community and serves it well",
             "Going global is never allowed", "Local shops cannot sell anything online",
             "Many great businesses stay local by knowing their neighbors' needs and giving personal service.", 2),
            ("Why might fresh fruit from far away cost more than local fruit?", "Fast shipping and cooling cost extra",
             "Faraway fruit is always bigger", "Local farms are not allowed to sell",
             "Fresh food must travel fast and stay cold, which adds cost. Local fruit travels a shorter distance.", 2),

            ("The exchange rate changes, and your money now buys fewer foreign parts. What happens to your import costs?", "They go up",
             "They go down", "They stay exactly the same",
             "If each of your dollars buys fewer foreign coins, you need more dollars for the same parts, so costs rise.", 3),
            ("Your partners are 6 hours ahead of you. Their office is open 9 a.m. to 5 p.m. their time. Which of your times works for a call?", "5 a.m.",
             "1 p.m.", "8 p.m.",
             "Add 6 hours to each choice. 5 a.m. is 11 a.m. for them, inside their hours. 1 p.m. is 7 p.m., and 8 p.m. is 2 a.m.", 3),
            ("Why do countries often gain from trading instead of making everything themselves?", "Each can focus on what it makes best",
             "Trading means no one needs to work", "Making things at home is always illegal",
             "When each place focuses on its strengths and trades, everyone can get more goods at lower cost.", 3),
            ("A coat costs 60 coins in another country. 1 of your dollars equals 3 coins. How many dollars is the coat?", "$20",
             "$180", "$63",
             "Divide the coins by the rate: 60 divided by 3 equals 20 dollars.", 3),
            ("A shipment is stuck for 3 extra weeks. What would have helped most?", "Keeping extra stock and backup suppliers",
             "Ordering only on the last possible day", "Promising customers it is already here",
             "Extra stock and backup suppliers keep you selling when shipping is late. Being honest with customers also keeps trust.", 3),
            ("Your gift shop wants to sell items with designs that have special meaning in another culture. What should you do?", "Learn their meaning and use them respectfully",
             "Use them carelessly as decoration only", "Make jokes about them on the label",
             "Some designs carry deep meaning. Learning first avoids hurting people and shows respect for their culture.", 3),
            ("A local bakery wants to sell its cookies abroad. What should it check first?", "Rules for food imports in that country",
             "Whether the oven is a nice color", "How many birds live near the port",
             "In many places, food from abroad must meet that country's safety and label rules. Checking first prevents trouble.", 3),
            ("You buy 100 shirts from abroad at $5 each and pay $100 for shipping. What is the cost per shirt?", "$6",
             "$5", "$105",
             "Shirts cost 100 times $5, or $500. Adding $100 shipping makes $600. $600 divided by 100 shirts is $6 each.", 3),
            ("A meeting is set for 'Monday 9 a.m.' with a partner in another time zone. What should you do?", "Confirm which time zone it means",
             "Assume they mean your time zone", "Show up whenever you feel ready",
             "Time zones can cause missed meetings. Confirming the exact time and zone avoids confusion.", 3),
            ("A country has lots of sunshine and good farmland but few factories. What might it likely export?", "Fruit and other crops",
             "Large factory machines", "Tiny computer chips",
             "Places often export what their land and skills make well. Sun and farmland suit crops.", 3),
            ("Why might a business buy the same part from suppliers in two different countries?", "If one has a delay, the other can still ship",
             "Two suppliers always means half the price", "It is required to have exactly two",
             "Using more than one supplier spreads risk. A storm or delay in one place will not stop the whole business.", 3),
            ("A buyer abroad pays you 200 coins. 1 of your dollars equals 4 coins. How many dollars did you earn?", "$50",
             "$800", "$204",
             "Divide coins by the rate: 200 divided by 4 equals 50 dollars.", 3),
        ],
        "facts": [
            ("An export is a product sold to buyers in another country.", True,
             "Exports leave a country, like a farm selling apples to stores overseas."),
            ("Every country in the world uses the same money.", False,
             "Many countries have their own currency, so traders often exchange money when buying and selling."),
            ("Exchange rates can change over time.", True,
             "The value of currencies moves up and down, which can make imports cheaper or more costly."),
            ("Shipping goods across an ocean by ship always takes just one day.", False,
             "Ships can take weeks. Planes are faster but cost more, so businesses plan ahead."),
            ("When it is daytime in one part of the world, it is night in another.", True,
             "The Earth turns, so different places are in different time zones. Partners plan meetings to fit both."),
            ("There is only one polite way to greet people everywhere.", False,
             "Greetings differ around the world. Learning a partner's customs shows respect."),
            ("Many products we use have parts made in more than one country.", True,
             "A bike might have a frame from one place and tires from another. Trade connects these makers."),
            ("Local businesses cannot succeed because global companies are bigger.", False,
             "Many local businesses thrive by knowing their community and giving personal service."),
            ("A tariff can make an imported product cost more.", True,
             "A tariff is a tax on some imports. Importers often add it into their prices."),
            ("Respecting other cultures does not matter in business.", False,
             "Respect builds trust and friendships with partners and customers, which helps business grow."),
            ("Countries trade partly because they are good at making different things.", True,
             "Weather, land and skills differ, so trade helps everyone get more variety at fair prices."),
            ("Imported goods are always cheaper than local goods.", False,
             "Shipping, tariffs and exchange rates can make imports cost more. It depends on the product."),
        ],
    },
    {
        "key": "green",
        "title": "Grow Green",
        "tagline": "Business that cares for the planet",
        "icon": "leaf",
        "cards": [
            ("Waste less, save more", "Waste is money thrown away. Using only what you need, like ordering the right amount of fruit, cuts costs and helps the planet."),
            ("Reduce, reuse, recycle", "First use less. Then reuse what you can, like sturdy boxes. Recycle the rest, such as paper, cans and many plastics."),
            ("Save energy and water", "Turn off lights and machines when not in use, fix leaky taps and pick efficient equipment. Lower bills mean more profit."),
            ("Be a good neighbor", "Keep your area clean, keep noise down and help local causes. A business that cares about its community earns trust."),
            ("Honest green claims", "Only say your product is green if it truly is. Making false eco claims is called greenwashing, and it breaks customer trust."),
        ],
        "questions": [
            ("What does 'reduce waste' mean?", "Use less and throw away less",
             "Buy more than you need", "Put trash in a bigger bin",
             "Reducing waste means using only what you need, which saves money and keeps trash out of landfills.", 1),
            ("Which is an example of recycling?", "Turning used paper into new paper",
             "Throwing cans in the regular trash", "Buying a new pen every day",
             "Recycling turns old materials into new products, so fewer new resources are needed.", 1),
            ("A shop leaves its lights on all night when closed. What is a green fix?", "Turn the lights off when closing",
             "Add even more lights", "Paint the lights a new color",
             "Turning lights off saves energy and lowers the electric bill. Small habits add up.", 1),
            ("How can a cafe save water?", "Fix dripping taps quickly",
             "Leave the taps running all day", "Wash clean cups twice",
             "A dripping tap can waste a lot of water over time. Fixing it saves water and money.", 1),
            ("Which is an example of reusing?", "Using sturdy boxes again for shipping",
             "Throwing boxes away after one use", "Buying new boxes for every order",
             "Reusing gives items a second life, which saves money and creates less trash.", 1),
            ("What is a good way for a business to help its community?", "Help clean up a local park",
             "Leave trash outside its door", "Play loud music late at night",
             "Helping the community makes the neighborhood nicer and shows customers you care.", 1),
            ("Why can saving energy help a business make more money?", "Lower energy bills mean lower costs",
             "Energy makes products taste better", "Customers pay more in the dark",
             "Energy costs money. Using less lowers costs, so more of each sale becomes profit.", 1),
            ("A bakery throws away 10 loaves a day. Each costs $2 to make. How much money is wasted daily?", "$20",
             "$12", "$10",
             "10 loaves times $2 each equals $20 wasted every day. Baking closer to demand saves that money.", 1),
            ("What does it mean to be a good business neighbor?", "Keep the area clean and treat neighbors well",
             "Park in front of other shops all day", "Put your trash in a neighbor's bin",
             "Good neighbors respect shared spaces, so others are glad to have your business nearby.", 1),
            ("Which bag choice creates the least waste?", "Customers bring their own reusable bag",
             "A new plastic bag for each item", "Two paper bags for every small item",
             "A reusable bag can be used many times, so far less waste is made.", 1),
            ("What is 'greenwashing'?", "Claiming to be eco-friendly when you are not",
             "Washing your shop floor with green soap", "Painting the outside of the store green",
             "Greenwashing is a false or overstated green claim. It misleads customers and can hurt trust.", 1),
            ("Leftover bread at the end of the day is still good. What is a kind and green choice?", "Give it to a local food bank",
             "Throw it straight in the trash", "Leave it outside to go stale",
             "Donating good food helps people in need and keeps food out of the trash. In many places, food banks welcome it.", 1),

            ("Your lemonade stand uses 100 plastic cups a week. What is a greener option that still works?", "Use cups that can be recycled or composted",
             "Use two plastic cups for each drink", "Hand out drinks with no cups at all",
             "Recyclable or compostable cups do the same job with less lasting waste. Always check what your area can recycle.", 2),
            ("What does 'sustainable' mean for materials?", "They can be used without running out or harming nature",
             "They are the most expensive ones available", "They come in the brightest colors",
             "Sustainable materials, like responsibly grown wood, can be replaced over time and cause less harm.", 2),
            ("Switching to efficient bulbs saves a shop $5 a month. How much is that in a year?", "$60",
             "$50", "$5",
             "12 months times $5 equals $60 a year. Small savings add up over time.", 2),
            ("A label says 'eco-friendly' but gives no reason. What should a careful buyer do?", "Look for clear facts behind the claim",
             "Believe it because it says so", "Assume every product is the same",
             "Honest green claims explain what makes them better, like '50 percent recycled paper.' Vague words alone prove nothing.", 2),
            ("Which is the best first step to cut waste in a bakery?", "Track what gets thrown away each day",
             "Buy a bigger trash bin", "Bake twice as much as usual",
             "Measuring waste shows where it comes from. Then you can bake closer to what actually sells.", 2),
            ("What is composting?", "Turning food scraps into rich soil",
             "Burning trash to make it smaller", "Mixing plastic into the garden",
             "Food scraps break down into compost, which helps plants grow and keeps waste out of landfills.", 2),
            ("A shop's water bill was $40. After fixing leaks, it is $30. What percent did it save?", "25 percent",
             "10 percent", "30 percent",
             "It saved $10. $10 out of the original $40 is one quarter, or 25 percent.", 2),
            ("Your bike shop has old tires it cannot sell. What is a responsible choice?", "Send them to a proper recycling place",
             "Dump them behind the shop", "Burn them in the parking lot",
             "Many places have special recycling for tires. Dumping or burning them harms the land and air and can break local rules.", 2),
            ("Why might customers choose a business that cares about the planet?", "Many people want to support good values",
             "Green shops never charge for anything", "Customers must shop green by law",
             "Many customers like to spend money where it does good. Real care can build loyalty.", 2),
            ("Your cafe gives a discount to people who bring their own cup. What is the main benefit?", "Fewer throwaway cups are used",
             "Customers drink less coffee", "The cafe needs more trash bags",
             "A small reward encourages reuse, which cuts waste and can lower what you spend on cups.", 2),
            ("Which of these is an honest green claim?", "Our boxes are made from 80 percent recycled paper",
             "We are the greenest shop on the whole Earth", "Our product is 100 percent good for nature",
             "A specific, true fact can be checked. Big, vague claims are hard to prove and can mislead.", 2),
            ("A delivery van drives a long, messy route each day. What is a green and money-saving fix?", "Plan a shorter route",
             "Drive the route twice", "Leave the engine running at stops",
             "A shorter route uses less fuel, which lowers costs and pollution at the same time.", 2),

            ("Reusable crates cost $50 and replace $10 of cardboard boxes each week. After how many weeks do they pay for themselves?", "5 weeks",
             "10 weeks", "50 weeks",
             "Each week saves $10. $50 divided by $10 equals 5 weeks. After that, the crates save money every week.", 3),
            ("Only the box is recyclable, not the product inside, but the ad says 'fully eco-friendly.' What is this?", "Greenwashing",
             "Honest labeling", "Composting",
             "Calling the whole product eco-friendly when only the box is greener misleads buyers. Claims should match the facts.", 3),
            ("Which order shows the best way to handle waste?", "Reduce first, then reuse, then recycle",
             "Recycle first, then buy more", "Throw away first, then reduce",
             "Reducing avoids waste entirely. Reusing comes next, and recycling handles what is left.", 3),
            ("An efficient freezer costs $200 more but saves $40 a year in energy. After how many years does it pay off?", "5 years",
             "4 years", "8 years",
             "$200 divided by $40 a year equals 5 years. After that, the savings are extra profit.", 3),
            ("Your shop made 20 bags of trash a week. After some changes it makes 15. By what percent did trash drop?", "25 percent",
             "5 percent", "15 percent",
             "Trash dropped by 5 bags. 5 out of the original 20 is one quarter, or 25 percent.", 3),
            ("A cheaper material saves money but harms a local river. What is the best choice?", "Choose a safer material, even if it costs more",
             "Use the cheap one and keep it a secret", "Use it, but only during the night",
             "Harming shared nature hurts neighbors and breaks trust. Good owners pick safe options and find savings elsewhere.", 3),
            ("A bakery bakes 100 muffins daily but sells about 80. What is the smartest change?", "Bake closer to 80 and keep tracking sales",
             "Bake 120 to be extra safe", "Keep baking 100 and throw extras out",
             "Baking to real demand cuts waste and cost. Watching sales lets you adjust if demand changes.", 3),
            ("Why should a green claim be specific and true?", "Customers and rules expect claims to be honest",
             "Specific claims always cost nothing to make", "Vague claims are required in most places",
             "In many places, false green claims can break advertising rules. True, specific claims build lasting trust.", 3),
            ("A local school asks businesses to sponsor a tree-planting day. How can this help your business?", "It helps the town and shows you care",
             "It lets you skip paying your bills", "It forces customers to buy from you",
             "Helping the community is good in itself, and people notice businesses that give back.", 3),
            ("Packaging costs $1 per item. A smaller package costs $0.70. For 100 items, how much is saved?", "$30",
             "$70", "$3",
             "Each item saves $0.30. 100 times $0.30 equals $30. Less packaging means less waste too.", 3),
            ("What is a 'carbon footprint'?", "The amount of planet-warming gases something causes",
             "The mark a shoe leaves on a clean floor", "The number of trees in a parking lot",
             "Burning fuel and using some kinds of energy release gases that warm the planet. A smaller footprint means less of those gases.", 3),
            ("You can buy flour from a farm 20 miles away or 2,000 miles away at the same price. Which is usually greener?", "The nearby farm, since less fuel is used",
             "The far farm, since it travels more", "Both always have the same impact",
             "Shorter trips usually burn less fuel. Buying nearby also supports local farmers.", 3),
        ],
        "facts": [
            ("Wasting less can help a business save money.", True,
             "Every wasted item was paid for. Using only what you need lowers costs."),
            ("Recycling is better than reducing waste in the first place.", False,
             "Reducing comes first, since waste that is never made needs no energy to recycle."),
            ("Fixing a dripping tap can save a lot of water over time.", True,
             "Small drips add up day after day, wasting water and money."),
            ("Any product can be called eco-friendly, even with no reason.", False,
             "Honest claims need facts. False or vague green claims are greenwashing and can break rules in many places."),
            ("Turning off machines when they are not in use saves energy.", True,
             "Many machines use power even when idle. Switching them off lowers the bill."),
            ("Being a good neighbor does not matter for a business.", False,
             "Neighbors are often customers. A clean, friendly, caring business earns trust and support."),
            ("Food scraps can be composted into soil for plants.", True,
             "Composting turns scraps into nutrients and keeps them out of the trash."),
            ("Green choices always cost a business more money.", False,
             "Many green choices, like saving energy and wasting less, actually lower costs."),
            ("Reusing sturdy boxes or crates can cut packaging costs.", True,
             "Using items many times means buying fewer new ones, which saves money and trash."),
            ("Everything put in a recycling bin can be recycled everywhere.", False,
             "Recycling rules differ by place. Owners should check what their local service accepts."),
            ("Helping with local projects, like park cleanups, can build trust with customers.", True,
             "People notice when a business cares about its town, and many like to support it."),
            ("Greenwashing means cleaning a store with eco-friendly soap.", False,
             "Greenwashing means making false or misleading green claims to look better than you are."),
        ],
    },
]
