"""Academy question bank: the Winning Mindset unit."""

WORLDS = [
    {
        "key": "champion",
        "title": "Champion Mindset",
        "tagline": "Think like a winner",
        "icon": "flag",
        "cards": [
            ("The power of yet", "Your brain gets better with effort and good strategies. When something is hard, add one word: \"I can't do it yet.\" Selling, math and free throws all improve with smart practice."),
            ("Be your own coach", "Talk to yourself like a good coach would. Swap \"I'm bad at this\" for \"What can I try next?\" Honest, helpful self-talk keeps you going when things get tough."),
            ("Mistakes are data", "A loss or a mistake is information. Review what happened, pick one thing to fix, then go again. A bake sale that flopped can teach you more than one that went great."),
            ("Confidence is built", "Real confidence comes from preparation and practice, not luck or bragging. Rehearse your pitch and know your prices, and you will feel steady when it counts."),
            ("Race your past self", "Compare yourself to who you were last month, not to everyone else. A friend's success is not your failure. People who are ahead of you can be your best teachers."),
            ("Win with class", "Credit the team when you win. Shake hands and skip excuses when you lose. Big moments are a privilege you earned: breathe slowly, use your routine, and own your effort and attitude."),
        ],
        "questions": [
            # Level 1
            ("What does adding the word \"yet\" to \"I can't do it\" mean?", "You are still learning it",
             "You should give up and try something else", "Only some people can ever learn it",
             "\"Yet\" reminds you that skills grow with effort and good strategies. It turns a dead end into a path you are still walking.", 1),
            ("Which is the most helpful thing to say to yourself after a mistake?", "What can I try next?",
             "I am just bad at this.", "This always happens to me.",
             "Good self-talk sounds like a coach: it points you to the next step. \"I'm bad at this\" shuts the door before you have even tried a fix.", 1),
            ("Where does real confidence mostly come from?", "Preparation and practice", "Being lucky on the big day",
             "Telling everyone you are the best",
             "When you have practiced your pitch or your free throws many times, you know you can do it. Bragging and luck do not give you that steady feeling.", 1),
            ("Your bake sale sold only 5 cookies. What is the best way to think about it?", "It is data I can learn from",
             "It proves I am bad at business", "It was bad luck, so forget it",
             "A flop tells you something: maybe the price, the spot or the sign. Treat it as information, find one thing to fix and try again.", 1),
            ("Who is the best person to compare yourself to?", "The person you were a month ago",
             "The top seller in your whole school", "Your best friend",
             "Racing your past self shows your real growth. Comparing yourself to others can feel bad and does not show how far you have come.", 1),
            ("Your team wins the game. What does winning with class look like?", "Shake hands and credit your teammates",
             "Remind the other team who won", "Say you did most of the work",
             "Good winners thank their team and respect the other side. People remember how you act when you win, and they want to work with gracious winners.", 1),
            ("What are two things you can always control?", "Your effort and attitude", "The weather and the score",
             "What other people think of you",
             "You can't control the weather, the score or other people. You can always choose how hard you try and how you face the moment. Focus there.", 1),
            ("What does \"growth mindset\" mean?", "Skills can grow with practice and good strategies",
             "Some people are just born good at things, and that never changes", "Smart people never have to try very hard",
             "With a growth mindset you see abilities as things you build. Effort alone is not enough; you also try new strategies and ask for help.", 1),
            ("You lost a race. Which is a graceful thing to say?", "Congrats, you ran a great race!",
             "I would have won if my shoe was tied.", "That race did not really count anyway.",
             "Losing with grace means congratulating the winner and skipping excuses. Excuses stop you from learning what you can do better next time.", 1),
            ("Why is it smart to ask a customer for feedback on your lemonade?", "So you learn what to make better next time",
             "To get them to say nice things", "So they feel they must buy more",
             "Feedback shows you what customers really think. It can sting a little, but it is free advice on how to make your product better.", 1),
            ("Before a big math test, what builds real confidence?", "Doing practice problems all week",
             "Wearing your lucky socks", "Telling friends it will be easy",
             "Practice lets you see that you can solve the problems. Lucky socks are fun, but the work you put in is what you can count on.", 1),
            ("Your friend's dog-walking business is busier than yours. What is a healthy thought?", "I can learn from what she does",
             "Her win means I am losing", "I should stop trying, she is better",
             "Someone else's success does not take away from yours. People who are ahead are great teachers if you watch and ask what works for them.", 1),
            ("Your coach says \"pressure is a privilege\" before a big game. What does that mean?", "You earned a chance at a big moment",
             "Pressure means you should be scared", "Only the best players feel pressure",
             "Big moments come to people who worked to get there. Feeling nervous is normal; it means the moment matters to you.", 1),
            # Level 2
            ("You keep missing free throws. Which plan shows a growth mindset?", "Ask the coach to watch and try a new form",
             "Shoot 500 the same way", "Switch to a sport that is easier for you",
             "Effort matters, but so does strategy. Practicing the same mistake over and over makes it stronger. Feedback plus a new approach helps you grow.", 2),
            ("Your pitch to a neighbor did not land a lawn-mowing job. What is the best next step?", "Ask what would have made it a yes",
             "Decide that neighbors never hire kids", "Pitch the next house the same way",
             "Asking for a reason turns a no into data. Maybe the price was high or they want weekly service. One fix can make the next pitch stronger.", 2),
            ("Which self-talk sounds most like a good coach?", "That was tough. Let's fix one thing.",
             "You always mess up the big ones.", "Whatever, it does not matter anyway.",
             "A good coach is honest and helpful: they admit it was hard, then point to one next step. Harsh talk and not caring both stop you from improving.", 2),
            ("Your family's bakery lost a big order to another shop. What shows ownership?", "Look at what we can do better",
             "Say the customer made a bad choice", "Blame the oven for being slow",
             "Ownership means looking at your own part first. You can't control the customer's choice, but you can improve your prices, speed or service.", 2),
            ("You sold 30 cupcakes last month and 38 this month. Your friend sold 60. How did you do?", "You grew by 8, which is real progress",
             "You failed, since your friend sold more", "It does not count unless you beat 60",
             "Compare with your past self: 38 is 8 more than 30. Your friend's number does not erase your growth, and it might give you ideas to learn from.", 2),
            ("Right before a big pitch, your hands are shaky. What helps most?", "Slow breaths and your usual routine",
             "Skip the pitch until you feel calm", "Tell yourself you must be perfect",
             "Slow breathing calms your body, and a routine you practiced tells your brain you know what to do. Waiting to feel totally calm can mean waiting forever.", 2),
            ("After your soccer team loses, a teammate blames the ref. What is a better response?", "Focus on what we can improve",
             "Agree, the ref cost us the game", "Say it was just bad luck this time",
             "Even if a call was bad, blaming it does not help you get better. Teams that focus on what they control improve faster.", 2),
            ("You got a C on a project. Which is the best way to review it?", "Read the comments and pick one thing to fix",
             "Throw it away and try to forget it", "Decide the teacher just does not like you",
             "Reviewing means looking at what happened and choosing one change. Trying to fix everything at once is hard; one clear fix you can practice works better.", 2),
            ("A classmate's lemonade stand makes more money than yours. What is the smartest move?", "Ask her what has worked for her",
             "Lower your price below hers right away", "Tell others her lemonade is too sour",
             "People ahead of you have learned things you can learn too. Asking is a quick way to grow, and copying a price cut without thinking can lose you money.", 2),
            ("Why do champions often have a routine before big moments?", "It helps them focus on what they control",
             "It is a magic charm that makes them win", "It means they never feel nervous at all",
             "A routine, like a few breaths and a checklist, gives your mind something familiar to do. It does not remove nerves, but it helps you perform with them.", 2),
            ("You want to sell at the school fair but feel scared to try. What does courage look like here?", "Sign up even though you feel nervous",
             "Wait until you are not nervous at all", "Let a friend sign up in your place",
             "Courage is not having zero fear. It is doing the hard thing while you feel the fear. Most nerves shrink once you start.", 2),
            ("Your team wins the science fair. A reporter asks how. What is a classy answer?", "We all worked hard and helped each other",
             "I came up with all the best ideas", "The other projects were not very good",
             "Crediting the team is both true and kind. Most wins come from many people, and sharing credit makes others want to work with you again.", 2),
            ("Which goal focuses on effort, the part you control?", "Practice my pitch every day this week",
             "Get every customer to say yes", "Be the top seller in my class",
             "You can't control what customers decide or what others sell. You can control your practice. Effort goals keep you moving even on slow days.", 2),
            # Level 3
            ("After a bad sales day, a friend says \"Don't worry, you're just not a business person.\" It sounds kind. What is the problem?",
             "It treats a skill as something you can't grow", "Nothing, kind words like that help you feel better about it",
             "It is too harsh to say to a friend",
             "Comfort that says you are not born for something sounds nice but quietly tells you to stop trying. Better comfort is: \"That was hard. What could we try next time?\"", 3),
            ("Your teacher says \"You're so smart!\" after an easy test. Which praise would build a stronger mindset?", "You studied well and it showed",
             "You are a natural, you never need to try", "You are smarter than everyone else here",
             "Praise for effort and strategy tells you what to repeat. Praise for being \"naturally smart\" can make people avoid hard things so they do not look less smart.", 3),
            ("Your stand had its best day ever. What is the champion move the next morning?", "Review what worked so you can repeat it",
             "Relax, since you clearly have it figured out", "Tell everyone you are the best stand in town",
             "Reviewing is not just for losses. Wins are data too. Knowing why a day went well, like the spot or the sign, lets you do it again on purpose.", 3),
            ("Before a big pitch, a friend says \"Just believe in yourself and you'll be fine.\" What is missing?", "Practice, so your belief rests on something",
             "Nothing, believing is the main thing", "Acting extra confident so nobody sees you are nervous",
             "Believing in yourself helps, but real confidence comes from knowing you prepared. Acting confident to hide nerves does not replace knowing your stuff.", 3),
            ("Your rival's bake sale beat yours, and you feel jealous. Which thought is most useful?", "What did they do that I could learn?",
             "I should feel happy and ignore it", "They got lucky, so it does not count",
             "Jealousy is a normal feeling, so you do not need to pretend it away. Turning it into curiosity helps you learn. Calling it luck skips the lesson.", 3),
            ("Your team lost because of a mistake you made. What is the best way to own it?", "Admit it, learn from it, and keep going",
             "Keep blaming yourself so you never forget it", "Quit the team so you can't let them down",
             "Ownership is not punishing yourself forever. It means saying \"that was on me,\" learning what to change and helping the team move forward.", 3),
            ("You win a pitch contest, and a friend who lost looks upset. What is winning with class?", "Thank them and say what you liked about theirs",
             "Tell them it was easy and they will win next time", "Avoid them so you do not make it worse",
             "Winning with class means respecting the people you competed with. Saying it was easy can feel like bragging, even if you meant well. Avoiding them can feel cold.", 3),
            ("You lost 10 to 2. A teammate says \"At least we tried our best, so there is nothing to learn.\" What is the catch?", "Trying hard and learning both matter",
             "Nothing, effort is all that matters", "You should be upset about it for a long time after",
             "Effort is great and worth being proud of. But champions also review: what worked, what did not and one thing to fix. Effort plus learning is how you improve.", 3),
            ("You are nervous before a big recital. Which thought helps the most?", "This matters to me, and I prepared",
             "I must not be nervous, nervous means bad", "If I mess up, it will ruin everything",
             "Nerves are your body getting ready for something important. Seeing them as a sign you care, plus remembering your practice, helps you use the energy.", 3),
            ("A customer gives harsh feedback on your bracelets. Which response shows the most courage?", "Thank them and ask what would make it better",
             "Tell them they are wrong about your bracelets", "Smile, say thanks, then forget about it",
             "Asking a follow-up question takes courage, because you might hear more hard things. But that is how feedback turns into a better product.", 3),
            ("You are the best speller in class and only enter easy contests to stay on top. What is the problem?", "Avoiding hard ones keeps you from growing",
             "Nothing, winning is the whole point", "You should lose on purpose sometimes to be fair to others",
             "Staying where you always win feels safe, but you learn the most from challenges you might fail. Losing on purpose is not the answer either; seek tougher contests.", 3),
            ("Your lawn business got two bad reviews. A friend says \"Ignore them, haters gonna hate.\" Why is that risky?", "The reviews may hold a real fix",
             "Nothing, confident owners ignore critics", "You should reply and argue with each one",
             "Some criticism is unfair, but some points to real problems, like missed edges. Champions check feedback for useful truth before deciding what to do.", 3),
            ("Your team is down at halftime. A teammate says \"We must win or the season is a waste.\" What is a better focus?", "Play our best on the next play",
             "Just think about the final score", "Accept the loss and save energy",
             "Thinking about the whole season adds pressure you can't use. Focusing on the next play, which you control, is how teams make comebacks.", 3),
        ],
        "facts": [
            ("Your brain can get better at a skill when you practice it.", True,
             "Practice strengthens connections in your brain. That is why things that felt hard, like reading or riding a bike, get easier over time."),
            ("If you are not good at something the first time, you never will be.", False,
             "Almost everyone starts as a beginner. With effort, good strategies and help, most skills improve a lot."),
            ("Feeling nervous before a big moment means you are going to do badly.", False,
             "Nerves are normal, even for pros. They often mean you care. Many people perform well while feeling nervous."),
            ("Slow, deep breaths can help your body feel calmer.", True,
             "Breathing out slowly helps your body relax. Many athletes and speakers use it before big moments."),
            ("Confidence that comes from preparation is steadier than confidence from bragging.", True,
             "When you have practiced, you have proof you can do it. Bragging can fall apart the moment things get hard."),
            ("Good sportsmanship only matters when you lose.", False,
             "It matters both ways. Winning with class and losing with grace both show respect and make people want to play and work with you."),
            ("Another person's success means there is less success left for you.", False,
             "Success is not a pie with a fixed number of slices. A friend doing well can teach you, and many businesses grow side by side."),
            ("Working harder without ever changing your strategy always leads to better results.", False,
             "Effort matters, but doing the same wrong thing harder can keep you stuck. Growth comes from effort plus new strategies and feedback."),
            ("You can learn useful lessons by reviewing a win, not only a loss.", True,
             "Knowing why something went well lets you repeat it on purpose instead of hoping it happens again."),
            ("Asking for feedback is a sign that you are weak at something.", False,
             "Asking for feedback is a strong move. Pros in sports, business and art ask for it all the time to keep improving."),
            ("Making excuses after a loss helps you improve faster.", False,
             "Excuses point away from what you can change. Looking honestly at your own part shows you what to fix."),
            ("You can always choose your effort and attitude, even when you can't choose the result.", True,
             "Results depend on many things, like weather or the other team. Effort and attitude are the parts that are always yours."),
            ("Comparing yourself to your past self is a good way to see your own progress.", True,
             "Your past self started where you did. Seeing how far you have come shows real growth and keeps you motivated."),
            ("Having a growth mindset means you believe you can learn anything instantly.", False,
             "A growth mindset means skills can grow over time with effort, strategy and help. It takes time and practice, not magic."),
        ],
    },
    {
        "key": "habits",
        "title": "Habits of Winners",
        "tagline": "Daily moves that build champions",
        "icon": "target",
        "cards": [
            ("1% better adds up", "Get a little better each day and it grows, like interest on savings. Practice your bake sale pitch 10 minutes a day and in a month you have 300 minutes of practice most people never do."),
            ("Practice the hard part", "Deliberate practice means picking the part you are worst at, working on just that, getting feedback and trying again. Doing the easy part over and over feels good but teaches you less."),
            ("Systems beat motivation", "Motivation comes and goes like weather. A routine, like walking dogs at 4pm every school day, keeps you going when you do not feel like it. Start small so you keep your promise to yourself."),
            ("Focus and energy", "Do one thing at a time with your phone in another room. Sleep, real food, moving your body and short breaks are not lazy. They are how your brain and body do their best work."),
            ("Prepare, then reflect", "Before a big moment like a pitch, test or game, use a checklist and rehearse. At the end of the day ask: what went well and what can I improve? Write it down and track your streaks."),
            ("Your people and patience", "Spend time with people who lift you up, and be that person for your team. Sometimes skip a small reward now for a bigger one later, like saving profits to buy a better cart."),
        ],
        "questions": [
            # Level 1
            ("What does \"getting 1% better each day\" mean?", "Small gains each day that add up", "Being perfect at one thing by tomorrow",
             "Only working on 1% of your days", "Tiny improvements stack on top of each other. Like money earning interest, a little extra skill each day grows into a big difference over months.", 1),
            ("You practice your bake sale pitch 15 minutes a day for 4 weeks. How many minutes is that?", "420 minutes", "60 minutes",
             "300 minutes", "4 weeks is 28 days, and 28 x 15 = 420. Small daily blocks quietly add up to hours of practice, which is how skills grow.", 1),
            ("Which is the best example of a routine?", "Walking dogs at 4pm every school day", "Walking dogs whenever you happen to feel like it",
             "Walking dogs once in a while", "A routine happens at the same time in the same way, so you do not have to decide again each day. That is what makes a small business reliable.", 1),
            ("Your phone keeps buzzing while you do homework. What helps you focus best?", "Put the phone in another room", "Check it after every buzz",
             "Keep it face up next to you", "Every check pulls your brain away, and it takes time to get back into the task. Out of sight makes it much easier to stay focused.", 1),
            ("Why is sleep important for a busy kid running a business?", "Rested brains think and learn better", "Sleep is only for lazy people",
             "Sleep does not matter if you work hard", "Sleep is when your brain stores what you learned and your body recovers. Good sleep is part of doing well, not a break from it.", 1),
            ("What is a checklist good for before a big day?", "Making sure you do not forget anything", "Making the day go by faster",
             "Proving you are smarter than others", "Pilots and doctors use checklists because even experts forget steps under pressure. A list for your lemonade stand means you never forget the cups.", 1),
            ("At the end of the day, which question helps you improve?", "What went well and what can I fix?", "Whose fault was it when things went wrong?",
             "How can I forget about today fast?", "A short review turns each day into a lesson. Noticing wins builds confidence, and noticing one fix gives you something to try tomorrow.", 1),
            ("What is a streak when you track a habit?", "The number of days in a row you did it", "A day when you skip the habit",
             "A prize your friends give to you", "Watching a streak grow on a calendar is motivating. If it breaks, just start a new one. One missed day does not erase the progress you made.", 1),
            ("Your friend says \"you can do it\" when you are nervous about a pitch. What is your friend doing?", "Lifting you up", "Bossing you around",
             "Wasting your time", "People who cheer you on and give honest help make it easier to try hard things. Be that kind of friend back to them.", 1),
            ("Which snack is best before a long, hot afternoon of mowing lawns?", "Fruit and a big glass of water", "Only a large bag of candy",
             "Nothing at all, so you can work faster", "Your body needs real fuel and water to work in the sun. Candy alone gives a quick burst of energy and then a crash.", 1),
            ("You want to start a reading habit. Which first step is easiest to keep?", "Read 2 pages every night before bed", "Read a whole book every night",
             "Read only when you feel bored", "Starting tiny makes the habit easy to keep. Once it is a normal part of your night, you can grow it to more pages.", 1),
            ("What is a short break during work time for?", "Resting so you can focus again", "Quitting the task for the day",
             "Showing that you do not care", "Short breaks let your brain recharge. Many people work about 25 to 50 minutes, rest a few minutes, then get back to it.", 1),
            ("You save $2 a day for 10 days. How much do you have?", "$20", "$12", "$200",
             "2 x 10 = 20. Small, steady saving adds up over time, just like small, steady practice does.", 1),
            # Level 2
            ("What makes practice \"deliberate\"?", "Working on weak spots and getting feedback", "Doing the part you are already good at many times",
             "Practicing for as many hours as you possibly can", "Deliberate practice targets the hard part, gets feedback and tries again. Hours alone do not help much if you keep repeating the same mistakes.", 2),
            ("You keep making mistakes giving change to customers. What is the best practice plan?", "Drill making change and have someone check you",
             "Keep running the stand and hope it fixes itself in time", "Let customers count out their own change", "Practicing the exact weak spot with feedback is the fastest way to fix it. Hoping it gets better on its own lets the same mistake repeat.", 2),
            ("You do not feel like walking the neighbor's dog today. What keeps you going?", "Your promise to the customer and your routine", "Waiting until motivation comes back",
             "Skipping it since you do not feel it", "Motivation goes up and down. A routine and a promise to a customer carry you on low days, and you often feel better once you start.", 2),
            ("What is habit stacking?", "Linking a new habit to one you already do", "Starting five brand-new habits on the very same day",
             "Stacking all your homework in one pile", "Tying a new habit to an old one gives it a reminder. Example: after I brush my teeth, I write tomorrow's to-do list.", 2),
            ("You practice guitar 20 minutes a day, 5 days a week. How many minutes is that each week?", "100", "25", "140",
             "20 x 5 = 100. Picking a clear amount for each day makes your weekly total easy to plan and track.", 2),
            ("Before pitching your dog-walking service to a neighbor, what is the smartest prep?", "Rehearse out loud and plan for questions",
             "Just wing it so you sound natural", "Write a very long speech and memorize every word", "Rehearsing out loud finds the bumpy parts. Thinking about likely questions, like price and times, helps you stay calm. Aim for practiced, not perfect.", 2),
            ("Which one is a deep work block?", "45 minutes on one task, phone away", "45 minutes jumping between tasks",
             "45 minutes of homework with videos on", "Deep work means full focus on one hard task. Switching tasks or watching videos splits your attention and makes everything take longer.", 2),
            ("A customer offers $5 now for a quick job, or $8 next week for a bigger one. Which choice shows delayed gratification?", "Waiting for the $8 job",
             "Taking the $5 right away", "Asking for both and doing neither", "Delayed gratification means picking the bigger later reward when it is worth it. Here, waiting one week earns $3 more for your business.", 2),
            ("Your bake sale team is tired and grumpy. How can you lift them up?", "Thank them and name one win so far", "Tell them to quit complaining",
             "Leave early so you do not catch the mood", "Thanks and a real win remind people their effort matters. A good teammate brings energy up instead of adding pressure or walking away.", 2),
            ("You missed one day of your new habit. What is the best move?", "Just start again the very next day", "Quit since the streak is broken",
             "Do triple tomorrow to catch up", "Missing once is normal. A good rule is never miss twice. Getting right back on track matters more than a perfect streak.", 2),
            ("Why do top athletes care so much about sleep and food?", "They help your body and brain perform well", "They are only treats after winning",
             "They matter only for older athletes", "Your body and brain are your tools. Rest and good food help muscles recover and help you think fast, at any age.", 2),
            ("Your journal shows you sell more lemonade on hot afternoons than cold mornings. What does reflecting help you do?", "Choose better times to open the stand",
             "Keep a list of fun memories only", "Prove that the weather is unfair", "Writing down what happened turns your days into data. Patterns help you make smarter choices, like opening when customers are thirsty.", 2),
            ("You do 10 push-ups a day and add 1 more each week. How many a day in week 5?", "14", "15", "50",
             "Week 1 is 10, week 2 is 11, week 3 is 12, week 4 is 13 and week 5 is 14. Slow, steady increases are how strength and skills grow safely.", 2),
            # Level 3
            ("You plan to practice piano 2 hours every day starting today. After 3 days you quit. What most likely went wrong?", "The start was too big to keep up",
             "You just are not a music person", "Two hours was not enough time", "Huge starts burn out fast. Starting with 10 minutes you can really do builds the habit, then you can grow it. It is not about being a type of person.", 3),
            ("Maya shoots 200 free throws alone. Leo shoots 80, films them and fixes one thing at a time. Who likely improves more?", "Leo, since he gets feedback and fixes",
             "Maya, because more shots is always better", "They tie since they practiced the same hour", "Repetition helps, but feedback tells you what to change. Leo is doing deliberate practice. Maya may be repeating the same mistake 200 times.", 3),
            ("Your stand earns $10 a week. You could buy candy now or save 6 weeks for a $60 juicer that helps you sell more. What is the best thinking?", "Save, since the juicer can earn more",
             "Spend it now, since money is for fun today", "Never spend on the business, since saving is best", "Delaying gratification is smart when the later reward is bigger. 6 x $10 = $60, and a tool that boosts sales can pay you back again and again.", 3),
            ("You feel super motivated and want to work 6 hours on your business tonight, but you have a test tomorrow. What is wise?", "Work a set time, then study and sleep",
             "Ride the motivation for all 6 hours", "Skip studying since business matters more", "Motivation is great fuel, but a plan keeps you balanced. Protecting study time and sleep means you do well on the test and still make progress.", 3),
            ("Your best friend teases you for saving money and practicing instead of hanging out. What is a healthy response?", "Share your goal and invite them along",
             "Drop your goals so the teasing will finally stop", "Stop being friends with them right away", "Good friends can support your goals, and sharing why it matters often turns teasing into support. If someone always pulls you down, spend more time with people who lift you up.", 3),
            ("You stayed up until midnight 3 nights in a row working on your bake sale and feel proud of the effort. What is the catch?", "Tired brains make more mistakes and learn less",
             "Late nights always lead to better results", "Sleep only matters on school nights", "Losing sleep makes it harder to think, remember and stay in a good mood. You often get more done by stopping on time and starting fresh.", 3),
            ("You checked your phone \"just once\" in a 30-minute study block and lost 10 minutes. What part of the block was lost?", "One third", "One tenth", "One half",
             "10 out of 30 minutes is 1/3. Quick checks rarely stay quick, and getting your focus back takes extra time too.", 3),
            ("Your family company keeps forgetting change, signs and bags for the farmers market. Which fix works best long-term?", "A packing checklist used every time",
             "Everyone trying harder to remember", "Blaming whoever packed the car last week", "Good intentions fade, but a system works every time. A checklist turns remembering into a routine anyone on the team can follow.", 3),
            ("A classmate says habits always take exactly 21 days to form. What is the best reply?", "It varies a lot from habit to habit",
             "Yes, after day 21 it is automatic", "No, habits form in exactly 7 days", "Research shows habits take very different amounts of time, often weeks to months, depending on the person and the habit. Keep going past 21 days.", 3),
            ("You have 3 lawns to mow today but keep thinking about a new video game. What helps you finish fastest?", "One lawn at a time, full focus",
             "Plan your game moves while you mow", "Mow a bit of each lawn and switch around", "Switching and daydreaming both slow you down. Full focus on one job at a time gets each lawn done well, and then the game can be your reward.", 3),
            ("Your review shows you sold 30 cookies but got 3 complaints about burnt edges. What is the best reflection?", "Great sales; fix the oven timing",
             "30 sales means nothing needs to change", "3 complaints means the day was a failure", "Good reflection sees both sides: celebrate what worked and pick one thing to improve. Ignoring problems or only seeing problems both stop you from growing.", 3),
            ("You get 1% better at typing each week for a year (52 weeks). A friend says that is too small to matter. What is true?", "It grows to about 68% better",
             "It stays at just 1% better", "It grows to about 520% better", "Each week builds on the last, like interest on savings. 1.01 multiplied by itself 52 times is about 1.68, so you end up about 68% better.", 3),
            ("A quiet teammate always does their dog-walking shifts but never speaks in team meetings. How can you lift the team?", "Thank them and ask for their ideas",
             "Ignore it since they do the work", "Tell the whole team they should talk more", "Lifting others up means noticing good work and making room for every voice. Quiet people often have great ideas when someone asks.", 3),
            ("You promised yourself to journal 1 page every night but keep skipping. Which change is most likely to help?", "One line, right after brushing teeth",
             "Promise to write 3 pages to make up for it", "Wait until you feel inspired to write", "A tiny habit tied to something you already do is easier to keep. Keeping small promises to yourself builds trust that you will follow through.", 3),
        ],
        "facts": [
            ("Habits can take weeks or even months to become automatic.", True,
             "Studies show it varies a lot. Simple habits may take a few weeks, harder ones many months. Keep going even when it feels slow."),
            ("Every habit takes exactly 21 days to form.", False,
             "This is a popular myth. Research shows the time ranges widely depending on the person and the habit."),
            ("Short breaks during long work sessions can help you focus better.", True,
             "A few minutes of rest lets your brain recharge, so you come back sharper instead of slowly running out of focus."),
            ("Your brain can give full focus to two hard tasks at the same time.", False,
             "When you multitask, your brain actually switches back and forth, which makes you slower and causes more mistakes."),
            ("Health experts say kids ages 6 to 12 need about 9 to 12 hours of sleep a night.", True,
             "Sleep helps you grow, learn and stay in a good mood. Teens need about 8 to 10 hours."),
            ("Motivation is the most reliable way to keep a habit going.", False,
             "Motivation rises and falls. Routines, small starts and reminders are what keep habits going on low-energy days."),
            ("Getting feedback is a key part of deliberate practice.", True,
             "Feedback from a coach, a video or a checked answer shows you exactly what to fix next, so practice time is not wasted."),
            ("Missing one day ruins a habit for good.", False,
             "Missing once barely matters. What counts is getting back to it the next day instead of missing again."),
            ("Pilots and surgeons use checklists to help avoid mistakes.", True,
             "Even experts forget steps under pressure. Checklists make sure the important things get done every single time."),
            ("Practicing only what you are already good at is the fastest way to improve.", False,
             "It feels nice, but growth comes from working on your weak spots and getting feedback on them."),
            ("Writing down what went well each day can help you notice your progress.", True,
             "Progress is easy to miss day to day. A journal shows how far you have come and keeps you motivated."),
            ("Sleeping and taking breaks are signs of being lazy.", False,
             "Rest is part of performing well. Top athletes, students and business owners plan rest so they can do their best work."),
            ("Moving your body, like a walk or a game of tag, can help your brain focus.", True,
             "Exercise gets blood flowing to your brain and can lift your mood, which helps you think and work better afterward."),
            ("Spending every dollar right away is the best way to grow a small business.", False,
             "Saving some profit lets you buy tools or supplies later that help you earn more. That is delayed gratification at work."),
        ],
    },
]
