"""Academy question bank: more words, pro-talk situations and scenarios for the original worlds."""

# More kid-friendly business vocabulary: (word, meaning).
GLOSSARY_MORE = [
    # Money and finance
    ("Asset", "Something valuable the business owns, like a delivery van, an oven or cash in the bank."),
    ("Liability", "Something the business owes to others, like a loan or an unpaid bill."),
    ("Loan", "Money borrowed from a bank or person that must be paid back, usually with extra."),
    ("Interest", "The extra money you pay for borrowing, or earn for saving, on top of the amount."),
    ("Debt", "Money you owe and still need to pay back."),
    ("Credit", "Trust that lets you buy now and pay later, as long as you pay on time."),
    ("Credit score", "A number that shows how well someone pays back what they borrow."),
    ("Savings", "Money you set aside instead of spending it, so it's there when you need it."),
    ("Emergency fund", "Money saved just for surprises, like a broken freezer or a slow month."),
    ("Bank account", "A safe place at a bank that holds your money and keeps track of it."),
    ("Deposit", "Money you put into a bank account, or pay ahead to hold an order."),
    ("Withdrawal", "Money you take out of a bank account."),
    ("Capital", "The money and tools used to start or grow a business."),
    ("Investor", "A person who gives money to a business hoping to earn more back later."),
    ("Return on investment", "How much you earn back compared to what you put in."),
    ("Shareholder", "A person who owns a small piece, called a share, of a company."),
    ("Equity", "The part of a business that truly belongs to the owners after debts are paid."),
    ("Dividend", "A share of the profit that a company pays to its owners."),
    ("Collateral", "Something valuable you promise to give a lender if you can't pay back a loan."),
    ("Bankruptcy", "A legal process for a business that can't pay its debts."),
    ("Cash flow", "The money coming in and going out of a business over time."),
    ("Expense", "Money spent to run the business, like rent, flour or electricity."),
    ("Fixed cost", "A cost that stays the same each month, like rent, no matter how much you sell."),
    ("Variable cost", "A cost that goes up when you sell more, like cups for each lemonade."),
    ("Overhead", "The everyday costs of running a business, like rent, lights and insurance."),
    ("Break-even", "The point where money coming in equals costs, so you neither win nor lose money."),
    ("Gross", "The total amount before anything is taken away, like costs or taxes."),
    ("Net", "The amount left after costs or taxes are taken away."),
    ("Margin", "The part of a sale's price that is profit after paying for the item."),
    ("Markup", "The amount added to an item's cost to set the price you sell it for."),
    ("Price", "How much money a customer pays to buy something."),
    ("Unit price", "The price for one item, like one cupcake or one pound of apples."),
    ("Discount", "A lower price than usual, like 20% off."),
    ("Sales", "The things a business sells, or the money it gets from selling them."),
    ("Forecast", "A smart guess about the future, like how many pies you'll sell next month."),
    ("Quarter", "One fourth of a year, or three months. Businesses check results each quarter."),
    ("Fiscal year", "The 12 months a business uses for its money records, which may not start in January."),
    ("Tax", "Money people and businesses pay to the government for roads, schools and more."),
    ("Audit", "A careful check of a business's records to make sure they are correct and honest."),
    ("Bookkeeping", "Writing down every dollar that comes in and goes out of the business."),
    ("Accountant", "An expert who keeps track of a business's money and helps with taxes."),
    ("Balance sheet", "A report that lists what a business owns, what it owes, and what's left."),
    ("Income statement", "A report that shows sales, costs and profit over a period of time."),
    ("Accounts receivable", "Money that customers owe the business but haven't paid yet."),
    ("Accounts payable", "Money the business owes to suppliers but hasn't paid yet."),
    ("Payment terms", "The rules for when and how a bill must be paid, like within 30 days."),
    ("Late fee", "Extra money charged when a bill is paid after the due date."),
    ("Down payment", "Part of the price paid up front, with the rest paid later."),
    ("Depreciation", "How things like trucks and computers lose value as they get older."),
    ("Inflation", "When prices go up over time, so the same dollar buys a little less."),
    ("Economy", "All the buying, selling and working that happens in a town or country."),
    ("Recession", "A time when the economy shrinks, people buy less and jobs are harder to find."),
    ("Risk", "The chance that something could go wrong or that you could lose money."),
    ("Diversify", "To spread out your money or customers so one problem can't sink you."),
    # Running the business
    ("Entrepreneur", "A person who starts a business and takes a risk to make an idea real."),
    ("Startup", "A brand-new business that is just getting going."),
    ("Partnership", "A business owned by two or more people who share the work and profits."),
    ("Partner", "A person who owns and runs a business together with you."),
    ("Sole proprietor", "A person who owns a business all alone."),
    ("Corporation", "A business that is its own legal thing, separate from the people who own it."),
    ("Nonprofit", "An organization that uses its money to help a cause, not to make owners rich."),
    ("Franchise", "A business that pays to use another company's name, recipes and way of working."),
    ("Merger", "When two companies join together to become one."),
    ("Family business", "A business owned and run by members of the same family."),
    ("Succession plan", "A plan for who will run the business when the current owner steps away."),
    ("Board of directors", "A group of people chosen to guide a company and check on its leaders."),
    ("CEO", "Chief Executive Officer: the top leader who runs a company day to day."),
    ("Manager", "A person who leads a team and makes sure work gets done well."),
    ("Supervisor", "A person who watches over workers during a shift and helps them."),
    ("Business plan", "A written plan that explains what a business will sell, to whom, and how it will make money."),
    ("Mission", "A short statement of what a business does and why it exists."),
    ("Vision", "A picture of what the business hopes to become in the future."),
    ("Strategy", "A big plan for how the business will reach its goals."),
    ("Goal", "Something specific you are working to achieve, like 50 sales by June."),
    ("Milestone", "An important step along the way to a bigger goal."),
    ("KPI", "Key Performance Indicator: a number you track to see if you're reaching a goal."),
    ("Benchmark", "A standard used to compare how well you're doing."),
    ("Prototype", "A first test version of a product, made to try out an idea."),
    ("Pilot", "A small test run of a new idea before doing it everywhere."),
    ("Innovation", "A new idea or better way of doing something."),
    ("Productivity", "How much good work gets done in a certain amount of time."),
    ("Efficiency", "Getting a job done well without wasting time, money or supplies."),
    ("Bottleneck", "One slow step that holds up everything else, like a single slow oven."),
    ("Quality control", "Checking products to make sure they meet the business's standards."),
    ("Safety", "Protecting workers and customers from getting hurt."),
    ("Regulation", "A rule made by the government that businesses must follow."),
    ("Permit", "Official permission to do something, like build a new sign or hold an event."),
    ("License", "An official paper that says a business or person is allowed to do certain work."),
    ("Insurance", "Paying a small amount regularly so you get help paying if something bad happens."),
    ("Liability insurance", "Insurance that helps pay if the business accidentally hurts someone or damages their stuff."),
    ("Lease", "A contract to rent a building or equipment for a set time."),
    ("Rent", "Money paid to use a building or space that belongs to someone else."),
    ("Landlord", "The person or company that owns a building and rents it out."),
    ("Utilities", "Services like water, electricity and heat that a building needs."),
    ("Agenda", "A list of topics to talk about in a meeting, in order."),
    ("Minutes", "Written notes of what was said and decided in a meeting."),
    ("Delegation", "Giving a task to someone else while still making sure it gets done right."),
    ("Accountability", "Being willing to answer for your actions and their results."),
    ("Ethics", "Ideas about what is right and fair, used to make good choices."),
    ("Integrity", "Being honest and doing the right thing, even when no one is watching."),
    ("Confidential", "Private information that should only be shared with people who need it."),
    ("Trade secret", "Private business know-how, like a secret recipe, that gives a company an edge."),
    ("Trademark", "A protected name, logo or symbol that only one business can use for its products."),
    ("Patent", "A legal right that lets only the inventor make and sell an invention for a time."),
    ("Copyright", "A legal right that protects things people create, like books, music and art."),
    # Buying, selling and moving goods
    ("Supplier", "A business that sells you the things you need, like flour for a bakery."),
    ("Vendor", "Someone who sells goods or services, often to other businesses."),
    ("Distributor", "A business that buys products in bulk and delivers them to stores."),
    ("Wholesale", "Selling large amounts to stores at a lower price per item."),
    ("Retail", "Selling items one at a time to everyday customers."),
    ("Bulk order", "Buying a large amount at once, often for a lower price per item."),
    ("Purchase order", "A written order a business sends to a supplier listing what it wants to buy."),
    ("Quote", "A written price a business offers for a job before the work starts."),
    ("Estimate", "A careful guess of how much a job will cost or how long it will take."),
    ("Bid", "An offer to do a job or buy something for a certain price."),
    ("Logistics", "Planning how to move and store products so they arrive in the right place on time."),
    ("Supply chain", "All the steps and businesses that help get a product from raw materials to the customer."),
    ("Shipment", "A group of goods sent from one place to another."),
    ("Lead time", "How long it takes from placing an order until it arrives."),
    ("Warehouse", "A large building where products are stored until they are sold."),
    ("Stockout", "When a business runs out of an item customers want to buy."),
    ("Barcode", "A pattern of lines a scanner reads to know what an item is and its price."),
    ("Point of sale", "The place and system where a customer pays, like a cash register."),
    ("Receipt", "A paper or email that proves what someone bought and how much they paid."),
    ("Refund", "Money given back to a customer who returns something."),
    ("Return policy", "The store's rules for bringing items back for a refund or exchange."),
    ("Warranty", "A promise to fix or replace a product if it breaks within a certain time."),
    ("Guarantee", "A promise that a product or service will work as described."),
    ("Recall", "When a company asks customers to return a product because it might be unsafe."),
    ("Demand", "How much of something people want to buy."),
    ("Supply", "How much of something is available to buy."),
    ("Exports", "Products a country sells to other countries."),
    ("Imports", "Products a country buys from other countries."),
    # Customers and marketing
    ("Brand", "The name, look and feeling people connect with a business."),
    ("Logo", "A small picture or symbol that stands for a business."),
    ("Slogan", "A short, catchy phrase that helps people remember a business."),
    ("Marketing", "Everything a business does to understand customers and get them interested."),
    ("Advertising", "Paying to tell people about your products, like with posters or online ads."),
    ("Promotion", "A move up to a bigger job with more responsibility, often with more pay."),
    ("Coupon", "A ticket or code that gives a customer money off a purchase."),
    ("Market research", "Studying customers and competitors to learn what people want."),
    ("Survey", "A short list of questions to learn what people think."),
    ("Target market", "The group of people a business most wants to sell to."),
    ("Niche", "A small, special group of customers a business focuses on serving very well."),
    ("Competitor", "Another business that sells similar things to the same customers."),
    ("Market share", "The part of all sales in a market that one business gets."),
    ("Monopoly", "When only one company sells something, so customers have no other choice."),
    ("Price fixing", "When rivals secretly agree on prices. It's illegal and hurts customers."),
    ("Customer service", "How a business helps and treats its customers before and after they buy."),
    ("Loyalty", "When customers keep choosing your business again and again."),
    ("Retention", "Keeping the customers or workers you already have."),
    ("Churn", "When customers stop buying or cancel, like leaving a subscription."),
    ("Repeat customer", "A customer who comes back to buy again."),
    ("Referral", "When someone sends a new customer or worker your way."),
    ("Testimonial", "A happy customer's words about the business, shared with permission."),
    ("Review", "A customer's opinion of a business, often posted online for others to read."),
    ("Complaint", "When a customer tells you something went wrong. It's a chance to fix it."),
    ("Upsell", "Suggesting a better or bigger item, like a large drink instead of a small one."),
    ("Subscription", "Paying regularly, like every month, to keep getting a product or service."),
    ("Pitch", "A short talk to convince someone to buy, invest or join."),
    ("Elevator pitch", "A super short pitch, about 30 seconds, that explains your idea."),
    ("Networking", "Meeting people and building friendly work connections."),
    ("Negotiation", "Talking with someone to reach a deal you both can agree on."),
    ("Compromise", "When each side gives up a little to reach an agreement."),
    ("Win-win", "A deal that is good for both sides."),
    # People and jobs
    ("Payroll", "The list of workers and how much each is paid, and the job of paying them."),
    ("Salary", "A set amount of pay for a year of work, paid in parts."),
    ("Wage", "Pay for each hour of work."),
    ("Minimum wage", "The lowest hourly pay the law allows a business to pay most workers."),
    ("Overtime", "Extra hours worked beyond the usual amount, often paid at a higher rate."),
    ("Benefits", "Extras a job offers besides pay, like health insurance or paid vacation days."),
    ("Raise", "An increase in a worker's pay."),
    ("Shift", "A block of time someone works, like 8 a.m. to noon."),
    ("Schedule", "A plan that shows who works when."),
    ("Job description", "A written list of a job's tasks, skills, hours and pay."),
    ("Resume", "A short document that lists a person's skills, schooling and work experience."),
    ("Interview", "A meeting where an employer asks questions to see if someone fits a job."),
    ("Reference", "A past boss or teacher who can tell an employer about how you work."),
    ("Onboarding", "Welcoming and training a new worker so they can do their job well."),
    ("Probation period", "The first weeks of a new job, when both sides see if it's a good fit."),
    ("Performance review", "A meeting to talk about how well someone is doing their job and how to grow."),
    ("Feedback", "Helpful comments about what's going well and what could be better."),
    ("Mentor", "An experienced person who gives advice and helps you grow."),
    ("Intern", "A student or beginner who works for a short time to learn a job."),
    ("Teamwork", "People working together and helping each other reach a shared goal."),
]

# More pro-talk situations: (situation, best, not-so-good, not-so-good, why).
PRO_TALK_MORE = [
    ("You need to leave a voicemail for a supplier. What should you say?",
     "This is Maya from Green Leaf Bakery. Please call me at 555-0142. Thanks!",
     "Hey, it's me again. Call me back when you get a chance, okay? Talk soon, bye!",
     "Hang up without a message and keep calling back until they answer",
     "Say your name, your company and your number slowly, so they know who called and how to reach you."),
    ("You meet a new client for the first time. What's the best greeting?",
     "Smile, shake hands, make eye contact and say, \"Hi, I'm Sam. Nice to meet you.\"",
     "Look down, mumble your name, and wait for them to start the conversation",
     "Skip the hello and jump straight into your prices, since a busy client's time is valuable",
     "A smile, eye contact and a clear introduction show confidence and make people feel welcome."),
    ("You're emailing your manager to ask for Friday off. Which subject line is best?",
     "Request: Day off on Friday, May 9",
     "Quick question about something I need to ask you",
     "IMPORTANT!!! PLEASE READ THIS RIGHT AWAY!!!",
     "A clear subject line tells the reader what the email is about before they even open it."),
    ("You're joining a video call with a customer. What should you do first?",
     "Find a quiet spot, test your camera and mic, and join on time",
     "Join from a noisy room with your camera pointed at the ceiling",
     "Join a few minutes late and eat lunch, since it's only a video call",
     "Video calls are real meetings. Being on time, easy to see and easy to hear shows respect."),
    ("You'll be late for your shift and need to text your coworker. What's the best text?",
     "Hi Jo, my bus is late. I'll be there by 9:15. Sorry for the trouble!",
     "hey running late again lol, not sure when i'll get there",
     "Send nothing, then walk in late and act like everything is normal.",
     "A short, clear text with the reason and your arrival time helps your team plan."),
    ("Your boss is talking with someone, but a customer urgently needs them. What do you say?",
     "Sorry to interrupt. A customer needs you at the front when you can.",
     "Hey! You need to come over here right now, there's a customer waiting!",
     "Wait quietly until they're done, even if the customer gives up and leaves",
     "\"Sorry to interrupt\" plus a quick reason is the polite way to break in when something matters."),
    ("You're waiting with a new client for a meeting to start. What's good small talk?",
     "Ask a friendly, easy question, like how their week is going",
     "Complain about how annoying your coworkers have been this week",
     "Ask how much money they make, so you know who you're dealing with",
     "Light, friendly small talk helps people relax. Avoid complaints and personal questions."),
    ("A coworker asks you to take on extra work, but your day is already full. What do you say?",
     "I'd like to help, but I'm full today. Could I help tomorrow morning?",
     "No way. I have my own work, so go find somebody else to do it.",
     "Say yes right away to be nice, then quietly never get around to doing any of it.",
     "A polite no with another option is honest and kind. Saying yes and not doing it breaks trust."),
    ("You sent a customer a price quote a week ago and heard nothing. What's best?",
     "Send a short, friendly email asking if they have questions about the quote",
     "Send an email asking why they ignored your quote after all of your hard work on it",
     "Call them five times in one afternoon so they can't forget about you",
     "A polite follow-up reminds busy people without pushing them away."),
    ("A supplier rushed an order to help you out of a jam. How should you thank them?",
     "Send a note: \"Thank you for rushing our order. You really saved the day.\"",
     "Say nothing, since rushing orders is part of a supplier's job anyway",
     "Thank them only if they bring it up, so you don't seem too eager",
     "A specific thank-you makes people feel valued and glad to help you again."),
    ("You were short with a coworker because you were stressed. What should you say?",
     "I'm sorry I snapped at you earlier. That wasn't fair to you.",
     "Sorry, but you made me mad, so it was really your fault too.",
     "Nothing. Just act extra nice so it seems like it never happened.",
     "A real apology names what you did and doesn't make excuses. It repairs the relationship."),
    ("You've worked hard for a year and want a raise. How should you ask?",
     "Ask for a private meeting, show your results, and politely ask",
     "Bring it up loudly in a team meeting so everyone sees you deserve it",
     "Tell your boss you'll quit tomorrow unless they pay you more",
     "Asking privately and showing your results makes it easy for your boss to say yes."),
    ("Your manager says your report had mistakes. What's the best reply?",
     "Thanks for telling me. Could you show me where, so I can fix them?",
     "That's not true. My report was perfect, so someone else must have changed it.",
     "Roll your eyes, say \"fine,\" and walk away without another word.",
     "Taking feedback calmly and asking how to improve shows you're mature and want to grow."),
    ("A teammate's sign for the shop has a spelling mistake. How do you tell them?",
     "Privately and kindly: \"Great sign! I spotted one small typo here.\"",
     "Point it out loudly in front of the team so everyone learns from it",
     "Fix it secretly, then tell others they should check their spelling",
     "Good feedback is private, kind and specific. Start with something positive."),
    ("You're giving a short talk to your family's team. What helps most?",
     "Practice ahead, start with your main point, and speak slowly and clearly",
     "Read every word off your slides, facing the screen so you don't get lost",
     "Skip practice and talk fast, so you finish before anyone gets bored",
     "Practice and a clear main point help people understand and remember your message."),
    ("A caller asks for someone who is out today. What should you say?",
     "She's out today. May I take a message or have her call you tomorrow?",
     "She's not here today, so you'll have to try calling back later. Bye.",
     "I don't know where she is or when she'll be back, sorry.",
     "Offering to take a message helps the caller and makes sure your coworker gets it."),
    ("An email went to 40 people. You only want to thank the sender. What should you do?",
     "Reply just to the sender",
     "Reply to all 40 people so everyone sees your thanks",
     "Forward it to even more people with a thumbs-up",
     "Reply all fills everyone's inbox. Only include people who need to read your message."),
    ("A supplier's delivery is late again and you're upset. What's best before you email them?",
     "Wait until you're calm, then write clearly what happened and what you need",
     "Write it in all capital letters right away, so they know it's serious",
     "Send several short emails in a row until they finally answer you",
     "Calm, clear emails solve problems. Angry emails can hurt the relationship for a long time."),
    ("Your mom, the owner, meets your teacher at the shop. How do you introduce them?",
     "\"Mr. Reed, this is my mom, Ana Cruz. Mom, this is Mr. Reed, my teacher.\"",
     "Wait for them to introduce themselves, since grown-ups know how",
     "Say \"Hey, that's my mom,\" then go back to stocking shelves",
     "A good introduction says each person's name and how you know them, so they can start talking."),
    ("You'll be five minutes late to a meeting. What should you do?",
     "Send a quick message before it starts saying you'll be five minutes late",
     "Walk in late quietly and sit in the back, so you don't interrupt anyone who is talking",
     "Skip the whole meeting, since walking in late looks even worse",
     "A heads-up lets people decide whether to wait or start, and shows you respect their time."),
    ("You need a coworker to send you a file. Which message is clearest?",
     "Could you send me the June sales file by 3 p.m. today? Thanks!",
     "Send me that stuff from last month whenever you can, thanks.",
     "Where is that file thing we talked about before?",
     "Say exactly what you need and when. Clear requests get done faster."),
    ("You forgot the name of a customer you've met before. What's polite?",
     "Say, \"I'm sorry, could you remind me of your name?\" and then use it",
     "Call them \"buddy\" or \"friend\" and hope they don't notice",
     "Avoid talking to them for the rest of the visit, so you never have to say their name",
     "Everyone forgets names sometimes. Asking honestly is better than faking it."),
    ("A customer on the phone is placing a big order. What should you do?",
     "Write it down and read it back to make sure it's right",
     "Try to remember it all in your head, since writing slows you down",
     "Keep chatting with a coworker, since you can listen at the same time",
     "Reading an order back catches mistakes before they cost money."),
    ("You need to put a caller on hold. What should you say?",
     "May I put you on hold for one minute while I check?",
     "Press hold right away without saying anything, so you save time",
     "Say \"Hold on,\" then leave them waiting while you help others",
     "Asking first and saying how long helps the caller feel respected, not forgotten."),
    ("In a meeting, your phone buzzes with a game alert. What should you do?",
     "Ignore it and silence your phone so you can focus",
     "Check it quickly under the table, since it only takes a second",
     "Read the alert out loud so nobody wonders what it was",
     "Giving people your full attention in meetings shows you take them seriously."),
    ("You don't understand something your manager just explained. What do you say?",
     "Could you explain that part again? I want to get it right.",
     "Nod and pretend you understood, so you don't look slow",
     "Say, \"That makes no sense at all,\" so they explain better",
     "Asking a clear question is smart. Pretending to understand leads to mistakes."),
    ("What makes a good handshake?",
     "A firm grip, a smile, eye contact and two or three shakes",
     "A soft, gentle grip while you look away, to seem polite",
     "Squeezing as hard as you can, so they know you're strong",
     "A firm but friendly handshake with eye contact shows confidence and respect."),
    ("A customer emails a question you can answer. How fast should you reply?",
     "Within one business day, even if just to say you're working on it",
     "Whenever you have time, maybe next week, once you know everything",
     "Never, since they can call you if it really matters to them",
     "Quick replies show customers they matter. If you need time, say when you'll answer."),
    ("A phone call with a customer is ending. What's a professional goodbye?",
     "Thanks for calling! I'll email your receipt today. Have a great day.",
     "Hang up as soon as you're done, so they don't waste their time.",
     "Say \"Okay, that's it, bye\" and hang up before they answer.",
     "Thank them, confirm the next step, and end warmly so they remember a good experience."),
    ("You emailed a price list to the wrong customer by mistake. What's best?",
     "Send a short, polite note saying it was sent in error and apologize",
     "Say nothing and hope they never open it, or that they won't notice the mistake at all",
     "Send lots of new emails so the mistake gets buried in their inbox",
     "Owning a mistake quickly and politely is professional and keeps trust."),
    ("Your manager says the meeting is Tuesday, but your calendar says Wednesday. What do you say?",
     "Quick check: I have it on Wednesday. Could you confirm which day?",
     "You're wrong. It's Wednesday. Check your calendar.",
     "Say nothing and show up on whichever day you think is right",
     "Asking politely to confirm fixes the mix-up without making anyone feel bad."),
    ("You must email the whole team about a schedule change. What's best?",
     "A clear subject, the change in the first line, and who to ask",
     "A long, detailed story with the change explained near the bottom",
     "No subject and no details, just \"FYI, schedule changed\"",
     "Busy readers skim. Put the most important news first and make it easy to act on."),
    ("Your boss praises a project you did with a teammate. What do you say?",
     "Thank you! Jamie did a lot of the work too.",
     "Thanks! I worked really hard on it all by myself.",
     "Just say thanks and leave Jamie out, since the boss is busy.",
     "Sharing credit is honest and makes teammates want to work with you again."),
]

# More scenarios: (situation, best answer, weaker answer, weaker answer, why).
OWN_IT_MORE = [
    ("You gave a customer too little change and noticed after they left. What should you do?",
     "Tell your manager and find a way to get the money back to them",
     "Keep quiet, since customers should always count their own change",
     "Wait and see if they come back to complain about it",
     "Honest owners fix mistakes even when nobody would find out. That's how trust is built."),
    ("Your team missed its sales goal. Your boss asks what happened. What do you say?",
     "Explain honestly what went wrong and share a plan to improve",
     "Explain that the goal was set too high for anyone to reach",
     "Point out that the newest worker slowed the whole team down",
     "Owning the results and bringing a plan shows you're ready for more responsibility."),
    ("You borrowed the shop's tablet and cracked the screen. What should you do?",
     "Tell the owner right away and offer to help pay for the repair",
     "Put it back carefully, since it still works fine for now",
     "Say the screen was already cracked when you picked it up this morning",
     "Telling the truth right away shows integrity. Lies about small things ruin trust in big things."),
    ("You're in charge of locking up the shop tonight, but you're tired. What shows responsibility?",
     "Check every door and window carefully, just like always",
     "Lock the front door and trust that the back one is probably fine",
     "Ask the last customer to lock up, since they're leaving anyway",
     "Responsible people do the job fully, even when they're tired and nobody is checking."),
    ("You signed up to bring supplies for a school bake sale but forgot. What's best?",
     "Admit it, apologize, and find a way to get supplies fast",
     "Say you thought someone else had signed up to bring them",
     "Stay home from the bake sale so nobody has to ask about it",
     "Admitting a slip and fixing it quickly turns a mistake into proof that you're reliable."),
    ("What does it mean to be accountable?",
     "You answer for your actions and results, good or bad",
     "You always have a good explanation for why things went wrong",
     "You only do the tasks your boss is going to check",
     "Accountable people don't hide from results. They own them and learn from them."),
    ("Your little brother helps at the family shop and makes a mistake you were supposed to check. Who is responsible?",
     "You share it, because checking his work was your job",
     "Only he is, since he was the one who made the mistake",
     "Nobody is, since it was just an honest accident",
     "When you're in charge of checking, the result is partly yours. Owners own what they oversee."),
    ("A customer says the bike you repaired has a loose brake. What do you do?",
     "Thank them, fix it right away for free, and recheck your steps",
     "Explain that brakes often loosen when bikes get bumped on the ride home",
     "Fix it, but charge a small fee since it's a second visit",
     "Standing behind your work keeps customers safe and loyal, and checking your steps prevents repeats."),
    ("You set a goal to save $100 for a lawn mower for your mowing business. How do you own that goal?",
     "Make a weekly savings plan, track it and adjust if you fall behind",
     "Save whatever is left over each week and hope it adds up by summer",
     "Ask your parents to buy the mower, and pay them back someday",
     "Owning a goal means making a plan, checking progress and changing course when needed."),
    ("You see a spill in the shop aisle, but it's not your area. What should you do?",
     "Put out a warning sign and clean it up or get help right away",
     "Walk past and trust the worker in that section to find it soon",
     "Warn the nearest customer to watch out and get back to your work",
     "Safety is everyone's job. Owners act on problems they see instead of waiting for someone else."),
    ("You find a typo on your price list that charged customers too much. What should you do?",
     "Fix the price list and refund the customers who paid too much",
     "Fix the price list from now on and keep what was already paid",
     "Leave it, since customers agreed to the price when they paid",
     "Keeping money you didn't earn fairly is wrong. Making it right builds a reputation for honesty."),
    ("You keep finishing chores late because of video games. What's the owner mindset?",
     "Admit the habit and set a rule: chores first, games after",
     "Promise yourself you'll try harder, without changing anything",
     "Wait for a parent to notice and take the game away",
     "Self-responsibility means noticing your own habits and fixing them yourself."),
    ("Your manager gives you a task, but the instructions are unclear. Whose job is it to get clear?",
     "Yours: ask questions until you know what to do",
     "Your manager's: they should explain it better without being asked",
     "Nobody's: make your best guess and fix it later if it's wrong",
     "Taking ownership includes asking for what you need to do the job right."),
    ("You promised a customer a cake by noon, but the oven broke. What now?",
     "Call them early, apologize, and offer the best option you can",
     "Wait until they come to pick it up, then explain that the oven broke",
     "Say nothing and bake a quick cake from a box instead",
     "When you can't keep a promise, honesty and a good backup plan protect the relationship."),
    ("A teammate covered your shift when you were sick. What's the responsible thing afterward?",
     "Thank them and catch up on anything you left behind",
     "Let them keep your tasks, since they already know what to do",
     "Say nothing, since they got paid for the extra hours",
     "Responsible teammates say thanks and pick their share back up quickly."),
    ("You got a bad grade because you didn't study. What's the best response?",
     "Admit you didn't prepare and plan study time for next time",
     "Explain to your parents that the test was harder than usual",
     "Decide you're just not a math person and move on",
     "Owning the real reason gives you the power to change the result next time."),
    ("Your lemonade stand made less money than you hoped. What should you look at first?",
     "Your own choices: price, spot, taste and how you greeted people",
     "The weather, since hot days always decide how much you sell",
     "Your friend's stand, since they took some of your customers",
     "Focus on what you can control. That's where owners find ways to improve."),
    ("You promised to feed the neighbor's cat all week, but friends invite you on a trip. What do you do?",
     "Keep your promise, or find a trusted helper the neighbor agrees to",
     "Ask a friend to do it and tell the neighbor when you get back",
     "Go, and leave the cat a big bowl of food for the whole week",
     "A promise is a promise. If plans change, the other person must agree to the new plan."),
    ("The shop's online ordering breaks while you're in charge. What's best?",
     "Tell customers right away, take orders another way, and get it fixed",
     "Wait for the owner to return, since fixing the website is their job",
     "Post that the website company caused the problem, not you",
     "Owners act fast on problems, keep customers informed and focus on fixing, not blaming."),
    ("What's the difference between a reason and an excuse?",
     "A reason explains and comes with a fix; an excuse just avoids blame",
     "A reason is always true, and an excuse is always a made-up lie",
     "An excuse is better, because it makes people less upset",
     "Responsible people explain what happened and what they'll do next. Excuses stop at the blame."),
]

GRIT_MORE = [
    ("You practiced your sales pitch, but the first five people said no. What now?",
     "Ask for feedback, improve your pitch and keep going",
     "Decide that selling just isn't one of your talents",
     "Keep giving the exact same pitch until someone says yes",
     "Most sales take many tries. Each no is a clue for making your next pitch better."),
    ("Your new cookie recipe came out burned three times. What's the gritty move?",
     "Change one thing at a time, like bake time, and test again",
     "Change the oven, the recipe and the pan all at once to save time",
     "Give up on that recipe and only bake ones you already know",
     "Testing one change at a time shows you what really fixes the problem."),
    ("Saving $500 to start a dog-walking business feels too huge. What helps?",
     "Break it into small steps, like saving $20 a week",
     "Wait until you get a big birthday gift that covers it all",
     "Lower the goal to $50, since $500 is just too much",
     "Big goals become doable when you break them into small, steady steps."),
    ("What is a growth mindset?",
     "Believing you can get better with effort and practice",
     "Believing some people are just born good at business",
     "Believing you already know everything you'll need",
     "People with a growth mindset keep learning, so they keep getting better."),
    ("You're tired halfway through a big job for a customer. What keeps you going?",
     "Remember why it matters, take a short break and finish strong",
     "Stop for the day and finish the rest whenever you feel like it",
     "Rush through the rest so you can be done sooner",
     "Short breaks restore energy. Finishing well is what earns customers' trust."),
    ("Someone laughs at your idea for a bike-washing business. What should you do?",
     "Listen for any useful points, then keep working on your plan",
     "Drop the idea, since others probably think the same thing and will laugh at it too",
     "Laugh at their ideas, so they know how it feels",
     "Many great businesses were doubted at first. Take good advice and ignore the rest."),
    ("You made a mistake that cost the shop $50. How should you handle it?",
     "Own it, learn the lesson, and move forward with a fix",
     "Stop trying new things so it can never happen again",
     "Pretend it didn't matter, since $50 is not a lot",
     "Mistakes are part of learning. Gritty people own them, learn and keep going."),
    ("Your stand had three slow weekends in a row. What's a smart, gritty step?",
     "Try one change, like a new spot, and track if sales go up",
     "Close the stand for good, since three weekends proves it won't work",
     "Keep everything the same and wait for business to pick up",
     "Grit isn't doing the same thing forever. It's sticking with the goal and testing new ways."),
    ("What's the difference between grit and being stubborn?",
     "Grit keeps the goal but changes the plan when needed",
     "There's no difference; both mean never giving up",
     "Grit means never changing anything you're doing",
     "Smart persistence means staying focused on the goal while learning better ways to reach it."),
    ("You keep making errors on the shop's cash register. What helps?",
     "Practice during quiet times and ask a coworker for tips",
     "Stay away from the register so you don't make more errors",
     "Go faster, since speed will fix the mistakes over time",
     "Skills grow with practice and help. Quiet times are a great chance to build them."),
    ("A rival shop got more customers than yours this month. What's the gritty response?",
     "Learn what customers want and keep improving your shop",
     "Decide you'll never catch up, since they're already ahead",
     "Wait for next month, since this one is already lost",
     "One bad month isn't the end. Steady improvement wins over time."),
    ("You planned to read one business book a month, but missed a month. What now?",
     "Start again this month; one miss doesn't erase your progress",
     "Quit the goal, since the streak is broken and you can't fix it",
     "Tell people you read it anyway so you don't look bad",
     "Everyone slips sometimes. Gritty people get back on track instead of quitting."),
    ("What do many successful business owners have in common?",
     "They kept trying after failing and learned something each time",
     "They were so talented that they hardly ever failed at anything",
     "They got lucky with their very first business idea",
     "Most successful owners failed often. What made them different was that they kept going."),
    ("A customer gave your shop a bad online review. How do you bounce back?",
     "Reply politely, fix the problem, and keep doing great work",
     "Delete your shop's page so nobody can see the review",
     "Reply and explain why the customer is wrong about it",
     "A calm reply and a real fix show everyone you care, and great work earns better reviews."),
    ("You're nervous to call a possible new customer. What builds courage?",
     "Practice what you'll say, then make the call anyway",
     "Wait until the nervous feeling goes away before calling",
     "Send a text instead, so you never have to call anyone",
     "Courage isn't having no fear. It's preparing and acting even when you're nervous."),
    ("A storm floods your family's shop and it must close for a week. What does a gritty owner do?",
     "Stay calm, make a cleanup plan and tell customers when you'll reopen",
     "Give up and close the shop for good, since floods can happen again",
     "Stay quiet until it's all fixed, so customers don't worry",
     "Hard surprises happen. A calm plan and clear updates help the business come back strong."),
    ("How long does it often take a new business to make a profit?",
     "Often months or years, so patience and planning matter",
     "Within the first few weeks, if the business idea is a good one",
     "Never, so there's no point in starting one",
     "Many new businesses take a while to earn a profit. Owners who plan for that can last."),
    ("You didn't pass your karate belt test. What's the best plan?",
     "Ask your teacher what to practice and try again next time",
     "Quit karate and try a different sport that's easier for you and feels more fun",
     "Retake the test tomorrow without changing anything",
     "Asking for feedback turns a setback into a plan. That's how champions and owners grow."),
    ("Your coach says, \"Done is better than perfect.\" What does that mean for a project?",
     "Finish and share it, then improve it, instead of waiting forever",
     "Quality doesn't matter, so finish as fast as you can",
     "Keep fixing it forever, and share it only when it's flawless",
     "Finishing lets you get real feedback. You can keep improving after it's out there."),
    ("What helps you stick with a hard goal for a long time?",
     "Tracking small wins so you can see your progress",
     "Only thinking about how far you still have to go",
     "Switching to a new, more exciting goal every week",
     "Seeing small wins adds up and gives you energy to keep going."),
]

RESPECT_MORE = [
    ("You have a meeting with a bank about a loan for the family shop. How should you dress?",
     "Neat, clean clothes that fit the meeting, like a collared shirt",
     "Your comfiest sweatpants and hoodie, so you look relaxed, calm and easygoing",
     "A bright, wild outfit, so they'll be sure to remember you",
     "Dressing for the situation shows you take the meeting and the people seriously."),
    ("Why does being on time earn respect?",
     "It shows you value other people's time",
     "It doesn't matter much once you're the owner",
     "It means you get the best seat in the room",
     "When you're on time, people see you as reliable and respectful."),
    ("You were wrong in a disagreement with a worker. What earns respect?",
     "Say, \"You were right, and I was wrong. Thank you.\"",
     "Never admit it, since the boss should always look right",
     "Quickly change the subject so nobody feels awkward",
     "Admitting mistakes takes confidence. People respect leaders who are honest about them."),
    ("A worker shares an idea with you. How do you show respect?",
     "Listen fully, ask questions and thank them",
     "Jump in with your own idea to show you were thinking too",
     "Listen while you check your phone, since you can do both",
     "Listening carefully makes people feel valued, and you might hear a great idea."),
    ("How should you stand when speaking to a group?",
     "Stand tall, shoulders back, hands relaxed, looking at people",
     "Lean on the wall with your hands in your pockets to look cool",
     "Face the screen the whole time so you don't lose your place",
     "Good posture and eye contact help you look and feel confident."),
    ("What does humility look like in a leader?",
     "Knowing you can learn from anyone, even the newest worker",
     "Making sure everyone knows you're the smartest one there",
     "Never speaking up or sharing your own ideas",
     "Humble leaders stay curious and open, and that makes people respect them more."),
    ("Your team just did a great job on a big order. Who should get the credit?",
     "The team, thanked by name in front of everyone",
     "You, since the boss is responsible for everything",
     "Nobody, so nobody gets a big head about it",
     "Leaders who give credit freely earn loyalty and respect."),
    ("You get bad news in front of your team. What shows strength?",
     "Take a breath, stay calm, and make a plan together",
     "Show how upset you are, so they know it's serious",
     "Find out whose fault it is before anything else",
     "A calm leader helps everyone stay calm and focus on solutions."),
    ("A visitor is rude to your cleaning staff. What does a respected leader do?",
     "Step in politely and make clear everyone here is treated with respect",
     "Laugh along, since keeping the visitor happy is good for business",
     "Stay out of it, since the staff can handle it themselves",
     "Standing up for your team, calmly and firmly, earns deep respect."),
    ("You can't keep a promise you made to your team. What keeps their respect?",
     "Tell them early, explain why and say what you'll do instead",
     "Wait quietly and hope everyone forgets you ever promised it",
     "Say you never really promised, you just said maybe",
     "Being honest about a broken promise keeps trust. Hiding it destroys it."),
    ("A customer asks a question during a busy rush. How do you respond?",
     "Look at them, smile and answer patiently",
     "Answer quickly without looking up, to save time",
     "Sigh so they know you're busy, then answer",
     "Patience and eye contact show respect, even when you're busy."),
    ("Why should a leader follow the same rules as everyone else?",
     "People respect leaders who don't act above the rules",
     "They shouldn't; leaders make rules, they don't follow them",
     "So they can catch other people breaking them",
     "When leaders follow the rules too, the team sees the rules are fair."),
    ("What's the best way to talk to a worker who made a mistake?",
     "Calmly and privately, focusing on how to fix it",
     "Right away, in front of customers, so they learn fast",
     "With a joke about it, so they feel silly and remember",
     "Correcting people privately and calmly keeps their dignity and helps them improve."),
    ("Someone asks you a business question you can't answer. What shows confidence?",
     "Say, \"I'm not sure, but I'll find out,\" and then follow up",
     "Give your best guess confidently, so you look like you know",
     "Change the topic so they don't notice you don't know",
     "Confident people don't need to know everything. They're honest and follow through."),
    ("You go to a customer's home to fix their bike. What shows respect?",
     "Arrive on time, wipe your feet, and clean up when you're done",
     "Leave a little mess, since they'll clean the floor anyway",
     "Show up whenever you're ready, since they said they'll be home all day anyway",
     "Respecting someone's time and home makes them trust you and call you again."),
    ("A worker tells you about a personal problem. Why does keeping it private earn respect?",
     "It shows you can be trusted with important things",
     "It doesn't; leaders should share everything with the team",
     "It doesn't; a little gossip makes a team feel closer",
     "People respect leaders they can trust. Keeping private things private shows you care."),
    ("Is it better for a leader to be feared or trusted?",
     "Trusted, because people work hard for leaders they trust",
     "Feared, because fear makes people follow the rules",
     "Feared, because nobody will ever argue with you",
     "Fear makes people hide problems. Trust makes them bring problems to you so you can fix them."),
    ("How should you speak to an adult supplier in a business meeting?",
     "Politely, clearly and confidently, like a fellow professional",
     "Quietly, letting them do all the talking since they're older",
     "Loudly and bossy, so they know you're the one in charge",
     "Speaking clearly and politely shows you're serious, no matter your age."),
    ("Your phone rings while a customer is talking to you. What should you do?",
     "Let it ring and finish helping the customer first",
     "Answer it quickly, since it could be an important order",
     "Hold up a finger and take the call for a few minutes",
     "The person in front of you deserves your full attention."),
    ("What does it mean that respect is earned, not demanded?",
     "People respect you because of how you act, not because you say so",
     "You can get respect by being the loudest one in the room",
     "Only bosses and owners deserve respect at work",
     "Respect grows from honesty, fairness and calm. Demanding it usually backfires."),
]

HIRING_MORE = [
    ("What is a job description?",
     "A written list of a job's tasks, skills, hours and pay",
     "A secret note about the kind of person you hope to hire",
     "A worker's diary of everything they did each day",
     "A clear job description helps the right people apply and know what's expected."),
    ("You're writing a job post for a bakery helper. What should it include?",
     "Clear tasks, hours, pay and the skills needed",
     "Just \"Help wanted\" so lots of people will apply",
     "A long story about the bakery's history and its owners",
     "Applicants need to know what the job is and what it pays to decide if it's right for them."),
    ("Why do owners check references before hiring?",
     "To hear from past bosses how the person really worked",
     "To find out about the person's family and home life",
     "To skip the interview, since references say enough",
     "References help you check that what someone says about their work is true."),
    ("Your best friend wants a job, but another applicant has better skills. What's fair?",
     "Choose the best person for the job using the same fair process",
     "Hire your friend, since you already trust them and get along well",
     "Hire both, and figure out how to pay them later",
     "Fair hiring is good for the business and everyone who applies, including your friends."),
    ("Which interview question is fair to ask?",
     "Tell me about a time you solved a problem at work.",
     "How old are you, and are you married or single right now?",
     "Are you planning to have kids in the next few years?",
     "Ask about skills and experience for the job. Personal questions are unfair and often illegal."),
    ("How should a new worker learn the job?",
     "Step-by-step training, practice and a buddy for questions",
     "Watch one training video, then start working on their own",
     "Jump right in, since people learn best from their mistakes",
     "Good training helps new people succeed faster and feel welcome."),
    ("Your shop is only extra busy in December. What kind of help makes sense?",
     "Hire seasonal or part-time help for December",
     "Hire five full-time workers to stay ready all year",
     "Ask your current team to work extra-long hours all month",
     "Matching help to the busy season keeps costs down and your team healthy."),
    ("Before an interview, what should the owner do?",
     "Read the applicant's resume and prepare fair questions",
     "Skip preparing, since you'll know the right person when you see them",
     "Decide who you'll hire before meeting anyone",
     "Preparing helps you ask good questions and treat every applicant fairly."),
    ("During an interview, who should do most of the talking?",
     "The applicant, while you listen carefully",
     "You, so they learn everything about your business",
     "Nobody; sit quietly and watch how they act",
     "You learn the most about an applicant by asking good questions and listening."),
    ("A great applicant asks for more pay than you can afford. What should you do?",
     "Be honest about your budget and see if a fair deal is possible",
     "Promise the pay they asked for now, and figure out how to afford it later on",
     "Tell them they should feel lucky to get any offer at all",
     "Honest talk about pay starts a good working relationship. False promises end badly."),
    ("What is a probation period for a new worker?",
     "The first weeks, when both sides see if the job is a good fit",
     "A trial time when new workers work for free to prove themselves",
     "A punishment period that every new worker must go through",
     "A probation period gives time to learn and check the fit. New workers must still be paid."),
    ("How can you make hiring fair for everyone?",
     "Use the same job-related questions and score answers the same way",
     "Pick the people who seem most like you, so the team gets along",
     "Only hire people you already know, so there are no surprises",
     "Using the same questions and scoring for everyone helps you choose on skills, not bias."),
    ("Your team is overworked, but sales are dropping. Should you hire right now?",
     "Probably not yet; first look at the sales and see if the work lasts",
     "Yes, hire three people today, since the team is tired and needs help right now",
     "Yes, and promise them raises to make the jobs more exciting",
     "Hiring is a long-term cost. Make sure the work and money will be there first."),
    ("What should a new worker get on their very first day?",
     "A warm welcome, a tour, the safety rules and their schedule",
     "A big pile of work, so they can show what they can do",
     "A long rule book to read alone at a desk all day",
     "A good first day helps new workers feel safe, welcome and ready to learn."),
    ("A resume says the applicant ran a store, but their reference says they didn't. What now?",
     "Politely ask the applicant to explain before you decide",
     "Ignore it, since everybody stretches the truth a little",
     "Turn them down right away without saying why",
     "Get the facts fairly and privately. There may be a mix-up, or it may be a real problem."),
    ("Why is it smart to write down how each job is done?",
     "New workers learn faster and do it the same right way",
     "So new workers never need to ask anyone a question",
     "It isn't; everyone should do each job their own way",
     "Written steps make training easier and help everyone do quality work."),
    ("What does \"hire for attitude, train for skill\" mean?",
     "Pick people with a great attitude and teach them the skills",
     "Only hire people who already know how to do everything",
     "Hire the fastest worker, even if their attitude is poor",
     "Many skills can be taught, but a good attitude is hard to teach."),
    ("Should you tell applicants who didn't get the job?",
     "Yes, with a short, kind message thanking them for applying",
     "No, they'll figure it out when nobody calls them back",
     "Yes, and list every weakness you noticed about them",
     "A kind reply respects people's time and protects your business's reputation."),
    ("Your family business wants to hire its first worker. What should you learn about first?",
     "The rules for pay, taxes and safety for employees",
     "Which uniform color will look the most professional",
     "How to pay workers in cash so there's less paperwork",
     "Hiring comes with legal rules. Learning them first keeps the business fair and out of trouble."),
    ("A new hire is nervous and slow in their first week. What's the best approach?",
     "Be patient, encourage them and check in often",
     "Let them go after one slow week, before they cost more money",
     "Compare them out loud to your fastest worker to motivate them",
     "Most people speed up as they learn. Patience and support help them get there."),
]

TOUGH_CALLS_MORE = [
    ("A worker's quality has slipped lately. What should the first talk include?",
     "Clear examples, what good work looks like and how you'll help",
     "A few hints, so they figure out the problem on their own",
     "A firm warning that they'll be fired if it ever happens again",
     "People can only fix what they understand. Clear examples and support give them a fair chance."),
    ("What are clear expectations at work?",
     "Telling people exactly what good work looks like and by when",
     "Hoping workers can tell what you want without being told",
     "Telling people the rules once on their first day, then changing them whenever you need to",
     "Clear expectations let people succeed, and make it fair if you must address a problem later."),
    ("A worker has just received a warning. What should happen next?",
     "Agree on goals and a time to check progress together",
     "Never mention it again, so the worker doesn't feel bad",
     "Quietly watch them every day, waiting to catch the next mistake",
     "A warning should come with a path to improve and a fair check-in."),
    ("What should a good written warning include?",
     "The problem, the date, what must change and the next steps",
     "Strong words about the worker's attitude and personality",
     "Just the word \"Warning,\" so it's short, simple and easy to read",
     "Clear, factual records keep things fair and help the worker know exactly what to fix."),
    ("A worker breaks a serious safety rule that could hurt someone. What's right?",
     "Stop the danger now, then follow company rules for serious problems",
     "Let it go this time, since nobody actually got hurt and it was quick",
     "Make a joke about it and hope it doesn't happen again",
     "Safety comes first. Serious risks must be dealt with right away and by the rules."),
    ("Workers are gossiping about why a coworker was let go. What should the owner do?",
     "Keep the details private and speak about the person with respect",
     "Share every detail with the team so the rumors stop right away",
     "Make up a simple story so people stop asking questions",
     "Private matters stay private. Respect for the person who left shows the team how you'll treat them."),
    ("A manager wants to let someone go because they're angry with them today. What's wise?",
     "Wait, calm down, and look at the facts and the fair process",
     "Do it right away today, while the problem and your feelings about it are still fresh",
     "Send a text tonight telling them not to bother coming back",
     "Big decisions about people should be made calmly, with facts and a fair process."),
    ("Is it okay to let someone go because of their age or skin color?",
     "No, that's unfair discrimination and it's against the law",
     "Yes, if the owner thinks it's better for the business",
     "Only if the owner is very careful that nobody ever finds out",
     "Decisions must be based on job performance and conduct, never on who someone is."),
    ("A worker is improving after a warning, but isn't perfect yet. What's fair?",
     "Notice the progress and keep coaching",
     "Let them go, since the warning said the work must be perfect",
     "Ignore the progress and give another warning to be safe",
     "Recognizing real effort encourages more of it. Improvement takes time."),
    ("What's the purpose of an improvement plan for a struggling worker?",
     "To give a clear, fair chance to improve with goals and support",
     "To make a worker want to quit, so you don't have to decide",
     "To show the whole team what happens when people slip up",
     "A good plan sets clear goals, offers help and gives a real chance to succeed."),
    ("If you must let someone go, what should you tell them?",
     "The honest reason, said kindly and clearly, and what happens next",
     "As little as possible, so the talk stays short and feels less awkward for both of you",
     "A made-up, nicer reason so their feelings don't get hurt",
     "People deserve honesty and respect, even when the news is hard."),
    ("A business must cut costs and can't keep everyone. What's the fair approach?",
     "Look for other savings first, then decide fairly and help those who leave",
     "Let go of the people you get along with the least, since that choice is quicker and easier",
     "Quietly cut everyone's pay without telling them, so nobody leaves",
     "Fair, open decisions and helping people who leave protect trust with the whole team."),
    ("Where should you have a hard talk with a worker?",
     "In a private room where others can't hear",
     "On the sales floor, so it feels normal and casual",
     "In the team group chat, so everything is in writing",
     "Privacy protects the person's dignity and lets them speak honestly."),
    ("A worker wrote extra hours on their timesheet that they didn't work. What's the right response?",
     "Take it seriously, talk privately with the facts, follow the rules",
     "Let it slide this time, since it's only a few hours of pay",
     "Post the timesheet in the break room so others learn a lesson",
     "Honesty problems can't be ignored, but they must still be handled privately and fairly."),
    ("Who should an owner talk to before letting someone go?",
     "An expert, like a lawyer or HR advisor, to do it legally",
     "Your favorite customers, to see which workers they like",
     "Nobody, since owners can make any choice they want",
     "Laws protect workers. Expert advice helps make sure the process is fair and legal."),
    ("After someone leaves the company, how should the team be told?",
     "Briefly and kindly, with no private details, and who covers the work",
     "With a full list of what the person did wrong, so others learn",
     "Not at all, since it's private and people will figure it out",
     "The team needs to know how work will be covered, not private details about the person."),
    ("A worker is struggling because of a family problem at home. What's a kind first step?",
     "Ask privately if they need support, like a schedule change",
     "Tell them to leave home problems at home or find a new job",
     "Tell the team, so everyone can be extra nice to them",
     "Good people sometimes go through hard times. Support often helps them get back on track."),
    ("A worker is still rude to customers after two talks about it. What's a fair next step?",
     "A final written warning that says what will happen if it continues",
     "A third friendly chat, just like the first two, with no record",
     "Let them go today without explaining, since they've had talks",
     "A clear final warning is fair: the worker knows exactly what's at stake and can still change."),
    ("Why should you treat a worker who is leaving with kindness?",
     "It's the right thing, and your team sees how you treat people",
     "It isn't needed, since they won't work for you anymore",
     "So they'll feel they owe you and agree to do some free work for you later",
     "How you treat people at hard moments shows your character to everyone watching."),
    ("What does it mean to be consistent with rules at work?",
     "Apply the same rules to every worker, even your friends",
     "Be extra strict with new workers, and easier on old friends",
     "Pick the consequence depending on how your day is going",
     "Using the same rules for everyone is fair and helps the team trust your decisions."),
]

CUSTOMERS_MORE = [
    ("A customer walks into your bike shop. What should happen first?",
     "Greet them with a smile within a few seconds",
     "Finish your task first, then wait for them to speak",
     "Follow them closely around the shop so they can ask anything",
     "A quick, friendly greeting makes customers feel noticed and welcome."),
    ("A customer wants a product you don't have. What's most helpful?",
     "Offer to order it or suggest something similar",
     "Say \"Sorry, we don't have it\" and go back to work",
     "Say you'll get it, even if you're not sure you can",
     "Helping customers find what they need, even when you don't have it, wins their loyalty."),
    ("What is a loyalty program?",
     "A reward for coming back, like a free cookie after ten visits",
     "A rule that regular customers can't shop at other stores",
     "An extra fee customers pay to be called regulars",
     "Rewarding repeat customers gives them one more reason to keep choosing you."),
    ("A customer is angry and raising their voice. What do you do?",
     "Stay calm, listen, and say, \"I understand. Let's fix this.\"",
     "Raise your voice too, so they can hear you over their yelling",
     "Walk away until they calm down on their own",
     "Staying calm and listening helps an upset customer calm down too."),
    ("How can you remember a regular customer's favorites?",
     "Pay attention and keep simple notes, like \"Mr. Diaz likes rye\"",
     "Don't bother, since every customer wants the same thing",
     "Ask them the same questions every visit, just to be sure",
     "Remembering what people like makes them feel special and keeps them coming back."),
    ("What makes a store's return policy good for customers?",
     "It's clear, fair and easy to find",
     "It's very strict, so nobody can take advantage of it",
     "It changes depending on who is working that day",
     "A clear, fair policy builds trust and avoids arguments."),
    ("A customer leaves a nice online review. What should you do?",
     "Thank them with a short, friendly reply",
     "Ignore it, since only bad reviews need an answer",
     "Offer them a prize to write even more reviews",
     "Thanking people for kind words shows you notice and care. Reviews should be honest, not paid for."),
    ("Your bakery ran out of a cake a customer pre-ordered. What's best?",
     "Call them early, apologize, and offer a good swap or a refund",
     "Wait until they arrive, so you can explain it in person",
     "Hand them a different cake and hope they don't notice",
     "Early, honest news gives customers choices and keeps their trust."),
    ("What is customer feedback?",
     "What customers tell you about what they like and don't like",
     "Only the nice things customers say about your business",
     "A fee customers pay for extra-good service",
     "Feedback is a gift. It shows you exactly what to keep and what to fix."),
    ("Why is it smart to solve a customer's problem quickly?",
     "A fast fix turns a bad moment into trust",
     "So you can stop thinking about that customer sooner",
     "It isn't; a slow fix looks more careful and thorough",
     "Customers remember how fast and well you fixed things, often more than the problem itself."),
    ("A customer asks your advice on a bike, and the priciest one is more than they need. What do you do?",
     "Recommend the bike that fits their needs and budget",
     "Recommend the priciest bike, since it's the best one",
     "Tell them all the bikes are basically the same",
     "Honest advice builds trust, and trusted shops get loyal customers for years."),
    ("How can a small shop make customers feel special?",
     "Use their names, remember what they like and say thank you",
     "Give big discounts, but only to brand-new customers",
     "Treat everyone exactly the same, like strangers, to be fair",
     "Personal touches are something small shops can do better than anyone."),
    ("A customer's order arrived broken. What should you say?",
     "I'm so sorry. I'll send a new one today at no cost to you.",
     "It was fine when it left our shop, so it's the mail's fault.",
     "You must have dropped it, but we can sell you a new one.",
     "Taking care of the customer first, without blame, keeps them happy and loyal."),
    ("What is customer lifetime value?",
     "All the money a customer may spend with you over many years",
     "The price of the one item a customer buys today",
     "How many years old a customer is when they first shop",
     "A loyal customer is worth far more than one sale, so it pays to treat them well."),
    ("Your lemonade stand has a long line on a hot day. How do you keep customers happy?",
     "Thank them for waiting and work quickly but carefully",
     "Work as fast as possible, even if some drinks spill",
     "Take breaks to chat with friends so you don't get tired",
     "People are patient when they feel noticed and see you working hard for them."),
    ("Should a business keep customer information private?",
     "Yes, protect it and use it only in ways customers agreed to",
     "No, it's fine to sell it to other businesses that ask",
     "Only if a customer asks you two times to keep it private",
     "Customers trust you with their information. Protecting it is the right thing and often the law."),
    ("A customer suggests a new cupcake flavor. What's a smart response?",
     "Thank them, write it down and think about trying it",
     "Tell them politely that your flavors are already perfect",
     "Promise to make it next week, even if you can't",
     "Customers often have great ideas, and they love seeing their ideas become real."),
    ("A regular customer stopped coming. How can you try to win them back?",
     "Reach out kindly, ask what went wrong and fix it",
     "Send a message telling them they made a big mistake leaving",
     "Let them go, since there are always new customers",
     "A friendly check-in can bring a customer back and teach you what to improve."),
    ("A customer can't decide between two items. How do you help?",
     "Ask how they'll use it and explain the difference simply",
     "Tell them to take their time and come back another day",
     "Pick the pricier one for them, since it's probably better",
     "Helping customers make a good choice makes them happy with what they buy."),
    ("Why should every worker care about customers, not just the owner?",
     "Every worker shapes what customers think of the business",
     "They shouldn't; keeping customers happy is the owner's job",
     "Only salespeople need to care, since they talk to customers",
     "One rude moment from anyone can lose a customer, and one kind moment can win one."),
]

COMPETE_MORE = [
    ("A new pizza shop opens near your family's pizza shop. What's a fair first step?",
     "Ask your customers what they love and make it even better",
     "Post a few bad reviews about the new shop online, just to warn people about them",
     "Ask the landlord to kick them out before they get busy",
     "The fair way to win is to give customers more reasons to choose you."),
    ("A rival delivers in 45 minutes. How can you compete on speed?",
     "Improve your steps so you deliver faster, but safely",
     "Tell drivers to drive faster, even if it means speeding",
     "Say you're faster in ads, even before you really are",
     "Improving how you work is a fair, lasting edge. Unsafe or false shortcuts are not."),
    ("A worker from a rival shop joins your team. What's the right rule?",
     "Use their skills, but never ask for the rival's secrets",
     "Ask them to bring the rival's customer list with them",
     "Have them teach you the rival's secret recipe",
     "Hiring skilled people is fair. Using a rival's secrets is wrong and can be illegal."),
    ("What is a unique selling point?",
     "What makes your business different and better",
     "The cheapest item you sell, which pulls customers in",
     "A secret sale that you only offer to your friends",
     "Knowing what makes you special helps customers see why they should choose you."),
    ("A competitor came up with a clever idea for a kids' menu. What's fair to do?",
     "Learn from it and create your own, better version",
     "Copy their menu's name and design exactly, since ideas are free",
     "Sneak into their kitchen to see how they do it",
     "Ideas inspire each other. Making your own better version is fair, but copying a design is not."),
    ("A rival advertises that they're the cheapest in town. How should your ads respond?",
     "Share true facts about your quality and service",
     "Say their food makes people sick, to scare customers away",
     "Hint that their owner can't be trusted",
     "Truthful ads about your strengths win customers. Lies about rivals are wrong and can be illegal."),
    ("A rival shop is having a hard time. How should you act?",
     "Keep serving your customers well and be gracious",
     "Spread rumors that they're closing, to win their customers",
     "Make fun of them online, since it's just a joke",
     "Gracious winners earn respect from customers and the whole town."),
    ("A rival suggests you split the town so you never compete for the same customers. What do you say?",
     "No, dividing up customers with a rival is against the law",
     "Yes, it's a smart way to keep both shops busy and happy",
     "Yes, as long as you both keep it a secret",
     "Rivals agreeing not to compete hurts customers and breaks competition laws."),
    ("How can a small bakery stand out from a big grocery store?",
     "Fresh, special treats and friendly, personal service",
     "Match their prices on every single item you sell",
     "Copy their store layout and signs exactly",
     "Small shops win by doing what big stores can't, like freshness and personal care."),
    ("How can customer service help you beat rivals?",
     "Treat customers so well that they prefer you over others",
     "Have lots of strict rules, so every customer behaves well",
     "Charge extra for friendly service, since it costs more",
     "Great service is hard to copy and keeps customers coming back."),
    ("Your rival opens on Sundays and you don't. How should you decide what to do?",
     "Ask customers if they want Sunday hours and check if it pays",
     "Open seven days a week right away, so you never fall behind",
     "Ask the town to make them close on Sundays too",
     "Decide with customer input and your numbers, not just because a rival did it."),
    ("Is it okay to pretend to be a customer to get a rival's secret plans?",
     "No, tricking people to get secrets is dishonest and can be illegal",
     "Yes, as long as nobody finds out about it and no one actually gets hurt by it",
     "Yes, because lots of companies probably do it",
     "Winning with tricks isn't winning. Honest competition protects your reputation."),
    ("A rival is copying your product. What's the best long-term defense?",
     "Keep improving to stay ahead, and protect your brand legally",
     "Copy one of their best products, so it's fair and even",
     "Sneak into their shop at night to check their plans",
     "Steady improvement keeps you ahead, and trademarks and patents protect what's yours."),
    ("Your rival just released a cool new feature. What's a strong response?",
     "Think about what customers need next and build something great",
     "Sue them right away, even though they did nothing wrong",
     "Tell customers the new feature is dangerous, even though you know it really isn't",
     "Innovation is a race to serve customers better. Answer with your own great ideas."),
    ("How can a small shop compete with a rival's much bigger ad budget?",
     "Earn word of mouth with great service and happy customers",
     "Borrow money you can't pay back to buy more ads than them",
     "Cover their posters around town with your own flyers",
     "Happy customers telling friends is powerful and free."),
    ("What is fair competition?",
     "Businesses winning customers honestly with better offers",
     "Businesses doing whatever it takes to win, no matter what",
     "Businesses agreeing to share customers so nobody loses",
     "Fair competition pushes everyone to improve, which is great for customers."),
    ("A customer tells you a rival overcharged them. What should you say?",
     "I'm sorry to hear that. Here's how our pricing works.",
     "Yes, they cheat everybody, so you should only shop here!",
     "You should post a really bad review about them online.",
     "Stay positive and focus on your own business. Bad-mouthing rivals makes you look bad."),
    ("Your bike shop is small. Which focus could help you win?",
     "Become the go-to shop for kids' bikes and fast repairs",
     "Sell every product a giant store sells, but in less space",
     "Change what you focus on every week to try everything",
     "A clear specialty helps customers remember you and choose you."),
    ("Why should you know who your competitors are?",
     "So you understand customers' choices and can serve them better",
     "So you can find ways to get a look at their private files",
     "So you can copy everything they do, exactly the same way",
     "Knowing the market helps you find your edge. Learning from public information is fair."),
    ("Two rival shops secretly agree to raise prices on the same day. What is that?",
     "Illegal price fixing, which hurts customers",
     "A smart team-up that helps both shops earn more",
     "Normal, friendly business between neighbors",
     "Each business must set its own prices. Secret price deals are illegal and unfair to customers."),
    ("How does quality help you win against rivals?",
     "People trust products that last and tell their friends",
     "It doesn't; customers only care about the lowest price",
     "It only matters for very expensive things like cars",
     "High quality earns repeat customers and great word of mouth."),
]

MOVES_MORE = [
    ("What is a win-win deal?",
     "A deal where both sides get something they want",
     "A deal where you win and the other side loses",
     "A deal where you win twice, by getting the best price",
     "Win-win deals last, because both sides are happy to keep working together."),
    ("A supplier offers 10% off if you buy 500 cups instead of 100. What should you check first?",
     "If you can store and use 500 cups before they go to waste",
     "Nothing, since buying more at a discount always saves money",
     "Whether your friends like the cup design",
     "A discount only helps if you'll really use what you buy. Waste can cost more than you save."),
    ("A deal keeps getting worse for you as you negotiate. What's a pro move?",
     "Politely walk away and look for a better option",
     "Accept anyway, since you've already spent so much time",
     "Keep going, since stopping now would waste the whole day",
     "Being willing to walk away protects you from bad deals."),
    ("Before you negotiate, what should you know?",
     "Your numbers, your goal and the lowest deal you'll accept",
     "Nothing; it's better to make it up as you go",
     "Only what the other side wants, so you can give it to them",
     "Preparation is the secret of good negotiators. Know your limit before you start."),
    ("Another shop wants to partner with yours. What should you do before saying yes?",
     "Check their reputation and write the deal down clearly",
     "Shake hands and trust it works out, since writing it down seems rude",
     "Say yes fast, before they change their mind",
     "Good partners are trustworthy, and clear written deals prevent fights later."),
    ("When is a good time to launch a new ice cream flavor?",
     "When it's warm and customers want ice cream",
     "In the coldest week, when no other shop is selling any",
     "Any random day, since good flavors sell themselves",
     "Timing matters. Launch when customers are most ready to buy."),
    ("Why should an owner know the business's numbers?",
     "To make smart choices about prices, spending and growth",
     "They don't need to; that's what accountants are for",
     "So they can brag to their friends about how much money the shop is making",
     "Owners who know their numbers can spot problems early and make better decisions."),
    ("Your stand sells lemonade for $1, and each cup costs $0.40 to make. What's your profit per cup?",
     "$0.60",
     "$1.40",
     "$0.40",
     "Profit is price minus cost: $1.00 minus $0.40 equals $0.60."),
    ("A customer asks for a lower price. What's a smart way to say yes?",
     "Offer a small discount if they buy more or pay early",
     "Cut the price in half, so they're sure to come back",
     "Refuse to talk about price at all, since it's set",
     "Trading a discount for something you value, like a bigger order, keeps the deal fair for you."),
    ("What does it mean to plan for the busy season?",
     "Get supplies and helpers ready before the rush",
     "Wait until it gets busy, then figure out what you need",
     "Order lots of supplies after the busy season ends",
     "Planning ahead lets you serve more customers and avoid running out."),
    ("Someone offers to buy your family's shop today for cash. What's the smart step?",
     "Take time, get expert advice and compare your options",
     "Sign today, since cash offers don't come around often",
     "Say no right away without hearing the offer",
     "Big decisions deserve time and good advice. Pressure to rush is a warning sign."),
    ("What's a good way to test a new idea without big risk?",
     "Try it small first, like selling a new treat for one weekend",
     "Spend all your savings on it at once to show you believe in it",
     "Wait years until you're sure it will work",
     "Small tests let you learn what works before you bet a lot of money."),
    ("You and your business partner disagree on a plan. What's a pro move?",
     "Share your reasons, listen, and look for a plan you both like",
     "Do your plan quietly, since you know it's the right one",
     "End the partnership right away, so you can finally run things your own way",
     "Partners who listen and find common ground make stronger decisions."),
    ("Why should business agreements be put in writing?",
     "So everyone remembers the same deal and avoids fights later",
     "So you can quietly change the deal later if you want",
     "It isn't needed, since a handshake between friends is enough",
     "Memories fade and differ. A written deal keeps everyone on the same page."),
    ("Two suppliers sell flour. One is cheaper but is often late. What should you think about?",
     "The real cost of late flour, like lost sales, not just price",
     "Only the price, since cheaper flour always means more profit",
     "Which supplier has the nicer logo and website",
     "The cheapest option can cost more if it causes problems. Look at the whole picture."),
    ("What is a backup plan?",
     "A second plan ready in case the first one doesn't work",
     "A plan for how to give up if things get hard",
     "A copy of your first plan, saved in a safe place",
     "Smart owners prepare for surprises so one problem doesn't stop the business."),
    ("A friend asks to borrow $200 from the business's cash. What's the pro move?",
     "Keep business cash for business, and talk to your partner first",
     "Lend it from the cash drawer, since you'll pay it back soon",
     "Lend it, but don't write it down, since it's just a friend",
     "Business money pays bills and workers. Mixing it with personal favors causes trouble."),
    ("When is a good time to ask a supplier for a discount?",
     "When you're a loyal customer or buying a large amount",
     "Every single time, while threatening to leave",
     "Never, since prices are set and can't change",
     "Suppliers value loyal and large customers, which gives you a fair reason to ask."),
    ("Why do smart owners set goals for the year?",
     "Goals guide daily choices and show if you're on track",
     "Because goals look nice framed on the wall",
     "So they can share them once a year, then move on",
     "Clear goals help you decide what matters most and measure your progress."),
    ("In a negotiation, what does listening help you do?",
     "Learn what the other side really needs, so you can find a deal",
     "Nothing much, since whoever talks the most wins",
     "Find weak spots you can use to trick the other side",
     "When you understand what the other side needs, you can find a deal that works for both."),
    ("You want to open a second lemonade stand. What should you check first?",
     "That the first stand makes steady profit and you have help",
     "That your friends think a second stand would be really cool",
     "Nothing, since more stands always means more money",
     "Grow when your first business is strong. Expanding too early can sink both."),
]
