"""Academy question bank: the Growth unit."""

WORLDS = [
    {
        "key": "marketing",
        "title": "Get the Word Out",
        "tagline": "Marketing that people love",
        "icon": "megaphone",
        "cards": [
            ("Know your customer", "Marketing starts with knowing who you help: what they need, where they shop and what they care about. Ask good questions and really listen."),
            ("Pick a target audience", "Your target audience is the group most likely to buy. A bike shop might focus on families and riders instead of trying to reach everyone."),
            ("Ads and word of mouth", "Ads are messages you pay for, like flyers, signs or posts. Word of mouth is free: happy customers telling friends. Great service powers both."),
            ("Keep ads honest", "Only promise what your product really does. Honest ads build trust, and in many places false ads are against the law."),
            ("Measure and budget", "Set a marketing budget and track results. If a $50 ad brings 10 customers, each customer cost $5. Keep what works and drop what doesn't."),
        ],
        "questions": [
            # Level 1
            ("What is marketing?", "Telling people about your business and how it helps them", "Counting all the money in the cash register each night",
             "Fixing broken tools in the back room", "Marketing is how people learn about you and why to choose you. Without it, even a great product can go unnoticed.", 1),
            ("What is word of mouth?", "Customers telling friends about your business", "A loud radio ad that plays every single hour of the day",
             "A sign with big, bright letters", "When happy customers tell others, it is free and trusted. People often believe friends more than ads.", 1),
            ("What is a target audience?", "The group of people most likely to buy from you", "Every single person in the whole world",
             "The workers, cooks and cashiers at your business", "Focusing on the people who need you most helps you spend your time and money where it works best.", 1),
            ("You run a lemonade stand. Which is an example of advertising?", "A sign at the corner that says Cold Lemonade Ahead", "Squeezing lemons before you open the stand",
             "Counting your coins and bills at the end of a long day", "Advertising is a message that tells people about your product. A sign pointing the way brings thirsty walkers to you.", 1),
            ("Which ad for a bakery is honest?", "Fresh cookies, baked this morning", "Cookies that cure colds",
             "Cookies that never, ever go stale or crumble", "Only the first claim is true and can be checked. Made-up claims break trust and can break the law.", 1),
            ("What is the best way to get more word of mouth?", "Give customers a great experience worth sharing", "Ask customers to post fake reviews for you",
             "Tell every customer that your rivals are bad people", "People share good experiences. Great service creates real fans, while tricks and insults hurt your name.", 1),
            ("Where should a flyer for a dog-walking service go?", "On a park notice board where dog owners walk", "Inside a closet where nobody will see it",
             "On a stranger's car without asking first", "Put flyers where your customers already are, and only where you have permission to post them.", 1),
            ("What should a good flyer include?", "What you sell, the price and where to find you", "A long story about your favorite movie",
             "Tiny text that fills every inch of the page", "A flyer must quickly answer three things: what is it, what does it cost and how do I get it? Clear and simple wins.", 1),
            ("Why do businesses spend money on marketing?", "So more of the right people learn about them and buy", "Because every shop must buy ads by law",
             "To make the store look busy even when it is totally empty", "Marketing is an investment: you spend some money to bring in customers who buy more than it cost.", 1),
            ("Which question helps you get to know your customer?", "What are you hoping to find today?", "Why don't you have more money to spend?",
             "Can you tell me your home address?", "Asking about needs shows you care and teaches you what to offer. Never ask for private details you don't need.", 1),
            ("A bakery's sign says Open 7am to 3pm. Why is this good marketing?", "It tells customers clearly when they can come in", "It makes the bakery seem closed forever",
             "It hides the hours so people get curious and come to ask", "Clear, useful information makes it easy to visit. Confused customers often just go somewhere else.", 1),
            ("What is a slogan?", "A short, catchy phrase about your business", "A secret password that only the workers know",
             "A list of every price in the store", "A good slogan is easy to remember, like Fresh Bread, Friendly Faces. It helps people recall you.", 1),
            # Level 2
            ("An ad costs $50 and brings 10 customers. What did each customer cost?", "$5", "$10",
             "$500", "Divide the cost by the number of customers: $50 / 10 = $5. This is called the cost per customer.", 2),
            ("You run a bike shop. Who is the best target audience for kids' helmets?", "Parents of kids who ride bikes", "People who only travel by train",
             "Grown-ups who drive big trucks", "Parents usually buy helmets for their kids, so ads should reach families who ride.", 2),
            ("Why should you ask new customers how they heard about you?", "To learn which marketing works so you spend wisely", "To make them fill out long forms",
             "So you can stop doing any marketing at all, right away", "Their answers show which ads bring people in, so you keep the winners and drop the rest.", 2),
            ("What is a marketing budget?", "A plan for how much you will spend on marketing", "A list of customers who owe you money",
             "The price tag on your best product", "A budget stops you from overspending. You decide ahead of time how much to try, then track the results.", 2),
            ("A shop raises its prices, then puts up a sign saying 50% off. What is wrong?", "The sign tricks customers, which is dishonest", "Nothing, because the sign looks very nice",
             "The discount should have been 60% to look even better", "Raising prices to fake a discount misleads people. It breaks trust and is against the law in many places.", 2),
            ("Which is an example of a 'call to action' in an ad?", "Visit us this Saturday for a free taste!", "Our shop was painted blue last year.",
             "We have many shelves inside our store.", "A call to action tells people exactly what to do next. A clear next step turns interest into visits.", 2),
            ("Your bakery's best customers are office workers. When is a good time to advertise?", "Early morning, on their way to work", "Midnight, when offices are closed",
             "Only on holidays, when offices are shut", "Reach people when they can act. Office workers pass by and want breakfast in the morning.", 2),
            ("What is a customer survey?", "A short set of questions asking what customers think", "A map that shows where your store is",
             "A coupon that gives a free item to every single visitor", "Surveys help you learn what customers like and what to improve. Keep them short and don't ask for private details.", 2),
            ("A new customer says a friend sent them. What is the best thing to do?", "Thank them, and thank the friend next time", "Ignore it, since it doesn't matter",
             "Charge them more because a friend sent them", "Thanking people for sending friends shows you value them and encourages even more word of mouth.", 2),
            ("What is a promotion in marketing?", "A special offer, like a free cookie with any milk", "A sign that says the shop is closed for the whole week",
             "A rule that bans all discounts", "A promotion is a special deal that gives people a reason to try you now. It works best when it is clear and honest.", 2),
            ("Your marketing budget is $300 a month. You have spent $240. How much is left?", "$60", "$540",
             "$40", "$300 - $240 = $60. Tracking what you spend keeps you inside your budget.", 2),
            ("A $40 bike helmet is on sale for 10% off. How much does a buyer save?", "$4", "$10",
             "$36", "10% of $40 is $40 / 10 = $4. The buyer saves $4 and pays $36.", 2),
            ("What is a 'unique selling point'?", "Something special that makes your business different", "The one product you sell for the lowest price",
             "The place where you sell your old things", "A unique selling point answers the question 'Why pick you?' Maybe it is homemade recipes or the fastest repairs in town.", 2),
            ("Customers say your flyer is confusing. What should you do first?", "Ask what confused them, then make it simpler", "Print twice as many of the same flyer",
             "Blame customers for not reading carefully", "Customer feedback shows you what to fix. A clearer flyer helps more people understand and act.", 2),
            ("What makes a customer 'loyal'?", "They choose you again and again because they trust you", "They signed a paper promising never to shop elsewhere",
             "They came only once during a big sale", "Loyal customers come back by choice. You earn loyalty with good products and kind service.", 2),
            # Level 3
            ("You spent $200 on ads and got 40 new customers. Each spent $15. How much did they spend in all?", "$600", "$240",
             "$215", "40 x $15 = $600. That is more than the $200 ad cost, but remember you also pay for the products you sell.", 3),
            ("Ad A costs $100 and brings 20 customers. Ad B costs $60 and brings 6. Which is the better deal?", "Ad A, at $5 per customer", "Ad B, because it costs less",
             "Ad B, at $6 per customer", "Ad A: $100 / 20 = $5 per customer. Ad B: $60 / 6 = $10. Ad A costs less per customer even though its price is higher.", 3),
            ("You test two flyer designs, one week each. What is the fairest way to compare them?", "Hand out the same number in the same places", "Hand one out at a fair and one on a rainy day",
             "Pick the one you like and skip counting", "A fair test changes only one thing at a time. Then you know the design, not the weather, made the difference.", 3),
            ("A rival puts up an ad with false claims about your shop. What is the best response?", "Stay calm, share true facts and keep serving well", "Make an even meaner false ad about them right away",
             "Tear down all of their signs at night", "Answering lies with lies or damage makes you look bad and can break rules. Truth and great service protect your name.", 3),
            ("Why is trying to sell to 'everyone' often a weak plan?", "Your money and message get spread too thin", "Selling to lots of people is against the rules",
             "Everyone already knows about every shop", "With a clear target, you can pick the right words and places. A message meant for everyone often speaks to no one.", 3),
            ("A toy shop has a $500 marketing budget. Which plan is wisest?", "Try small ads, measure, then spend more on the best", "Spend all $500 on one ad before testing anything",
             "Spend nothing at all and just hope people find the shop", "Testing small first shows what works. Then you put more money behind the winners instead of guessing.", 3),
            ("Sales doubled the week you ran a radio ad, and the town also had a fair. What should you think?", "The ad may have helped, but the fair could be why", "The ad must be the only reason sales went up",
             "Ads never work, so it was surely the fair", "When two things happen at once, you can't be sure which caused the change. Ask customers how they heard about you.", 3),
            ("Why does keeping a customer often cost less than finding a new one?", "They already trust you, so less advertising is needed", "Returning customers always pay double",
             "New customers are never allowed to buy anything on sale", "Winning a new customer takes ads and effort. A happy returning customer already knows you, so a simple thank-you often works.", 3),
            ("A bakery deal: buy 2 muffins at $3 each, get 1 free. What does each muffin really cost?", "$2", "$3",
             "$1", "The buyer pays 2 x $3 = $6 for 3 muffins. $6 / 3 = $2 per muffin.", 3),
            ("Which ad claim needs proof before you can use it?", "Our shop has the lowest prices in town", "Come and visit our friendly shop on Main Street",
             "We are open on Saturdays", "Comparing yourself to others is a claim you must be able to prove. If you can't prove it, don't say it.", 3),
            ("A shop sells $1,000 a month and sets aside 5% for marketing. How much is that?", "$50", "$500",
             "$5", "5% of $1,000 is $1,000 x 0.05 = $50. Many businesses set their marketing money as a share of sales.", 3),
            ("Your ad brought 30 new customers, but almost none came back. What does this suggest?", "The ad worked, but something about the visit needs fixing", "The ad was a total failure and should be deleted",
             "Customers who come once are the only ones that matter", "Marketing can bring people in, but the product and service bring them back. Ask what would make them return.", 3),
        ],
        "facts": [
            ("Word of mouth can be one of the cheapest ways to market a business.", True,
             "When happy customers tell friends, it costs you nothing extra, and people trust advice from friends."),
            ("A good ad can promise things the product can't do.", False,
             "Ads must be honest. False promises break trust and can break the law in many places."),
            ("Knowing your target audience helps you choose where to advertise.", True,
             "If you know who your customers are, you can put ads where they will actually see them."),
            ("The most expensive ad is always the one that works best.", False,
             "Price doesn't prove results. A cheap sign can beat a costly ad, so compare the cost per customer."),
            ("A business can learn which ads work by tracking where new customers come from.", True,
             "Counting how people found you shows which ads, signs or friends brought them in."),
            ("You may put flyers on any wall or car you like.", False,
             "You need permission to post on other people's property, and many towns have rules about where flyers can go."),
            ("A marketing budget helps you avoid spending too much on ads.", True,
             "Deciding ahead of time how much to spend keeps marketing from eating up the money you need for other things."),
            ("Once your shop is well known, you never need marketing again.", False,
             "New people move in, tastes change and rivals open. Smart owners keep reminding customers why they are great."),
            ("Great customer service is a kind of marketing.", True,
             "Every happy visit can turn into a good review or a friend's recommendation."),
            ("Marketing is only about making ads.", False,
             "Marketing also includes knowing your customers, choosing where to sell and how you treat people."),
            ("Testing a small ad first can save money.", True,
             "A small test shows whether an idea works before you spend a lot of money on it."),
            ("If an ad brings lots of visitors, it must have made a profit.", False,
             "Visitors don't always buy, and sales must cover the ad and the cost of the products before there is any profit."),
        ],
    },
    {
        "key": "brand",
        "title": "Build a Brand",
        "tagline": "Names, logos and reputation",
        "icon": "badge",
        "cards": [
            ("What is a brand?", "A brand is what people think and feel when they hear your business name. It comes from your name, look, products and how you treat people."),
            ("Logos and colors", "A logo is a simple symbol for your business. Using the same colors and style everywhere helps people spot you fast."),
            ("Your brand is a promise", "A brand tells customers what to expect, like fresh bread daily or fast bike repairs. Keep that promise every single time."),
            ("Reputation and reviews", "Your reputation is what people say about you. It takes years to build and moments to lose. Reviews share it with new customers."),
            ("Stand out and protect it", "Find what makes you special. In many places you can register a trademark, so others can't use a name or logo too close to yours."),
        ],
        "questions": [
            # Level 1
            ("What is a brand?", "What people think and feel about your business", "The cash register at the front counter",
             "The truck that delivers your supplies every morning", "A brand lives in customers' minds. Your name, look, products and kindness all shape it.", 1),
            ("What is a logo?", "A simple symbol that stands for a business", "A list of rules for all the workers to follow",
             "A receipt you give after a sale", "A logo helps people recognize you quickly on signs, bags and websites.", 1),
            ("Which name is best for a bakery?", "Sunrise Bakery", "Shop Number 4721",
             "Xqzt Goods", "A good name is easy to say and remember, and it hints at what you do.", 1),
            ("What is a reputation?", "What people say and believe about your business", "The number of shelves in your shop",
             "The color you choose to paint the shop's front door", "Your reputation is built by every visit. A good one brings customers back and sends friends your way.", 1),
            ("Why do many shops use the same colors on signs, bags and shirts?", "So customers recognize the business quickly", "Because other paint colors are not allowed",
             "To confuse people about which shop it is", "Matching colors everywhere make your business easy to spot and remember.", 1),
            ("What is a customer review?", "A customer's opinion about their experience", "A test that new workers take before they start",
             "A paper listing what the shop owes", "Reviews tell others what it is like to buy from you. Many people read them before choosing a shop.", 1),
            ("Which helps build a good reputation?", "Treating every customer kindly and fairly", "Being rude when the store is busy",
             "Breaking promises whenever keeping them is hard", "People remember how you made them feel. Steady kindness and fairness earn trust over time.", 1),
            ("What does it mean for a business to stand out?", "To be different from others in a good way", "To stand outside the shop all day",
             "To copy exactly what everyone else does", "Standing out gives customers a reason to pick you, like a special recipe or extra-friendly help.", 1),
            ("A good logo is usually...", "Simple and easy to recognize", "Packed with tiny details and words",
             "Changed every single week", "Simple logos are easy to remember and look good both tiny and huge.", 1),
            ("Which is part of a family bakery's brand?", "Its name, its logo and how friendly the staff are", "Only the oven in the back kitchen",
             "Only the price the bakery paid for flour last month", "A brand is everything customers notice and feel, from the sign out front to the smile at the counter.", 1),
            ("You promise a customer their cake will be ready at noon. What should you do?", "Have it ready, or call early if something changes", "Forget about it once they leave",
             "Make an even bigger promise to them next time instead", "Keeping promises builds trust. If a problem comes up, telling people early shows respect.", 1),
            ("What do happy customers often do for your brand?", "Tell friends and leave good reviews", "Ask you to change your name",
             "Keep your business a secret from their friends", "Happy customers spread the word. Their stories help new people trust you.", 1),
            # Level 2
            ("Your bakery promises fresh bread daily. Today's batch burned, so only yesterday's is left. What should you do?", "Tell customers honestly and sell it for less", "Say it is fresh from today and hope no one notices",
             "Hide it and pretend nothing happened", "Being honest when things go wrong protects your brand. A fair price for day-old bread keeps trust.", 2),
            ("What does 'brand consistency' mean?", "Looking and acting the same way every time", "Changing your name whenever you like",
             "Using a new logo on every bag", "When your look and service stay steady, customers know what to expect and trust you more.", 2),
            ("A customer's review says their cake was late. What is the best reply?", "Apologize, explain the fix and invite them back", "Argue in public that the customer is the one who is wrong",
             "Close your page so no one sees it", "A polite, helpful reply shows everyone reading that you care and fix problems.", 2),
            ("What is a trademark?", "A legal way to protect a business name or logo", "A mark on the floor from a delivery cart",
             "A sticker that shows an item is on sale", "In many places, a registered trademark stops others from using a name or logo that could confuse customers.", 2),
            ("A new shop nearby has a name and logo almost like yours. Why is that a problem?", "Customers might mix you up and go to the wrong shop", "It means more people will remember your shop",
             "It is never a problem to share a look", "Your name and logo help customers find you. A copycat look can send them, and your good reputation, to someone else.", 2),
            ("Your bike shop is known for fast repairs. What protects that brand?", "Staying fast, and being honest when a job takes longer", "Taking longer and charging more for waiting",
             "Saying repairs are fast when they take weeks", "A brand is only as strong as what you really do. Honesty when things are slow keeps trust.", 2),
            ("Which is an example of a brand promise?", "Every pizza is made fresh when you order", "We have a parking lot behind the store",
             "Our phone number has seven digits", "A brand promise tells customers what they can always count on from you.", 2),
            ("Why do reviews matter to new customers?", "They show what real customers experienced", "They reveal the owner's secret recipes",
             "They prove the shop has the lowest prices", "New customers can't see inside your shop yet, so they trust what others say about it.", 2),
            ("A worker in the shop's shirt is rude to someone at the park. Why does this matter?", "People may link the rude act to the shop", "It doesn't, because the shop was closed",
             "The shirt makes people think it was someone else", "Everyone who represents a business shapes its brand, even outside work hours.", 2),
            ("What makes a business name easy to remember?", "It is short, simple and fits what you sell", "It is very long and uses hard words",
             "It copies the name of a famous company exactly", "A short, fitting name sticks in people's minds. Copying a famous name can break the rules and confuse people.", 2),
            ("How can a lemonade stand stand out from the one next door?", "Offer something special, like mint lemonade", "Copy the stand next door exactly",
             "Charge more money for the very same cups of lemonade", "Giving people something different and good is a reason to choose you.", 2),
            ("Why is it wrong to put another company's logo on your products?", "It can break trademark rules and mislead buyers", "It uses too much ink to print on every product",
             "Other companies' logos fade very quickly in the sun", "A logo belongs to its owner. Using it without permission tricks buyers and can be illegal in many places.", 2),
            ("Your shop has 4 reviews: 5, 4, 5 and 2 stars. What is the average?", "4 stars", "5 stars",
             "3.5 stars", "Add them up and divide: (5 + 4 + 5 + 2) / 4 = 16 / 4 = 4. Averages show the big picture, not just one review.", 2),
            ("Why should all your workers know your brand's values?", "So every customer gets the same good experience", "So each worker can make up their own new rules every day",
             "So the owner never has to meet customers", "When everyone shares the same values, customers get great service no matter who helps them.", 2),
            # Level 3
            ("A shop has 9 five-star reviews and 1 one-star review. What is the average rating?", "4.6 stars", "5 stars",
             "3 stars", "(9 x 5 + 1 x 1) / 10 = 46 / 10 = 4.6. One bad review lowers the average a little, but steady good service keeps it high.", 3),
            ("Your bakery wants a new logo after 20 years. What is the smartest approach?", "Update it gently so loyal customers still know you", "Change the name, colors and look overnight",
             "Use five different logos at once", "Big sudden changes can confuse loyal customers. A gentle update keeps the trust you have built.", 3),
            ("Which shows that a reputation is hard to build but easy to lose?", "Years of good service hurt by one unkind act shared widely", "A new logo making everyone trust you at once",
             "Reviews that never change once written", "Trust grows slowly with every visit, but one bad moment that spreads can undo a lot of it.", 3),
            ("A big rival has lower prices. How can your small shop compete honestly?", "Win with friendly service, expert help and local trust", "Spread rumors that the rival sells unsafe goods",
             "Promise prices you know you can't offer", "Small shops can stand out with service and know-how. Lies and rumors hurt others and destroy your own name.", 3),
            ("Why can paying people for fake good reviews backfire?", "It is dishonest, breaks rules and can ruin trust", "Fake reviews always cost more than ads",
             "Real customers aren't allowed to write reviews at all", "Fake reviews trick shoppers. Many review sites ban them, and in many places they are illegal. If people find out, trust is gone.", 3),
            ("You want your shop to be known as eco-friendly. What must you do first?", "Really cut waste, like using reusable bags", "Just add a green leaf to your logo",
             "Say it on signs without changing anything", "A brand must match what you really do. Claiming to be green without real action misleads customers.", 3),
            ("What is the main difference between a logo and a brand?", "A logo is a symbol; a brand is how people feel about you", "Logos are for big shops; brands are for small ones",
             "There is no difference at all", "A logo is one small part of a brand. The brand is the whole picture: your name, look, service and reputation.", 3),
            ("You find a shop in another town using your exact business name. What is a good first step?", "Learn the rules and ask an adult or expert for advice", "Post angry messages about them online so people take sides",
             "Change your own name right away", "Name rules differ from place to place. Getting good advice first helps you act fairly and wisely.", 3),
            ("Your promise is 'Fixed in one day or it's free.' One repair takes three days. What should you do?", "Keep your promise and make that repair free", "Charge full price and quietly change the sign",
             "Tell the customer the promise was a joke", "A promise only builds trust if you keep it, even when it costs you. Then check whether the promise is realistic.", 3),
            ("A famous cartoon character would look great on your cupcakes. Can you just use it?", "No, you usually need the owner's permission", "Yes, anything found online is free to use",
             "Yes, if you sell only a few cupcakes", "Characters and logos belong to their owners. Using them without permission can break the law in many places.", 3),
            ("Three bakeries on one street sell plain bread. What would help one stand out most?", "Becoming known for one special item done really well", "Cutting prices until it loses money on every loaf",
             "Painting the shop the same color as the others", "Being the best at something special gives people a clear reason to choose you. Losing money on every sale can't last.", 3),
            ("Your good reputation helps sales grow 10% from $2,000 a month. What are the new monthly sales?", "$2,200", "$2,010",
             "$3,000", "10% of $2,000 is $200. $2,000 + $200 = $2,200.", 3),
        ],
        "facts": [
            ("A brand is more than just a logo.", True,
             "A brand includes your name, look, products, service and how people feel about you."),
            ("Changing your logo every month helps customers remember you.", False,
             "Constant changes confuse people. Consistency helps customers recognize and trust you."),
            ("One bad experience that gets shared widely can hurt a good reputation.", True,
             "Stories spread fast, especially online. That is why every customer visit matters."),
            ("You can put any famous logo you like on things you sell.", False,
             "Logos belong to their owners. Using them without permission can break trademark laws in many places."),
            ("In many places, a trademark can protect a business name or logo.", True,
             "A registered trademark helps stop others from using a name or logo that could confuse customers."),
            ("Paying for fake five-star reviews is a smart way to build a brand.", False,
             "Fake reviews trick people, break the rules of many review sites and can be illegal. When found out, trust is lost."),
            ("Keeping your promises is one of the best ways to build a brand.", True,
             "Customers trust businesses that do what they say. That trust brings them back again and again."),
            ("Only big companies have brands.", False,
             "Every business, even a lemonade stand, has a brand: how people see and remember it."),
            ("How workers treat customers is part of a business's brand.", True,
             "Customers judge a business by the people they meet there. Friendly workers make a friendly brand."),
            ("The best way to handle a bad review is to argue with the customer.", False,
             "Arguing makes you look worse. A polite reply that fixes the problem shows new customers you care."),
            ("A simple logo is often easier to remember than a busy one.", True,
             "Simple shapes and few colors are easy to recognize, even from far away or on a tiny screen."),
            ("To stand out, you should copy the most popular shop exactly.", False,
             "Copying makes you look the same, not special. Standing out means offering something different and good."),
        ],
    },
    {
        "key": "sales",
        "title": "Sales Superstar",
        "tagline": "Helping people say yes",
        "icon": "handshake",
        "cards": [
            ("Listen first", "Great salespeople listen more than they talk. Ask what the customer needs, then help them find the right fit."),
            ("Features vs benefits", "A feature is a fact about a product, like 21 gears. A benefit is how it helps you, like climbing hills easily. People buy benefits."),
            ("Handle no with grace", "When someone says no, thank them politely. A kind no today can become a happy yes later. Never push, pressure or argue."),
            ("Honest selling only", "Never lie or trick someone into buying. Only suggest extras that truly help, like a lock for a new bike. Trust brings people back."),
            ("Close and follow up", "Closing means asking for the sale clearly, like 'Would you like to take it today?' Checking in later shows you care."),
        ],
        "questions": [
            # Level 1
            ("What should a good salesperson do first?", "Listen to what the customer needs", "Talk nonstop about the priciest item",
             "Tell the customer what they must buy", "Listening tells you what the person really wants, so you can help them find the right thing.", 1),
            ("A customer says, 'No, thank you.' What is the best response?", "Thank them and say you're happy to help later", "Keep asking until they finally say yes",
             "Act upset so they feel bad and buy something anyway", "Respecting a no keeps people comfortable. They are more likely to come back when they are ready.", 1),
            ("Which is a feature of a bike?", "It has 21 gears", "It makes hills easier to climb",
             "It gets you to school faster", "A feature is a fact about the product. The other two are benefits: how the product helps you.", 1),
            ("Which is a benefit of a warm winter coat?", "It keeps you cozy on cold days", "It has two zippers and four pockets",
             "It is made of wool", "A benefit explains how something helps you. Zippers and wool are features, facts about the coat.", 1),
            ("Is it okay to lie to make a sale?", "No, lying breaks trust and loses customers", "Yes, if the sale is very big",
             "Yes, as long as no one will ever find out the truth", "Lies hurt the customer and your name. Honest sellers keep customers for years.", 1),
            ("Which is a good question to ask a customer?", "What will you use this for?", "Why haven't you bought anything yet?",
             "How much money is in your wallet?", "Asking how they will use it helps you suggest the right item without being pushy or nosy.", 1),
            ("What does 'closing a sale' mean?", "Politely asking if the customer wants to buy", "Locking all the shop doors at the end of the night",
             "Telling the customer it is time to leave", "Closing is the moment you kindly ask for the sale, like 'Would you like this one?'", 1),
            ("Cookies cost $2. A child has only $1. What should you do?", "Kindly explain the price and show $1 treats", "Look away and wait quietly until they give up and leave",
             "Make fun of them for not having enough", "Being kind and helpful turns a small moment into a happy customer who may come back.", 1),
            ("Why do good salespeople smile and greet customers?", "It helps people feel welcome and relaxed", "It makes the products cheaper to make in the factory",
             "It is the only way to count change", "A warm hello makes people comfortable to ask questions and look around.", 1),
            ("What is pressuring a customer?", "Pushing them to buy before they are ready", "Answering all of their questions clearly and kindly",
             "Showing them where an item is", "Pressure makes people feel trapped. Good selling helps people decide for themselves.", 1),
            ("A customer asks something you don't know. What should you do?", "Say you're not sure and offer to find out", "Make up an answer that sounds smart",
             "Change the subject to something else", "Honesty builds trust. Finding the right answer shows you care about getting it right.", 1),
            ("Which is a kind way to greet a shopper?", "Hi! Let me know if I can help you find anything.", "You need to buy something today.",
             "Hurry up and pick something, we're very busy in here.", "A friendly offer to help makes people feel welcome without pushing them.", 1),
            # Level 2
            ("What is upselling?", "Suggesting a better or extra item that would help", "Selling things from a very high shelf",
             "Raising the price after the customer agrees", "Good upselling helps the customer get more of what they need. It is never about tricking them.", 2),
            ("A customer buys a new bike. Which extra item would truly help them?", "A helmet and a lock to keep rider and bike safe", "A second bike in the same size and color",
             "A fancy gold bell that costs more than the whole bike", "A helpful upsell solves a real need. Safety gear fits a new rider perfectly.", 2),
            ("What is a follow-up in sales?", "Checking in after a sale to see if they're happy", "Walking behind customers around the store",
             "Sending ten messages a day until they buy", "A friendly follow-up shows you care about the customer, not just the sale.", 2),
            ("A customer says, 'That's too expensive.' What is a good response?", "Ask their budget and show options that fit", "Tell them they can't afford nice things",
             "Say the price goes up tomorrow when it won't", "Finding something that fits their budget helps them and keeps the sale honest.", 2),
            ("You sell a backpack with padded straps. Which sentence explains a benefit?", "The padded straps make heavy books comfy to carry", "The straps are 5 centimeters wide and made of nylon",
             "The backpack comes with two straps", "A benefit tells the customer how the feature helps them. Comfort is what they really want.", 2),
            ("Why are open questions useful in sales?", "They let customers explain what they need", "They make customers answer only yes or no",
             "They end the conversation quickly", "Open questions start with words like what, how or why. They help you learn far more than yes-or-no questions.", 2),
            ("Which is an open question?", "What kind of riding do you like to do?", "Do you like the color red?",
             "Is this the very first bike you have bought?", "Open questions can't be answered with just yes or no, so customers share more about what they need.", 2),
            ("A customer wants a cheap toy, but a pricier one earns you more. What should you do?", "Help them choose what fits their needs and budget", "Hide the cheap toy so they buy the pricey one",
             "Say the cheap toy is broken when it isn't", "Putting the customer first earns trust. A happy customer comes back and tells friends.", 2),
            ("A shopper says, 'I need to think about it.' What is the best response?", "Say that's fine and offer info to take home", "Stand in front of the door until they decide",
             "Say it will be gone forever in one minute", "Giving people time shows respect. Many come back once they have thought it over.", 2),
            ("You sell lemonade for $2 a cup. A family buys 6 cups. How much do they pay?", "$12", "$8",
             "$10", "6 x $2 = $12. Quick, correct math at the counter builds trust.", 2),
            ("A shop puts up a fake 'Only 1 left!' sign. Why is that wrong?", "It tricks people into rushing with a lie", "It uses too much paper and ink",
             "Signs should only show numbers above 10", "Fake hurry tricks people into buying before they think. Honest sellers let customers decide freely.", 2),
            ("Which is a good way to close a sale?", "Would you like to take this one home today?", "You have to buy this right now or else.",
             "I will be very sad if you don't buy it.", "A clear, friendly question invites a yes without pressure or guilt.", 2),
            ("A customer bought a laptop bag last week. Which follow-up is best?", "Ask if it works well and if they have questions", "Call every day to sell them more bags",
             "Tell them they should have bought a much pricier one", "A short, caring check-in builds loyalty. Too many calls or put-downs drive people away.", 2),
            ("Why should you know your products well?", "You can answer honestly and match items to needs", "So you can use fancy words that confuse people",
             "So customers stop asking any questions", "Knowing your products helps you give true, useful answers and suggest the right fit.", 2),
            # Level 3
            ("Shoes cost $40, and you suggest $5 socks that help them fit. If 10 customers buy both, what are total sales?", "$450", "$400",
             "$405", "Each customer spends $40 + $5 = $45. 10 x $45 = $450. A helpful extra adds up.", 3),
            ("A customer needs a basic phone case, but you earn more on a deluxe one. What builds long-term trust?", "Recommend the basic case since it meets their need", "Push the deluxe one and hide the basic one",
             "Say the basic case breaks easily when it doesn't", "When you put the customer's needs first, they trust you and come back for bigger buys later.", 3),
            ("You help 20 shoppers and 5 of them buy something. What percent bought?", "25%", "5%",
             "50%", "5 out of 20 is 5 / 20 = 0.25, or 25%. This is called a conversion rate.", 3),
            ("A customer says no to a $300 bike. What is the smartest next step?", "Ask kindly what held them back, then listen", "Drop the price to $100 without thinking",
             "Tell them they are making a big mistake", "Learning their reason helps you find a better fit, or improve for next time, without pushing.", 3),
            ("Why do honest salespeople often sell more over time?", "Customers come back and send friends", "Honest people may charge more money",
             "Customers never compare honest sellers' prices", "Trust is a seller's best tool. Customers who trust you return and recommend you.", 3),
            ("A customer loves a tent but needs room for four, and it fits one. What should you do?", "Point out the size and show tents that fit four", "Sell the small tent before they notice",
             "Say the tent stretches to fit more people if you pull it", "Helping them get what they really need prevents returns and earns a loyal customer.", 3),
            ("What is the difference between persuading and pressuring?", "Persuading gives true reasons; pressuring pushes unfairly", "Persuading is loud and fast; pressuring is slow and quiet",
             "They are two words for the same thing", "Persuading shares honest reasons and lets people choose. Pressure uses fear or rushing to push them.", 3),
            ("You make $3 profit per cake. You want $60 profit this week. How many cakes must you sell?", "20 cakes", "18 cakes",
             "57 cakes", "$60 / $3 = 20 cakes. A clear sales goal helps you plan your week.", 3),
            ("A grandparent wants a tablet for a grandchild. What should you ask first?", "How old the child is and what it's for", "How much money is in their bank account",
             "Whether they want the most expensive one", "Knowing the child's age and needs helps you suggest the right tablet without guessing.", 3),
            ("A customer returns to complain about an item you sold. How can this help you?", "Fixing it well can earn their trust and future business", "It can't, so try to get them to leave fast",
             "It helps if you blame the factory and move on", "A problem solved kindly often makes a customer more loyal than if nothing had gone wrong.", 3),
            ("You followed up with a customer and got no reply. What is best?", "Respect it; maybe try once more later, then stop", "Message them every hour until they answer",
             "Show up at their home without being invited", "Too many messages feel like pressure. Respecting someone's space keeps the door open.", 3),
            ("A customer buys 3 notebooks at $4 each and pays with $20. How much change do they get?", "$8", "$12",
             "$16", "3 x $4 = $12. $20 - $12 = $8 change. Always count change back carefully.", 3),
        ],
        "facts": [
            ("Listening is one of the most important sales skills.", True,
             "You can only help people find the right thing once you know what they need."),
            ("A good salesperson never takes no for an answer.", False,
             "Respecting no builds trust. Pushing people makes them uncomfortable and less likely to return."),
            ("A benefit explains how a product helps the customer.", True,
             "Features are facts, like 21 gears. Benefits are what those facts do for you, like easier hill climbing."),
            ("Upselling means always selling the most expensive item.", False,
             "Good upselling suggests extras that truly help, like a helmet with a bike. It is about need, not price."),
            ("Following up after a sale can turn a buyer into a loyal customer.", True,
             "A short, kind check-in shows you care and gives you a chance to fix any problem."),
            ("Saying there is only one left when there are many is a fair sales trick.", False,
             "It is a lie that rushes people. Tricks like this break trust and can be illegal in many places."),
            ("Saying 'I don't know, but I'll find out' is better than guessing.", True,
             "A wrong guess can cause problems. Being honest and finding the answer builds trust."),
            ("Features and benefits mean exactly the same thing.", False,
             "A feature is a fact about a product. A benefit is how that fact helps the customer."),
            ("Selling people things they don't need can cost you their trust.", True,
             "When customers feel tricked, they stop coming back and may warn their friends."),
            ("Talking fast and nonstop helps customers decide better.", False,
             "Customers need time to think and ask questions. Good salespeople pause and listen."),
            ("A customer who says no today might buy from you later.", True,
             "Needs and budgets change. A polite goodbye keeps the door open for next time."),
            ("Making a customer feel guilty is a good way to close a sale.", False,
             "Guilt is a kind of pressure. Good closing is a clear, friendly question that lets people choose freely."),
        ],
    },
    {
        "key": "online",
        "title": "Business Online",
        "tagline": "Websites, reviews and social media",
        "icon": "wifi",
        "cards": [
            ("Websites and online stores", "A website tells people what you sell, your hours and how to reach the business. An online store lets customers buy any time of day."),
            ("Social media for business", "Businesses post photos, news and tips to stay in touch. Post what is true, kind and useful. Kids should always post with a grown-up's OK."),
            ("Reviews and comments", "Online reviews shape your reputation. Thank people for kind ones and answer complaints politely. Never argue or post fake reviews."),
            ("Protect customer privacy", "Customers trust you with names, emails and card numbers. Keep them safe, collect only what you need and never share them without permission."),
            ("Email with permission", "Only send newsletters to people who signed up, and make it easy to unsubscribe. In many places this is the law, and it is always good manners."),
        ],
        "questions": [
            # Level 1
            ("What is a business website for?", "Showing what you sell and how to reach you", "Storing your family's private photos and home videos",
             "Playing games during work hours", "A website is like a sign that never sleeps. It helps people learn about you and find you.", 1),
            ("What is an online store?", "A website where customers can buy products", "A shop that is only open at night",
             "A store that is built inside a big computer box", "An online store lets people shop from home, at any hour, and have items sent to them.", 1),
            ("A customer leaves a kind review online. What should you do?", "Thank them with a friendly reply", "Ignore it because it's already good",
             "Ask them to make it even longer", "A quick thank-you shows you notice and care, and other readers see it too.", 1),
            ("Someone posts a rude comment on your bakery's page. What should a kid helper do?", "Stay calm and ask a grown-up to help reply", "Post something even ruder back",
             "Copy the comment and spread it around to all your friends", "Staying calm protects your shop's name. A grown-up can help write a polite answer or report it.", 1),
            ("Which is private information a kid should keep off the internet?", "Their home address and school name", "The name of their favorite fruit",
             "A drawing of a cupcake they made", "Personal details can help strangers find you. Keep them private, even when helping a family business.", 1),
            ("What is social media?", "Apps and sites where people share posts and talk", "A newspaper that is delivered to your door each morning",
             "A phone book printed on paper", "Businesses use social media to share news, photos and tips and to talk with customers.", 1),
            ("Why might a bakery post photos of new cakes online?", "So customers see what's new and want to visit", "So other bakeries can copy the recipes",
             "Because every shop needs photos online before it can open", "Good photos show off your work and give people a reason to come in.", 1),
            ("What is an email newsletter?", "A regular email sent to people who signed up", "A paper letter you mail with a stamp on the envelope",
             "A secret note passed between workers", "Newsletters keep customers up to date, but only send them to people who asked to get them.", 1),
            ("Before posting a photo of a customer, what must you do?", "Ask the customer for permission first", "Post it quickly before they notice",
             "Blur only the background of the photo", "People have a right to choose whether their picture goes online. Always ask first.", 1),
            ("What should a business website always show correctly?", "Its hours and how to contact the business", "Every worker's home address and phone number",
             "A list of all the customers' card numbers", "Correct hours and contact details help customers. Private details about workers or customers never belong online.", 1),
            ("A post says your shop is open Sunday, but your hours changed. What should you do?", "Update the post so the hours are right", "Leave it alone and just see who shows up on Sunday",
             "Delete your whole website", "Wrong information wastes customers' time and hurts trust. Keep your posts up to date.", 1),
            ("Which online post is responsible for a business?", "A true, friendly post about a new menu item", "A rumor about a rival shop's owner",
             "A photo of a customer taken without asking", "Responsible posts are true, kind and respect other people's privacy.", 1),
            # Level 2
            ("What does it mean to protect customer privacy?", "Keeping their personal information safe and private", "Making sure customers never talk to anyone about you",
             "Hiding your prices from customers", "Customers trust you with their details. Keeping them safe and not sharing them protects that trust.", 2),
            ("Which is a sign that reviews might be fake?", "Many same-sounding reviews posted on one day", "A review that names a dish the person ate",
             "A review with both good and bad points", "Real reviews tend to be different and specific. Lots of copycat reviews at once are a warning sign.", 2),
            ("A customer complains online that their order was late. Which reply is best?", "Sorry for the delay! Please message us so we can fix it.", "You should have ordered earlier. Not our fault.",
             "We don't answer complaints online. Goodbye.", "A polite apology and an offer to help shows everyone that you care. Moving details to a private message protects privacy.", 2),
            ("How should a shop build its email newsletter list?", "Invite people to sign up and let them choose", "Copy emails from another shop's list",
             "Add every email address you've ever seen", "People should choose to get your emails. In many places, emailing people without permission breaks the law.", 2),
            ("Why should every marketing email have an unsubscribe link?", "So people can easily stop emails they don't want", "So you can collect more of their personal data",
             "Because emails can't be sent without links", "Letting people leave easily respects their choice. In many places it is required by law.", 2),
            ("Your online store sells 15 shirts at $12 each. How much money comes in?", "$180", "$27",
             "$150", "15 x $12 = $180. Remember that some of that money pays for the shirts and shipping.", 2),
            ("A stranger messages the shop's page asking a kid helper for their home address. What should the kid do?", "Not answer, and tell a trusted adult right away", "Send the address, since being polite matters most",
             "Ask the stranger for their address first", "Never share personal details with strangers online. A trusted adult can handle the message safely.", 2),
            ("Why should a business use strong passwords for its accounts?", "To keep accounts and customer data safe from thieves", "So workers can't ever log in at all",
             "Because short passwords cost the business more money each month", "Strong, different passwords make it much harder for someone to break in and steal information.", 2),
            ("What is a good reason to sell online as well as in a shop?", "Customers can buy any time, even from far away", "Online selling takes no work at all once it is set up",
             "Shops can't sell to people in person", "An online store reaches more people and stays open all night, though it still takes work to run.", 2),
            ("Which question should you ask yourself before posting for a business?", "Is this true, kind and okay for anyone to see?", "Will this make the most people angry?",
             "Can I post it before anyone checks it?", "Posts can be seen by many people and copied forever. Checking first prevents mistakes and hurt feelings.", 2),
            ("Another shop offers to trade fake good reviews with you. What should you do?", "Say no, because fake reviews mislead customers", "Agree, since lots of other shops probably do it too",
             "Write fake bad reviews about them instead", "Fake reviews trick shoppers and break the rules of many review sites. Earn real reviews with real service.", 2),
            ("Why should you answer customer questions online quickly and kindly?", "It shows you care and helps them decide", "It lets you argue before others notice",
             "It means you never have to answer again", "Fast, friendly answers make customers feel valued and can turn a question into a sale.", 2),
            ("What does 'think before you post' mean for a business?", "Check that it's true, kind and respects privacy", "Post first and fix it if people complain",
             "Only post late at night when few are online", "Once something is posted, many people may see it fast. A quick check first avoids harm.", 2),
            # Level 3
            ("Your shop's page has 400 followers. A post reached 25% of them. How many people saw it?", "100", "25",
             "375", "25% of 400 is 400 / 4 = 100. Not every follower sees every post.", 3),
            ("Your newsletter goes to 200 people and 10 of them buy something. What percent bought?", "5%", "10%",
             "20%", "10 / 200 = 0.05, or 5%. Tracking this shows whether your emails really help.", 3),
            ("A review says 'Best shop ever!!!' from an account made today with no other reviews. What should you think?", "It might be fake, so read many reviews", "It must be true because it is so excited",
             "New accounts only write true reviews", "One review from a brand-new account can't tell you much. Looking at many reviews gives a truer picture.", 3),
            ("A worker accidentally emails the customer list to every customer. What is the right first step?", "Tell the owner right away so they can act", "Hope no one notices and stay quiet about the mistake",
             "Blame the email program and move on", "Fast honesty limits harm. In many places, businesses must tell customers when their data is exposed.", 3),
            ("What is the safest way to handle customers' card numbers?", "Use a trusted payment system and don't store them", "Write them in a notebook kept next to the cash register",
             "Save them in a file named card numbers", "Trusted payment systems are built to protect card data. Keeping card numbers yourself puts customers at risk.", 3),
            ("An upset customer posts something untrue about your shop. What is wisest?", "Reply calmly with true facts and offer to talk privately", "Post their name and address so people know them",
             "Write many fake reviews to bury their post", "A calm, true reply shows readers you are fair. Sharing private details or faking reviews would hurt people and your name.", 3),
            ("A post making fun of a customer could get lots of likes. Should you post it?", "No, mocking customers is unkind and hurts trust", "Yes, likes are always good for business",
             "Yes, as long as you hide their face a little bit", "Likes don't matter if you lose customers' trust. Kindness online protects people and your brand.", 3),
            ("You want to collect customer details for a newsletter. What should you collect?", "Only a name and email, with their permission", "Everything, like birthdays and passwords",
             "Their friends' emails too, to grow faster", "Collect only what you need, and only with permission. Less data means less to protect and less risk.", 3),
            ("Your website gets 1,000 visits and 20 orders. Each order is $25. How much did the site sell?", "$500", "$250",
             "$25,000", "20 orders x $25 = $500. Only orders bring in money, not visits.", 3),
            ("Why can a photo posted online be hard to take back?", "Others can copy or share it before you delete it", "Photos turn into text after a day",
             "Deleting your own posts is against the rules online", "Once something is online, others can save it. That is why you think carefully before posting.", 3),
            ("Your shop has 4.8 stars. A new 1-star review makes a fair, true complaint. What is best?", "Fix the problem and reply politely", "Ask friends to post 5-star reviews to hide it",
             "Report it as fake even though it's true", "A fair complaint is a chance to improve. A polite reply shows readers you listen and care.", 3),
            ("A website shows Free Shipping in big letters but adds a hidden $8 fee at checkout. What is wrong?", "It misleads customers, which is dishonest", "The letters are too big for a website",
             "Shipping should cost $10 instead", "Hiding fees surprises customers and breaks trust. In many places, prices must be shown clearly.", 3),
        ],
        "facts": [
            ("Many customers read online reviews before choosing a business.", True,
             "Reviews let people learn from other customers, so good service online and off really matters."),
            ("It's fine to send marketing emails to anyone whose address you find.", False,
             "People should choose to get your emails. In many places, emailing without permission is against the law."),
            ("Things posted online can be copied and shared even after you delete them.", True,
             "Others can save or screenshot a post in seconds. Think before you post."),
            ("Businesses should argue with every bad review online.", False,
             "Arguing makes a business look unkind. A polite reply that offers to fix things wins more trust."),
            ("A business should collect only the customer information it really needs.", True,
             "Less data is easier to keep safe, and customers feel more comfortable sharing less."),
            ("A review must be real if it gives five stars.", False,
             "Fake reviews can have any rating. Look for many detailed reviews from different people over time."),
            ("An online store can take orders even when the shop is closed.", True,
             "Websites work day and night, so customers can order whenever it suits them."),
            ("Kids helping a family shop should share their home address online so customers can find them.", False,
             "Kids should keep personal details private online. Grown-ups decide what business details go online."),
            ("A good newsletter makes it easy to unsubscribe.", True,
             "Respecting people's choice keeps trust, and in many places an easy way to unsubscribe is required."),
            ("You can post a customer's photo without asking if they look happy in it.", False,
             "People get to decide whether their picture goes online. Always ask permission first."),
            ("Strong, different passwords help protect a business's accounts.", True,
             "If one password is stolen, different passwords stop thieves from getting into every account."),
            ("A business website never needs updating once it is built.", False,
             "Hours, prices and products change. Out-of-date information confuses customers and hurts trust."),
        ],
    },
]
