"""Academy question bank: the Mindset unit."""

WORLDS = [
    {
        "key": "goals",
        "title": "Goal Getter",
        "tagline": "Set goals and crush them",
        "icon": "target",
        "cards": [
            ("Make it specific", "\"Sell more\" is a wish. \"Sell 20 cupcakes by Saturday\" is a goal. It says what, how much and by when, so you can plan for it and know when you hit it."),
            ("Give it a deadline", "A deadline turns \"someday\" into a plan. Pick a date that is a stretch but still doable, then work backward to see what must happen each week."),
            ("Small steps win", "Big goals can feel scary. Break them into small steps you can finish in a day or a week. Every step you finish is real progress you can see."),
            ("Track and adjust", "Check your progress often with a chart or list. If you fall behind, change the plan, not the dream: try a new step, add time or ask for help."),
            ("Celebrate milestones", "A milestone is a checkpoint on the way to a big goal. Celebrate small wins to stay motivated. Mix short-term goals (this week) with long-term ones (this year)."),
        ],
        "questions": [
            # Level 1
            ("Which goal is the most specific?", "Sell 20 cupcakes by Saturday", "Sell a lot of cupcakes",
             "Be better at selling cupcakes", "A specific goal says what, how much and by when, so you know exactly when you reach it.", 1),
            ("What does a deadline add to a goal?", "A date to finish it by", "A prize for finishing it",
             "A partner to help with it", "A deadline gives your goal a finish line in time. That helps you plan and stops the goal from drifting into someday.", 1),
            ("What is a milestone?", "A checkpoint on the way to a big goal", "The very last step of any goal",
             "A reason to stop working on a goal", "Milestones are smaller targets along the way, like selling 50 of your 200 cookies. They show you are on track.", 1),
            ("Your goal is to read 10 books this summer. What is a good first small step?", "Pick the first book and read one chapter",
             "Wait until you really feel like reading", "Make a list of 50 books to maybe read", "A small first step gets you moving right away. Starting is often the hardest part, so make it easy.", 1),
            ("Which is a short-term goal?", "Finish my science poster this week", "Own a big bakery of my own someday",
             "Become a great business leader", "Short-term goals happen soon, in days or weeks. The other two are long-term goals that take years.", 1),
            ("Which is a long-term goal?", "Run the family store one day", "Clean my room tonight",
             "Finish my math homework today", "A long-term goal takes months or years to reach. Running a store one day is a big future goal.", 1),
            ("Why is it smart to write your goal down?", "So you remember it and can check progress", "So nobody else can ever find out about it",
             "So you never have to change it later", "Writing a goal down makes it clear and easy to come back to, so you can see how far you have come.", 1),
            ("You reached a milestone on your goal. What is a good thing to do?", "Celebrate a little and keep going", "Stop, because you did enough",
             "Hide it so nobody expects more", "Celebrating small wins gives you energy and motivation to reach the next step.", 1),
            ("What does \"measurable\" mean for a goal?", "You can count or check if you did it", "It is very big and hard to reach",
             "Someone else picked it for you", "A measurable goal uses numbers or a clear check, like 20 cupcakes, so you know if you made it.", 1),
            ("You want to save $20 in 4 weeks. How much should you save each week?", "$5", "$4", "$10",
             "$20 divided by 4 weeks is $5 each week. Splitting a goal into equal parts makes it easy to follow.", 1),
            ("Which helps you track progress on a goal?", "A chart you fill in each day", "A guess you make at the very end",
             "A promise to just try harder", "A simple chart shows exactly how far you have come and how far you still need to go.", 1),
            ("A lemonade stand made $8 Monday, $12 Tuesday and $10 Wednesday. What is the total?", "$30", "$28", "$32",
             "8 + 12 + 10 = 30. Adding up daily results lets you see real progress toward a weekly goal.", 1),
            # Level 2
            ("You want to sell 100 cookies in 5 days. How many should you sell each day?", "20", "25", "50",
             "100 divided by 5 days is 20 cookies a day. A daily target makes a big number feel doable.", 2),
            ("A friend's goal is \"get good at soccer.\" Which version is more specific?", "Make 8 of 10 penalty shots by May 31",
             "Watch more soccer games on weekends", "Try really, really hard at soccer", "It has a number (8 of 10) and a date (May 31), so your friend can practice for it and check if they made it.", 2),
            ("Halfway to your deadline, you have done only a quarter of the work. What should you do?", "Change your plan so you can catch up",
             "Give up because you are already behind", "Keep the same plan and hope for the best", "Being behind is useful information. Changing the plan, like adding time or a new step, helps you still reach the goal.", 2),
            ("Which goal has a number and a deadline?", "Get 15 new lawn-mowing customers by June 1", "Get many new lawn-mowing customers soon",
             "Grow the lawn-mowing business by June", "It says how many (15), what (customers) and by when (June 1). \"Grow by June\" has a date but no number to check.", 2),
            ("Your big goal is to put on a class play. What is the best way to start?", "List the jobs and break them into steps",
             "Start rehearsing before there is a script", "Wait for a teacher to plan all of it", "Listing the jobs first shows what to do and in what order, so nothing big gets missed.", 2),
            ("Why celebrate milestones, not just the final goal?", "Small wins keep you going on long goals", "It means you can stop working early",
             "It makes the final goal less important", "Long goals can feel endless. Celebrating checkpoints gives you a boost and proves your plan is working.", 2),
            ("You finished your goal in one day because it was too easy. What is a good next step?", "Set a new goal that stretches you a bit more",
             "Keep the same easy goal every single day", "Set a goal that is impossible to reach", "Good goals are a stretch but still doable. Too easy does not help you grow, and impossible goals feel discouraging.", 2),
            ("What is the main reason to track progress on a goal?", "To see early if your plan needs changing", "To prove you are better than others",
             "To make the goal take longer to finish", "Tracking shows problems while there is still time to fix them, instead of finding out on the last day.", 2),
            ("Your goal was 50 sales and you made 42. What is the most helpful way to think about it?", "Learn what to change for next time",
             "Decide that you are just bad at selling", "Pretend the goal never really mattered", "42 is real progress. Looking at what helped and what didn't turns a miss into a better plan next time.", 2),
            ("Which is a good way to break down \"write a 10-page story in 10 days\"?", "Write one page each day", "Write all 10 pages on the last day",
             "Write only when you feel inspired", "One page a day spreads the work out evenly, and each day you can see if you are on track.", 2),
            ("Your family bakery wants more customers. Which is the best goal to set?", "Get 30 new customers this month", "Become the most famous bakery ever",
             "Make every customer happy forever", "It is specific, measurable and has a deadline. The others are nice dreams but cannot be planned or checked.", 2),
            ("You need $200 for a new bike and earn $25 a week walking dogs. How many weeks will it take?", "8 weeks", "10 weeks", "6 weeks",
             "$200 divided by $25 a week is 8 weeks. Knowing this helps you set a real deadline.", 2),
            # Level 3
            ("You have $15 saved and need $45 for a new sign. You save $5 a week. How many weeks until you have enough?", "6 weeks", "9 weeks", "3 weeks",
             "You still need $45 - $15 = $30. Then $30 divided by $5 a week is 6 weeks.", 3),
            ("Your long-term goal is to own a bike repair shop. Which short-term goal helps most right now?", "Learn to fix flat tires this month",
             "Pick the color of the shop's sign", "Choose a name for a shop cat", "Short-term goals should build skills for the long-term goal. Fixing flats is a real first skill for a repair shop.", 3),
            ("Your goal has a deadline in 4 weeks. Which plan is best?", "Set weekly milestones and check each Friday",
             "Check your progress only on the deadline day", "Work very hard the first week, then rest", "Weekly checkpoints catch problems early and keep steady progress, instead of a surprise at the end.", 3),
            ("You need 120 flyers handed out in 4 days. After 2 days you have done 40. How many per day now?", "40 per day", "30 per day", "20 per day",
             "You still need 120 - 40 = 80 flyers, and you have 2 days left. 80 divided by 2 is 40 per day.", 3),
            ("You set a goal to sell 200 candles by December, but supplies are late for 2 weeks. What is best?", "Update the target and make a new plan",
             "Keep the old plan and ignore the delay", "Drop the goal because it is now ruined", "Good goal-setters adjust when things change. Updating the target keeps the goal realistic so you still move forward.", 3),
            ("Which goal would be the hardest to track?", "Be a nicer team leader", "Hold a 10-minute team meeting every Monday",
             "Thank each teammate once a week", "\"Be nicer\" has no number or clear check. Turning it into actions, like weekly thank-yous, makes it trackable.", 3),
            ("You sell about 10 cookies a week. Which is the best stretch goal for next week?", "Sell 13 cookies", "Sell 100 cookies", "Sell 10 cookies",
             "13 is a small stretch that pushes you to grow. 100 is not realistic, and 10 is no change at all.", 3),
            ("You hit every milestone, but the final result was still short of your goal. What does that tell you?", "The milestones were set too low",
             "Milestones never help with big goals", "You should stop tracking next time", "Milestones should add up to the whole target. If they add up to less, they were set too low.", 3),
            ("Your team agrees on a goal, but nobody knows who does what. What is missing?", "A plan that gives each step an owner",
             "A bigger and more exciting goal", "A much longer deadline for everyone", "Steps get done when one person owns each one. Without owners, everyone thinks someone else will do it.", 3),
            ("Why is \"Get 20 five-star reviews by June\" better than \"Get good reviews\"?", "It can be measured and has a deadline",
             "It sounds more exciting to customers", "It does not need any planning at all", "With a number and a date, you can plan steps and know exactly when you reach it.", 3),
            ("You planned to save $10 a week. After 5 weeks you have $35. How far behind are you?", "$15", "$5", "$25",
             "5 weeks x $10 = $50 planned. $50 - $35 = $15 behind. Now you know how much to catch up.", 3),
            ("Why might a business owner set both short-term and long-term goals?", "Small goals are steps toward big ones",
             "Short-term goals replace long-term ones", "Long-term goals are only for big companies", "Long-term goals give direction, and short-term goals are the steps that get you there.", 3),
        ],
        "facts": [
            ("Big goals are easier when you break them into small steps.", True,
             "Small steps feel doable, show progress and keep you motivated."),
            ("A goal with a deadline is usually easier to plan than one without.", True,
             "A deadline lets you work backward and decide what to do each week."),
            ("Changing your plan when you fall behind is a smart move, not a failure.", True,
             "Plans are tools. Adjusting them helps you still reach the goal."),
            ("Writing a goal down makes it easier to remember and track.", True,
             "A written goal is clear and easy to check, so you can see your progress."),
            ("Short-term goals can help you reach long-term goals.", True,
             "Short-term goals are like stepping stones toward the big goal."),
            ("Numbers make it easier to tell if you reached a goal.", True,
             "\"Sell 20\" can be checked. \"Sell a lot\" cannot."),
            ("\"Make more money\" is a specific, measurable goal.", False,
             "It has no number and no deadline. \"Earn $50 by Friday\" is specific and measurable."),
            ("If you miss a goal once, you should stop setting goals.", False,
             "Missing a goal is a chance to learn. Most successful people miss goals and try again."),
            ("The best goals are so big that they are impossible to reach.", False,
             "Impossible goals are discouraging. The best goals are a stretch but still doable."),
            ("You should check your progress only on the very last day.", False,
             "Checking often lets you fix problems while there is still time."),
            ("Celebrating small wins makes people lazy.", False,
             "Small celebrations give people energy and motivation to keep going."),
            ("Long-term goals do not need any short-term steps.", False,
             "Every big goal is reached through many smaller steps along the way."),
        ],
    },
    {
        "key": "time",
        "title": "Master Your Time",
        "tagline": "Plan, prioritize and focus",
        "icon": "clock",
        "cards": [
            ("Urgent vs important", "Urgent means it needs doing soon. Important means it really matters. Do what is both first, and plan time for important things before they turn urgent."),
            ("Make a to-do list", "Write every task down, then number them by priority. Crossing items off feels great and frees your brain to focus on one job at a time."),
            ("Beat procrastination", "Procrastinating means putting things off. Start with just 5 minutes, break the task into tiny steps and do the hardest part while you have the most energy."),
            ("Guard your focus", "Put the phone away, close extra tabs and work in short focused blocks. Switching between tasks feels fast but usually makes work slower and sloppier."),
            ("Plan, say no, rest", "Put tasks on a schedule with extra time for surprises. Say no politely when your plate is full. Breaks and sleep recharge your brain so you work better."),
        ],
        "questions": [
            # Level 1
            ("What does \"procrastinate\" mean?", "To put off a task you should do", "To finish a task very early",
             "To ask someone to help with a task", "Procrastinating is delaying a task, often because it feels hard or boring. Spotting it is the first step to beating it.", 1),
            ("What is the best way to remember all your tasks?", "Write them on a to-do list", "Try to keep them all in your head",
             "Wait for someone to remind you", "A written list does the remembering for you, so nothing gets forgotten and your mind can focus.", 1),
            ("You need to study, but your phone keeps buzzing. What should you do?", "Put the phone in another room",
             "Answer each message as soon as it comes", "Study with the phone in your hand", "Every buzz pulls your focus away. Out of sight helps keep your attention on the work.", 1),
            ("Which task is urgent?", "A library book that is due back today", "A hobby you want to try next year",
             "A puzzle you might finish sometime", "Urgent means it has to happen very soon. The book is due today, so it can't wait.", 1),
            ("Why are short breaks helpful when you work?", "They rest your brain so you can focus again", "They let you put off work until tomorrow",
             "They mean you never need much sleep", "Brains get tired. A short break, like a stretch or a drink of water, helps you come back sharper.", 1),
            ("What is a schedule?", "A plan that shows when you will do each task", "A list of all the things you already finished",
             "A rule that says you can't take breaks", "A schedule puts tasks into time slots, so you know what to do and when.", 1),
            ("A friend asks you to play, but your homework isn't done. What is a polite way to say no?", "\"I'd love to, but homework comes first.\"",
             "\"No. Stop asking me to play all the time.\"", "Say \"sure\" and just skip your homework tonight", "A polite no is kind and honest. It protects your time without hurting the friendship.", 1),
            ("A big school project is due in two weeks. When is the best time to start?", "Today, with one small step", "The night before it is due",
             "Whenever you finally feel ready", "Starting early with a small step spreads the work out and leaves time to fix problems.", 1),
            ("What is a priority?", "What matters most and should go first", "What you can skip when you are busy",
             "What is always the most fun to do", "Priorities are the tasks that matter most. Doing them first means the big stuff gets done.", 1),
            ("Your bakery opens at 8:00. Baking takes 1 hour. When should baking start?", "By 7:00 or a little earlier", "At 8:00, when the doors open",
             "At 8:30, after customers come", "Work backward from when things must be ready. Starting a bit before 7:00 also leaves time for surprises.", 1),
            ("Which is a distraction while doing homework?", "A TV playing in the same room", "A quiet desk with good light",
             "A glass of water nearby", "A TV grabs your eyes and ears. A quiet space helps you focus and finish faster.", 1),
            ("You have 60 minutes to study and take a 10-minute break in the middle. How much time is left for studying?", "50 minutes", "40 minutes", "70 minutes",
             "60 - 10 = 50 minutes of study. Planning breaks into your time helps you use the rest well.", 1),
            # Level 2
            ("You have homework due tomorrow, a game with friends and a closet to clean next week. What should you do first?", "The homework due tomorrow",
             "The game with friends", "Cleaning out the closet", "Homework is both urgent and important. The game and the closet can fit in later.", 2),
            ("What is the difference between urgent and important?", "Urgent is soon; important really matters",
             "They mean exactly the same thing in business", "Important tasks can never also be urgent", "Some tasks are urgent but small, and some matter a lot but have no deadline yet. Knowing which is which helps you choose.", 2),
            ("You think a poster will take 1 hour, but last time a similar one took 2. How long should you plan for?", "About 2 hours", "About 1 hour", "About 30 minutes",
             "Past tasks are the best guide. People often guess too low, so plan using what really happened last time.", 2),
            ("You keep putting off a big essay. Which trick helps most?", "Promise to work on it for just 5 minutes",
             "Wait until you are in the mood for it", "Do every easy chore in the house first", "Starting is the hardest part. Once you begin for 5 minutes, it is much easier to keep going.", 2),
            ("Why does multitasking often slow you down?", "Switching between tasks wastes time and focus",
             "Your brain works best on many things at once", "It makes each task too much fun", "Each time you switch, your brain needs time to catch up. Doing one thing at a time is usually faster and neater.", 2),
            ("A customer wants your lawn service on a day you are fully booked. What is best?", "Politely offer them the next free day",
             "Say yes and hope you can squeeze it in", "Ignore the message and hope they ask again", "A polite no with another option keeps the customer happy without breaking promises to others.", 2),
            ("Which task should go highest on your lemonade stand to-do list?", "Buy lemons before tomorrow's sale",
             "Design a new logo for next year", "Sort your old receipts by color", "Without lemons there is no sale tomorrow. It is urgent and important, so it goes first.", 2),
            ("What is a good way to plan a busy week?", "Put tasks into time slots on a calendar", "Do whatever feels right each morning",
             "Plan only the fun things and wing the rest", "A calendar shows where your time goes, so big tasks get a spot and nothing sneaks up on you.", 2),
            ("Why should you leave extra time in your schedule?", "Tasks run long and surprises pop up",
             "So you can skip some tasks later on", "Extra time makes tasks harder to start", "Delays happen. A little extra time means one surprise doesn't wreck your whole plan.", 2),
            ("You want to finish a 90-page book in 6 days. How many pages should you read each day?", "15 pages", "9 pages", "20 pages",
             "90 divided by 6 is 15 pages a day. A daily target turns a big task into small ones.", 2),
            ("Which is an important but not urgent task?", "Practicing math facts a little each day", "Answering the doorbell right now",
             "Catching a bus that leaves in 2 minutes", "Daily practice matters a lot for the future but has no deadline today, so it is easy to skip. Plan time for it.", 2),
            ("Weekend plan: 2 hours of chores, 3 hours on a project and 1 hour of practice. You have 8 free hours. How much is left?", "2 hours", "3 hours", "1 hour",
             "2 + 3 + 1 = 6 hours planned. 8 - 6 = 2 hours left for rest or fun.", 2),
            # Level 3
            ("You agreed to help at two events at the same time. What is the best thing to do?", "Tell one group early and help find a fill-in",
             "Go to one and say nothing at all to the other", "Run between both and do half of each", "Telling people early is honest and gives them time to plan. Doing half of each lets both groups down.", 3),
            ("Your to-do list has 15 tasks, but you only have time for 5 today. What should you do?", "Do the 5 most important and move the rest",
             "Do the 5 quickest, whatever they are", "Try to rush through all 15 tonight", "When time is short, choose by importance. The rest can go on tomorrow's list.", 3),
            ("Three jobs each take 20 minutes, with a 5-minute break between jobs. You start at 4:00. When do you finish?", "5:10", "5:00", "5:20",
             "20 + 5 + 20 + 5 + 20 = 70 minutes. 70 minutes after 4:00 is 5:10.", 3),
            ("A task is important but not urgent. If you keep ignoring it, what usually happens?", "It turns urgent and stressful later",
             "It goes away all by itself", "It becomes less important over time", "Important tasks don't disappear. Ignored long enough, they become emergencies, so plan time for them early.", 3),
            ("Why is \"clean the whole garage\" a hard item for a to-do list?", "It is too big; break it into small tasks",
             "It has too many words in it", "Chores never belong on a to-do list", "Big, fuzzy tasks are easy to put off. \"Sort the tools shelf\" is a clear step you can finish today.", 3),
            ("Your 4-part project is due Friday. It is Monday. Which plan is best?", "One part a day, then check it all Friday",
             "Do all 4 parts late on Thursday night", "Do part 1 now and the rest whenever you can", "Spreading the parts out keeps each day light and leaves Friday to check and fix mistakes.", 3),
            ("A store owner spends all day on small questions and never gets to planning. What would help most?", "Set a quiet planning hour each day",
             "Answer questions faster and skip lunch", "Stop planning since there is no time", "Blocking time for important work protects it from small urgent things that would eat the whole day.", 3),
            ("Your tasks usually take 1.5 times as long as you guess. You guess a job will take 2 hours. What should you plan for?", "About 3 hours", "About 2 hours", "About 1.5 hours",
             "2 hours x 1.5 = 3 hours. Using your own track record makes your plans much more accurate.", 3),
            ("You are already busy, and a classmate asks you to do their part of a group project. What is the best reply?", "\"I can't take that on, but I can help you start.\"",
             "Say \"okay\" and stay up all night doing both", "Say \"do it yourself\" and walk away", "This kind no protects your time and still helps your classmate move forward on their own work.", 3),
            ("Which shows good use of the urgent vs important idea?", "Saving time each week for important jobs",
             "Doing whatever task seems loudest right now", "Working only on tasks that are due today", "Making time for important work early stops it from becoming a last-minute rush.", 3),
            ("You studied 3 hours straight and forgot most of it by the next day. What usually works better?", "Several shorter sessions with breaks",
             "One even longer study session with no breaks", "Studying only the night before", "Brains remember more with short, spaced practice and breaks than with one long cram.", 3),
            ("You are excited about many projects and keep starting new ones but finish none. What is the best fix?", "Pick one to finish before starting another",
             "Start even more so one might work", "Work on all of them for a few minutes", "Focus wins. Finishing one project gives real results, while many half-done projects give none.", 3),
        ],
        "facts": [
            ("Breaking a big task into small steps can help you stop procrastinating.", True,
             "Small steps feel easy to start, and starting is often the hardest part."),
            ("Most people guess that tasks will take less time than they really do.", True,
             "This is very common. Plan extra time and use past tasks as a guide."),
            ("Short breaks during work can help you focus better afterward.", True,
             "A quick rest lets your brain recharge so you come back sharper."),
            ("Saying no politely can be a good way to protect your time.", True,
             "Saying yes to everything means doing nothing well. A kind no keeps your promises realistic."),
            ("A task can be important without being urgent.", True,
             "Practicing a skill or saving money matters a lot but rarely has a deadline today."),
            ("Putting your phone out of sight can help you focus.", True,
             "Even a phone you can see can pull your attention. Out of sight helps you stay on task."),
            ("Doing many tasks at once is always faster than doing one at a time.", False,
             "Switching between tasks wastes time. Focusing on one at a time is usually faster."),
            ("Urgent and important mean the same thing.", False,
             "Urgent means it needs doing soon. Important means it really matters. A task can be one, both or neither."),
            ("The best way to beat procrastination is to wait until you feel motivated.", False,
             "Motivation often comes after you start. Begin with a tiny step and the feeling follows."),
            ("A good schedule is packed full, with no extra time.", False,
             "Surprises happen. A little extra time keeps one delay from ruining your whole day."),
            ("Keeping your to-do list in your head is just as reliable as writing it down.", False,
             "Memory slips, especially when busy. A written list keeps track for you."),
            ("Staying up very late to finish work always makes you more productive.", False,
             "Being tired leads to mistakes and slow thinking. Sleep helps you do better work the next day."),
        ],
    },
    {
        "key": "ideas",
        "title": "Big Ideas",
        "tagline": "Creativity and problem solving",
        "icon": "bulb",
        "cards": [
            ("Brainstorm without judging", "When brainstorming, list as many ideas as you can, even silly ones. Don't judge yet. Lots of ideas lead to good ideas, and wild ones can spark smart ones."),
            ("Find the real problem", "Before fixing, ask \"why?\" a few times. Sales are low. Why? People can't see the stand. Why? It's behind a tree. Now you know what to fix."),
            ("Ask your customers", "Customers know what they need. Ask open questions, listen more than you talk and watch what they actually buy. Their answers beat your guesses."),
            ("Test small, learn fast", "Try a new idea in a small, cheap way first, like selling a new flavor for one day. If it fails, you lose little and learn a lot. Improve it and try again."),
            ("Steps to solve problems", "1. Name the problem. 2. Find the cause. 3. Brainstorm fixes. 4. Test one. 5. Check results. Teams solve better when everyone shares and builds on ideas."),
        ],
        "questions": [
            # Level 1
            ("What is brainstorming?", "Listing lots of ideas without judging", "Picking the one best idea right away",
             "Copying the idea of the store next door", "Brainstorming is about quantity first. You sort out the best ideas later.", 1),
            ("During a brainstorm, a friend shares a silly idea. What should you do?", "Write it down and keep the ideas coming",
             "Laugh and tell them it's a dumb idea", "Stop everything to argue about it", "Silly ideas can lead to great ones. If people feel judged, they stop sharing.", 1),
            ("What is the best way to find out what customers want?", "Ask them and really listen", "Guess what they might like",
             "Make only what you like best", "Customers know their own needs. Asking beats guessing every time.", 1),
            ("Your new cookie flavor did not sell. What is the best way to see it?", "A chance to learn what to change", "Proof that you are bad at baking",
             "A reason to never try new things", "Every flop teaches you something. Many great products came after a few failed tries.", 1),
            ("What does \"test small\" mean?", "Try an idea in a small, cheap way first", "Spend a lot before you try the idea",
             "Wait to test until the idea is perfect", "A small test shows whether an idea works before you risk lots of time or money.", 1),
            ("Which is an example of improving something that already exists?", "Adding a handle to a lunchbox",
             "Throwing away a lunchbox that works fine", "Buying the exact same lunchbox again", "Many great ideas make an existing thing a little better, easier or cheaper to use.", 1),
            ("Why is it helpful to come up with many ideas, not just one?", "More ideas mean more chances at a great one",
             "The first idea you have is always the best one", "Then you never have to test any of them", "Your first idea is rarely your best. Having many to choose from improves your odds.", 1),
            ("What is the first step in solving a problem?", "Say clearly what the problem is", "Pick a fix right away",
             "Find someone to blame for it", "You can't fix what you haven't named. A clear problem points you toward the right fix.", 1),
            ("Why can a team come up with better ideas than one person alone?", "Different people notice different things",
             "Teams never disagree about anything", "One person does all of the thinking", "Each person brings different experiences, so together you see more options.", 1),
            ("A customer says your lemonade is too sour. What is a good response?", "Thank them and try a little less lemon",
             "Tell them they are wrong about it", "Ignore it and change nothing at all", "Feedback is free advice. Small changes based on what customers say can make your product better.", 1),
            ("Which is a creative way to tell neighbors about a dog-walking business?", "Make bright flyers with a fun dog drawing",
             "Wait for people to find you on their own", "Tell only your own family about it", "Creative, eye-catching flyers help people notice and remember your business.", 1),
            ("What should you do after you test an idea?", "Look at the results and decide what to change",
             "Forget about it and move on", "Repeat the test exactly the same way forever", "A test is only useful if you learn from it. Check what happened and use it to improve.", 1),
            # Level 2
            ("Your stand sells few drinks. You ask why and learn people can't see it. What is the real problem?", "The stand is hard to see",
             "The drinks taste bad", "The price is too high", "Asking why led to the real cause. Moving the stand fixes it, while changing the recipe would not.", 2),
            ("Which is the best question to ask a customer?", "\"What would make this better for you?\"", "\"You like it, right?\"",
             "\"Why don't you buy more from me?\"", "Open questions invite honest answers. \"You like it, right?\" pushes people to just say yes.", 2),
            ("Before spending $100 on supplies for a new product, what is smart?", "Make a few and see if people buy them",
             "Buy everything now so you are ready", "Ask only your best friend if it's good", "A small test shows real demand. If it flops, you lose a little instead of $100.", 2),
            ("What does asking \"why?\" several times help you do?", "Dig down to the real cause of a problem",
             "Annoy people until they agree with you", "Skip the planning step completely", "Each \"why\" peels back a layer, so you fix the cause instead of just the symptom.", 2),
            ("Your team can't agree on a booth design. What is a good way to decide?", "List pros and cons of each and pick together",
             "Let the loudest person on the team choose", "Give up on having a booth this year", "Comparing pros and cons keeps the focus on what works best, and everyone feels heard.", 2),
            ("What is a prototype?", "An early, simple model used to test an idea", "The finished product sold in big stores",
             "A set of rules for how to run a team", "A prototype can be rough, like a cardboard model. It lets you test and improve before building the real thing.", 2),
            ("You did badly at a craft fair. Which question helps you learn the most?", "\"What would I do differently next time?\"",
             "\"Whose fault was this whole mess?\"", "\"Why am I always so unlucky at fairs?\"", "This question looks forward and turns a bad day into a better plan.", 2),
            ("Many customers ask if your bakery sells mini cupcakes. What does that tell you?", "There may be a need you could meet",
             "Customers are just being too picky", "You should stop selling big cupcakes", "When many people ask for the same thing, it is a clue to a new product they would buy.", 2),
            ("Which is a good example of building on a teammate's idea?", "\"Yes, and we could also add a sign.\"", "\"No, that will never work.\"",
             "\"Let's just do my idea instead.\"", "\"Yes, and\" keeps ideas growing. Shutting ideas down stops the creative flow.", 2),
            ("A problem has three possible fixes. What should you do?", "Test the best one, then check results",
             "Do all three at once without tracking", "Wait to find the one perfect fix first", "Testing one fix at a time shows clearly what worked. Waiting for perfect means nothing gets fixed.", 2),
            ("Why should you judge ideas only after brainstorming is done?", "Early judging stops people from sharing",
             "All ideas turn out to be equally good", "You should never judge any ideas", "Brainstorm first, then judge. Mixing the two makes people afraid to share wild ideas.", 2),
            ("Which is an example of learning from failure?", "Changing the recipe after a batch burns",
             "Hiding the burnt batch and doing it again", "Deciding baking is just not for you", "Learning from failure means finding what went wrong and changing it next time.", 2),
            # Level 3
            ("You sell 10 cups a day. You test a new flavor for one day and sell 15 cups. What is the smartest next step?", "Test it a few more days to be sure",
             "Spend all your money on the new flavor", "Stop selling the old flavor right away", "One good day could be luck. More tests show if the idea really works before you bet big on it.", 3),
            ("Customers say they want lower prices, but they keep buying your pricier deluxe cookies. What should you trust more?", "What they actually buy",
             "What they say they want", "What your friends think", "Actions often show what people really value. Watch what customers do, not only what they say.", 3),
            ("Your phone case shop gets lots of returns. What is the best first step?", "Find out why people return them",
             "Lower the price on every case", "Stop letting people return cases", "You need the cause before the fix. Maybe the cases don't fit, which a price cut would not solve.", 3),
            ("A new idea worked in a small test with 10 friends. Before making 1,000, what should you do?", "Test with a bigger, different group",
             "Make all 1,000 of them right away", "Ask the same 10 friends again", "Friends may be kind rather than honest. A bigger, different group shows if real customers want it.", 3),
            ("A team member never shares ideas in meetings. What might help?", "Have everyone write ideas first, then share",
             "Let only the team leader speak in meetings", "Tell them in front of everyone to talk more", "Writing first gives quieter people time to think, and every idea gets heard.", 3),
            ("Tutoring sign-ups are low. Why? Parents don't know about it. Why? Flyers went to one school. What is the real fix?", "Share flyers at more schools and places",
             "Lower the price of tutoring sessions", "Offer more subjects to teach kids", "The \"why\" chain shows the problem is people not knowing. Reaching more families fixes that.", 3),
            ("Which shows the steps of problem solving in the best order?", "Name it, find the cause, list fixes, test, check",
             "Test, name it, list fixes, find the cause, check", "List fixes, test, name it, check, find the cause", "You must know the problem and its cause before picking fixes, and you test before checking results.", 3),
            ("You add a free tire check to your bike-wash service. How can you best tell if it helped?", "Compare sales before and after",
             "Ask yourself if it feels better", "Check the numbers once a year", "Comparing real numbers before and after shows whether the change made a difference.", 3),
            ("An idea failed, but you learned customers want faster service. What is a smart move?", "Use that lesson to shape your next idea",
             "Forget everything you learned from it", "Try the exact same idea again next week", "Failures carry clues. Building the next idea on that lesson makes it more likely to work.", 3),
            ("Two teammates have opposite ideas for the store window. What is often the best approach?", "Look for a way to combine the best parts",
             "Flip a coin and never talk about it", "Always pick the oldest person's idea", "Combining ideas often beats both. It also helps everyone feel their ideas matter.", 3),
            ("A $5 test could save you from wasting $50 on a bad idea. Is the test worth it?", "Yes, a small cost can prevent a big loss",
             "No, tests are always a waste of money", "Only if the test is sure to pass", "Spending $5 to protect $50 is a smart trade. Tests are cheap insurance for big decisions.", 3),
            ("What makes a \"good failure\" in business?", "It was small and taught you something",
             "It was huge and nobody learned anything", "It was hidden so no one found out", "Small failures you learn from are part of growing. Big hidden ones just cost money.", 3),
        ],
        "facts": [
            ("In brainstorming, you list lots of ideas first and judge them later.", True,
             "Judging too early stops ideas from flowing. Sorting comes after."),
            ("Many successful products started as improvements to something that already existed.", True,
             "Making something easier, faster or cheaper is one of the most common ways new businesses start."),
            ("Testing an idea in a small way first can save time and money.", True,
             "A small test shows whether people want it before you spend a lot."),
            ("Asking \"why?\" several times can help you find the real cause of a problem.", True,
             "Each answer digs deeper, so you fix the cause instead of just the symptom."),
            ("Listening to customers can give you ideas you would not think of alone.", True,
             "Customers see your product differently and often know exactly what they wish it did."),
            ("A prototype does not have to be perfect to be useful.", True,
             "A rough model is enough to test an idea and learn what to improve."),
            ("Only very smart people can be creative.", False,
             "Everyone can be creative. Creativity grows with practice, curiosity and trying new things."),
            ("If an idea fails, it means you are a failure.", False,
             "An idea failing is not the same as you failing. It is information that helps your next try."),
            ("The first idea you think of is always the best one.", False,
             "First ideas are often the most obvious. Thinking of more usually leads to better ones."),
            ("You should spend all your money on a new idea before testing it.", False,
             "Test small first. If the idea does not work, you will still have money to try another."),
            ("Good teams always agree right away on every idea.", False,
             "Good teams often disagree, then talk it through. Different views lead to better ideas."),
            ("Customers can never help you improve your product.", False,
             "Customer feedback is one of the best sources of ideas for improving a product."),
        ],
    },
    {
        "key": "calm",
        "title": "Cool Under Pressure",
        "tagline": "Handle stress and big feelings",
        "icon": "brain",
        "cards": [
            ("Big feelings are normal", "Everyone feels stressed, angry or nervous sometimes, even business owners. Feelings are not good or bad. What matters is what you choose to do next."),
            ("Breathe, then think", "When upset, pause. Breathe in slowly for 4 counts and out for 4. Your body calms down and your thinking brain catches up, so you can choose a smart reply."),
            ("Take feedback like a pro", "When someone points out a mistake, listen, stay calm and ask questions. Useful feedback helps you improve, and you can take time before you answer."),
            ("Empathy and asking for help", "Empathy means imagining how someone else feels. When things feel too big, talk to a trusted adult. Asking for help is a strength, not a weakness."),
            ("Confident, not arrogant", "Confidence is believing you can learn and do hard things. Arrogance is thinking you are always right. Sleep, good food, moving and breaks keep you steady."),
        ],
        "questions": [
            # Level 1
            ("You feel your face get hot because you are angry. What is a good first step?", "Take a few slow, deep breaths",
             "Yell to let it all out", "Throw something to feel better", "Slow breaths calm your body down, so you can think clearly before you act.", 1),
            ("What does empathy mean?", "Understanding how someone else feels", "Always agreeing with everyone else",
             "Hiding your own feelings from others", "Empathy is imagining yourself in someone else's shoes. You can understand someone even when you disagree.", 1),
            ("Is it okay to feel nervous before a big event?", "Yes, it is normal and very common", "No, only weak people feel nervous",
             "No, you should never feel anything", "Nerves are normal, even for grown-up business owners. They often mean you care about doing well.", 1),
            ("You are stuck on a hard problem and feel upset. What is a smart move?", "Ask someone you trust for help",
             "Keep it to yourself and give up", "Pretend the problem isn't there", "Talking to someone you trust can give you new ideas and make the problem feel smaller.", 1),
            ("Which is a healthy habit that helps you stay calm?", "Getting enough sleep", "Skipping meals to save time",
             "Staying up late on screens", "A rested body handles stress much better. Sleep is one of the best calm-keeping habits.", 1),
            ("A customer says your cookies are too dry. What is a calm reply?", "\"Thanks for telling me. I'll work on it.\"",
             "\"You don't know what good cookies are.\"", "\"Then go buy cookies somewhere else.\"", "Thanking people for feedback keeps customers and helps you make better cookies.", 1),
            ("Which sounds confident, not arrogant?", "\"I can do this if I practice.\"", "\"I'm better than everyone here.\"",
             "\"I never make any mistakes.\"", "Confidence believes in growing. Arrogance thinks it is already the best and stops learning.", 1),
            ("Your friend is sad because their stand had no customers. What shows empathy?", "\"That sounds hard. Want to talk about it?\"",
             "\"Mine did way better than yours.\"", "\"It's no big deal, so stop being sad.\"", "Empathy names the feeling and offers support, instead of bragging or brushing it off.", 1),
            ("What is a simple deep-breathing trick?", "Breathe in for 4 counts, then out for 4", "Hold your breath as long as you can",
             "Breathe very fast for a whole minute", "Slow, even breaths signal your body to relax. Fast breathing can make you feel more stressed.", 1),
            ("Why can a short break help when you feel frustrated?", "It gives your mind time to reset", "It means you never have to finish",
             "It makes the problem vanish for good", "Stepping away for a bit lets your feelings settle, so you come back with a clearer head.", 1),
            ("Who is a good person to talk to about big worries?", "A trusted adult, like a parent", "A stranger online you just met",
             "Nobody; keep it all inside you", "Trusted adults care about you and can help. Keeping worries inside usually makes them feel bigger.", 1),
            ("What does it mean to \"think before you react\"?", "Pause, then choose what to do next", "Say the first thing that pops into your head",
             "Never respond to anyone at all", "A short pause lets you pick a response you won't regret later.", 1),
            # Level 2
            ("Your little brother knocks over your craft display right before a sale. What should you do first?", "Breathe and calm down before speaking",
             "Shout at him right away so he learns", "Cancel the whole sale and go home", "Calming down first helps you fix the display and talk to him kindly, instead of making things worse.", 2),
            ("When someone tells you how your work could be better, what is that called?", "Feedback", "Gossip", "Bragging",
             "Feedback is information to help you improve. It can feel uncomfortable, but it is often very useful.", 2),
            ("A teacher says your project needs more detail. What is the most helpful response?", "Ask what details would help most",
             "Argue that it is already perfect", "Decide you are bad at projects", "Asking questions turns criticism into a clear plan for making your work better.", 2),
            ("Your lemonade stand had a bad day. Which thought is most helpful?", "\"Bad days happen. What can I try tomorrow?\"",
             "\"I'm just terrible at running a business.\"", "\"It's all everyone else's fault, not mine.\"", "This thought is kind to yourself and looks for a next step. Every business has bad days.", 2),
            ("What is a key difference between confidence and arrogance?", "Confidence keeps listening; arrogance stops",
             "There is no real difference between them", "Arrogant people always end up doing better", "Confident people trust themselves and stay open to learning. Arrogant people stop listening to others.", 2),
            ("You feel frustrated because your robot kit won't work. Which plan is best?", "Take a break, then try one small fix",
             "Keep forcing it while getting angrier", "Break it so you don't have to try again", "A break cools your frustration, and small fixes help you find the real problem.", 2),
            ("A customer is upset because their order was late. What shows empathy?", "\"I'm sorry you waited. That's frustrating.\"",
             "\"It's not my fault, so calm down.\"", "\"Lots of orders are late. Deal with it.\"", "Naming their feeling shows you understand. Then you can work together on a fix.", 2),
            ("Why can not getting enough sleep make stress feel worse?", "A tired brain has a harder time with feelings",
             "Sleep has nothing to do with how you feel", "Being tired makes you calmer and happier", "When you are rested, small problems feel smaller and it is easier to stay calm.", 2),
            ("You feel upset with a teammate. Which is the best way to tell them?", "\"I felt upset when the plan changed without me.\"",
             "\"You always ruin everything we plan.\"", "Say nothing and stay mad at them for a week", "An \"I feel\" statement shares your feeling without attacking, so the other person can listen.", 2),
            ("When is the best time to answer an angry message?", "After you calm down and think it through",
             "Right away, while you are still upset", "Never; it is best to just ignore it", "Replies sent while angry often make things worse. Waiting helps you answer clearly and kindly.", 2),
            ("Your friend won a prize and you didn't. You feel jealous. What is a healthy step?", "Notice the feeling, then congratulate them",
             "Say that their prize doesn't really count", "Pretend you don't care at all", "Feeling jealous is normal. Noticing it and still being kind keeps you and the friendship strong.", 2),
            ("Which is a sign you should talk to a trusted adult?", "A worry keeps bothering you for days", "You finished all of your homework early",
             "You had a fun day with friends", "Worries that stick around are a signal to get support. A trusted adult can help you sort them out.", 2),
            # Level 3
            ("Someone criticizes your shop sign rudely, but part of what they said is true. What is best?", "Use the true part and let the rudeness go",
             "Ignore all of it because they were rude", "Argue back until they finally say sorry", "Even rude feedback can hold a useful idea. Taking the good part helps you, while arguing wastes energy.", 3),
            ("You lead a team, a big mistake happens and everyone is panicking. What should you do first?", "Stay calm and focus on the next step",
             "Find someone to blame right away", "Panic right along with everyone else", "Calm is contagious. A steady leader helps the team think clearly and fix the problem.", 3),
            ("Which shows healthy confidence for a young business owner?", "\"I'm good at baking and still learning pricing.\"",
             "\"I already know everything I need to know about business.\"", "\"I'll never be good enough at anything I try.\"", "Healthy confidence knows your strengths and admits what you are still learning.", 3),
            ("Why does slow, deep breathing help when you feel stressed?", "Slow breaths tell your body it is safe to relax",
             "Holding air in makes your muscles stronger", "It stops all of your feelings forever", "Stress speeds up your heart and breathing. Slowing your breath helps your whole body settle down.", 3),
            ("A customer yells about a problem that wasn't your fault. What is the best response?", "Stay calm, listen and try to help",
             "Yell back so they know it wasn't you", "Walk away without saying anything", "Staying calm cools the situation. Helping solve the problem matters more than who caused it.", 3),
            ("You have a big pitch tomorrow and feel very nervous. Which plan is best?", "Practice, sleep well, then breathe deeply",
             "Stay up all night practicing over and over", "Skip the pitch so you won't feel nervous", "Practice builds confidence, sleep keeps your brain sharp and breathing calms the nerves.", 3),
            ("You snapped at a friend because you were stressed. What is the best next step?", "Say sorry and explain you were stressed",
             "Act as if nothing happened and move on", "Wait for them to apologize first", "A real apology repairs trust. Explaining helps them understand, but it is not an excuse.", 3),
            ("A teammate keeps making the same mistake and you feel frustrated. Which approach is best?", "Calmly ask what's hard and offer help",
             "Complain about them to everyone else", "Quietly do their work and stay angry", "Asking calmly finds the real cause. Maybe they were never shown how, which you can fix together.", 3),
            ("Which shows a business owner using empathy?", "Opening later after learning customers work late",
             "Keeping hours that only suit the owner's plans", "Ignoring what customers keep saying about hours", "Empathy means seeing things from the customer's side and acting on it.", 3),
            ("After one hard day running your stand, your feelings say \"quit!\" What is wise?", "Rest and decide when you feel calmer",
             "Quit right away while you feel strongly", "Never think about the stand again", "Big decisions are better made calm. Tired, upset feelings often look different after rest.", 3),
            ("You get 9 kind comments and 1 harsh one. You keep thinking about the harsh one. What is a helpful view?", "Learn from it, but remember the 9 kind ones too",
             "Believe the harsh one is the only true one", "Delete all the comments and stop asking", "Brains tend to focus on the negative. Learn what you can, then keep the whole picture in mind.", 3),
            ("Why is asking for help a sign of strength?", "It puts solving the problem ahead of pride",
             "It means someone else does all your work", "Strong people never need help from anyone", "Everyone needs help sometimes, even great leaders. Asking shows courage and gets problems solved faster.", 3),
        ],
        "facts": [
            ("Everyone feels big feelings like anger or worry sometimes.", True,
             "Big feelings are a normal part of being human. Learning to handle them is a skill you can practice."),
            ("Slow, deep breaths can help your body calm down.", True,
             "Slow breathing helps your heart rate settle so you can think more clearly."),
            ("Getting enough sleep helps you handle stress better.", True,
             "A rested brain manages feelings and solves problems more easily."),
            ("Criticism can help you improve, even when it is hard to hear.", True,
             "Feedback points out things you might not see yourself, so you can get better."),
            ("Asking a trusted adult for help is a smart and brave choice.", True,
             "Sharing a problem makes it easier to solve and helps you feel less alone."),
            ("Naming your feeling, like \"I feel frustrated,\" can help you calm down.", True,
             "Putting a feeling into words helps your brain understand it and makes it easier to manage."),
            ("Confident people never make mistakes.", False,
             "Everyone makes mistakes. Confident people believe they can learn from them."),
            ("Feeling nervous means you are not ready to do something.", False,
             "Nerves are normal, even when you are well prepared. They often just mean you care."),
            ("Empathy means you must always agree with the other person.", False,
             "Empathy is understanding how someone feels. You can understand and still disagree."),
            ("The best time to answer an angry message is right away.", False,
             "Waiting until you are calm helps you reply clearly and avoid saying things you regret."),
            ("Arrogance and confidence are the same thing.", False,
             "Confidence believes you can learn and grow. Arrogance thinks you are always right."),
            ("Keeping all your worries inside is the healthiest choice.", False,
             "Bottled-up worries often grow. Talking to a trusted adult can make them easier to handle."),
        ],
    },
]
