"""Academy question bank: the Money unit."""

WORLDS = [
    {
        "key": "pricing",
        "title": "Price It Right",
        "tagline": "How businesses choose prices",
        "icon": "tag",
        "cards": [
            ("Cost, price and profit", "Cost is what you spend to make something. Price is what a customer pays you. Profit is price minus cost. If the price is below the cost, you lose money on every sale."),
            ("Markup", "Markup is the amount you add on top of cost. A $2 cost with a 50% markup adds $1, so the price is $3. Your prices must also cover rent, wages and other bills."),
            ("Sales and discounts", "A discount lowers the price for a while. 25% off a $20 item saves $5, so it costs $15. Sales can bring in new customers, but too many sales shrink your profit."),
            ("Value and competitors", "Customers pay for value: quality, service and convenience. Check what other shops charge, but you do not have to be the cheapest if you give more value."),
            ("Raising prices fairly", "When costs go up, prices may need to rise. Tell customers early, explain why, and keep quality high. Honest pricing builds trust that lasts."),
        ],
        "questions": [
            # Level 1
            ("A cupcake costs $1 to make and sells for $3. What is the profit on one cupcake?", "$2", "$3", "$4",
             "Profit is price minus cost: $3 - $1 = $2.", 1),
            ("What is the 'cost' of a product?", "The money you spend to make or buy it", "The money a customer pays you for it", "The money left over after you sell it",
             "Cost is what it takes you to make or get the product. Price is what the customer pays, and profit is what is left.", 1),
            ("What is 'profit'?", "Money left after you pay your costs", "All the money customers hand you", "Money you borrow to start a business",
             "Profit is what remains after costs are paid. All the money customers pay you is called revenue or sales.", 1),
            ("Your lemonade costs 50 cents a cup to make. Which price lets you make a profit?", "$1", "40 cents", "50 cents",
             "Only a price above your cost leaves a profit. At 50 cents you just break even, and at 40 cents you lose money on every cup.", 1),
            ("A toy costs $10. It is on sale for 10% off. How much do you save?", "$1", "$10", "$0.10",
             "10% means 10 out of every 100. 10% of $10 is $1, so the sale price is $9.", 1),
            ("Which is an example of a discount?", "A shirt marked down from $20 to $15", "A shirt that went up from $15 to $20", "A shirt that costs $15 to make",
             "A discount lowers the price a customer pays. Going up is a price increase, and $15 to make is the cost.", 1),
            ("Two stands sell the very same lemonade. One charges $1 and one charges $5. Where will most people buy?", "At the $1 stand", "At the $5 stand", "At both stands equally",
             "When products are the same, most people pick the lower price. To charge more, you must offer something extra.", 1),
            ("A book costs $8. It is on sale for half price. What is the new price?", "$4", "$2", "$6",
             "Half means divide by 2. Half of $8 is $4.", 1),
            ("You sell 5 bracelets for $2 each. How much money do you take in?", "$10", "$7", "$12",
             "Multiply the number sold by the price: 5 x $2 = $10. This is your revenue before costs.", 1),
            ("If you sell something for less than it costs to make, what happens?", "You lose money on each one you sell", "You make extra profit on each sale", "Nothing changes for your business",
             "Selling below cost means each sale takes money away from you. The more you sell, the more you lose.", 1),
            ("Why is it smart to look at what other shops charge?", "So your price makes sense to customers", "So you can copy their whole business", "So you never have to think about cost",
             "Other shops' prices show what customers expect to pay. You still set your own price based on your costs and the value you give.", 1),
            ("A pencil costs 20 cents to make and sells for 50 cents. What is the profit on one pencil?", "30 cents", "70 cents", "20 cents",
             "Profit is price minus cost: 50 - 20 = 30 cents.", 1),
            # Level 2
            ("A bike shop buys a helmet for $20 and adds a 50% markup. What is the selling price?", "$30", "$25", "$70",
             "50% of $20 is $10. Add it to the cost: $20 + $10 = $30.", 2),
            ("A $40 jacket is 25% off. What is the sale price?", "$30", "$10", "$35",
             "25% is one quarter. A quarter of $40 is $10, so the price drops to $40 - $10 = $30.", 2),
            ("Flour costs a lot more now, so your bakery must raise prices. What is the fairest way?", "Raise them a little and explain why", "Make loaves smaller and say nothing", "Raise them a lot without a word",
             "Clear, honest changes keep trust. Secretly shrinking products is a trick that makes customers feel cheated when they notice.", 2),
            ("A cafe charges $1 more than the one next door, but its food is fresher and its staff are kinder. Why do many people still pick it?", "They feel they get more for their money", "They like paying the highest price", "They never look at the prices at all",
             "Value is what you get for what you pay. Better food and service can be worth a bit more to customers.", 2),
            ("What is markup?", "The amount added to cost to set a price", "The amount taken off a price in a sale", "The amount a customer leaves as a tip",
             "Markup is added on top of cost so the price can cover other bills and still leave a profit.", 2),
            ("You sell 20 cups of cocoa at $2 each. Each cup costs $1 to make. What is your total profit?", "$20", "$40", "$2",
             "Profit per cup is $2 - $1 = $1. Twenty cups times $1 each is $20.", 2),
            ("Besides ingredients, what else should a bakery's prices cover?", "Rent, power bills and wages", "Only the flour and the sugar", "Just the paper bags it uses",
             "Every bill must be paid from sales. If prices cover only ingredients, the bakery can lose money even when it is busy.", 2),
            ("A shop has a big sale every single week. What could go wrong?", "Customers wait for sales and profits shrink", "Customers start to pay more than full price", "The shop's costs all drop down to zero",
             "When sales never stop, people learn never to pay full price. The shop then earns less on almost every item.", 2),
            ("Which is the best reason to hold a sale?", "To clear old stock or win new customers", "To trick shoppers into buying broken items", "Because prices should always be the lowest",
             "A planned sale can make room for new stock or bring in people who may return. Tricking shoppers is dishonest and loses trust.", 2),
            ("A board game costs $5 to make. You want $3 profit on each one. What price should you charge?", "$8", "$2", "$15",
             "Price = cost + the profit you want: $5 + $3 = $8.", 2),
            ("Your price is $10 and you raise it by 10%. What is the new price?", "$11", "$20", "$10.10",
             "10% of $10 is $1. Add it on: $10 + $1 = $11.", 2),
            ("Another shop sells the same toy as you for $2 less. What is a smart first step?", "Check what extra value you can offer", "Cut your price to below your cost", "Tell people the other shop is dirty",
             "First look at what makes you different, like service or quality. Pricing below cost loses money, and spreading lies is wrong.", 2),
            ("What does 'value' mean to a customer?", "What they get compared to what they pay", "Only how cheap an item is today", "How much the item cost the shop",
             "Value is the benefit for the price. A pricier item can be good value if it lasts longer or works better.", 2),
            # Level 3
            ("Each muffin costs $1 to make and sells for $3. Rent is $50 a day. How many muffins must the bakery sell each day to cover rent?", "25", "50", "17",
             "Each muffin leaves $3 - $1 = $2 toward rent. $50 / $2 = 25 muffins.", 3),
            ("What is the 'break-even point'?", "Where sales exactly cover all your costs", "Where you earn the most profit possible", "Where your prices are lowest in town",
             "At break-even you have no profit and no loss. Every sale after that point adds profit.", 3),
            ("Each item costs $6. At $10 you sell 100 a week. At $12 you sell 70 a week. Which price earns more profit?", "$12, with $420 profit", "$10, with $400 profit", "Both earn the same profit",
             "At $10: $4 x 100 = $400. At $12: $6 x 70 = $420. Selling fewer items can still mean more profit.", 3),
            ("A $50 bike light is 20% off. Then you get 10% off the sale price. What is the final price?", "$36", "$35", "$40",
             "20% off $50 is $40. Then 10% of $40 is $4, so $40 - $4 = $36. Two discounts in a row do not just add up to 30%.", 3),
            ("A price goes up from $20 to $25. By what percent did it rise?", "25%", "5%", "20%",
             "The rise is $5. Compare it to the old price: $5 / $20 = 0.25, which is 25%.", 3),
            ("A shop buys mugs for $4 and sells them for $6. What is the markup as a percent of cost?", "50%", "33%", "200%",
             "The markup is $6 - $4 = $2. Then $2 / $4 = 0.5, which is 50% of the cost.", 3),
            ("Why might a new shop set a low opening price for a short time?", "To get people to try it and come back", "Because low prices always beat high ones", "Because costs are lower in the first week",
             "A short opening price lowers the risk of trying something new. The goal is loyal customers who return at the normal price.", 3),
            ("A family shop's costs rose 10%, and its prices have not changed in years. What is the smartest plan?", "Raise prices a bit, tell customers early, keep quality", "Keep prices the same and quietly cut the quality", "Double every price overnight to catch up at once",
             "A small, honest rise covers the new costs and keeps trust. Hidden quality cuts and sudden huge jumps both drive customers away.", 3),
            ("You sell handmade cards for $3. A visitor says they are worth $6. What should you do first?", "Test a higher price and watch sales", "Double every price right away", "Ignore it, since prices never change",
             "Testing on a few items shows what customers will really pay, without risking all your sales at once.", 3),
            ("You sell 200 drinks at $2 each. Each drink costs $0.50 to make. Rent and wages are $250. What is your profit?", "$50", "$300", "$400",
             "Sales are 200 x $2 = $400. Drink costs are 200 x $0.50 = $100. Then $400 - $100 - $250 = $50.", 3),
            ("Why should an owner know the exact cost of every item they sell?", "To be sure each price really earns a profit", "So they can tell every customer their costs", "So the cost can be printed on each tag",
             "If you do not know your costs, you cannot tell whether a sale makes money or loses it.", 3),
            ("A store sells a $100 bike at 30% off. The bike cost the store $60. What is the store's profit on that sale?", "$10", "$40", "$30",
             "30% off $100 means a price of $70. Profit is $70 - $60 = $10. Big discounts can eat most of your profit.", 3),
            ("A new stand opens and sells the same drink as yours for less. Which choice is both fair and smart?", "Improve quality or service so you stand out", "Spread a rumor that their drinks are unsafe", "Secretly agree with them to both charge more",
             "Competing on value is fair. Lying about rivals is wrong, and secret deals to fix prices hurt customers and are against the law in many places.", 3),
        ],
        "facts": [
            ("A higher price always means more profit.", False,
             "If the price is too high, fewer people buy, and total profit can drop."),
            ("Profit is what is left after you subtract costs from sales.", True,
             "Sales minus costs equals profit. If costs are bigger than sales, you have a loss."),
            ("10% of $50 is $5.", True,
             "To find 10%, divide by 10. $50 / 10 = $5."),
            ("The cheapest shop always gets the most customers.", False,
             "Many people pay more for better quality, service or convenience. Value matters, not just price."),
            ("A 50% markup on a $4 cost gives a price of $6.", True,
             "50% of $4 is $2, and $4 + $2 = $6."),
            ("Taking 20% off and then another 20% off is the same as 40% off.", False,
             "The second discount comes off the lower price. On $100 you get $80, then $64. That is 36% off, not 40%."),
            ("Your prices need to cover bills like rent and wages, not just materials.", True,
             "Every cost of running the business is paid from sales. Leave any out and you can lose money while busy."),
            ("Once you set a price, you should never change it.", False,
             "Costs and customer needs change over time. Good owners review prices and adjust them fairly."),
            ("Secretly making a product smaller at the same price is a fair way to handle rising costs.", False,
             "It hides a price rise from customers. Being open about changes is what keeps their trust."),
            ("At the break-even point, a business makes no profit and no loss.", True,
             "Sales exactly match costs. Every sale beyond that point adds profit."),
            ("A discount is always a good idea because it brings in more sales.", False,
             "A discount can bring sales, but each sale earns less. If the discount is too big, you can lose money."),
            ("Customers will often pay a little more to a business they trust.", True,
             "Trust is part of value. People are willing to pay a bit more to a shop that is honest and reliable."),
            ("Revenue and profit mean the same thing.", False,
             "Revenue is all the money from sales. Profit is what is left after paying costs."),
        ],
    },
    {
        "key": "budget",
        "title": "Budget Boss",
        "tagline": "Plan your money before you spend it",
        "icon": "piggy",
        "cards": [
            ("What a budget is", "A budget is a plan for your money. You list what comes in, then decide where it goes before you spend it. Planning first stops nasty surprises later."),
            ("Needs vs wants", "Needs keep you or your business going, like food, rent or supplies. Wants are nice extras, like a fancy sign. Pay for needs first, then wants."),
            ("Fixed and variable costs", "Fixed costs stay the same each month, like rent. Variable costs change with how much you make or sell, like flour for a bakery."),
            ("Emergency fund", "An emergency fund is money saved for surprises, like a broken oven. Many experts suggest saving enough to cover a few months of costs."),
            ("Track, then pause", "Write down every dollar you spend. Before an impulse buy, wait a day and ask: is this in my plan? Cash flow is money moving in and out over time."),
        ],
        "questions": [
            # Level 1
            ("What is a budget?", "A plan for how you will use your money", "A list of all the things you already bought", "A loan you get from a bank",
             "A budget is a plan made before you spend. It helps make sure money goes to what matters most.", 1),
            ("Which is a need for a bakery?", "Flour to bake bread", "A gold-painted sign", "A new music speaker",
             "A bakery cannot make bread without flour. The other items are nice extras, which makes them wants.", 1),
            ("Which of these is a want, not a need?", "A shiny new phone case", "Food for tonight's dinner", "Shoes that fit your feet",
             "Food and shoes that fit keep you healthy. A new phone case is nice, but you can live without it.", 1),
            ("You get $10 a week and save $3. How much is left to spend?", "$7", "$13", "$3",
             "Take the savings out first: $10 - $3 = $7.", 1),
            ("When you make a budget, what should you pay for first?", "Your needs", "Your wants", "Fun extras",
             "Needs keep you and your business running. Pay those first, then use what is left for wants.", 1),
            ("What is an emergency fund?", "Money saved for surprise problems", "Money spent on a fun day out with friends", "Money borrowed from a friend",
             "An emergency fund is ready for surprises, like a broken bike or a sick pet, so you do not have to borrow.", 1),
            ("Why should you write down what you spend?", "To see where your money really goes", "To make shopping feel more fun", "So you can spend more money every day",
             "Small buys add up fast. A written record shows where money goes, so you can spot and fix leaks.", 1),
            ("You want a $20 game and you save $5 a week. How many weeks until you can buy it?", "4 weeks", "5 weeks", "2 weeks",
             "Divide the price by what you save each week: $20 / $5 = 4 weeks.", 1),
            ("You grab a candy bar at the checkout that you did not plan to buy. What is this called?", "An impulse buy", "A fixed cost", "A budget plan",
             "An impulse buy is a quick, unplanned purchase. Shops put treats near the checkout because they know people grab them.", 1),
            ("Which is a good money habit?", "Planning before you spend", "Spending it the day you get it", "Never checking your money",
             "A plan tells your money where to go. Without one, money tends to disappear on things you did not really need.", 1),
            ("You earn $15 mowing lawns and spend $4 on fuel for the mower. How much is left?", "$11", "$19", "$9",
             "Subtract the cost from what you earned: $15 - $4 = $11.", 1),
            ("What does it mean to stay within your budget?", "Spend no more than you planned", "Spend everything you have", "Borrow money for every single buy",
             "Staying within budget means your spending matches your plan, so you never run short for what matters.", 1),
            # Level 2
            ("Which is a fixed cost for a bike shop?", "Monthly rent for the shop", "Tires bought for each repair", "Extra wages on busy days",
             "Rent stays the same each month no matter how many bikes you fix. Tires and extra hours change with how busy you are.", 2),
            ("Which is a variable cost for a lemonade stand?", "Lemons and sugar", "The table bought once", "A yearly stand permit",
             "The more cups you sell, the more lemons and sugar you need. A cost that changes with sales is variable.", 2),
            ("Your bakery's oven breaks, and you have an emergency fund. What should you do?", "Use the fund to fix the oven quickly", "Close the bakery until next year", "Buy a fancy sign to cheer yourself up",
             "This is exactly what an emergency fund is for. Fixing the oven fast keeps sales coming in.", 2),
            ("A family shop earns $3,000 a month. Rent is $1,000, supplies are $1,200 and wages are $600. How much is left?", "$200", "$800", "$1,000",
             "Costs are $1,000 + $1,200 + $600 = $2,800. Then $3,000 - $2,800 = $200.", 2),
            ("What is 'cash flow'?", "Money moving in and out of a business over time", "The coins and bills kept inside the cash register", "The value of everything the business owns",
             "Cash flow is about timing: when money arrives and when bills must be paid. Healthy cash flow means bills get paid on time.", 2),
            ("One simple rule splits money into 50% needs, 30% wants and 20% savings. With $100, how much goes to savings?", "$20", "$30", "$50",
             "20% of $100 is $20. A rule like this is an easy starting point for a budget.", 2),
            ("You planned to spend $30 on snacks this month but spent $45. What is the best next step?", "Find out why and adjust your plan", "Stop tracking so you feel better", "Borrow $15 and keep on spending",
             "Mistakes are lessons. Finding out where the extra money went helps you plan better next month.", 2),
            ("A seller says, 'Buy now, this deal ends in 5 minutes!' What is the smartest move?", "Pause and check if it fits your budget", "Buy it fast before the deal is gone for good", "Buy two so you never miss out",
             "Pressure to hurry is a sales trick. If it is not in your plan, a deal is still money you did not need to spend.", 2),
            ("Your ice cream shop sells a lot in summer and little in winter. How should you plan?", "Save some summer money for slow months", "Spend all summer money while sales are high", "Close the shop for the whole year",
             "Busy months must help pay for slow ones. Saving in good times keeps bills paid when sales drop.", 2),
            ("Why should a budget include bills that come only once a year, like a yearly license fee?", "So the big bill does not surprise you", "Because yearly bills are always small", "So you can skip paying monthly bills",
             "Setting aside a bit each month for a yearly bill means the money is ready when it is due.", 2),
            ("You earn $40. Your needs cost $25. You save half of what is left. How much do you save?", "$7.50", "$20", "$12.50",
             "$40 - $25 = $15 left over. Half of $15 is $7.50.", 2),
            ("Which is the best example of tracking spending?", "Writing every buy in a notebook or app", "Guessing your spending once a year", "Only counting the big things that you buy",
             "Recording every buy gives a true picture. Guesses and skipping small buys hide where money goes.", 2),
            # Level 3
            ("A shop sells $5,000 of goods this month, but customers will pay in 60 days. Rent is due now. What problem might it have?", "A cash flow problem", "A pricing problem", "A marketing problem",
             "A business can make a profit on paper and still run out of cash if money arrives later than bills are due.", 3),
            ("A business has $2,000 of costs each month. It wants 3 months of costs saved for emergencies. How much is that?", "$6,000", "$2,000", "$5,000",
             "3 x $2,000 = $6,000. That cushion keeps the business running through a hard stretch.", 3),
            ("A bakery's fixed costs are $900 a month. Each cake costs $5 to make and sells for $20. How many cakes cover the fixed costs?", "60", "45", "180",
             "Each cake leaves $20 - $5 = $15 toward fixed costs. $900 / $15 = 60 cakes.", 3),
            ("Your shop has some extra money this month. What is usually the wisest order?", "Build the emergency fund, then think about upgrades", "Buy upgrades now, then hope to save some money later", "Spend it all, since next month will be the same",
             "A safety cushion comes first. Once it is in place, upgrades are less risky because a surprise will not sink you.", 3),
            ("Sales dropped by 20% this month. Which cost is usually easiest to cut quickly?", "Variable costs, like buying fewer supplies", "Fixed costs, like the rent on a long shop lease", "Neither, since costs can never change",
             "Variable costs move with sales, so you can buy fewer supplies. Fixed costs like rent are often locked in for a while.", 3),
            ("You budget $200 for supplies for a 4-week month. You spend $150 in the first 2 weeks. At that pace, how far over budget will you go?", "$100", "$50", "$150",
             "$150 every 2 weeks means $300 for 4 weeks. $300 - $200 = $100 over budget.", 3),
            ("A friend's business shows a profit but keeps running out of cash. What is the most likely reason?", "Money comes in later than bills are due", "The business is selling too many items", "The owner tracks spending too closely",
             "Profit and cash are not the same. If customers pay late, cash can run out even when sales are good.", 3),
            ("You want to buy a $600 machine for your shop. Which plan fits a good budget?", "Save a set amount each month until you have it", "Use the rent money and hope that sales go up soon", "Buy it now and skip paying other bills",
             "Saving toward a goal keeps needs paid. Using rent money or skipping bills puts the whole business at risk.", 3),
            ("Why do many owners compare their budget with real spending every month?", "To see the gap between the plan and what happened", "Because a budget stops working after one month", "So they can spend more than planned each time",
             "Comparing plan and reality shows what to fix early, before a small problem becomes a big one.", 3),
            ("A family shop spends $50 a week on snacks for staff. How much is that in a 52-week year?", "$2,600", "$600", "$2,500",
             "$50 x 52 = $2,600. Small regular costs add up to big yearly totals.", 3),
            ("Your income is $1,000. Fixed costs are $400 and variable costs are $350. What percent of income is left?", "25%", "35%", "75%",
             "Costs total $750, leaving $250. Then $250 / $1,000 = 0.25, which is 25%.", 3),
            ("You had to use your emergency fund to fix a freezer. What should you do next?", "Refill the fund bit by bit", "Forget about the fund now", "Spend more to feel better",
             "The next surprise could come anytime. Rebuilding the fund a little each month gets you ready again.", 3),
        ],
        "facts": [
            ("A budget is only for people who do not have much money.", False,
             "Everyone can use a budget. Big companies plan where every dollar goes, too."),
            ("Rent is usually a fixed cost.", True,
             "Rent usually stays the same each month, no matter how much you sell."),
            ("You should pay for wants before needs.", False,
             "Needs keep you and your business going, so they come first. Wants come from what is left."),
            ("Small daily buys can add up to a lot of money over a year.", True,
             "$2 a day for 365 days is $730. Tracking your spending shows these hidden leaks."),
            ("A business that makes a profit can never run out of cash.", False,
             "If customers pay late and bills are due now, even a profitable business can run short of cash."),
            ("An emergency fund helps you handle surprises without borrowing.", True,
             "Having money set aside means a surprise bill does not turn into debt."),
            ("Waiting a day before an unplanned buy can help you avoid impulse spending.", True,
             "A short pause lets the excitement fade, so you can decide if you really need it."),
            ("For a bakery, flour is usually a fixed cost.", False,
             "The more you bake, the more flour you buy. That makes it a variable cost."),
            ("Once you write a budget, you never need to change it.", False,
             "Life and business change. Good budgets are checked and updated often."),
            ("Cash flow is about when money comes in and when it goes out.", True,
             "Timing matters. Money must be there when bills are due, not just at the end of the year."),
            ("If a deal says 'today only', you should always buy it.", False,
             "Hurry-up deals are a sales tactic. If you did not plan for it, skipping it saves money."),
            ("Tracking your spending makes it easier to stick to a budget.", True,
             "When you can see where each dollar went, you notice overspending early and can fix it."),
            ("Spending any money on wants is always wrong.", False,
             "Wants are fine when they fit your budget after needs and savings. A good budget leaves room for some fun."),
        ],
    },
    {
        "key": "saving",
        "title": "Save and Grow",
        "tagline": "Saving, interest and investing",
        "icon": "bank",
        "cards": [
            ("Pay yourself first", "Save a set amount as soon as money comes in, before you spend any. Even small amounts grow into big savings over time."),
            ("Simple interest", "Interest is money a bank pays you for keeping your savings there. At 5% a year, $100 earns $5 in one year."),
            ("Compound growth", "Compound growth means you earn interest on your interest, too. Over many years, money can grow like a snowball rolling downhill."),
            ("Risk and reward", "Investments that might grow more usually have a bigger risk of losing money. Spread money out so one loss does not sink you."),
            ("Spot the scams", "Anyone who promises big, fast, sure profits is a red flag. Real growth takes time. If it sounds too good to be true, it probably is."),
        ],
        "questions": [
            # Level 1
            ("What does it mean to save money?", "Keep some money to use later", "Spend all your money right now", "Give your money to strangers",
             "Saving means setting money aside for the future, so it is there when you need it or want something bigger.", 1),
            ("You save $2 every week. How much will you have after 5 weeks?", "$10", "$7", "$25",
             "Multiply what you save by the number of weeks: $2 x 5 = $10.", 1),
            ("Which place is usually safest for keeping savings?", "A savings account at a bank", "Under a rock in the garden", "Inside an old coat pocket",
             "Banks keep money safe and often pay interest. In many places, savings accounts are also insured up to a limit.", 1),
            ("What is 'interest' on savings?", "Extra money the bank pays you for saving", "A fee you pay the bank to look at your money", "Money you lose when you save it",
             "Banks use savers' money to make loans, so they pay savers a little extra called interest.", 1),
            ("Someone says, 'Give me $10 and I will give you $100 tomorrow, guaranteed!' What is this most likely?", "A scam", "A smart deal", "A savings plan",
             "Nobody can safely promise to turn $10 into $100 overnight. Big, fast, sure profits are a classic sign of a scam.", 1),
            ("What does 'do not put all your eggs in one basket' mean for money?", "Spread your money across different places", "Keep all your money together in one place", "Spend your money on eggs and other food",
             "If one basket drops, you only lose some eggs. Spreading money out means one bad choice cannot wipe you out.", 1),
            ("Which is a good saving habit?", "Saving a little from all money you get", "Saving only when nothing is left to buy", "Saving once and then never again",
             "Saving a bit every time money comes in builds a habit, and the amounts add up over time.", 1),
            ("A bank pays 10% interest a year. You save $50. How much interest do you earn in one year?", "$5", "$10", "$50",
             "10% of $50 is $5, so after one year you have $55.", 1),
            ("Why does saving take patience?", "Money grows slowly, a little at a time", "Banks hide your money away for many years", "Saving only works for older people",
             "Interest adds a little at a time. The longer you wait, the more it grows.", 1),
            ("Your lemonade stand made $20 profit. Which choice helps the business grow?", "Use some to buy more lemons and cups", "Spend all of it on new toys right away", "Hide it and forget where it is",
             "Putting profit back into the business is called reinvesting. More supplies mean you can sell more.", 1),
            ("What is 'risk' when you invest money?", "The chance that you could lose money", "A promise that you will get rich", "A fee that the bank always charges you",
             "Every investment has some chance of losing value. Knowing the risk helps you choose wisely.", 1),
            ("You want a $30 skateboard. You have $12. How much more do you need to save?", "$18", "$42", "$22",
             "Subtract what you have from the price: $30 - $12 = $18.", 1),
            # Level 2
            ("You save $100 at 5% simple interest a year. How much interest do you earn in 2 years?", "$10", "$5", "$105",
             "Simple interest is the same each year: 5% of $100 is $5. For two years, $5 x 2 = $10.", 2),
            ("What is compound interest?", "Earning interest on your savings and past interest", "Earning interest only on the first money you saved", "Paying a fee each time you add money to the bank",
             "With compounding, interest is added to your savings, and next time you earn interest on that bigger amount.", 2),
            ("You have $100 earning 10% a year, added once a year. How much do you have after 2 years?", "$121", "$120", "$110",
             "Year 1: $100 + $10 = $110. Year 2: $110 + $11 = $121. The extra $1 is interest on interest.", 2),
            ("Which of these is usually the riskiest?", "Putting all savings into one new company", "Keeping savings in a bank savings account", "Splitting savings across many safe places",
             "A single new company could fail, and then everything is lost. Spreading out and safe accounts lower the risk.", 2),
            ("A bakery earns a profit, and the owner uses it to buy a second oven. What is this called?", "Reinvesting the profit", "Spending on a want", "Borrowing from a bank",
             "Reinvesting means putting profit back into the business so it can make even more in the future.", 2),
            ("An online ad promises to 'double your money in a week with no risk.' What should you do?", "Ignore it and tell a trusted adult", "Send money fast before it is gone", "Share it so your friends get rich",
             "Real investments never promise sure, fast doubling. A trusted adult can help you check and report scams.", 2),
            ("Why is it smart to start saving when you are young?", "Your money has more years to grow", "Banks pay more interest to kids", "Older people cannot open accounts",
             "Time is the secret of compound growth. Money saved early has many more years to earn interest on interest.", 2),
            ("Which is the best example of diversification?", "Owning small parts of many different businesses", "Putting all of your money into one friend's game", "Keeping all your cash in a single shoebox",
             "Diversification spreads money across many investments, so one bad result does not ruin everything.", 2),
            ("An investment might grow a lot or lose a lot. How would you describe it?", "High risk, high reward", "No risk, sure reward", "Low risk, low reward",
             "Bigger possible gains usually come with bigger chances of loss. That trade-off is called risk and reward.", 2),
            ("You save $5 a week for a 52-week year. How much do you save?", "$260", "$250", "$57",
             "$5 x 52 = $260, before any interest is added.", 2),
            ("An owner keeps 3 months of costs in a savings account and invests the rest. Why keep some in savings?", "So cash is ready if a surprise hits", "Because investing is always a scam", "Because savings always grow fastest",
             "Investments can drop in value right when you need cash. Savings stay steady and are easy to reach in an emergency.", 2),
            ("Which question should you ask before any investment?", "Can I afford to lose this money?", "How fast will this make me rich?", "Will my friends be jealous of it?",
             "Any investment can lose value. Only invest money you will not need for bills or emergencies.", 2),
            # Level 3
            ("$1,000 grows by 10% each year, added once a year. How much is it after 3 years?", "$1,331", "$1,300", "$1,030",
             "Year 1: $1,100. Year 2: $1,210. Year 3: $1,331. Each year earns interest on a bigger amount.", 3),
            ("The 'rule of 72' says money doubles in about 72 divided by its yearly growth rate. At 8% a year, about how long is that?", "9 years", "8 years", "64 years",
             "72 / 8 = 9, so at 8% a year money takes about 9 years to double. It is a handy estimate, not an exact answer.", 3),
            ("Why is a 'guaranteed' 50% return every month a warning sign?", "Real investments cannot promise such big, sure gains", "Monthly returns like that are not allowed in any place", "Only the biggest banks can earn that much",
             "Real investments go up and down, and none can promise huge, sure gains. Promises like this are a common sign of fraud.", 3),
            ("An owner puts all their savings into one supplier's company, and the supplier fails. What lesson does this teach?", "Spread money out so one failure cannot ruin you", "Only invest in the companies you buy your things from", "Saving money is never worth all the trouble",
             "With all your money in one place, one failure takes everything. Diversification limits the damage.", 3),
            ("Two friends save the same amount each year at the same rate. One starts at 15, the other at 25. Who likely has more at 60?", "The one who started at 15", "The one who started at 25", "They will both have the same",
             "The early starter gets 10 extra years of compound growth. Those early years keep earning interest on interest.", 3),
            ("Your savings earn 2% a year, but store prices rise 3% a year. What happens to what your savings can buy?", "It shrinks a little each year", "It grows faster than prices", "It stays exactly the same",
             "When prices rise faster than your interest, your money buys a bit less each year. Rising prices are called inflation.", 3),
            ("Your bike shop made $2,000 profit. Which is the most balanced plan?", "Save some, reinvest some, and keep a small reward", "Put it all into one risky bet for fast growth", "Keep all of it in a drawer so nothing can go wrong",
             "Balance builds safety and growth at the same time. A drawer earns nothing, and one big bet risks everything.", 3),
            ("Someone says you will earn money from everyone you get to join after you, as long as they each pay to join. What is this likely?", "A pyramid scheme", "A savings account", "A smart investment",
             "Pyramid schemes pay early members with money from new recruits. They collapse, most people lose money, and they are illegal in many places.", 3),
            ("You save $200 at 4% simple interest a year for 3 years. How much interest do you earn in total?", "$24", "$8", "$12",
             "4% of $200 is $8 a year. Over 3 years that is $8 x 3 = $24.", 3),
            ("Why do safer investments usually pay less than riskier ones?", "People accept lower returns in exchange for safety", "Safe investments are always run by people who are lazy", "Banks keep the extra money as a secret prize",
             "Investors want extra reward for taking extra risk. If you choose safety, you usually accept a smaller return.", 3),
            ("You plan to keep an investment for 20 years, and it drops 10% in one month. What is often wisest?", "Stay calm and stick to the long-term plan", "Sell all of it right away in a panic", "Borrow some money to buy much more of it right now",
             "Prices go up and down. Selling in a panic locks in the loss, and borrowing to invest adds risk. Long-term plans expect bumpy months.", 3),
            ("You save $50, and it earns 10% the first year. You leave it all in, and year 2 also pays 10%. How much interest does year 2 pay?", "$5.50", "$5", "$10",
             "Year 1: $50 + $5 = $55. Year 2: 10% of $55 is $5.50. Compound growth makes each year's interest bigger.", 3),
        ],
        "facts": [
            ("Saving a small amount often can add up to a lot over time.", True,
             "Steady saving plus interest grows over the years. $5 a week is $260 in a year before interest."),
            ("Compound growth means earning interest on your interest.", True,
             "Interest is added to your savings, so the next round of interest is figured on a bigger amount."),
            ("An investment that promises big, fast and sure profits is usually safe.", False,
             "Real investments cannot promise that. It is one of the most common signs of a scam."),
            ("Diversification means spreading money across different investments.", True,
             "Spreading out means one bad investment does not wipe out all of your money."),
            ("Investments always go up in value.", False,
             "Investments can go up or down. That is why you should only invest money you can afford to leave alone."),
            ("At 10% simple interest, $100 earns $10 in one year.", True,
             "10% of $100 is $10."),
            ("Investments with higher possible rewards usually have lower risk.", False,
             "It is the other way around: bigger possible rewards usually come with a bigger risk of loss."),
            ("Starting to save later in life works just as well as starting early.", False,
             "Starting early gives compound growth more years to work, so early savers usually end up with more."),
            ("Reinvesting profit means putting money back into your business to help it grow.", True,
             "Buying better tools or more stock with profit can help the business earn more later."),
            ("Keeping all your money in one investment is the safest plan.", False,
             "If that one investment fails, you lose everything. Spreading money out is safer."),
            ("In many places, bank savings are insured up to a set amount.", True,
             "Deposit insurance means savers get their money back, up to a limit, even if a bank fails."),
            ("If prices rise faster than your interest, your savings can buy more over time.", False,
             "Your money buys less, because prices grow faster than your savings do."),
            ("Pyramid schemes make most of the people who join rich.", False,
             "Only a few people at the top usually gain. Most people who join lose the money they put in."),
        ],
    },
    {
        "key": "credit",
        "title": "Banks and Borrowing",
        "tagline": "Loans, interest and good credit",
        "icon": "card",
        "cards": [
            ("What banks do", "Banks keep people's savings safe and lend money to others. They pay savers a little interest and charge borrowers more. That difference helps the bank earn money."),
            ("Loans and interest", "A loan is borrowed money you must pay back. Interest is the extra cost of borrowing. Borrow $100 at 10% for a year and you pay back $110."),
            ("Credit scores", "A credit score is like a report card for borrowing. Paying on time helps it. A good score can mean easier loans and lower interest later."),
            ("Good debt and bad debt", "Good debt helps you earn more, like a loan for an oven that bakes more bread. Bad debt pays for things that lose value fast and do not earn money."),
            ("Read before you sign", "Always read the fine print: the interest rate, the fees and what happens if you pay late. Never borrow more than you can repay."),
        ],
        "questions": [
            # Level 1
            ("What is a loan?", "Money you borrow and must pay back", "Money you earn from selling things", "Money you get as a free gift",
             "A loan has to be repaid, usually with interest. It is never free money.", 1),
            ("You borrow $10 from your sister with no interest. How much should you pay back?", "$10", "$5", "$20",
             "With no interest, you repay exactly what you borrowed. Paying it back on time keeps her trust.", 1),
            ("What is interest on a loan?", "The extra money you pay for borrowing", "The money the bank lets you keep for free", "A gift for paying back early",
             "Interest is the price of using someone else's money. The longer you borrow and the higher the rate, the more you pay.", 1),
            ("Why is paying a loan back on time important?", "It builds trust and avoids late fees", "It makes the loan cost a lot more", "It lets you skip the very next payment",
             "Paying on time shows lenders you are reliable, and it saves you from extra fees.", 1),
            ("What does a bank do with the money people save there?", "Keeps it safe and lends some to others", "Locks it in a big box and never uses it", "Gives it away to anyone who asks",
             "Banks lend part of savers' money to borrowers and charge interest. That is how they can pay savers interest too.", 1),
            ("You borrow $100 at 10% interest for one year. How much interest do you pay?", "$10", "$100", "$1",
             "10% of $100 is $10, so you repay $110 in total.", 1),
            ("What is a credit score?", "A number that shows how well you repay debts", "The total amount of money in your bank account", "A grade you get in a math class",
             "Lenders check a credit score to guess how likely you are to pay back a loan on time.", 1),
            ("Before you sign a loan, what should you do?", "Read all of it, even the fine print", "Sign fast so the bank does not wait", "Read only the first line of the page",
             "The small print holds the fees, the rate and the rules for late payments. Know them before you agree.", 1),
            ("Which is a smart rule for borrowing?", "Never borrow more than you can repay", "Borrow as much as the bank will allow you", "Borrow again to pay old loans",
             "If you cannot repay, debt grows with fees and interest. Borrow only what your plan can pay back.", 1),
            ("What often happens if you pay a loan late?", "You may pay fees and hurt your credit", "The bank gives you a reward for waiting", "Nothing at all if you pay it someday",
             "Late payments often bring fees and can lower your credit score, which makes future loans harder or pricier.", 1),
            ("You owe $50 and pay back $10 each week. How many weeks will it take to pay it all?", "5 weeks", "10 weeks", "4 weeks",
             "Divide what you owe by each payment: $50 / $10 = 5 weeks.", 1),
            ("Who is the 'borrower' in a loan?", "The one who gets money and must repay it", "The one who lends money to someone else", "The one who counts money at the bank",
             "The borrower receives the money and pays it back. The lender is the one who gives the money.", 1),
            # Level 2
            ("A bakery borrows money for a bigger oven so it can sell twice as much bread. What kind of debt is this?", "Good debt, since it helps earn more money", "Bad debt, since every kind of debt is bad", "No debt, since ovens are not paid with loans",
             "Debt that helps you earn more than it costs can be good debt, as long as the bakery can make the payments.", 2),
            ("Which is an example of bad debt?", "Borrowing for fancy clothes you cannot afford", "Borrowing for a delivery van for the shop", "Borrowing for a tool that helps you earn more",
             "Fancy clothes lose value and do not earn money, but you still pay interest. That makes it bad debt.", 2),
            ("What is collateral?", "Something the lender can take if you do not repay", "A gift the bank gives you when you open an account", "The money you save each month for emergencies",
             "Collateral, like a car or equipment, backs up a loan. If the loan is not repaid, the lender can take it.", 2),
            ("A bank charges 5% interest a year on a $1,000 loan. How much interest is that for one year?", "$50", "$5", "$500",
             "5% of $1,000 is $50. You can find it with $1,000 x 0.05.", 2),
            ("How do banks earn money from savings and loans?", "They charge borrowers more than they pay savers", "They print brand new money whenever they run out", "They keep every saver's money as a fee",
             "If a bank pays savers 2% and charges borrowers 7%, it keeps the difference to pay its costs and earn a profit.", 2),
            ("Which habit helps build a good credit score?", "Paying every bill in full and on time", "Opening many loans at the same time", "Missing a payment every now and then",
             "A record of on-time payments is one of the biggest parts of a good credit score.", 2),
            ("Why might someone with a good credit score get a lower interest rate?", "Lenders see them as more likely to repay", "Banks simply like some names more than others", "A good score lets them skip payments",
             "Lower risk for the lender means a lower price for the loan. A good track record saves real money.", 2),
            ("A loan ad says, 'No payments for 6 months!' What should you check first?", "Whether interest still grows during those months", "Whether the ad has bright colors and fun pictures", "Whether you can borrow even more money later",
             "Interest may keep building while you are not paying, so the loan can cost much more than it looks.", 2),
            ("You borrow $200 and will repay it in 4 equal parts with no interest. How much is each payment?", "$50", "$40", "$80",
             "Divide the loan by the number of payments: $200 / 4 = $50.", 2),
            ("A family shop owner wants a loan for a new freezer. What should they do first?", "Check that sales can cover the payments", "Borrow double in case they want more later", "Sign the first offer without comparing",
             "A loan is only safe if the business can make every payment. Comparing offers can also save money.", 2),
            ("What is the 'fine print' on a loan?", "The small details, like fees and rules", "The big bold title at the top of the form", "The pictures in the bank's adverts",
             "Important details, like fees, rate changes and late rules, are often in small print. Read it all.", 2),
            ("You cannot make this month's loan payment. What is the best step?", "Talk to the lender early about options", "Hide from the lender and hope they forget", "Quietly take a new loan to cover it",
             "Many lenders will work out a plan if you speak up early. Hiding usually brings fees and bigger trouble.", 2),
            # Level 3
            ("You borrow $500 at 10% simple interest a year for 2 years. How much do you repay in total?", "$600", "$550", "$1,000",
             "Interest is 10% of $500 = $50 a year, so $100 for 2 years. Total repaid: $500 + $100 = $600.", 3),
            ("A store card charges 2% interest each month on what you owe. About how much is that per year?", "24%", "2%", "12%",
             "2% x 12 months = 24% a year, even before compounding. Small monthly rates add up to a big yearly cost.", 3),
            ("A bike shop borrows $3,000 and puts up its tools as collateral. If it stops paying, what can happen?", "The lender may take the tools", "The loan simply disappears for good", "The bank must lend it more",
             "Collateral is the lender's backup. If payments stop, the lender can take it, and the shop loses tools it needs.", 3),
            ("Loan A: $1,000 at 5% plus a $100 fee. Loan B: $1,000 at 8% with no fee. For one year, which costs less?", "Loan B, costing $80", "Loan A, costing $50", "Both cost $150",
             "Loan A costs $50 interest plus a $100 fee, which is $150. Loan B costs $80. Always add the fees, not just the rate.", 3),
            ("Why is taking a new loan to pay off an old one often a warning sign?", "It can trap you in growing debt", "It always lowers what you owe", "Lenders reward it with high scores",
             "If you cannot pay without borrowing more, interest and fees keep piling up. It is a sign to cut costs or ask for help.", 3),
            ("A shop's monthly profit is $400. A new loan payment would be $350 a month. Is this a safe loan?", "Risky, since one slow month could mean a missed payment", "Very safe, since the profit is a bit more than the payment", "Safe, since loans pause on their own in slow months",
             "Only $50 a month would be left as a cushion. One slow month could mean a missed payment, fees and a hurt credit score.", 3),
            ("You owe $1,000 on a card at 20% a year. You pay only the interest, $200. After the year, how much do you still owe?", "$1,000", "$800", "$0",
             "Paying only the interest does not touch the amount you borrowed, so you still owe the full $1,000.", 3),
            ("Which is most likely to hurt a credit score?", "Paying bills late many times", "Paying a loan off early", "Checking your own report",
             "A pattern of late payments tells lenders you may not repay. Paying early and checking your own report do not usually hurt.", 3),
            ("Why does a lender often ask for collateral?", "It lowers the lender's risk if the loan is not repaid", "It means the whole loan is free of any interest at all", "It proves the borrower has very good taste",
             "Collateral gives the lender a way to get money back. Lower risk can also mean a lower interest rate for you.", 3),
            ("A shop offers 'quick cash': borrow $100 today and repay $150 in two weeks. What is wrong with this deal?", "It costs $50 for two weeks, a very high price", "Nothing, since $150 is close to $100", "Loans can never be paid back in as little as two weeks",
             "Paying $50 to borrow $100 for two weeks is a huge cost. Over a year that rate would be many times the loan. Look for cheaper options.", 3),
            ("Your business asks a bank for a loan. Which is the best reason for the bank to say yes?", "Steady sales, clear records and bills paid on time", "A big shiny sign and a very fancy office", "A promise from the owner that the business will surely succeed",
             "Banks look at proof you can repay: steady income, good records and a history of paying on time.", 3),
            ("A loan has a low rate for 1 year, then jumps much higher. Where would you most likely find this detail?", "In the fine print of the loan papers", "On the front page in giant letters", "Nowhere, since rates cannot change",
             "Rate changes and fees are often in the fine print. Reading it all stops nasty surprises later.", 3),
        ],
        "facts": [
            ("A loan is free money that you never have to pay back.", False,
             "A loan must be repaid, usually with interest on top."),
            ("Interest is the cost of borrowing money.", True,
             "When you borrow, you pay back the loan plus interest, which is the price of using the money."),
            ("Paying bills on time can help build a good credit score.", True,
             "On-time payments show lenders you are reliable, which is a big part of a credit score."),
            ("Paying only the smallest amount due on a card clears the debt quickly.", False,
             "Minimum payments are small, so much of each one may go to interest. The debt can last for years."),
            ("Collateral is something a lender can take if a loan is not repaid.", True,
             "Things like equipment or a car can back up a loan and lower the lender's risk."),
            ("All debt is bad debt.", False,
             "Debt that helps you earn more, like a loan for equipment that boosts sales, can be good debt if you can repay it."),
            ("Banks pay interest to savers and charge interest to borrowers.", True,
             "Banks charge borrowers more than they pay savers, and that difference helps them earn money."),
            ("If a loan has a low interest rate, it has no other costs.", False,
             "Loans can have fees, too. Add up the interest and the fees to see the full cost."),
            ("A good credit score can help you get loans at lower interest.", True,
             "Lenders see a good score as lower risk, so they often offer a better rate."),
            ("It is fine to sign a loan without reading it if the bank seems friendly.", False,
             "Friendly or not, the contract decides what you owe. Always read the rate, fees and rules first."),
            ("Borrowing $100 at 10% for one year means paying back $110.", True,
             "10% of $100 is $10 in interest, so you repay $100 + $10 = $110."),
            ("Missing loan payments has no effect on future borrowing.", False,
             "Missed payments can lower your credit score, making future loans harder to get or more costly."),
        ],
    },
]
