"""Academy question bank: the Operations unit."""

WORLDS = [
    {
        "key": "operations",
        "title": "Run the Machine",
        "tagline": "Processes, checklists and quality",
        "icon": "gear",
        "cards": [
            ("What operations means", "Operations is how the work gets done every day: making, serving, shipping and cleaning up. Good operations means the same good result every time."),
            ("Processes and checklists", "A process is the set of steps for a job. A checklist lists those steps so nobody forgets one, even on a busy day. Experts like pilots and chefs use them too."),
            ("Quality control", "Quality control means checking work before it reaches the customer. Catch a burnt cookie in the kitchen, not at the counter."),
            ("Fix the cause", "When something goes wrong, keep asking why it happened. Fixing the real cause stops the problem from coming back. Blaming people rarely fixes anything."),
            ("Measure and write it down", "Count things like orders, mistakes and wait times to see what is improving. Write down how jobs are done so anyone can do them the right way."),
        ],
        "questions": [
            # Level 1
            ("What does 'operations' mean in a business?", "The everyday work of making and delivering what you sell", "Only the advertising the business does",
             "Only the money the owner keeps in the bank", "Operations is the daily work: making, serving, delivering and cleaning up. Ads and savings matter, but they are other parts of a business.", 1),
            ("Why do pilots and chefs use checklists?", "So important steps are never forgotten", "So they look busy to other people",
             "Because checklists make the work slower", "Even experts forget steps when busy or tired. A checklist makes sure every step happens every time.", 1),
            ("What is a process?", "A set of steps you follow to get a job done", "A prize you get for working hard",
             "A list of the business's customers", "A process is the order of steps for a job, like mix, bake, cool, then pack. Following it gives the same result each time.", 1),
            ("What is quality control?", "Checking work to make sure it is good before customers get it", "Making products as fast as you possibly can",
             "Letting customers find the mistakes for you", "Quality control catches problems early, so customers get what they paid for and keep coming back.", 1),
            ("At your lemonade stand, one cup tasted too sour. What is a good quality check?", "Taste a small sample from each new pitcher before selling", "Sell it anyway and hope nobody notices",
             "Stop making lemonade for the rest of summer", "Tasting each new batch catches a bad pitcher before any customer drinks it. Small checks prevent big disappointments.", 1),
            ("Which is an example of a checklist?", "Closing steps: wipe counters, turn off oven, lock door", "A poster showing the shop's new logo",
             "A note that says the shop is great", "A checklist lists specific steps to tick off. A closing list makes sure the oven is off and the door is locked every night.", 1),
            ("Why should you write down how a job is done?", "So others can do the job right when you are away", "So the job becomes a secret only you know",
             "So you never have to do the job again", "Written steps let a new helper or a fill-in worker do the job the right way, so the business keeps running.", 1),
            ("A bike shop fixes 4 bikes on Monday and 6 on Tuesday. How many bikes did it fix in both days?", "10 bikes", "8 bikes",
             "12 bikes", "4 plus 6 is 10. Counting the work done each day helps an owner see how busy the shop really is.", 1),
            ("What does 'efficient' mean?", "Getting good work done without wasting time or materials", "Doing work as quickly as possible, even if sloppy",
             "Using as many supplies as you can find", "Efficient work saves time and materials but still does the job right. Fast but sloppy is not efficient.", 1),
            ("Your bakery's cookies keep coming out different sizes. What helps most?", "Use the same scoop for every cookie", "Ask customers to pick the biggest one",
             "Charge more for only the big ones", "Using the same tool every time makes each cookie the same size. Standard tools are an easy way to get steady quality.", 1),
            ("What is a good reason to measure things in a business?", "To see what is getting better or worse", "To make the work take much longer",
             "To have numbers to hide from the team", "You can't improve what you don't track. Counting orders or mistakes shows if a change really helped.", 1),
            ("A new helper starts at your family store. What should you give them first?", "Clear steps for their job and someone to show them", "A long list of things they might do wrong",
             "No help, so they learn by guessing", "New people learn fastest with written steps and a friendly demonstration. Guessing leads to mistakes and stress.", 1),
            # Level 2
            ("Customers keep getting cold pizza because the oven timer is broken. What fixes the cause?", "Repair or replace the oven timer", "Give each upset customer a free drink",
             "Tell customers pizza tastes fine cold", "A free drink only treats the symptom. Fixing the timer stops cold pizzas from happening in the first place.", 2),
            ("What is the 'root cause' of a problem?", "The deepest reason the problem happened", "The first customer who complained about it",
             "The person who should be blamed for it", "The root cause is the real reason underneath, often a broken step or tool, not a person to blame. Fix it and the problem stops coming back.", 2),
            ("To find a root cause, which question should you keep asking?", "Why did this happen?", "Who can we blame for this?",
             "How fast can we forget this?", "Asking 'why' several times digs past the symptom to the real cause. Blaming people makes them hide mistakes instead.", 2),
            ("Your shop makes 20 sandwiches an hour. How many does it make in a 3-hour lunch rush?", "60 sandwiches", "23 sandwiches",
             "50 sandwiches", "20 times 3 is 60. Knowing your output per hour helps you plan helpers and ingredients for busy times.", 2),
            ("Which change makes a bakery more efficient without cutting corners?", "Setting out all ingredients before starting to mix", "Skipping handwashing to save a minute",
             "Taking cakes out before they finish baking", "Getting ingredients ready first saves walking back and forth. Skipping washing or baking time hurts safety and quality.", 2),
            ("Out of 50 orders, 5 had mistakes. What fraction had mistakes?", "1 out of 10", "1 out of 5",
             "1 out of 50", "5 out of 50 is the same as 1 out of 10, or 10 percent. Tracking this number shows if your fixes are working.", 2),
            ("Why should everyone on a team follow the same process?", "So customers get the same good result no matter who helps", "So nobody ever has to think at work",
             "So the owner never has to do any work", "When everyone follows the same steps, quality stays steady. Customers trust a business that is good every single time.", 2),
            ("A worker finds a faster way to pack boxes that is still safe and neat. What should a good owner do?", "Test it, then update the written steps if it works", "Ignore it because the old way is the rule",
             "Let only that worker use it in secret", "Good businesses keep improving their processes. Testing an idea and writing it down lets the whole team benefit.", 2),
            ("What is a 'bottleneck' in a process?", "The slowest step that holds up the other steps", "A step that is skipped to save time",
             "The fastest worker on the whole team", "Like the narrow neck of a bottle, one slow step limits how fast everything flows. Speeding up that step helps the most.", 2),
            ("A car wash has three steps: soap takes 2 minutes, rinse 2 minutes, drying 6 minutes. Which step is the bottleneck?", "Drying", "Soap",
             "Rinse", "Drying takes the longest, so cars pile up waiting for it. Adding a second dryer would help more than speeding up the soap.", 2),
            ("Which task belongs on a bakery's daily opening checklist?", "Check fridge temperatures and turn on the ovens", "Decide what color to paint the walls",
             "Plan next year's summer vacation", "Opening checklists cover daily must-dos like safe fridge temperatures. Big projects belong in a separate plan.", 2),
            ("What is a 'standard' in operations?", "The agreed right way and right result for a task", "A rule that only the owner has to follow",
             "The cheapest possible way to do any task", "A standard says what 'done right' looks like, like a burger cooked all the way through. Everyone can check work against it.", 2),
            # Level 3
            ("Deliveries are late every Friday. What is the lasting fix?", "Find out why Fridays are slow and change the plan for them", "Apologize to every Friday customer forever",
             "Stop taking orders on every day of the week", "A repeating pattern points to a cause. Learning why Fridays run late, like too few drivers, lets you fix it for good.", 3),
            ("A lemonade stand makes 1 pitcher in 10 minutes. Each pitcher fills 8 cups. How many cups can it make in an hour?", "48 cups", "18 cups",
             "80 cups", "An hour has 60 minutes, so that is 6 pitchers. 6 pitchers times 8 cups is 48 cups.", 3),
            ("You check boxes and find most mistakes happen late in the shift. What is the best next step?", "Look at what changes late in the shift, like tiredness or low supplies", "Stop checking boxes since it shows bad news",
             "Blame whoever packed the last box of the day", "Data shows when problems happen. Looking at what changes at that time helps find the true cause.", 3),
            ("Why is 'fast but sloppy' not really efficient?", "Fixing mistakes and redoing work wastes more time later", "Customers always prefer slow service",
             "Sloppy work uses no materials at all", "Redoing work, giving refunds and losing customers cost far more than doing it right once. Real efficiency counts the whole job.", 3),
            ("A bike shop wants fewer bikes returned with problems. Which number should it track?", "How many repaired bikes come back each week", "How many posters hang on the walls",
             "How many pencils are in the office", "Measure the thing you want to improve. If returns drop after a change, you know the change worked.", 3),
            ("Only one worker knows how to run the cash register, and she gets sick. What should the owner have done earlier?", "Written down the steps and trained a second person", "Told her she is never allowed to get sick",
             "Planned to close the shop whenever she rests", "When know-how lives in one head, the business is stuck without that person. Written steps and cross-training protect it.", 3),
            ("What does 'cross-training' mean?", "Teaching workers to do more than one job", "Training workers only on their one main job",
             "Training that happens just once in a career", "Cross-trained workers can cover for each other on busy or sick days, so the business keeps running smoothly.", 3),
            ("A checklist has 40 steps and workers keep skipping some. What is the best improvement?", "Keep the key steps, make it clear, and ask workers why they skip", "Add 40 more steps so it looks complete",
             "Punish anyone who skips without asking why", "A checklist only works if people use it. Short, clear lists and listening to workers lead to better follow-through.", 3),
            ("A cafe can serve 30 people an hour. 45 people come in one lunch hour. How many will still be waiting when the hour ends?", "15 people", "30 people",
             "75 people", "45 minus 30 is 15. Knowing your capacity helps you plan, like adding a helper at lunch so the line stays short.", 3),
            ("What is the main idea of 'continuous improvement'?", "Making many small changes over time to get better", "Changing everything at once every single day",
             "Never changing anything that already works", "Small, steady improvements add up. Each change is tested and kept if it helps, so the business slowly gets better.", 3),
            ("Two cooks make the same soup, but it tastes different each time. What will most likely fix this?", "A written recipe with exact amounts that both cooks follow", "Letting each cook guess the amounts",
             "Telling customers to add their own salt", "Exact written amounts make the result the same no matter who cooks. That is how big restaurant chains taste the same everywhere.", 3),
            ("Packing takes 5 minutes per box. A new tool cuts it to 4 minutes. How much time is saved on 30 boxes?", "30 minutes", "1 minute",
             "10 minutes", "Each box saves 1 minute, and 30 boxes times 1 minute is 30 minutes. Small savings per item add up fast.", 3),
        ],
        "facts": [
            ("Writing down how a job is done helps new workers learn it.", True,
             "Written steps let anyone do the job the right way, even when the expert is away."),
            ("Experts never need checklists because they remember everything.", False,
             "Even experts forget steps when tired or rushed. That is why surgeons and pilots still use checklists."),
            ("Fixing the cause of a problem can stop it from happening again.", True,
             "Treating only the symptom means the problem keeps coming back. Fixing the cause solves it for good."),
            ("Doing work faster is always better, even if the quality drops.", False,
             "Sloppy work leads to redos, refunds and lost customers. Good speed never comes at the cost of quality."),
            ("Checking products before they reach customers is part of quality control.", True,
             "Quality control catches mistakes inside the business, so customers only get good products."),
            ("If customers stop complaining, the problem must be fixed.", False,
             "Many unhappy customers never complain; they just leave. Check your own numbers to know if a problem is really gone."),
            ("The slowest step in a process limits how fast the whole process can go.", True,
             "Work piles up at the slowest step, called the bottleneck. Speeding it up helps the whole line move faster."),
            ("Once a process is written down, it should never be changed.", False,
             "Good processes get updated when the team finds a better or safer way. Then the written steps are changed too."),
            ("Measuring things like mistakes and wait times helps a business improve.", True,
             "Numbers show whether a change really helped, instead of just guessing."),
            ("Blaming a worker is the best way to find the root cause of a mistake.", False,
             "Most problems come from a step, tool or plan that needs fixing. Asking 'why' finds causes; blame makes people hide mistakes."),
            ("Using the same tools and amounts every time helps products come out the same.", True,
             "Standard tools and recipes remove guessing, so every batch matches the last one."),
            ("Only big factories need to think about operations.", False,
             "Every business, even a lemonade stand, has daily work to do. Operations is how that work gets done well."),
        ],
    },
    {
        "key": "inventory",
        "title": "Stock Smart",
        "tagline": "Keep the right things on the shelf",
        "icon": "box",
        "cards": [
            ("What inventory is", "Inventory is the stuff a business keeps to sell or use: flour in a bakery, tires in a bike shop, cups at a lemonade stand."),
            ("Not too little, not too much", "Run out and you lose sales. Buy too much and money sits on the shelf, takes space and may spoil. Aim for just right."),
            ("Reorder points", "A reorder point is the amount left when you order more. Daily sales times the days a delivery takes (the lead time) gives the number. Add a little extra for safety."),
            ("First in, first out", "Sell or use the oldest stock first. Put new items behind old ones and check expiration dates so nothing goes bad on the shelf."),
            ("Count and store it safely", "Count stock often so your records match the shelf. Store heavy items low, keep aisles clear, and keep cold food cold."),
        ],
        "questions": [
            # Level 1
            ("What is inventory?", "The goods a business keeps to sell or use", "The money a business owes to the bank",
             "The list of people who work at a business", "Inventory is the stuff on hand, like flour at a bakery or bike tires at a bike shop.", 1),
            ("What happens if your lemonade stand runs out of cups?", "You lose sales because customers can't buy", "You make more money because cups are rare",
             "Nothing, since customers will wait all day", "No cups means no sales. Customers often go somewhere else and may not come back.", 1),
            ("What does 'out of stock' mean?", "The store has none of that item left to sell", "The item is on sale for half price",
             "The item is stored outside the shop", "Out of stock means the shelf is empty. Good inventory planning makes this rare.", 1),
            ("What does 'first in, first out' mean?", "Sell or use the oldest items first", "Sell or use the newest items first",
             "Let the first customer take anything free", "Using the oldest stock first keeps things from expiring or going stale on the shelf.", 1),
            ("A new crate of milk arrives at the store. Where should it go?", "Behind the older milk on the shelf", "In front of the older milk on the shelf",
             "On the floor next to the fridge", "New milk behind old milk means customers grab the older one first, so less milk expires.", 1),
            ("What does an expiration date tell you?", "The last day a product should be sold or used", "The day the product was first invented",
             "The day the store first opened", "After the expiration date, food may be unsafe or lower quality. Check dates and remove old items.", 1),
            ("You have 12 cupcakes and sell 7. How many are left?", "5 cupcakes", "7 cupcakes",
             "19 cupcakes", "12 minus 7 is 5. Keeping track of what is left tells you when to bake more.", 1),
            ("What is a supplier?", "A business that sells you the things you need", "A customer who buys a lot from you",
             "A worker who cleans the shop at night", "Suppliers sell you goods, like a flour mill selling to a bakery. Good suppliers help you stay stocked.", 1),
            ("Why is buying way too much stock a problem?", "Money gets stuck on the shelf and items may spoil", "Customers dislike stores that have things",
             "Extra stock always makes items taste better", "Extra stock ties up money you could use elsewhere, takes space, and can go bad or out of style.", 1),
            ("Where should heavy boxes go on storage shelves?", "On the lower shelves", "On the very top shelves",
             "Stacked high in the walkway", "Heavy items on low shelves are less likely to fall and hurt someone, and are easier to lift safely.", 1),
            ("What does 'counting stock' mean?", "Checking how many of each item you really have", "Guessing how much you sold last year",
             "Counting the customers who walk in", "Counting shows what is really on the shelf, so you can catch mistakes, losses and items that need reordering.", 1),
            ("Which item is most likely to spoil?", "Fresh strawberries", "Pencils",
             "Bike bells", "Fresh food like strawberries goes bad in days. Spoilable items need careful ordering and first in, first out.", 1),
            # Level 2
            ("What is a reorder point?", "The amount left on the shelf when you should order more", "The day the store closes for a holiday",
             "The price you pay for each new item", "When stock drops to the reorder point, you order. That way new stock arrives before you run out.", 2),
            ("What is lead time?", "How long an order takes to arrive after you place it", "How long a worker's lunch break lasts",
             "How long a product lasts before it expires", "Lead time is the wait between ordering and receiving. Longer lead times mean you must order earlier.", 2),
            ("You sell 5 boxes a day and new boxes take 3 days to arrive. How many should you have when you reorder?", "At least 15 boxes", "At least 5 boxes",
             "At least 8 boxes", "You sell 5 a day for the 3 days you wait, and 5 times 3 is 15. Reorder at 15 or more so you don't run out.", 2),
            ("Your records say 20 helmets, but you count 17 on the shelf. What should you do?", "Fix the records and look into where 3 went", "Ignore it because records are always right",
             "Order 20 more helmets right away to be safe", "Counts catch errors, damage or theft. Updating records and finding the cause keeps your numbers trustworthy.", 2),
            ("Why do stores keep 'safety stock'?", "To cover surprises like a busy day or a late delivery", "To have extra items to throw away",
             "To make the shelves look full for photos", "Safety stock is a small extra amount that protects you when sales jump or a delivery is late.", 2),
            ("A bakery bakes 50 rolls a day but sells only 35. What is the best change?", "Bake closer to 35 and track sales each day", "Keep baking 50 and throw out the rest",
             "Bake 70 so the shelves look extra full", "Making about what sells cuts waste and saves money. Tracking daily sales helps you adjust for busy days.", 2),
            ("You have 40 water bottles and sell 8 a day. How many days until you run out?", "5 days", "8 days",
             "32 days", "40 divided by 8 is 5. Knowing this tells you when to order before the shelf is empty.", 2),
            ("A supplier's delivery time grows from 2 days to 5 days. What should you do?", "Reorder earlier by raising your reorder point", "Keep the same reorder point as before",
             "Stop counting your stock for a while", "Longer lead time means more sales happen while you wait, so you need to order sooner.", 2),
            ("Which storage habit is safest in a stockroom?", "Keep aisles clear and stack boxes neatly", "Stack boxes as high as they will go",
             "Leave boxes in front of the exit door", "Clear aisles and neat stacks prevent trips and falling boxes, and keep exits open in an emergency.", 2),
            ("Why should a store remove expired food from its shelves?", "It may be unsafe and could make people sick", "It sells better after the date passes",
             "Expired food is worth more to collectors", "Expired food can be unsafe. Removing it protects customers and the store's good name.", 2),
            ("What is 'shrinkage' in inventory?", "Stock that goes missing from loss, damage or theft", "Clothes that get smaller in the wash",
             "A sale where all prices shrink for a day", "Shrinkage is the gap between what records say and what is really there. Regular counts help spot it.", 2),
            ("A customer asks for a bike part you don't have. What is a good response?", "Offer to order it and say when it should arrive", "Say you will never carry that part",
             "Tell them to stop asking for parts", "Offering to order keeps the sale and the customer. Telling them the arrival date sets clear expectations.", 2),
            ("Which item should be checked for expiration dates most often?", "Fresh milk", "Canned beans",
             "Paper towels", "Fresh milk lasts days, cans last a long time, and paper towels don't spoil. Check the fastest-spoiling items most often.", 2),
            ("Why do warehouses label shelves and bins with clear names and numbers?", "Workers can find, count and put away items correctly", "Labels make the boxes much lighter to carry",
             "Labels mean workers never need to count", "Clear labels mean less searching, fewer mix-ups and faster, more accurate counts.", 2),
            # Level 3
            ("Which item needs the smallest safety stock?", "One that sells the same amount every day", "One whose sales jump up and down a lot",
             "One whose deliveries are often late", "Steady sales are easy to predict, so less extra is needed. Jumpy sales or late deliveries need a bigger cushion.", 3),
            ("You sell 6 bags of flour a day, lead time is 4 days, and you keep 6 extra as safety stock. What is your reorder point?", "30 bags", "24 bags",
             "10 bags", "During the 4-day wait you sell 6 times 4, which is 24. Add 6 for safety stock and the reorder point is 30.", 3),
            ("Why is too much inventory risky for a business that is short on cash?", "Money spent on stock can't pay bills until it sells", "Stock costs nothing until it is sold",
             "Banks give free money for full shelves", "Cash tied up in boxes can't pay rent or wages. Selling stock turns it back into cash.", 3),
            ("A shop sells many umbrellas in rainy months and few in dry months. How should it order?", "Order more before rainy months and less in dry months", "Order the same amount every single month",
             "Stop ordering umbrellas completely", "Matching orders to the season keeps shelves full when demand is high and avoids piles of unsold stock later.", 3),
            ("Supplier A delivers in 2 days but costs a bit more. Supplier B takes 10 days and costs a bit less. Why might a bakery pick A for fresh fruit?", "Fresh fruit spoils fast, so quick delivery matters more", "Cheaper is always the best choice",
             "Long waits make fruit taste fresher", "For spoilable goods, a short lead time means fresher stock and less waste, which can be worth a slightly higher price.", 3),
            ("Why is it risky to rely on only one supplier?", "If that supplier has a problem, you may run out", "One supplier always has the lowest price",
             "Suppliers refuse to sell to small shops", "A backup supplier helps if the main one has a storm, a closure or runs out. It protects your shelves.", 3),
            ("Your records say 125 pens, but you count 120. What percent of the recorded pens are missing?", "4 percent", "5 percent",
             "25 percent", "5 pens are missing out of 125. 5 divided by 125 is 0.04, which is 4 percent.", 3),
            ("A toy store has 200 of a toy that stopped selling. What is a smart move?", "Lower the price to sell them and order fewer next time", "Order 200 more so the shelf looks full",
             "Hide the toys in the back room forever", "A sale turns stuck stock back into cash. Learning from it helps you order smarter next time.", 3),
            ("Your shop is open 6 days a week and sells 10 caps each open day. Delivery takes one week. What is the lowest safe reorder point?", "60 caps", "70 caps",
             "10 caps", "During a one-week wait the shop is open 6 days. 10 caps times 6 days is 60, so reorder at 60 or more.", 3),
            ("Medium shirts sell twice as many as small or large. How should you split an order of 40 shirts?", "10 small, 20 medium, 10 large", "13 small, 14 medium, 13 large",
             "20 small, 10 medium, 10 large", "Medium gets 2 parts and the other sizes get 1 part each, so 4 parts. 40 divided by 4 is 10 per part.", 3),
            ("Why is 'just in time' ordering risky when suppliers are often late?", "With little extra stock, any delay leaves shelves empty", "It means you always have too much stock",
             "Suppliers charge double for on-time orders", "Just in time keeps stock very low to save money. That only works when deliveries are reliable.", 3),
            ("A cafe throws away 10 muffins every night. Each costs $1 to make. How much is wasted in a 7-day week?", "$70", "$17",
             "$10", "10 muffins times $1 is $10 a night. Over 7 nights that is $70 of waste that better planning could save.", 3),
            ("Why do a full stock count even if you use a computer system?", "Computers only know what people enter, so errors build up", "Computers change the numbers on purpose",
             "Counting matters only when the shop is new", "Mistakes, damage and theft are not always recorded. A real count fixes the records so ordering stays accurate.", 3),
        ],
        "facts": [
            ("Putting new stock behind old stock helps prevent waste.", True,
             "Customers reach for the front items first, so older stock sells before it expires."),
            ("Having as much inventory as possible is always best.", False,
             "Too much stock ties up money, takes space and can spoil. The goal is the right amount, not the most."),
            ("Lead time is the wait between ordering goods and receiving them.", True,
             "Knowing your lead time tells you how early you must order to avoid running out."),
            ("If the computer says you have 20 items, there is no need to ever count them.", False,
             "Breakage, theft and typing mistakes make records drift. Real counts keep the numbers honest."),
            ("Running out of a popular item can send customers to another store.", True,
             "If the shelf is empty, many customers buy elsewhere and may keep shopping there."),
            ("Expired food is fine to sell if it still looks okay.", False,
             "Some germs can't be seen or smelled. Follow the dates and food safety rules to keep customers safe."),
            ("Heavy items should be stored on low shelves.", True,
             "Low shelves keep heavy things from falling on people and make them easier to lift safely."),
            ("A longer lead time means you can wait longer before reordering.", False,
             "It is the opposite. When delivery takes longer, you must order earlier so stock arrives before you run out."),
            ("Unsold stock ties up money a business could use for other things.", True,
             "Money spent on items sitting on a shelf can't pay bills until those items sell."),
            ("Shrinkage means items getting smaller while they sit on the shelf.", False,
             "Shrinkage is stock that goes missing through theft, damage or mistakes. It shows up when counts don't match records."),
            ("Having a backup supplier can protect a business from running out.", True,
             "If the main supplier has a problem, a second one can still send what you need."),
            ("Every product needs the same amount of safety stock.", False,
             "Items with jumpy sales or slow, unreliable deliveries need more extra stock than steady sellers."),
        ],
    },
    {
        "key": "supply",
        "title": "Supply and Demand",
        "tagline": "Why prices go up and down",
        "icon": "chart",
        "cards": [
            ("Supply and demand", "Supply is how much of something is for sale. Demand is how much people want to buy. Together they help set prices."),
            ("Shortages", "A shortage happens when people want more than there is. Shelves empty and prices often rise, like snow shovels before a big storm."),
            ("Surpluses", "A surplus is more stuff than people want to buy. Sellers often lower prices to clear it, like winter coats on sale in spring."),
            ("Seasons and busy times", "Demand changes with seasons and events: sunscreen in summer, pumpkins in fall. Smart owners plan and stock up before the rush."),
            ("Competition and prices", "When many sellers offer the same thing, they compete. Buyers can choose, so prices tend to stay lower and quality goes up."),
        ],
        "questions": [
            # Level 1
            ("What is demand?", "How much of something people want to buy", "How much a seller has in the storeroom",
             "How much it costs to make a product", "Demand is about buyers. When lots of people want something, demand is high.", 1),
            ("What is supply?", "How much of something is available to sell", "How much customers want to buy",
             "How much money a store has saved", "Supply is about sellers: how many items are out there for people to buy.", 1),
            ("When is a lemonade stand likely to sell the most?", "On a hot, sunny day", "On a cold, rainy day",
             "In the middle of the night", "People want cold drinks when it is hot. Weather changes demand.", 1),
            ("In which season do people usually buy the most sunscreen?", "Summer", "Winter",
             "Fall", "People spend more time in the sun in summer, so demand for sunscreen rises then.", 1),
            ("What is a shortage?", "When people want more of something than there is", "When a store has far too much of something",
             "When prices are lower than usual", "In a shortage, buyers want more than sellers have, so shelves empty and prices often go up.", 1),
            ("What is a surplus?", "When there is more of something than people want", "When everyone wants an item that is sold out",
             "When a store raises all of its prices", "A surplus means extra stock that isn't selling. Sellers often lower prices to clear it.", 1),
            ("Many kids want the same new toy, but stores have only a few. What usually happens to the price?", "It tends to go up", "It tends to go down",
             "It must stay exactly the same", "When demand is high and supply is low, buyers compete for few items, so prices tend to rise.", 1),
            ("Farms grow far too many tomatoes one year. What often happens to tomato prices?", "They tend to go down", "They tend to go up",
             "They stay exactly the same", "Lots of supply means sellers lower prices to sell the tomatoes before they spoil.", 1),
            ("Which is an example of a seasonal product?", "Pumpkins in the fall", "Toothpaste all year round",
             "Bread every single day", "Seasonal products sell mostly at certain times of year. Toothpaste and bread sell all year long.", 1),
            ("What is competition in business?", "Different businesses trying to win the same customers", "Workers arguing over who gets a day off",
             "A store raising prices for no reason", "Competition happens when several sellers want the same buyers. It pushes each one to do better.", 1),
            ("A new snack stand opens right next to yours. What is a good response?", "Make your snacks better or your service friendlier", "Say unkind things about the new stand",
             "Close your stand forever on the first day", "Competition pushes businesses to improve. Better quality, service or price helps you win customers fairly.", 1),
            ("Why do stores sell winter coats for less in spring?", "Fewer people want coats, so stores clear them out", "Coats cost more to make in spring",
             "Stores like to lose money on purpose", "Demand drops when the weather warms, so stores lower prices to sell leftover coats and free up space.", 1),
            # Level 2
            ("A big snowstorm is coming. What happens to demand for snow shovels?", "It goes up quickly", "It goes down quickly",
             "It stays exactly the same", "People suddenly need shovels before the storm, so demand jumps. Stores that stocked up early are ready.", 2),
            ("You sell hot cocoa. When should you buy extra cocoa mix?", "Before the cold season starts", "Right after the cold season ends",
             "Only after you have already run out", "Buying before demand rises means you are ready for the rush instead of missing sales while you wait for deliveries.", 2),
            ("Five stands sell lemonade on one street. What usually happens to their prices?", "They stay lower because buyers can choose", "They go up because there is lots of lemonade",
             "Each stand can charge anything it wants", "With many choices, buyers pick the better deal, so sellers keep prices fair to win customers.", 2),
            ("A bakery sells 30 pies in a normal week and twice as many the week before a big holiday. How many should it plan for that week?", "60 pies", "32 pies",
             "90 pies", "Twice as many as 30 is 60. Planning ahead means having enough ingredients and helpers ready.", 2),
            ("What does it mean to 'plan for busy times'?", "Get extra stock and helpers ready before the rush", "Close the shop on the busiest days",
             "Wait to see what happens, then react", "Planning ahead means you are ready when customers arrive, instead of running out or making them wait.", 2),
            ("Why might an ice cream shop hire extra helpers in summer?", "Demand is higher, so more customers need serving", "Ice cream melts more slowly in summer",
             "Helpers are not needed in other seasons at all", "Hot weather brings more ice cream buyers. Extra helpers keep the line moving and customers happy.", 2),
            ("A store has 100 extra notebooks after the school year starts. What is a sensible move?", "Put them on sale to sell them faster", "Raise the price because they aren't selling",
             "Order 100 more notebooks right away", "A sale lowers the price to match lower demand, turning extra stock back into cash.", 2),
            ("A new, cheaper seller of the same product opens nearby. What usually happens next?", "Other sellers may lower prices or improve to compete", "Every seller raises prices right away",
             "Customers stop buying that product at all", "When buyers have a cheaper option, other sellers must offer a better price, quality or service to keep them.", 2),
            ("Why might strawberries cost less in summer than in winter where you live?", "Local strawberries are ripe, so supply is high", "People dislike strawberries in summer",
             "Strawberries weigh more in winter", "In summer, local farms grow lots of strawberries. High supply usually means lower prices; in winter they may travel far.", 2),
            ("A shortage of flour hits your town. What might a bakery do?", "Find another supplier and plan carefully what to bake", "Stop telling customers anything at all",
             "Throw away the flour it has left", "Looking for other suppliers and baking the best sellers first helps the bakery keep serving customers.", 2),
            ("Which event would most likely raise demand for umbrellas?", "A week of rainy weather", "A long dry, sunny spell",
             "A sale on sunglasses", "When it rains, people need umbrellas. Weather is one of the biggest drivers of demand.", 2),
            ("You run a beach snack stand. On which day should you have the most stock?", "A hot, sunny holiday weekend", "A cold, windy weekday",
             "A rainy day in winter", "Hot days and holidays bring crowds to the beach. More people means more demand for snacks.", 2),
            # Level 3
            ("Why do prices act like a signal?", "High prices tell sellers to make more and buyers to buy less", "Prices tell customers which color to pick",
             "Prices never change, so they signal nothing", "When prices rise, makers want to supply more and buyers cut back. That helps balance supply and demand.", 3),
            ("Concert tickets sell out in minutes. What does that tell the organizers?", "Demand was higher than the supply of seats", "Supply was higher than demand",
             "Hardly anyone wanted to go", "Selling out fast means more people wanted seats than there were. Next time they might book a bigger place.", 3),
            ("A store raises its price on a toy, and sales drop from 20 to 5 a week. What does this show?", "Buyers bought much less when the price went up", "Buyers didn't care about the price at all",
             "Raising prices always increases sales", "Higher prices usually lower how many people buy. Owners test prices carefully to find the right balance.", 3),
            ("You sell 40 cups of lemonade on hot days. Tomorrow is hot, and you have enough for 15 cups. How many more cups should you prepare?", "25 more cups", "15 more cups",
             "40 more cups", "On a hot day expect about 40 cups. You have 15, and 40 minus 15 is 25 more.", 3),
            ("Why should a store avoid raising prices hugely on basic needs during an emergency?", "Customers remember it, and in many places it is illegal", "Customers never notice prices in emergencies",
             "It makes supply grow overnight", "Many places have rules against price gouging in emergencies. Treating people fairly builds trust that lasts long after.", 3),
            ("A shop orders its holiday stock 2 months early. What risk is it avoiding?", "Suppliers running low when every shop wants the same items", "Customers buying too little after the holiday",
             "Being too ready for the holiday rush", "Before big holidays, many shops order the same things. Ordering early helps you get stock before suppliers run short.", 3),
            ("Two shops sell the same bike. One is cheaper; the other gives free repairs. Why might people choose the pricier one?", "They value the extra service more than the price gap", "People always buy the most expensive thing",
             "Cheaper bikes are always broken", "Competition is not only about price. Service, quality and trust can matter more to many buyers.", 3),
            ("A farmer has 50 bags of apples. She can sell them for $2 a bag at a busy fall market or $1 a bag in a slow week. How much more does she earn at the busy market?", "$50 more", "$100 more",
             "$25 more", "At $2 a bag she earns $100; at $1 a bag she earns $50. The difference is $50. Selling when demand is high pays.", 3),
            ("What can happen if a business stocks up for a rush that never comes?", "It is left with a surplus it must sell off", "It always earns extra money anyway",
             "Its supplier must buy everything back", "Over-planning creates extra stock. Studying past sales and forecasts helps make better guesses.", 3),
            ("How can a business use last year's sales to plan for this year?", "Look at which weeks were busy and prepare for them again", "Ignore them because every year is totally random",
             "Copy last year's orders without checking anything", "Past sales show patterns like holiday rushes. Use them as a guide, then adjust for what is new this year.", 3),
            ("Many new bakeries open in a small town. What is likely to happen to each bakery's sales?", "Each may sell less as customers spread out", "Each will sell much more than before",
             "Every bakery's sales stay exactly the same", "More sellers split the same customers. To stand out, each bakery must offer something special.", 3),
            ("A game is so popular it sells out, so its maker builds many more copies. If demand stays the same, what happens over time?", "The shortage ends and prices may come down", "The shortage gets much worse",
             "Prices must keep climbing forever", "More supply meets the demand, so empty shelves fill up and sellers no longer need high prices.", 3),
        ],
        "facts": [
            ("When many people want something that is hard to find, its price often goes up.", True,
             "High demand and low supply let sellers charge more, because buyers compete for the few items."),
            ("A surplus means there is not enough of something.", False,
             "A surplus is extra, more than people want. Not enough is called a shortage."),
            ("Demand for some products changes with the seasons.", True,
             "Sunscreen sells in summer, coats in winter and pumpkins in fall. Smart owners plan for these swings."),
            ("Competition always makes prices go up.", False,
             "Competition usually keeps prices lower, because buyers can choose another seller."),
            ("Stores often lower prices to sell extra stock.", True,
             "A sale makes buyers more interested, turning a surplus back into cash and freeing up space."),
            ("Supply means how much people want to buy.", False,
             "That is demand. Supply is how much of something is available to sell."),
            ("Planning ahead for busy times helps a business avoid running out.", True,
             "Ordering stock and lining up helpers early means you are ready when the rush arrives."),
            ("Weather has no effect on what people buy.", False,
             "Rain sells umbrellas and heat sells cold drinks. Weather is one of the biggest drivers of demand."),
            ("Businesses can compete with better service, not just lower prices.", True,
             "Friendly help, quality and trust win customers too, even when a rival is a bit cheaper."),
            ("When a price goes up, people usually buy more of it.", False,
             "Usually, higher prices mean people buy less. That is why owners test prices carefully."),
            ("Past sales can help a business guess what customers will want next season.", True,
             "Sales records show patterns, like busy holidays, that often repeat each year."),
            ("A shortage means shelves are overflowing with extra items.", False,
             "Overflowing shelves mean a surplus. A shortage means people want more than there is."),
        ],
    },
    {
        "key": "safety",
        "title": "Safety First",
        "tagline": "Keep everyone safe at work",
        "icon": "hardhat",
        "cards": [
            ("Why safety rules exist", "Safety rules come from lessons learned, often after someone got hurt. Following them keeps workers and customers safe every day."),
            ("Spot it, report it", "If you see a spill, a broken step or a frayed cord, tell a supervisor or adult right away. Never try to fix dangerous things yourself."),
            ("Protective gear", "Gloves, goggles, helmets and hairnets protect your body. Wear the right gear for the job every time, even for quick tasks."),
            ("Exits and drills", "Know where the exits are and keep them clear. Practice drills so everyone knows what to do and where to meet in an emergency."),
            ("Clean hands, safe lifts", "Scrub hands with soap for about 20 seconds before touching food. Lift with your legs, not your back, and ask an adult for help with heavy loads."),
        ],
        "questions": [
            # Level 1
            ("You see water spilled on the shop floor. What should you do first?", "Warn people nearby and tell an adult or supervisor", "Walk around it and forget about it",
             "Run across it to get to the other side", "Spills cause slips. Warning others and reporting it keeps people safe until it is cleaned up.", 1),
            ("Why do people wear safety goggles?", "To protect their eyes from flying bits or splashes", "To look cool while they are working",
             "To help them see better in the dark", "Eyes are easy to hurt and hard to heal. Goggles block chips, dust and splashes.", 1),
            ("How long should you scrub your hands with soap?", "About 20 seconds", "About 2 seconds",
             "About 5 minutes", "About 20 seconds, like humming a short song twice, gives soap time to loosen germs. Then rinse and dry.", 1),
            ("When should food workers wash their hands?", "Before handling food and after using the restroom", "Only at the end of the work day",
             "Only when their hands look dirty", "Germs are invisible. Washing at key times stops them spreading to food and customers.", 1),
            ("What is an emergency exit for?", "A safe way out of a building in an emergency", "A place to store extra boxes",
             "A shortcut for taking out the trash", "Exits must always stay clear so everyone can get out fast if there is a fire or other emergency.", 1),
            ("Why do schools and businesses hold fire drills?", "So everyone practices how to get out safely", "To give everyone a break from work",
             "To test how loud the alarm can be", "Practicing means people know the way out and where to meet, so they stay calm in a real emergency.", 1),
            ("What is a hazard?", "Something that could cause harm or injury", "A tool that is brand new",
             "A rule about lunch breaks", "Hazards include spills, sharp edges, loose cords and blocked exits. Spotting them early prevents injuries.", 1),
            ("Which is an example of protective gear?", "Gloves for handling sharp or hot things", "A fancy wristwatch",
             "A shiny name tag", "Protective gear shields your body from harm. Gloves guard hands from cuts, burns and chemicals.", 1),
            ("How should you lift a light box from the floor?", "Bend your knees and keep your back straight", "Bend at your waist and pull up fast",
             "Twist your body while you lift", "Your legs are stronger than your back. Bending your knees and holding the box close protects your back.", 1),
            ("A box looks too heavy for you. What should you do?", "Ask an adult for help or use a cart", "Try hard to lift it anyway",
             "Kick it across the floor", "Lifting too much can hurt your back. A helper or a cart moves heavy things safely.", 1),
            ("Why do safety rules exist?", "To keep people from getting hurt", "To make work boring",
             "To slow workers down for no reason", "Most safety rules were written after people got hurt. They protect workers and customers.", 1),
            ("You see a frayed electrical cord on a machine. What should you do?", "Don't touch it and tell a supervisor right away", "Wrap it with tape yourself",
             "Keep using the machine carefully", "Damaged cords can shock people or start fires. Only a trained adult should handle it, so stay away and report it.", 1),
            # Level 2
            ("An adult in a hurry says to skip the safety check just this once. What is the best response?", "Politely remind them the check is required and do it", "Skip it since everyone is in a hurry",
             "Skip it but don't tell anyone", "Accidents happen when people rush. A quick check takes minutes; an injury can last a lifetime.", 2),
            ("What is the main reason workers get safety training?", "So they know how to do tasks without getting hurt", "So they can skip reading the rules",
             "So they can do dangerous jobs alone", "Training teaches the safe way to use tools and handle problems, so mistakes don't turn into injuries.", 2),
            ("Why must raw meat be kept away from ready-to-eat food?", "Germs from raw meat can spread and make people sick", "Raw meat makes other food taste better",
             "It only matters for how the fridge looks", "This is called cross-contamination. Separate cutting boards and storage keep germs off food that won't be cooked.", 2),
            ("Why should cold food be kept in a fridge?", "Cold slows the growth of germs", "Cold food always tastes sweeter",
             "Fridges make food last forever", "Germs grow fast in warm food. Keeping it cold slows them, though food still has a use-by date.", 2),
            ("What is a safety inspection?", "A careful check for hazards and broken equipment", "A party to celebrate a safe year",
             "A test to see who works fastest", "Inspections find problems like blocked exits or worn cords before they cause injuries.", 2),
            ("Where should everyone go during a fire drill?", "To the planned meeting spot outside", "Back to their desk to grab their things",
             "Into the nearest closet to hide", "A meeting spot lets leaders count everyone and know nobody is left inside.", 2),
            ("Why should you never block an emergency exit, even for a minute?", "An emergency can happen at any moment", "Exits are only for the boss to use",
             "Blocked exits make the shop look neater", "Fires and other emergencies give no warning. A clear exit can save lives in seconds.", 2),
            ("A floor has just been mopped. What should go next to it?", "A wet floor warning sign", "A sign saying the shop is closed",
             "A box to cover the wet spot", "A warning sign tells people to walk carefully or go around, which prevents slips.", 2),
            ("A coworker is using a cleaning chemical without gloves. What should you do?", "Kindly remind them and tell a supervisor if needed", "Laugh about it with the others",
             "Hide their gloves as a joke", "Looking out for each other keeps the whole team safe. A kind reminder is the first step.", 2),
            ("Which is the safest way to get something from a high shelf?", "Ask an adult to use a proper step ladder", "Climb up the shelves yourself",
             "Stand on a rolling office chair", "Climbing shelves or chairs leads to falls. A proper ladder used by an adult is much safer.", 2),
            ("A worker gets a small cut at work. Besides first aid, what should happen?", "Report it so the cause can be found and fixed", "Hide it so nobody worries",
             "Keep working without telling anyone", "Reporting even small injuries helps find hazards, like a sharp edge, before someone gets hurt worse.", 2),
            ("Why do food workers often wear hairnets or hats?", "To keep hair out of the food", "To keep their heads warm",
             "To show which team they are on", "Hair can carry germs and nobody wants it in their meal. Hairnets keep food clean and safe.", 2),
            ("Why should a business keep a first aid kit stocked and easy to find?", "So small injuries can be treated right away", "So workers can take supplies home",
             "Because kits make the shop look busy", "Quick care for cuts and burns helps stop them from getting worse. A kit is useless if it is empty or hidden.", 2),
            # Level 3
            ("A worker almost tripped on a loose mat but didn't fall. Why should this 'near miss' be reported?", "It shows a hazard that could hurt someone next time", "It doesn't matter because nobody was hurt",
             "Reporting it gets the worker in trouble", "Near misses are free warnings. Fixing the mat now prevents a real injury later.", 3),
            ("Skipping safety gear saves 1 minute per task. Why is it still a bad trade?", "One injury can cost weeks of pain and missed work", "Gear makes each task take hours longer",
             "Saved minutes matter more than safety", "A minute saved is tiny compared with an injury that could cost health, money and time. Safety is always worth it.", 3),
            ("A shop has 4 fire extinguishers, and each must be checked once a month. How many checks is that in a year?", "48 checks", "16 checks",
             "12 checks", "4 extinguishers times 12 months is 48 checks. Regular checks make sure they work when needed.", 3),
            ("You spot a hazard. In what order should you act?", "Keep people away, tell a supervisor, let trained adults fix it", "Fix it yourself, then maybe tell someone",
             "Take a photo, post it online, then walk away", "Protect people first, report it fast, and leave repairs to trained adults.", 3),
            ("Why are many safety rules written after accidents?", "People learn what went wrong and make rules to stop it", "Rule writers like to punish workers",
             "Accidents make rules unnecessary", "Many safety rules are lessons learned the hard way. Following them means you don't have to learn those lessons yourself.", 3),
            ("Why is it better to remove a hazard than just warn people about it?", "Removing it means nobody can get hurt by it", "Warnings always cost more money",
             "Warning signs are never allowed at work", "Warnings help, but people can miss them. Removing or fixing the hazard is the strongest protection.", 3),
            ("A new worker hasn't been trained on the meat slicer. What should happen?", "They must not use it until they are trained", "They should try it to learn fast",
             "They can use it if nobody is watching", "Slicers can cause serious cuts. Only trained adult workers who are allowed should use them; kids should not use them at all.", 3),
            ("A recipe says to cool soup quickly before storing it. Why?", "Germs grow fastest in warm food", "Hot soup tastes worse the next day",
             "Fridges break if anything warm goes in", "Leaving food warm for hours lets germs multiply. Cooling it fast keeps it safe to eat later.", 3),
            ("Your family store gets busy, and boxes pile up in the hallway to the exit. What is the best fix?", "Move the boxes and find a proper storage place", "Leave them because the rush will end soon",
             "Put up a sign saying the exit may be blocked", "Exits must stay clear at all times. Finding real storage space fixes the cause, not just today's pile.", 3),
            ("Why should safety gear fit properly?", "Gear that doesn't fit can slip off or fail to protect", "Loose gear is more comfortable and safer",
             "Fit doesn't matter as long as you wear it", "Gloves that are too big can catch on things, and loose goggles let dust in. Gear only protects when it fits.", 3),
            ("A safety guard on a machine is slowing down work. What should the team do?", "Keep the guard on and look for other safe ways to speed up", "Remove the guard to work faster",
             "Tape the guard open when the boss leaves", "Guards keep hands away from moving parts. Never remove safety parts; improve speed in other safe ways.", 3),
            ("A weekly safety walk-through finds 3, then 2, then 1, then 0 hazards. What does this show?", "Checking often and fixing problems is working", "Inspections can stop for good now",
             "The store is getting more dangerous", "Hazards dropped each week, which shows the checks and fixes work. Keep inspecting so new hazards are caught.", 3),
            ("Why should kids never run dangerous machines at a family business, even after watching adults?", "Watching is not training, and some jobs are for adults only", "Kids always learn faster than adults",
             "Machines are safe if you are careful", "In many places, rules limit which jobs kids can do. Dangerous machines need training plus adult strength and judgment.", 3),
        ],
        "facts": [
            ("Washing hands with soap helps stop germs from spreading to food.", True,
             "Soap and scrubbing loosen germs so water can rinse them away before they reach food."),
            ("It is okay to skip safety gear for a quick job.", False,
             "Accidents can happen in seconds. Wear the right gear every time, even for short tasks."),
            ("A near miss is a warning sign worth reporting.", True,
             "A near miss shows a hazard before anyone gets hurt, so it can be fixed in time."),
            ("Emergency exits can be used for storage when the business is busy.", False,
             "Exits must stay clear at all times. Emergencies don't wait for the rush to end."),
            ("Your legs are stronger than your back for lifting.", True,
             "Bending your knees lets your strong leg muscles do the work and protects your back."),
            ("If you spot a hazard, the safest move is always to fix it yourself.", False,
             "Some hazards, like electrical problems, need trained adults. Keep people away and tell a supervisor."),
            ("Practicing drills helps people stay calm in a real emergency.", True,
             "When people have practiced, they know the way out and the meeting spot without having to think."),
            ("You can always see germs on your hands if you look closely.", False,
             "Germs are far too small to see. Hands can look clean and still carry germs, so wash them anyway."),
            ("Raw meat should be kept apart from food that is ready to eat.", True,
             "Keeping them apart stops germs from raw meat spreading to food that won't be cooked."),
            ("Safety training is only needed on a worker's first day.", False,
             "Refresher training keeps skills sharp, and new tools or rules need new training too."),
            ("Keeping walkways clear helps prevent trips and falls.", True,
             "Boxes, cords and spills in walkways are common causes of injuries. Clear paths keep everyone safe."),
            ("Safety rules are mostly made to slow workers down.", False,
             "Safety rules exist to prevent injuries. Many were written after someone got hurt."),
        ],
    },
]
