"""Academy question bank: the Rules and Trust unit."""

WORLDS = [
    {
        "key": "ethics",
        "title": "Do the Right Thing",
        "tagline": "Honesty, fairness and integrity",
        "icon": "compass",
        "cards": [
            ("Integrity", "Integrity means doing the right thing even when nobody is watching. Return extra change, fix hidden mistakes, and follow safety rules every time."),
            ("Keep Your Promises", "A promise is something people count on. If you cannot keep one, tell them early and offer a fair fix. Broken promises break trust."),
            ("Fair to Everyone", "Treat every customer and worker with respect. Pay the same for the same work, post clear prices, and choose people for skill, not friendship."),
            ("Conflicts of Interest", "A conflict of interest is when something personal, like family or a gift, could sway a business choice. Tell others about it and let fair rules decide."),
            ("Speak Up", "If you see cheating or danger, tell a trusted adult or the right person in charge. Owning up to your own mistakes fast is part of speaking up too."),
        ],
        "questions": [
            # Level 1
            ("A customer pays you $20 for a $10 item by mistake. What should you do?", "Give back the extra $10",
             "Keep it, since it was their mistake", "Put the extra $10 in the tip jar",
             "Honest businesses fix mistakes even when the mistake helps them. Customers remember it and come back.", 1),
            ("What does integrity mean?", "Doing what is right even when nobody is watching",
             "Doing whatever makes the most money today", "Following rules only when a boss is nearby",
             "Integrity means your actions match your values all the time, not just when someone is checking.", 1),
            ("You promised a neighbor cookies by Saturday, but you are behind. What is best?", "Tell them early and offer a new day",
             "Say nothing and hope they forget", "Rush and deliver burnt cookies on time",
             "Telling people early shows respect and lets them plan. Hiding a problem makes it worse when they find out.", 1),
            ("You made a mistake on a customer's order. What is the best first step?", "Admit it and offer to fix it",
             "Blame the customer for ordering wrong", "Pretend the order was right all along",
             "Owning mistakes quickly builds trust. Most customers forgive a mistake that is fixed fast and honestly.", 1),
            ("Which is an example of honesty in a bakery?", "Marking yesterday's bread as day-old",
             "Calling day-old bread 'baked this morning'", "Hiding the bake date so nobody asks",
             "Honest labels let customers choose for themselves. Many bakeries sell day-old bread at a lower price, clearly marked.", 1),
            ("A new kid joins your team at the bike shop. How should you treat them?", "With the same respect as everyone else",
             "Give them only the jobs nobody wants", "Ignore them until they prove themselves",
             "Respect for everyone helps people do their best work. A welcoming team is a stronger team.", 1),
            ("You find a wallet left in your family's shop. What should you do?", "Keep it safe and try to return it",
             "Take the cash and leave the wallet", "Leave it on the counter for anyone",
             "Returning lost things is the right thing to do, and it shows customers your shop can be trusted.", 1),
            ("Your helper at the lemonade stand worked as hard as you. How should you pay them?", "The way you both agreed before starting",
             "Nothing, because the stand was your idea", "With leftover cups instead of money",
             "Fairness means keeping the deal you made with workers. Agree on pay before work starts so nobody feels cheated.", 1),
            ("What is a promise in business?", "Your word that you will do something",
             "A nice idea you can drop if you get busy", "Something that only matters if it is written",
             "Customers and partners plan around your promises. Keeping them is how a business earns a good name.", 1),
            ("Nobody is watching the cash box at the school fair stand. What should you do?", "Act the same as if everyone were watching",
             "Borrow a few dollars and pay them back later", "Leave it open since nobody will check",
             "Taking money that is not yours is wrong even if you plan to return it. Doing right when alone is real integrity.", 1),
            ("A customer speaks a different language and is slow to order. What is best?", "Be patient and try to help them",
             "Serve other people first and skip them", "Laugh with friends about how they talk",
             "Every customer deserves respect. Patience and kindness make people feel welcome and want to come back.", 1),
            ("Which is a good way to build trust with customers?", "Tell the truth, even when it is not fun to hear",
             "Promise anything to make the sale today", "Only ever say good things about your product",
             "Trust grows when people learn your words are true. One lie can undo years of good work.", 1),
            # Level 2
            ("Your bike shop is out of the right part. A cheaper part might fail. What should you do?", "Explain the choice and let the customer decide",
             "Use the cheaper part and not mention it", "Charge for the good part but use the cheap one",
             "Customers have a right to know what they are buying. Hiding a cheaper part is cutting corners and can be unsafe.", 2),
            ("What is 'cutting corners'?", "Skipping steps that keep work safe or good",
             "Finishing a job early because you planned well", "Trimming cardboard boxes to fit the shelves",
             "Cutting corners saves a little time but can hurt quality and safety. It often costs more later.", 2),
            ("Your uncle sells flour, and you buy flour for the family bakery. What is the honest move?", "Tell the family and compare prices",
             "Buy from him without telling anyone at all", "Pay him extra because he is family",
             "This is a conflict of interest: a personal tie that could sway a business choice. Being open and comparing keeps it fair.", 2),
            ("What is a conflict of interest?", "When a personal tie could sway a business choice",
             "When two customers both want the very last cake", "When two workers argue about the lunch schedule",
             "Family ties or gifts can pull you away from what is fair. Being open about them lets others check that choices are fair.", 2),
            ("A supplier offers you a free video game if you pick their company. What should you do?", "Say no and choose on price and quality",
             "Take the game, since gifts are always fine", "Take it, pick them, and keep it a secret",
             "Gifts meant to sway a choice can be a kind of bribe. Good owners pick suppliers for what is best for the business.", 2),
            ("You notice a coworker taking snacks from the shop without paying. What is a good first step?", "Tell a trusted adult or the manager",
             "Start taking snacks too, since it seems allowed", "Post about it online to embarrass them",
             "Telling the right person lets an adult handle it fairly. Posting online or joining in only makes things worse.", 2),
            ("Your cleaning service missed a spot at a customer's home. They didn't notice. What is best?", "Go back and clean it, or tell them and fix it",
             "Leave it, since they will never know", "Charge them extra next time to make up for it",
             "Doing good work when nobody checks is integrity, and it protects your good name.", 2),
            ("Two workers do the same job equally well. What is fair pay?", "The same pay for the same work",
             "More pay for the one who is your friend", "Less pay for the one who is quieter",
             "Fair pay is based on the job and how well it is done, not on friendship or personality.", 2),
            ("Your sign says your lemonade has 'no sugar', but it does. Why is that a problem?", "It is false and could hurt people avoiding sugar",
             "It is fine, since signs always stretch the truth", "It is only a problem if someone complains",
             "False claims mislead customers and can harm their health. In many places, lying in ads is against the law.", 2),
            ("You broke a customer's bike part while fixing it. What should you do?", "Tell them, apologize, and pay to fix it",
             "Hide it and hope they do not notice", "Say it was already broken when it came in",
             "Taking responsibility shows you can be trusted. Lying about it could cost you the customer and your good name.", 2),
            ("A worker at your bakery warns you about a safety problem with the oven. How should you react?", "Thank them and get it checked right away",
             "Tell them to stop complaining and keep baking", "Wait until the oven fully breaks down",
             "People who speak up about safety protect everyone. Thanking them makes others feel safe to speak up too.", 2),
            ("Which is an example of treating customers fairly?", "Charging everyone the same posted price",
             "Charging more to people who look rich", "Giving bigger scoops only to your friends",
             "Clear prices for everyone are fair. Sales are fine too, as long as they are open to all customers.", 2),
            # Level 3
            ("Your best friend applies for a job at your family shop, but another person has more skill. What is fairest?", "Hire the best fit and tell your friend kindly",
             "Hire your friend and hide the other application", "Hire both and ask one to work for free",
             "Fair hiring is based on skill. Being kind and honest with your friend protects both the business and the friendship.", 3),
            ("Your boss asks you to write a 5-star review of your own shop under a fake name. What is best?", "Politely say no, since fake reviews mislead people",
             "Write it, because the boss asked you to", "Write it, but give 4 stars so it looks real",
             "Fake reviews trick customers and are against the rules in many places. Saying no politely is doing the right thing.", 3),
            ("You told a customer a repair would take 2 days. Now it will take 5. When should you tell them?", "As soon as you know about the delay",
             "On day 2, when they come to pick it up", "Only if they call and ask about it",
             "Early news lets the customer plan. Waiting until the last moment breaks trust, even if the delay was not your fault.", 3),
            ("Which best describes a whistleblower?", "Someone who reports wrongdoing to stop it",
             "Someone who blows a whistle to start a sports game", "Someone who spreads rumors about coworkers",
             "Whistleblowers speak up about real problems like cheating or danger. Many places have rules that protect them.", 3),
            ("You see an adult at work hiding broken safety gear so an inspector won't see it. What should you do?", "Tell a trusted adult or the right person in charge",
             "Help hide it so nobody gets in trouble", "Keep quiet because it is not your business",
             "Hiding safety problems can get people hurt. Telling a trusted adult or the right person is the brave and right choice.", 3),
            ("A big customer offers a huge order if you skip a safety check. What is best?", "Keep the safety check and explain why",
             "Skip it this once, since the order is big", "Skip it but write down that you did it",
             "Safety rules protect people. Skipping them or faking records can cause harm, fines and lost trust.", 3),
            ("Your shop's scale adds a little extra weight, so customers pay a bit more. What is right?", "Fix it and make things right with customers",
             "Leave it, since each extra amount is tiny", "Fix it quietly and keep the extra money",
             "Small overcharges still take money that is not yours. In many places, scales used for selling must be accurate by law.", 3),
            ("You are judging a school business contest and your cousin enters. What should you do?", "Tell the organizers and step back from that entry",
             "Give your cousin a top score to be loyal", "Judge as normal and tell no one about it",
             "This is a conflict of interest. Stepping back lets someone else judge fairly and keeps the contest trusted.", 3),
            ("A worker made an honest mistake that cost the shop $50. What is the best owner response?", "Talk it through and help them learn",
             "Yell at them in front of the customers", "Act like it never happened at all and move on",
             "Calm feedback helps people learn. If honest mistakes are punished harshly, people start hiding them instead.", 3),
            ("Why does honesty help a business earn more over time?", "Trust brings customers back, and they tell friends",
             "Honest businesses never have to pay any bills", "Honesty lets you charge any price you want",
             "Repeat customers and good word of mouth are worth a lot. Trust is one of the most valuable things a business has.", 3),
            ("A rule seems silly to you, like washing hands before baking. What is the right approach?", "Follow it, and ask an adult why it exists",
             "Skip it whenever you are in a hurry", "Make up your own rule that seems better",
             "Many rules have reasons you cannot see, like stopping germs. Asking why helps you learn instead of guessing.", 3),
            ("You promised a customer free delivery, then fuel prices rose. What is the fair thing?", "Keep it, and change prices for future orders",
             "Charge them for delivery after all", "Cancel their order without explaining anything",
             "A promise made should be kept. You can change prices for the future if you tell customers clearly before they buy.", 3),
        ],
        "facts": [
            ("It's okay to bend the rules if nobody will find out.", False,
             "Rules protect people whether or not anyone is watching, and secrets usually come out."),
            ("Admitting a mistake quickly often helps customers trust you more.", True,
             "People know everyone makes mistakes. What they remember is whether you were honest and fixed it."),
            ("A conflict of interest should be shared openly so others can check the choice.", True,
             "Having a personal tie is not always wrong. Hiding it is what makes a choice look unfair."),
            ("If a customer does not notice your mistake, you do not need to fix it.", False,
             "Integrity means fixing problems even when nobody notices. Hidden mistakes often show up later anyway."),
            ("In many places, workers who report real wrongdoing are protected by law.", True,
             "These rules help people speak up about danger or cheating without fear of losing their job."),
            ("Being honest means you must share every private thing about your business.", False,
             "Honesty means not lying or tricking people. You can keep a secret recipe private and still be honest."),
            ("Treating workers fairly helps a business keep good people.", True,
             "Workers who feel respected and fairly paid tend to stay, work harder, and help customers more."),
            ("Fake online reviews are fine as long as your product is good.", False,
             "Fake reviews trick customers no matter how good the product is, and they break the rules in many places."),
            ("One broken promise can undo a lot of trust you built.", True,
             "Trust takes a long time to build and can be lost fast. That is why careful owners only promise what they can do."),
            ("Respect only matters for customers who spend a lot of money.", False,
             "Every customer deserves respect. Small customers can become big ones, and they all talk to friends."),
            ("Doing the right thing can cost money in the short term.", True,
             "Refunding a mistake costs money today, but the trust it builds usually pays back much more over time."),
            ("If your boss tells you to do something wrong, it becomes okay.", False,
             "Wrong is still wrong. You can say no politely and tell a trusted adult or the right person."),
            ("Clear, posted prices help treat every customer fairly.", True,
             "When everyone sees the same price, nobody is charged more because of who they are or how they look."),
            ("Cutting corners always saves money in the end.", False,
             "Skipped steps often lead to broken products, refunds, injuries or fines that cost far more later."),
        ],
    },
    {
        "key": "contracts",
        "title": "Deals and Contracts",
        "tagline": "Promises in writing",
        "icon": "scroll",
        "cards": [
            ("What Is a Contract?", "A contract is an agreement the law can enforce. Both sides agree, and each gives something, like money for cupcakes. It can be spoken or written."),
            ("Read Before You Sign", "Never sign something you have not read and understood. Ask about any part that is unclear. A signature means you agree to all of it, even small print."),
            ("Clear Terms", "Good deals say what will be done, how much it costs, and when it is due. Clear terms stop arguments before they start."),
            ("Keep Your Side", "Once you agree, do what you promised, on time. If something goes wrong, talk early. Breaking a deal can mean paying for the harm it causes."),
            ("Get It in Writing", "Spoken deals can count, but memories fade. Writing it down gives proof of what you agreed. For big deals, ask a lawyer to check it first."),
        ],
        "questions": [
            # Level 1
            ("What is a contract?", "An agreement the law can enforce",
             "A thank-you note you send after a sale", "A list of things you want to buy someday",
             "Contracts turn promises into agreements with rules. If one side breaks it, the other can ask for help to make it right.", 1),
            ("Before you sign a paper, what should you do first?", "Read it all and ask about anything unclear",
             "Sign quickly so you do not look unsure", "Read only the first line and the price",
             "Your signature means you agree to everything in it, even the small print. Reading first protects you.", 1),
            ("Which is an example of a deal?", "You mow a lawn and get paid $15",
             "You mow your own lawn just for fun", "You watch your neighbor mow their lawn",
             "A deal has both sides giving something, here work for money. That exchange is at the heart of most contracts.", 1),
            ("For a contract to work, who must agree to it?", "Both sides",
             "Only the side that pays", "Only the side that wrote it",
             "A contract needs both sides to agree to the same terms. One side cannot force a deal on the other.", 1),
            ("Which three things should a good deal make clear?", "What, how much, and when",
             "Who is older, taller, and smarter", "The weather, the music, and the snacks",
             "Clear terms say what is being done, the price, and the deadline. That stops confusion later.", 1),
            ("You agreed to bake 20 cupcakes for a party by Friday. What should you do?", "Deliver 20 cupcakes by Friday",
             "Deliver 10 cupcakes and keep the rest", "Deliver them next week instead",
             "Keeping your side of the deal means doing exactly what you agreed, on time.", 1),
            ("What does your signature on a contract mean?", "That you read it and agree to it",
             "That you liked the paper it was on", "That you might think about it later",
             "Signing shows you agree to the terms. That is why reading first matters so much.", 1),
            ("Your neighbor says, 'I'll pay you $5 to walk my dog Saturday.' You say yes. Is that a deal?", "Yes, a spoken agreement is still a deal",
             "No, a deal only counts if it is typed", "No, a deal only counts if a judge sees it",
             "Spoken agreements can be real deals. Writing them down just makes them easier to prove later.", 1),
            ("Why is it smart to write a deal down?", "So both sides remember the same terms",
             "So it looks fancy hanging on the wall", "So you can change it later without asking",
             "Memories fade and people remember things differently. Writing it down gives proof of what was agreed.", 1),
            ("A paper you are asked to sign has words you do not understand. What should you do?", "Ask someone you trust to explain them first",
             "Sign it and look the words up later", "Guess what they mean and hope for the best",
             "Never agree to what you do not understand. A trusted adult or a lawyer can explain hard words.", 1),
            ("What is the 'price' part of a deal?", "How much will be paid",
             "When the job will be done", "Where the job will happen",
             "The price says how much money changes hands. Writing it clearly stops arguments over money.", 1),
            ("You can't finish a job you agreed to do. What is best?", "Tell the other side early and work out a fix",
             "Disappear and stop answering their messages", "Finish half and still ask for full pay",
             "Talking early gives both sides time to adjust. Hiding makes the problem bigger and hurts trust.", 1),
            # Level 2
            ("You agree to paint a fence for $40, with half paid at the start. How much is paid at the start?", "$20",
             "$40", "$10",
             "Half of $40 is $20. Splitting payment, some at the start and some at the end, is common in deals.", 2),
            ("A party orders 3 cakes from your bakery at $25 each. What total goes in the contract?", "$75",
             "$50", "$100",
             "3 times $25 is $75. Checking the math before you sign makes sure the total is right.", 2),
            ("A contract says delivery will happen 'soon'. What is the problem?", "'Soon' is unclear, so people may disagree",
             "It is too short to be a real contract", "Contracts are not allowed to mention delivery",
             "Vague words cause fights. A clear date leaves no room for confusion about when something is due.", 2),
            ("What can happen if someone breaks a contract?", "They may have to make up for the harm caused",
             "Nothing, since contracts are just paper", "The other side can take anything they want",
             "When a deal is broken, the other side can ask to be paid back for losses, sometimes with help from a court.", 2),
            ("A customer wants to change a deal after you both agreed. What should happen?", "Both sides agree to it, ideally in writing",
             "The customer just changes it on their own", "You must accept any change they ask for",
             "A deal changes only when both sides agree. Writing the change down keeps everyone clear.", 2),
            ("Which detail belongs in a bike repair deal?", "The price and the ready date",
             "The color of the shop's front door", "The name of your favorite bike brand",
             "Price and timing are key terms. Details that do not affect the job just add clutter.", 2),
            ("Why might a spoken deal cause trouble later?", "People can remember the terms differently",
             "Spoken deals are always against the law", "Spoken words can never count as a promise",
             "Spoken deals can be real, but they are hard to prove. Writing down the key terms prevents 'I never said that.'", 2),
            ("You rent a market stall for $30 a day for 4 days. How much do you owe?", "$120",
             "$34", "$90",
             "$30 times 4 days is $120. Always work out the full total before you agree.", 2),
            ("What is 'the fine print' in a contract?", "Small or detailed text that still counts",
             "Pretty pictures printed along the edges", "A part you can skip because it is small",
             "Fine print is still part of the deal. Important rules, like extra fees, are often found there.", 2),
            ("Your family shop is about to sign a 5-year lease for a store. What is wise?", "Have a lawyer review it before signing",
             "Sign right away before the price changes", "Let the landlord explain it and skip reading",
             "Big, long deals can have big costs. A lawyer knows what to look for and can spot problems early.", 2),
            ("What is a deadline in a contract?", "The date something must be done by",
             "The very last line of the contract", "The day the contract was printed",
             "Deadlines tell both sides when work or payment is due, so everyone can plan.", 2),
            ("Why should both sides keep a copy of a signed contract?", "So each can check what was agreed later",
             "So each can change their own copy", "So the contract counts twice as much",
             "A copy lets each side check the terms if a question comes up. Never change a signed copy on your own.", 2),
            # Level 3
            ("You agreed to sell 50 cookies at $1 each but can only deliver 40. What is fair to charge?", "$40, and tell the buyer why",
             "$50, because that was the deal", "$45, to split the difference",
             "Charge only for what you delivered: 40 times $1 is $40. Telling the buyer early about the shortfall keeps trust.", 3),
            ("A supplier misses a delivery date in your contract, and your bakery loses an order. What can you usually do?", "Ask them to cover the loss as the deal allows",
             "Refuse to pay any supplier ever again", "Post mean things about their whole family online",
             "Contracts often say what happens if a side breaks the deal. Following those steps, sometimes with a lawyer, is the fair way.", 3),
            ("What is a 'late fee' in a contract?", "An extra charge, agreed ahead, for paying late",
             "A gift you receive for paying on time", "A fee for showing up late to a meeting",
             "Late fees push people to pay on time. Because they are in the contract, both sides know about them before signing.", 3),
            ("Someone pressures you: 'Sign now or the deal is gone!' What is best?", "Take time to read it, or walk away",
             "Sign fast so you do not lose the deal", "Sign it now and read it afterward",
             "Pressure to rush is a warning sign. A fair partner gives you time to read and ask questions.", 3),
            ("A contract says you pay $100 now, then $50 a month for 3 months. What is the total?", "$250",
             "$150", "$300",
             "$100 plus 3 payments of $50 ($150) equals $250. Adding up every payment shows the real cost.", 3),
            ("Why might a big deal explain what happens if there is a disagreement?", "So both sides know the steps to settle it",
             "So the deal can be canceled for no reason", "So nobody has to keep their promises",
             "Planning for disagreements ahead of time saves stress and money if one comes up.", 3),
            ("Which deal is the clearest?", "Paint the blue fence by May 3 for $60, paid when done",
             "Paint the fence sometime soon for a fair price", "Do some painting and we will figure out the pay",
             "It says what, when, how much, and when payment happens. Clear terms prevent arguments.", 3),
            ("You signed a deal, then find a better offer elsewhere. What is right?", "Keep your deal, or ask the other side to end it",
             "Ignore the deal and take the better offer", "Say you never agreed to anything at all",
             "A signed deal is a promise. You can ask to end it, but walking away without agreement can mean paying for their losses.", 3),
            ("A contract has a blank space where the price should be. What should you do?", "Fill in the price before anyone signs",
             "Sign it and let them fill it in later", "Sign it, since blank spaces do not matter",
             "A blank could be filled with anything later. Make sure every key term is written in before you sign.", 3),
            ("What makes an agreement a contract instead of just a friendly plan?", "Both agree and each gives something",
             "It is printed on very fancy, thick paper", "It uses lots of long, hard words",
             "A contract needs agreement and an exchange, like work for pay. Fancy paper and hard words do not matter.", 3),
            ("Your family business wants to buy another shop. Who should help with the contract?", "A lawyer who handles business deals",
             "A friend who once signed a phone plan", "Nobody, since it is like any small deal",
             "Big deals have many hidden risks. A business lawyer knows the rules and can protect the family.", 3),
            ("A deal says you deliver by Friday 'unless a storm closes the roads'. A storm hits. What happens?", "The delay is allowed because the deal says so",
             "You must pay a penalty no matter what", "The whole deal is canceled forever",
             "Contracts can plan for events nobody controls. Reading these parts tells you your rights when things go wrong.", 3),
        ],
        "facts": [
            ("A spoken agreement can be a real deal, but it is harder to prove.", True,
             "Spoken deals can count, but when memories differ, nobody can show what was agreed. Writing helps."),
            ("If you do not read a contract, you do not have to follow it.", False,
             "Signing usually means you agree to it all, read or not. That is why you read before you sign."),
            ("A good contract says what will happen, how much it costs, and when.", True,
             "What, how much, and when are the key terms. Leaving one out is a common cause of arguments."),
            ("Only one side needs to agree for a contract to work.", False,
             "A contract is a meeting of minds. Both sides must agree to the same terms."),
            ("Contracts are used for everyday things, like renting a stall or buying supplies.", True,
             "Contracts are not just for giant companies. Many normal business tasks are deals with terms."),
            ("Once you sign a contract, you can never ask to change it.", False,
             "You can always ask. A change works when both sides agree to it, ideally in writing."),
            ("Lawyers are only needed after something goes wrong.", False,
             "Lawyers help most before signing big deals, when they can spot problems early and cheaply."),
            ("Writing the date on a contract helps show when the deal was made.", True,
             "Dates matter for deadlines and payments. A dated contract makes the timeline clear."),
            ("If a deal goes badly, it is okay to just stop answering messages.", False,
             "Hiding makes things worse. Talking honestly is the best way to find a fair fix."),
            ("Many deals split payment, with part at the start and part at the end.", True,
             "Splitting payment shares the risk. The worker gets some money up front, and the buyer pays the rest when the job is done."),
            ("A handshake deal means there are no rules at all.", False,
             "A handshake can seal a real agreement. Both sides should still keep their word."),
            ("A contract can protect both sides, not just the one who wrote it.", True,
             "Clear terms tell each side what they will get, so both can count on the deal."),
            ("If the other side is a friend, you never need to agree on terms.", False,
             "Friends can remember things differently too. Clear terms protect the deal and the friendship."),
            ("Asking questions before you sign is a sign of a smart business owner.", True,
             "Good owners make sure they understand a deal first. Fair partners are happy to answer."),
        ],
    },
    {
        "key": "taxes",
        "title": "Taxes Explained",
        "tagline": "Why businesses pay taxes",
        "icon": "receipt",
        "cards": [
            ("What Are Taxes?", "Taxes are money people and businesses pay to the government. Taxes help pay for roads, schools, parks, firefighters and other things everyone shares."),
            ("Sales Tax", "In many places, a small extra amount is added when you buy things. The shop collects it from the customer and passes it on to the government."),
            ("Income Tax", "Businesses usually pay income tax on profit: the money left after costs. More profit usually means more tax. Never hide income."),
            ("Keep Good Records", "Save receipts and write down every sale and cost. Good records show what you earned and spent, and they make tax time much easier."),
            ("Pay on Time", "Taxes have due dates. Late or missing taxes can bring penalties and interest. An accountant can help you get it right and on time."),
        ],
        "questions": [
            # Level 1
            ("What are taxes?", "Money paid to the government for shared things",
             "Money you pay a store for a toy", "A fee you pay a friend for helping",
             "Taxes pay for things a whole community uses, like roads, schools and parks.", 1),
            ("Which is something taxes help pay for?", "Firefighters and fire trucks",
             "Your family's private vacation", "A new bike just for you",
             "Taxes pay for public services everyone can use, like firefighters who protect the whole town.", 1),
            ("A $10 toy has $1 sales tax. What does the customer pay?", "$11",
             "$10", "$9",
             "Sales tax is added on top of the price: $10 plus $1 is $11.", 1),
            ("In many places, who pays sales tax when you buy a toy?", "The customer, as part of the bill",
             "The worker who made the toy", "The store owner, from their own pocket",
             "In many places, the shop adds sales tax to the bill, collects it from the customer, and sends it to the government.", 1),
            ("Why should a business keep receipts?", "To show what it earned and spent",
             "Because receipts make nice bookmarks", "So it can throw them all out at once",
             "Receipts are proof. They help a business work out the right tax and answer questions later.", 1),
            ("What does an accountant do?", "Helps keep track of money and taxes",
             "Bakes bread for the business", "Fixes broken bikes for customers",
             "Accountants are experts in money records and tax rules. Many businesses hire one to get taxes right.", 1),
            ("Which of these jobs is often paid for with taxes?", "A public school teacher",
             "A clerk at a private toy shop", "A chef at a family restaurant",
             "Public schools are often paid for with taxes, so their teachers are paid from that money too.", 1),
            ("When should a business pay its taxes?", "By the due date",
             "Whenever it feels like it", "Only if someone reminds it",
             "Taxes have deadlines. Paying on time avoids extra charges called penalties.", 1),
            ("What is a receipt?", "A paper or digital note that proves a purchase",
             "A recipe card for making fresh lemonade at home", "A sign that shows the store's hours",
             "Receipts show what was bought, when, and for how much. They are key records for any business.", 1),
            ("Is it okay to hide some income so you pay less tax?", "No, hiding income is against the law",
             "Yes, if it is only a little money", "Yes, if nobody asks you about it",
             "Hiding income is cheating and can lead to big fines or worse. Honest businesses report all income.", 1),
            ("Why do people share the cost of things like parks through taxes?", "Many people use them, so sharing is fair",
             "So only one family can use the park", "Because parks are free to build and keep",
             "A park is too costly for one family, but when everyone chips in a little, the whole town gets one.", 1),
            ("A $5 notebook has $0.50 sales tax. What is the total?", "$5.50",
             "$5.05", "$5.00",
             "$5 plus 50 cents is $5.50. Always add the tax to see the full price.", 1),
            # Level 2
            ("What is profit?", "Money left after paying costs",
             "All money from sales, before costs", "Money you borrow from a bank",
             "Profit is sales minus costs. Income tax for a business is usually based on profit, not total sales.", 2),
            ("Your lemonade stand sells $50 and spends $20 on supplies. What is the profit?", "$30",
             "$70", "$20",
             "$50 minus $20 is $30. Knowing your profit helps you understand what may be taxed.", 2),
            ("A shop collects sales tax from customers. What should it do with that money?", "Send it on to the government",
             "Keep it as extra profit for the shop", "Give it back to customers next year",
             "Sales tax is not the shop's money. The shop holds it for the government and must send it on.", 2),
            ("What is a tax penalty?", "An extra charge for paying late or wrong",
             "A prize for paying taxes early", "A foul called in a sports game",
             "Penalties push people to follow tax rules. Paying on time and correctly avoids them.", 2),
            ("Your bakery forgot to pay its tax on time. What is best?", "Pay it soon and ask how to fix it",
             "Wait and hope nobody ever notices", "Never pay it, since it is already late",
             "Late taxes often grow with penalties and interest. Fixing it fast keeps the cost lower.", 2),
            ("A $20 shirt has 10% sales tax. What is the total?", "$22",
             "$20.10", "$30",
             "10% of $20 is $2, so the customer pays $20 plus $2, which is $22.", 2),
            ("Why do business costs matter for income tax?", "Costs lower profit, and tax is often on profit",
             "Costs are always paid by the government", "Costs always make the tax bill go up",
             "Since income tax is usually on profit, recording real costs means you pay the right amount, not too much.", 2),
            ("Which should go in your business records?", "Every sale and every cost",
             "Only the days with big sales", "Only the costs you remember",
             "Complete records show the true picture. Missing items can lead to paying the wrong tax.", 2),
            ("How long should a business keep its tax records?", "As long as the rules say, often years",
             "Until the end of the week it was made", "Only until the tax is paid, then shred them",
             "Tax offices can ask about past years. Many places require keeping records for several years.", 2),
            ("Is an honest mistake on a tax form the same as cheating?", "No, but fix it once you find it",
             "Yes, any mistake means you cheated", "No, so you can leave it as it is",
             "Honest mistakes happen. Fixing them quickly is the right thing and usually costs less than leaving them.", 2),
            ("You buy flour for your bakery. Why save that receipt?", "It proves a business cost",
             "It has a nice picture of flour", "You need it to bake the bread",
             "Business costs can lower the profit that gets taxed, but you need proof. Receipts are that proof.", 2),
            ("A business owes $200 in tax and also pays a $20 late penalty. How much did it pay in all?", "$220",
             "$180", "$200",
             "$200 plus $20 is $220. Paying on time would have saved that $20.", 2),
            # Level 3
            ("A bike sells for $100 with 8% sales tax. What does the customer pay?", "$108",
             "$100.08", "$180",
             "8% of $100 is $8, so the total is $100 plus $8, which is $108.", 3),
            ("Your shop had $500 in sales and $350 in costs. What is the profit?", "$150",
             "$850", "$350",
             "$500 minus $350 is $150. Income tax is often based on this profit, not on the $500 in sales.", 3),
            ("A customer offers to pay cash 'so you don't have to report it'. What should you do?", "Record and report it like any sale",
             "Agree and leave it out of the books", "Charge more for keeping it secret",
             "All income must be reported, whether cash or card. Leaving it out is hiding income, which is against the law.", 3),
            ("Why might a business set aside some money each month for taxes?", "So it has enough when the tax bill is due",
             "So it can spend it all on a party", "Because banks require every business to",
             "Tax bills can be big. Saving a bit each month means the money is ready on time.", 3),
            ("A tax office asks about last year's sales. What helps most?", "Clear records and saved receipts",
             "A good memory of the busy days", "A guess that sounds about right",
             "Records give proof. Guessing or memory can lead to mistakes and penalties.", 3),
            ("Which is a good reason to hire an accountant?", "Tax rules are tricky and they know them well",
             "They can make all of your taxes go away completely", "They promise you will never owe tax again",
             "Accountants help you follow the rules and avoid mistakes. They cannot make taxes vanish, and honest ones never hide income.", 3),
            ("Your bakery collected $40 in sales tax this month. How much of it belongs to the bakery?", "$0, it belongs to the government",
             "$40, it is the bakery's money", "$20, half goes to the bakery",
             "Sales tax is collected for the government. The business only holds it until it is time to send it.", 3),
            ("A business owes $300 in tax, with a $10 penalty for each month late. It pays 3 months late. What is the total?", "$330",
             "$310", "$303",
             "3 months times $10 is $30, and $300 plus $30 is $330. Penalties often grow the longer you wait.", 3),
            ("What is the difference between sales and profit?", "Sales is all money in; profit is what is left after costs",
             "They are just two names for the same thing", "Profit is all money in; sales is what is left after costs",
             "Mixing them up can lead to the wrong tax. Profit is smaller because costs are taken out.", 3),
            ("A friend says 'everyone hides a little income'. What is the best reply?", "That is cheating, and it can bring penalties",
             "If everyone does it, it must be fine", "Only big companies have to report their income",
             "Something wrong does not become right because others do it. All businesses must report their income.", 3),
            ("Why should business money and personal money be kept apart?", "It makes records clear and taxes easier to get right",
             "So the owner can spend business money freely", "Because banks charge much less when they are kept apart",
             "Separate accounts show exactly what the business earned and spent, which makes records and tax forms accurate.", 3),
            ("Two months of business receipts got lost. What is best?", "Rebuild them from bank records with an expert",
             "Make up numbers that look about right", "Leave those two months out of the records for good",
             "Never invent numbers. Bank records and an expert can help rebuild a true picture.", 3),
        ],
        "facts": [
            ("Taxes help pay for libraries and parks that a whole town can use.", True,
             "Shared places like libraries and parks are often paid for by taxes, so everyone can use them."),
            ("Paying taxes is optional for small businesses.", False,
             "Even small businesses must follow tax rules. Some may owe little, but the rules still apply."),
            ("In many places, sales tax rates can be different from town to town.", True,
             "Different areas can set different rates, so the same item may cost a little more or less with tax."),
            ("Throwing away receipts right after you buy things is a smart habit.", False,
             "Receipts are proof of costs. Businesses should save them, on paper or digitally, for as long as the rules require."),
            ("Interest on late taxes can keep growing the longer you wait.", True,
             "Interest adds a little more for each period you are late, so a small bill can grow if ignored."),
            ("A business can choose its own tax due date each year.", False,
             "Due dates are set by tax rules. Owners should mark them on a calendar so nothing is missed."),
            ("Many businesses use a calendar or reminders for tax due dates.", True,
             "Reminders help owners pay on time and avoid late penalties."),
            ("Taxes only pay for things in faraway cities, not in your town.", False,
             "Many taxes pay for local things like your town's roads, schools and fire station."),
            ("Tax rules can change, so owners check each year or ask an expert.", True,
             "Rules and rates can change over time. Staying up to date helps you pay the right amount."),
            ("Making an honest tax mistake always means you go to jail.", False,
             "Honest mistakes usually just need fixing, sometimes with a small charge. Hiding income on purpose is far more serious."),
            ("A receipt can be paper or digital.", True,
             "Many shops email receipts. Saving digital copies in an organized folder counts as good record keeping."),
            ("If your business made no profit, you can ignore all tax forms.", False,
             "Even with no profit, many places still require businesses to file forms. Check the rules or ask an accountant."),
            ("Paying taxes honestly helps a business keep a good name.", True,
             "Customers, banks and partners trust businesses that follow the rules, which can help them grow."),
            ("Taxes are a punishment for businesses that make money.", False,
             "Taxes are how communities pay for shared services. Paying them is a normal part of running a business."),
        ],
    },
    {
        "key": "cyber",
        "title": "Cyber Shield",
        "tagline": "Keep the business safe online",
        "icon": "lock",
        "cards": [
            ("Strong Passwords", "Use long passwords, like a passphrase of 4 random words. Use a different one for each account and never share them, even with friends."),
            ("Two-Step Login", "Two-step login asks for a second proof, like a code on your phone, after your password. Even if someone steals the password, they still cannot get in."),
            ("Spot Phishing", "Phishing messages pretend to be someone you trust to trick you into clicking or sharing secrets. Watch for rushing, scary warnings and odd links."),
            ("Update and Back Up", "Updates fix security holes, so install them soon. Backups are extra copies of files kept somewhere else, so you can recover if something breaks."),
            ("Protect and Report", "Keep customer data private and share it only with people who need it. If something looks strange, stop and tell an adult or your manager right away."),
        ],
        "questions": [
            # Level 1
            ("Which password is the strongest?", "Blue-pizza-river-lamp-7",
             "password123", "Max2015",
             "Long passphrases of random words are hard to guess but easy to remember. Simple words and pet names are easy to guess.", 1),
            ("Your friend asks for your password to the shop computer. What should you do?", "Say no, passwords are never shared",
             "Give it, since they are your friend", "Give it, but change it next year",
             "A password is like a key to the shop. Each person should have their own login.", 1),
            ("What is phishing?", "A trick message that tries to steal your secrets",
             "A hobby where you catch fish at a lake on weekends", "A way to make your computer run faster and smoother",
             "Phishing messages pretend to be someone trustworthy so you click a bad link or share a password.", 1),
            ("You get an email with a strange link saying you won a prize. What should you do?", "Do not click it, and tell an adult",
             "Click it fast before the prize is gone", "Forward it to all of your friends",
             "Surprise prize messages are a common trick. Not clicking and telling an adult keeps you safe.", 1),
            ("Why should you install software updates?", "They fix security holes attackers use",
             "They only change the colors of apps", "They make computers slower on purpose",
             "Updates often patch weaknesses. Installing them soon helps keep attackers out.", 1),
            ("What is a backup?", "An extra copy of files kept somewhere safe",
             "A truck that beeps while driving backward", "A second password written on a sticky note",
             "If a computer breaks or files get locked, a backup lets you get your work back.", 1),
            ("Where is the WORST place to keep your password?", "On a sticky note on the screen",
             "In your memory as a passphrase", "In a password manager an adult set up",
             "A note on the screen lets anyone walking by see it. Memory or a trusted password manager is much safer.", 1),
            ("A pop-up says 'Your computer has a virus! Call this number now!' What should you do?", "Close it and tell an adult",
             "Call the number right away", "Type your password to fix it",
             "Scary pop-ups that rush you are a common scam. Real security tools do not ask you to call random numbers.", 1),
            ("Should you use the same password for every account?", "No, each account needs a different one",
             "Yes, so it is easier to remember", "Yes, as long as the password is very long",
             "If one site leaks your password, attackers try it everywhere. Different passwords stop one leak from opening every door.", 1),
            ("A message that says it is from 'the bank' asks for your password. What is true?", "Real banks do not ask for it by message",
             "Banks often ask for passwords by text", "It is fine if the message has a logo",
             "Trusted companies do not ask for your password in an email or text. Logos are easy to fake.", 1),
            ("What is two-step login?", "A password plus a second proof, like a phone code",
             "Typing the same password two times in a row", "Logging in on two different computers at the same time",
             "The second step means a stolen password alone is not enough to break in.", 1),
            ("You see a message at work that seems strange. Who should you tell?", "An adult or your manager",
             "Nobody, just ignore it", "Only your friends online",
             "Telling a manager or adult helps protect the whole business, since others may get the same trick.", 1),
            # Level 2
            ("Which is a warning sign of a phishing email?", "It rushes you to click a link and log in",
             "It says hello and has correct spelling", "It arrived on a normal weekday morning",
             "Rushing, scary warnings and links that ask for logins are classic phishing tricks. Slow down and check.", 2),
            ("An email says it is from your bakery's flour supplier, but the address looks odd. What is best?", "Contact the supplier using a number you know",
             "Reply to the email and ask them if it is real", "Click the link to see where it goes",
             "Checking with a phone number or website you already trust avoids the trickster's own contact info.", 2),
            ("Customers' addresses and phone numbers are on the shop computer. How should they be treated?", "Kept private and shared only when needed",
             "Posted online so delivery drivers can find them", "Sold to other shops for extra money",
             "Customers trust you with their data. Keeping it private protects them and, in many places, is the law.", 2),
            ("What is a passphrase?", "A password made of several random words",
             "A short code made of just 4 numbers in a row", "Your name with a number added",
             "Several random words make a long password that is hard to crack but easy to remember.", 2),
            ("Why keep a backup somewhere other than the main computer?", "So one broken computer cannot wipe out both",
             "So the computer has more room for games", "Because backups only work on other computers",
             "If the backup sits on the same computer, one problem can wipe out both copies.", 2),
            ("You get a login code you did not ask for, and a caller asks you to read it to them. What should you do?", "Do not share it, and tell an adult",
             "Read it, since they asked politely", "Share it if they say they are a company",
             "Login codes are secret. Someone asking for one is likely trying to break into your account.", 2),
            ("A link's text shows one website, but hovering over it shows a different address. What does that mean?", "The link may be fake and should not be clicked",
             "It is fine, since addresses always change", "The website must have just been updated",
             "Tricksters hide bad addresses behind safe-looking text. Hovering to check before clicking is a smart habit.", 2),
            ("Your shop's tablet asks to install an update. When is a good time?", "Soon, when it will not interrupt work",
             "Never, because updates are always risky", "Only after waiting a whole year",
             "Updates fix security holes. Planning a quick time to install them soon keeps the tablet safe.", 2),
            ("A worker leaves the family business. What should happen to their accounts?", "Remove their access and change shared passwords",
             "Keep their login active just in case", "Give their password to the newest worker to use",
             "Old logins are open doors. Removing access when someone leaves protects the business.", 2),
            ("You step away from the shop computer for lunch. What should you do?", "Lock the screen first",
             "Leave it open so others can use it", "Turn off the monitor but stay logged in",
             "Locking the screen stops others from using your login while you are away.", 2),
            ("A cafe has open Wi-Fi with no password. What is smart?", "Avoid logging in to important accounts",
             "Use it for all banking and business logins", "Turn off your screen lock while using it",
             "Open networks can be watched by others. Save important logins for a trusted network.", 2),
            ("Which is a safe way to remember many strong passwords?", "Use a password manager an adult sets up",
             "Write them all on the back of your hand", "Use your birthday for every account",
             "A password manager safely stores strong, different passwords so you only need to remember one.", 2),
            # Level 3
            ("An email from 'the boss' asks you to buy gift cards fast and keep it secret. What is best?", "Ask the boss in person or on a known number",
             "Buy them quickly so the boss stays happy with you", "Reply to the email asking for more details",
             "Secret, rushed money requests are a common scam. Checking in a different way protects the business.", 3),
            ("A file from an unknown sender is named 'invoice.zip'. What should you do?", "Do not open it; report it to a manager",
             "Open it to find out who sent it", "Forward it to all your coworkers to check it",
             "Unknown attachments can hide harmful programs. Reporting lets someone check it safely.", 3),
            ("Ransomware locks the shop's files and demands money. What helps the business most?", "Recent backups stored away from the computer",
             "A bright and cheerful screensaver", "Using one long password for every single account",
             "With separate backups, the shop can restore its files. It should also report the attack to the right people.", 3),
            ("Why is two-step login helpful even with a strong password?", "A stolen password alone is not enough to get in",
             "It makes your password shorter and easier", "It means you never need a password again",
             "Passwords can leak in data breaches. The second step blocks attackers who only have the password.", 3),
            ("Which is the best rule for customer data?", "Collect only what you need and lock it up",
             "Collect everything you can get, just in case", "Keep it in a file that anyone can open",
             "Less data means less to lose. Locking up what you do keep protects customers.", 3),
            ("A text says your delivery is stuck and asks you to pay $1 through a link. What is this most likely?", "A scam trying to steal card details",
             "A normal way shippers collect fees", "A free gift from the delivery company",
             "Small fees with links are a common trick to grab card numbers. Check through the real company's app or website.", 3),
            ("You clicked a bad link by mistake. What should you do first?", "Tell an adult or manager right away",
             "Hide it so you do not get in trouble", "Keep using the computer and hope",
             "Fast reporting lets adults change passwords and stop damage early. Hiding a mistake makes things worse.", 3),
            ("Which password idea is the safest?", "A long phrase of random words used for one site only",
             "A favorite word with an ! added at the end", "Your pet's name followed by 123",
             "Long, random and unique beats short and guessable. Pet names are often easy to find online.", 3),
            ("Someone calls saying they are 'tech support' and asks to control the shop computer. What is best?", "Hang up and check with your manager",
             "Let them in, since they sound helpful", "Give them your password so they work fast",
             "Real tech support rarely calls out of the blue. Letting strangers control a computer can expose all its data.", 3),
            ("How should a business know its backups really work?", "Test them regularly by restoring a file",
             "Trust them if the backup says it finished", "Wait until a disaster happens to find out",
             "A backup you cannot restore is no help. Testing regularly proves your files can come back.", 3),
            ("A coworker offers their login so you can finish a task faster. Why is that a problem?", "Each person's actions should match their own login",
             "It is not a problem if the task is urgent", "Logins only matter for managers",
             "Shared logins make it hard to know who did what and spread risk. Ask for your own access instead.", 3),
            ("A customer emails asking you to send their refund to a new bank account. What is wise?", "Confirm with them using contact info you have",
             "Make the change right away so they stay happy", "Ask them to send their password as proof",
             "Tricksters pretend to be customers to steal money. Checking through a known contact protects everyone.", 3),
        ],
        "facts": [
            ("A long passphrase can be stronger than a short password with symbols.", True,
             "Length makes passwords much harder to crack. Four random words beat a short jumble of symbols."),
            ("Emails that greet you by your name are always safe.", False,
             "Tricksters can find names online. Check the sender and the links, not just the greeting."),
            ("Phishing can happen by text message and phone call, not just email.", True,
             "Scammers use any way they can reach you. The same warning signs apply: rushing, secrets and odd links."),
            ("Security software means you can safely click any link.", False,
             "Security tools help, but they cannot catch everything. Careful clicking is still needed."),
            ("Many websites let you turn on two-step login in their settings.", True,
             "It often takes just a few minutes to turn on, and it adds a strong extra lock to the account."),
            ("Kids are too young to be targets of online tricks.", False,
             "Tricksters target people of all ages, including kids, often with fake prizes or game offers."),
            ("It is okay to say no if someone online pressures you to act fast.", True,
             "Real friends and companies give you time. Pressure to hurry is a sign of a trick."),
            ("Backups are only needed by big companies.", False,
             "Any business can lose files to a broken device or an attack. Small businesses need backups too."),
            ("Criminals often pretend to be someone you trust, like a boss or a bank.", True,
             "Pretending to be trusted helps tricksters get people to act without checking."),
            ("Deleting a phishing email is the only step you need to take.", False,
             "Reporting it to an adult or manager helps protect others who may get the same message."),
            ("A website with a lock icon can still be fake.", True,
             "The lock means the connection is private, not that the site is honest. Scam sites can have locks too."),
            ("Turning off updates makes a computer safer.", False,
             "Updates fix security holes. Without them, known weaknesses stay open for attackers."),
            ("A real company will not mind if you call them back on a number you trust.", True,
             "Checking through a known number is normal. Only scammers push you to use their own contact info."),
            ("If a message comes from a friend's account, it cannot be a scam.", False,
             "Accounts can be hacked. If a friend's message seems odd, check with them another way."),
        ],
    },
]
