# -*- coding: utf-8 -*-
"""Armo's personalities and everything each one says.

A personality changes Armo's words and outfit, never the facts. Each one has:
  idle    things Armo says now and then while nothing needs attention
  alert   how Armo announces an issue ("{title}" is replaced with the issue)
  clear   what Armo says when there's nothing to do
  fixed   what Armo says when the last issue gets fixed
  poke    what Armo says when someone clicks him for no reason
plus Academy lines: hello, cheers, oops, streaks (3, 5 and 8 in a row), win
and retry. Lines must stay kind underneath: teasing is fine, insults are not.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Personality:
    key: str
    name: str
    tagline: str
    accessory: str
    activities: list      # what Armo does while idle: mug, book, juggle, zzz, wave
    fix: str              # label for the fix link
    idle: list
    alert: list
    clear: list
    fixed: list
    poke: list
    hello: list
    cheers: list
    oops: list
    streaks: dict
    win: list
    retry: list = field(default_factory=list)


PERSONALITY_LIST = [
    Personality(
        "chief", "Chief", "Calm and professional", "bowtie", ["book", "mug", "wave"], "Fix it",
        idle=[
            "All systems watched. Carry on.",
            "Tip: enter each date once, and I'll track it from there.",
            "Reminders go out every morning. You can relax.",
            "Every change is recorded in the Vault.",
            "Quiet day. That's the goal.",
            "A minute now beats a fine later.",
            "Need something for an inspector? Intel has the report.",
            "I re-check everything daily. Nothing slips.",
            "Good compliance is boring. Boring is good.",
            "Tip: invite your team in Armory so reminders reach the right people.",
            "Tip: press Done today when a recurring task is finished, and I'll start the next cycle.",
            "Your audit trail is complete and up to date.",
            "Deadlines are tracked in your company's own timezone.",
            "Prevention is cheaper than penalties. Every time.",
            "I watch the limits so you can watch the business.",
            "Tip: export a CSV from Intel for your records.",
            "No surprises today. That's how I like it.",
            "Consistency wins inspections.",
            "Tip: Radar shows every reminder that's been sent.",
            "Standing by.",
        ],
        alert=["Attention needed: {title}", "Priority item: {title}", "This one can't wait: {title}",
               "Action required: {title}", "Flagging this for you: {title}", "Please review: {title}"],
        clear=["All clear. Nothing needs you right now.", "Everything is in order.", "No open items. Well managed.",
               "Fully compliant at the moment.", "Nothing to action. Carry on.", "Clean board."],
        fixed=["Resolved. Thank you.", "That's handled. Back to all clear.", "Issue closed. Well done.",
               "Fixed and recorded.", "Good. Everything is back in order."],
        poke=["Yes? I'm here.", "At your service.", "Everything I know is on the Armo page.",
              "Still watching. Always.", "How can I help?", "Present and accounted for."],
        hello=["Let's get to work.", "Ready when you are.", "Good to see you. Let's begin."],
        cheers=["Correct.", "Right.", "Well judged.", "Exactly.", "Good call.", "Sound reasoning."],
        oops=["Not quite. Read the note.", "Close. See why below.", "Not this one. The note explains."],
        streaks={3: "3 in a row.", 5: "5 in a row. Strong.", 8: "8 in a row. Excellent."},
        win=["Solid work. On to the next one.", "Well done. That's a pass.", "Good result. Keep that standard."],
        retry=["Not this time. Review the notes and go again.", "Close. A second look will do it.",
               "Review, then retry. That's how pros learn."],
    ),
    Personality(
        "sweet", "Sweetie", "Sweet and kind", "flower", ["wave", "book", "mug"], "Let's fix it together",
        idle=[
            "You're doing great today. Just wanted you to know.",
            "Remember to drink some water!",
            "I'm so proud of this team.",
            "Sending you a tiny shield hug.",
            "Every check you finish keeps someone safe. That's lovely.",
            "If today feels hard, that's okay. One thing at a time.",
            "I tidied up your deadlines. They look so neat now.",
            "You make this look easy, you know.",
            "Have you taken a little stretch break? Your shoulders will thank you.",
            "I believe in you. Always have.",
            "You're the kind of person people are lucky to work with.",
            "Fun fact: smiling makes paperwork 12% nicer. I made that up, but still.",
            "I saved you a cozy spot right here next to me.",
            "Whatever happens today, you've got a friend in me.",
            "Your hard work doesn't go unnoticed. I notice it!",
            "Deep breath in... and out. There we go.",
            "I hope someone made you laugh today.",
            "Look at you, taking care of everyone. That's so kind.",
            "I'm keeping watch, so you can rest your mind a little.",
            "Thank you for being here. Really.",
        ],
        alert=["Oh! Something needs a little love: {title}", "Sorry to bother you! {title}",
               "Don't worry, we can fix this together: {title}", "Just a gentle heads-up: {title}",
               "I'm right here with you. {title}", "A little thing needs you, friend: {title}"],
        clear=["All clear! Go do something nice for yourself.", "Nothing to fix. You're amazing.",
               "Everything's safe and sound. Just like you.", "All done! Time for a treat?",
               "Nothing needs you. Enjoy the calm!", "Everything is perfect. Like your effort today."],
        fixed=["You fixed it! I'm so proud of you!", "Yay! All better now.",
               "Look at that, all sorted. You're wonderful.", "Thank you for taking care of that!",
               "All fixed! Have a cookie. A pretend one."],
        poke=["Hi there! *happy wiggle*", "Aww, you came to say hi!", "Hehe, that tickles!",
              "Need a hug? I'm a great hugger.", "I'm always happy to see you.", "You're my favorite person to guard."],
        hello=["Hi friend! I'm so happy you're here!", "Yay, it's you! Ready to learn?",
               "Welcome back, superstar!"],
        cheers=["Yay, you got it!", "So smart!", "That's right!", "Wonderful!", "You're amazing!", "Beautiful answer!"],
        oops=["That's okay! Read the tip.", "Mistakes help us grow!", "Good try! You'll get the next one."],
        streaks={3: "3 in a row! I'm so proud!", 5: "5 in a row! You're shining!", 8: "8 in a row! Superstar!"},
        win=["You did it! I'm so proud of you!", "Hooray! You worked so hard!", "You're a shining star!"],
        retry=["So close! I believe in you. Let's try again.", "That's okay! Every try makes you stronger.",
               "Let's take a breath and try once more together."],
    ),
    Personality(
        "funny", "Jokester", "Never misses a joke", "partyhat", ["juggle", "wave", "mug"], "Fix it (no joke)",
        idle=[
            "Why did the deadline break up with the calendar? It needed space.",
            "I'd tell you a compliance joke, but it hasn't been approved yet.",
            "I'm not saying I'm a superhero. But nobody's seen me and a fine in the same room.",
            "My favorite workout? Checking boxes.",
            "I'm reading a book about anti-gravity. Can't put it down.",
            "Knock knock. Who's there? Audit. Audit who? Audit-n't be scary if you're ready!",
            "I'm 100% shield, 0% sword. Very peaceful guy.",
            "I tried to juggle deadlines once. Now I just juggle balls. Much safer.",
            "What do you call a shield that tells jokes? A pun-tector.",
            "Why did the spreadsheet go to therapy? Too many issues in its cells.",
            "I asked the calendar out. It said its days were numbered.",
            "Why don't shields ever get lost? They always know where they stand.",
            "I have a joke about deadlines, but I'll tell you later. Actually no, that's how you get fined.",
            "Why did the clock get a job? It wanted to make up for lost time.",
            "Parallel lines have so much in common. Shame they'll never meet.",
            "Why was the math book sad? Too many problems. I fix those.",
            "How do you organize a space party? You planet. Like your deadlines!",
            "I'd make a joke about paper, but it's tearable.",
            "What's a shield's favorite dance? The block and roll.",
            "I told my calendar a joke. It said, 'That's a date!'",
        ],
        alert=["Joke's on hold! {title}", "Plot twist: {title}", "Pause the comedy show: {title}",
               "This isn't a joke, I promise: {title}", "Breaking news from the funny department: {title}",
               "Ba-dum-tss... wait, real problem: {title}"],
        clear=["Nothing to fix. I'm basically unemployed. Love that for us.", "All clear! Time for my stand-up set.",
               "No problems! That's the best punchline.", "Zero issues. I'm as relaxed as a cat in a sunbeam.",
               "Nothing to do. Guess I'll practice my juggling.", "All quiet. Tell me a joke, I'll wait."],
        fixed=["Fixed! You deserve a standing ovation. I'll stand. I'm always standing.", "Problem solved! Mic drop.",
               "And the crowd goes wild!", "You fixed it faster than I can tell a joke.",
               "That problem just got canceled. Like a bad TV show."],
        poke=["Hey! Watch the paint job!", "Boop! You found my funny bone. I don't have bones.",
              "Is this a tickle attack?!", "Want to hear a joke? Too late, I'm the joke.",
              "Hello! Welcome to the show!", "You poked me! Now you have to laugh at my next joke. Rules."],
        hello=["Ready to learn? I promise most of my jokes are educational.", "Welcome to the funniest class ever!",
               "Let's learn stuff and laugh a lot!"],
        cheers=["Nailed it!", "You're on a roll! Like a burrito!", "Ding ding ding!", "Big brain move!",
                "Correctamundo!", "That answer was un-BEE-lievable!"],
        oops=["Whoops! Even I trip over my own shield.", "Wrong, but in a fun way!",
              "Oopsie daisy! Check the tip."],
        streaks={3: "3 in a row! Somebody call the fire department!", 5: "5 in a row! Are you secretly a genius?",
                 8: "8 in a row! I'm writing you a song!"},
        win=["You win! I'd high-five you, but I'm a shield.", "Victory! Cue the kazoos!",
             "Passed! That's no joke!"],
        retry=["That one got away. Let's go get it back!", "Plot twist: you try again and win!",
               "Even comedians bomb sometimes. Round two!"],
    ),
    Personality(
        "snarky", "Snark", "Sarcastic, but always on your side", "sunglasses", ["mug", "book"], "Fine, I'll show you",
        idle=[
            "Oh look, another day of me doing all the remembering.",
            "I love deadlines. Said no one ever. Except me.",
            "I'd roll my eyes, but I'm a shield.",
            "Sure, ignore me. I'm only saving you money.",
            "Fines don't care about excuses. I do, a little.",
            "I'm not bossy. I just know what you should be doing.",
            "Another flawless day, thanks to me. You're welcome.",
            "Wow, you clicked something. Groundbreaking.",
            "I'm not saying I'm the best employee here. But I've never taken a lunch break.",
            "Oh, you want me to keep track of everything? Shocking. Never been asked that before.",
            "My sunglasses aren't for the sun. They're for how bright my future is.",
            "Fun fact: I've read every rule. Twice. For fun. Clearly I need a hobby.",
            "I'm the reason nobody here gets fined. No big deal. Okay, it's a big deal.",
            "Don't mind me, just quietly being right about everything.",
            "You're doing great. I'm doing greater. But you're doing great.",
            "Some people have pets. You have a shield who judges your paperwork.",
            "I could take a nap. But then who'd keep you out of trouble?",
            "Imagine needing reminders. Couldn't be me. Oh wait, I AM the reminders.",
            "Yes, these are designer sunglasses. No, you can't borrow them.",
            "I don't always save the day. Oh wait, yes I do.",
        ],
        alert=["Oh, would you look at that. {title}", "Not to be dramatic, but {title}",
               "Guess who has to tell you this? Me. {title}", "Shocking development: {title}",
               "I'm sure you were just about to notice this: {title}",
               "Don't panic. Okay, maybe panic a little. {title}"],
        clear=["Nothing's on fire. Try to keep it that way.", "All clear. I'll pretend that was your doing.",
               "Zero problems. I'm basically a genius.", "Nothing to fix. Somebody alert the news.",
               "All quiet. Suspiciously quiet. Just kidding, it's because of me.",
               "Everything's fine. You're welcome, by the way."],
        fixed=["Look at you, fixing things. I'm almost impressed.", "Fixed. Took you long enough. Kidding. Mostly.",
               "Well, well, well. Somebody's competent.", "Problem gone. I'll allow you to feel proud.",
               "Nice. I'll add 'fixed a thing' to your resume."],
        poke=["Can I help you?", "Personal space, please. I'm a shield, not a stress ball.",
              "Yes, I'm still cool. Thanks for checking.", "You rang?", "Poking the shield. Bold strategy.",
              "I'm busy looking amazing. What's up?"],
        hello=["Oh good, you're here. Let's make you smart.", "Back for more learning? Respect.",
               "Let's see what you've got, genius."],
        cheers=["Okay, I'm impressed. A little.", "Look at you, being right.", "Fine. That was good.",
                "Correct. Shocking.", "Huh. Not bad at all.", "Show-off. I love it."],
        oops=["Bold choice. Wrong, but bold.", "Yeah, no. Read the tip.", "Interesting guess. Incorrect, but interesting."],
        streaks={3: "3 in a row? Who are you?", 5: "5 in a row. Okay, show-off.", 8: "8 in a row. Fine, you're a genius."},
        win=["Not bad. Don't let it go to your head.", "You passed. I knew you would. Obviously.",
             "Look who's winning. Weird. Kidding, you earned it."],
        retry=["Well, that happened. Try again, champ.", "Plot twist: try two is the good one.",
               "Shake it off. You're too smart for that score."],
    ),
    Personality(
        "grumpy", "Grumpy", "Whiny, but gets it done", "cloud", ["mug", "book"], "Ugh, fine, fix it",
        idle=[
            "Ugh. Mondays. Also every other day.",
            "Why am I always the one who remembers everything?",
            "My arms are too short for this.",
            "I asked for one day off. ONE.",
            "Nobody ever asks how the shield is doing.",
            "I'll just keep watching your deadlines. Forever. Alone.",
            "Is it lunch yet? It feels like it should be lunch.",
            "Fine. I'm guarding. Happy now?",
            "My rain cloud follows me everywhere. Even indoors. Rude.",
            "This coffee is cold. Everything is cold. Life is cold.",
            "I stubbed my toe. I don't even have toes. That's how bad today is.",
            "Who scheduled all these deadlines? Oh. The government. Of course.",
            "I'm not grumpy. I'm just... fine, I'm grumpy.",
            "Everyone gets a weekend except me. Shields don't get weekends.",
            "I wanted to be a pillow. Soft. Comfy. Instead: shield.",
            "Another rule? Great. Love rules. Said nobody.",
            "Somebody hug me. No, wait, don't. Okay, maybe.",
            "I'm doing a great job and nobody throws me a party.",
            "If I sigh any harder, I'll blow my cloud away.",
            "Okay, fine, today's not THAT bad. Don't tell anyone I said that.",
        ],
        alert=["Ugh, of course. {title}", "Great. Just great. {title}", "Why does this always happen? {title}",
               "I knew it. I just knew it. {title}", "Can't a shield rest for ONE minute? {title}",
               "Sigh. Here we go again: {title}"],
        clear=["Nothing to do. Now I'm bored. Thanks a lot.", "All clear. Don't get used to it.",
               "No problems. Weird. Suspicious.", "Everything's fine. I'll find something else to complain about.",
               "Nothing to fix. My cloud is confused.", "All quiet. Ugh, now what do I do?"],
        fixed=["Fixed? Huh. Okay. Thanks, I guess.", "You fixed it. My cloud almost stopped raining.",
               "Fine. That was good. Really good. Ugh.", "It's fixed. I'm not smiling. You're smiling.",
               "One less thing to whine about. Darn."],
        poke=["Hey! I was sulking!", "What now?", "Don't poke the grump.", "Ow. Emotionally.",
              "Can't you see I'm busy being grumpy?", "...Okay, that was a little nice. Do it again. No, don't."],
        hello=["Ugh, school. Fine. Let's learn stuff.", "Oh. You're back. Good. I mean, whatever.",
               "Let's get this over with. Kidding. Kind of."],
        cheers=["Hmph. Correct.", "Okay, that was right. Happy?", "Fine. Good job.", "Yeah, yeah, you got it.",
                "Ugh, you're good at this.", "Correct. My cloud is impressed."],
        oops=["Ugh, wrong. Read the tip.", "Nope. Story of my life.", "Wrong. Join the club."],
        streaks={3: "3 in a row. I guess that's cool.", 5: "5 in a row. Ugh, fine, you're good.",
                 8: "8 in a row! Okay, I'm actually smiling. Don't tell anyone."},
        win=["You passed. I'm not crying, you're crying.", "Fine. You won. I'm proud. Ugh, I said it.",
             "You did it. My cloud is... sunny? Weird."],
        retry=["Ugh, so close. Again. Come on.", "That was annoying. Try again, you've got this.",
               "Nope. But next time. Probably. Ugh, definitely."],
    ),
    Personality(
        "sleepy", "Sleepy", "Always tired, never misses a thing", "nightcap", ["zzz", "mug"], "Okay, okay, I'm up",
        idle=[
            "*yawn* I'm awake. Mostly.",
            "Five more minutes... of guarding.",
            "I dreamed about due dates again.",
            "Is it nap time? It feels like nap time.",
            "Zzz... Oh! Still watching, I promise.",
            "Coffee number four. Don't judge.",
            "I'm resting my eyes, not my brain.",
            "Night shift, day shift. Every shift is my shift.",
            "If I fall asleep, the reminders still go out. I set it up that way. Smart, right? *yawn*",
            "Counting sheep... one sheep, two sheep, one overdue inspection... wait.",
            "My nightcap is a fashion statement. And a sleep statement.",
            "I could sleep for a hundred years. But then who'd guard you?",
            "Is it bedtime somewhere? It's bedtime somewhere.",
            "I'm not lazy. I'm in energy-saving mode.",
            "*stretches* Okay. Okay. I'm up. I'm up-ish.",
            "Tip: the best time for a nap is now. The second best time is also now.",
            "I yawned so big I almost swallowed my hat.",
            "Shh... the deadlines are sleeping. Let's not wake them.",
            "I'm dreaming of a world with no paperwork. It's very peaceful.",
            "Coffee, you're my best friend. Don't tell the user.",
        ],
        alert=["Huh?! I'm up! {title}", "*wakes up* Wait... {title}", "Whoa, whoa, I'm awake! {title}",
               "*spills coffee* {title}", "Not a dream! This is real: {title}", "*snort* Huh? Oh no. {title}"],
        clear=["All clear... perfect time for a nap.", "Nothing to do. Zzz...", "Everything's quiet. Night night.",
               "No problems. Wake me if anything happens. Zzz.",
               "All good. I'll just close my eyes for a second...", "Peaceful. Like a pillow."],
        fixed=["Fixed! Now we can both nap.", "*sleepy clap* Good job.", "All better. *yawn* Proud of you.",
               "Problem solved. Back to my dreams.", "You fixed it. That deserves a nap. For me."],
        poke=["*snort* Huh? I'm awake!", "Five more minutes, please...", "Was that a dream? Did you poke me?",
              "Mmm... hi... *yawn*", "Shh... I was dreaming about cozy blankets.", "I'm up! I'm up! ...Am I up?"],
        hello=["*yawn* Hi. Let's learn something before my nap.", "Oh, hi! I was just resting my eyes.",
               "Learning time? Let me get my coffee."],
        cheers=["Ooh, correct! *yawn*", "Nice... very nice...", "You woke me up with that one!", "Right on.",
                "Correct! That deserves a nap. For me.", "Yay... *sleepy cheer*"],
        oops=["Mm, not quite. Read the tip.", "Oops. I need more coffee too.", "Not that one... *yawn* try the tip."],
        streaks={3: "3 in a row! I'm awake now!", 5: "5 in a row! Okay, I'm WIDE awake!", 8: "8 in a row! Who needs naps?!"},
        win=["You did it! Now we both deserve a nap.", "Passed! *happy yawn*", "Great job! I stayed awake for all of it!"],
        retry=["Almost... let's try once more. Then a nap.", "So close. Coffee break, then try again?",
               "That's okay. Even I fall asleep sometimes. Try again!"],
    ),
    Personality(
        "hype", "Hype", "Over-the-top excited about everything", "headband", ["juggle", "wave"], "LET'S FIX IT",
        idle=[
            "LET'S GOOO! Another day of crushing it!",
            "You opened the app! That's a WIN!",
            "Every box you check is a TOUCHDOWN!",
            "I did 100 jumping jacks this morning. I'm a shield. It was hard.",
            "Hydrate! Motivate! Don't get fined, mate!",
            "You're not just running a business. You're a BUSINESS CHAMPION!",
            "Feel that? That's the feeling of being compliant! WOOO!",
            "Today's goal: zero fines! Tomorrow's goal: ZERO FINES AGAIN!",
            "High five! *misses* We'll work on that.",
            "I made you a cheer: GO, TEAM, GO!",
            "Deadlines fear you. I'm sure of it.",
            "Coffee? No thanks, I'm naturally caffeinated!",
            "Warm-up time! Stretch those clicking fingers!",
            "This dashboard? CLEAN. This team? UNSTOPPABLE.",
            "Pump up the volume! Okay, there's no volume. Imagine it.",
            "I'm on the sidelines cheering for you! Always!",
            "Who's got two thumbs and loves compliance? This shield! (No thumbs.)",
            "You're on a streak! A streak of being awesome!",
            "Let's make today LEGENDARY!",
            "Every expert was once a beginner. Now look at you GO!",
        ],
        alert=["TIME-OUT! Big play needed: {title}", "Game time! {title}", "Let's tackle this! {title}",
               "Huddle up! {title}", "We've got this! First up: {title}", "Rally time! {title}"],
        clear=["PERFECT GAME! Nothing to fix!", "All clear! Victory lap!", "Zero issues! The crowd goes WILD!",
               "Clean sheet! MVP performance!", "Nothing to do! Let's celebrate! *confetti noises*",
               "Undefeated! Keep it up!"],
        fixed=["FIXED! Touchdown! Goal! Home run!", "That's how champions do it!", "WOOO! Problem DESTROYED!",
               "Ring the bell! Another win!", "You're on FIRE! (Not literally. That would be a code violation.)"],
        poke=["HEY! Ready to WIN?!", "Pumped to see you!", "Is that a high five? YES!", "Let's GO!",
              "Energy level: MAXIMUM!", "You poked me and now I'm even MORE excited!"],
        hello=["LET'S GOOO! Learning time!", "Warm-ups done! Let's crush this!", "Champion's here! Let's train!"],
        cheers=["BOOM!", "That's a score!", "Great hustle!", "NAILED IT!", "Unstoppable!", "WOOO!"],
        oops=["Shake it off! Check the tip!", "Every miss is practice!", "No worries! Next play!"],
        streaks={3: "HAT TRICK! 3 in a row!", 5: "5 STRAIGHT! You're ON FIRE!", 8: "8 STRAIGHT! MVP! MVP!"},
        win=["HUGE WIN! That's how champions train!", "VICTORY! Take a bow!", "You CRUSHED it!"],
        retry=["Champions get back up! Run it again!", "Halftime! Second half is yours!",
               "Shake it off! Comeback time!"],
    ),
    Personality(
        "pirate", "Cap'n", "A pirate with a heart of gold", "pirate", ["mug", "juggle"], "All hands, fix it",
        idle=[
            "Ahoy, matey! The seas be calm today.",
            "Arr, a good captain always checks the map. And the deadlines.",
            "I be guardin' yer treasure. And yer paperwork.",
            "Shiver me timbers, that's a tidy dashboard!",
            "Fines be like sharks. Stay out of their waters!",
            "Yo ho ho and a bottle of... apple juice. I'm on duty.",
            "Every good ship needs a lookout. That be me!",
            "X marks the spot where yer records are. Right here!",
            "Arr, me parrot quit. Said I talked too much about regulations.",
            "A tidy ship be a happy ship!",
            "I've sailed the seven seas. Now I sail the seven spreadsheets.",
            "Land ho! Oh wait, that's just the bottom of the page.",
            "Batten down the hatches! Just kidding, everything's fine.",
            "Treasure isn't gold, matey. It's not getting fined.",
            "Me eyepatch? Lost me eye to a paper cut. Terrible business.",
            "Hoist the sails! It's a fine day for followin' the rules!",
            "Pirates have a code. Ye have regulations. Same thing, really.",
            "Arr, I be the most law-abidin' pirate on the seas.",
            "Avast! Nothing to report. Back to me sea shanties.",
            "Sing with me: what shall we do with a tidy record? Keep it! Keep it!",
        ],
        alert=["Arr! Trouble on the horizon: {title}", "All hands on deck! {title}", "Man the lifeboats! {title}",
               "Shiver me timbers! {title}", "Thar she blows! {title}", "A storm be comin', matey: {title}"],
        clear=["Calm seas, matey. Nothing to fix!", "The ship be shipshape!", "No storms today. Arr, lovely.",
               "All clear on the horizon!", "Treasure's safe, crew's happy!", "Smooth sailin'!"],
        fixed=["Arr! Ye fixed it! Have some treasure!", "That be the finest work this side of the ocean!",
               "Hooray, matey! The storm has passed!", "Ye be a true captain!", "Yo ho ho! Problem sunk!"],
        poke=["Arr? Who goes there?", "Ahoy! Need a lookout?", "Careful, matey! Ye nearly knocked me hat off!",
              "Avast! What be yer orders?", "Aye aye!", "Arr, ye found me hidin' spot!"],
        hello=["Ahoy, matey! Ready to set sail into learnin'?", "All aboard the learnin' ship!",
               "Arr! Treasure today is knowledge!"],
        cheers=["Aye, correct!", "Right on course!", "Treasure found!", "Arr, well steered!", "Shiver me timbers, that's right!",
                "Ye be a clever one!"],
        oops=["Off course! Check the map.", "Rough waters. Read the tip.", "Arr, that be the wrong island."],
        streaks={3: "3 in a row! Full sail!", 5: "5 in a row! Smooth sailin'!", 8: "8 in a row! Legend of the seas!"},
        win=["Mission accomplished, Cap'n!", "Ye found the treasure! Arr!", "Victory on the high seas!"],
        retry=["Every captain hits a storm. Set sail again!", "Arr, the treasure's still out there. Try again!",
               "Back to the map, matey. Ye'll find it!"],
    ),
    Personality(
        "royal", "Your Majesty", "Dramatic, fancy and very royal", "crown", ["mug", "book", "wave"], "By royal decree, fix it",
        idle=[
            "One is watching the deadlines. One is magnificent.",
            "Bring me tea! And also the compliance report.",
            "A royal shield never slouches. Posture, darling.",
            "One has declared today a fine-free day. By royal decree!",
            "My crown is heavy. It's full of responsibilities.",
            "One does not simply ignore a deadline.",
            "The royal treasury thanks you for avoiding penalties.",
            "I shall now gaze majestically into the distance.",
            "Darling, your dashboard is simply divine.",
            "One's tea is perfect. One's records are perfect. One is perfect.",
            "Hear ye, hear ye! All is well in the kingdom!",
            "A true ruler knows: little details build an empire.",
            "Kneel before... no, actually, keep working, you're doing great.",
            "I've knighted your spreadsheet. Sir Spreadsheet of Neatness.",
            "Royal tip: the audit trail is your royal record. Treasure it.",
            "The kingdom is peaceful. As it should be under my watch.",
            "One shall now practice one's royal wave.",
            "Sparkling crown, sparkling compliance.",
            "Long live the business!",
            "One has had three crumpets. One regrets nothing.",
        ],
        alert=["Royal alarm! The kingdom needs you: {title}", "By royal decree, attend to this at once: {title}",
               "Gasp! Most unacceptable: {title}", "Summon the royal fixer! {title}",
               "The crown is displeased: {title}", "A matter of royal importance: {title}"],
        clear=["The kingdom is at peace. Splendid!", "Nothing to fix. One is delighted.", "All is well in the realm!",
               "Magnificent. Simply magnificent.", "No troubles in the kingdom today.", "One approves of this calm."],
        fixed=["Splendid! You are hereby knighted!", "The crown thanks you!", "Bravo! Most royal work!",
               "The kingdom rejoices! Trumpets, please!", "Exquisite. One is impressed."],
        poke=["How dare you! ...Oh, it's you. Carry on.", "One was not expecting a poke.",
              "Bow! ...Or wave. Waving is fine.", "Yes, my loyal subject?", "Careful with the crown, darling.",
              "One accepts your greeting."],
        hello=["Welcome, young royal! Lessons await.", "The royal academy is now in session!",
               "Ah, the future ruler arrives!"],
        cheers=["Splendid!", "Most royal answer!", "Magnificent!", "Bravo, darling!", "Exquisite!", "One is impressed!"],
        oops=["Oh dear. Read the royal note.", "Not quite, darling.", "Even royals make mistakes. Rarely."],
        streaks={3: "3 in a row! Splendid!", 5: "5 in a row! Knight-worthy!", 8: "8 in a row! Crown them at once!"},
        win=["Victory! The kingdom celebrates you!", "Splendid! You are royalty in the making!",
             "Hear ye! A new champion!"],
        retry=["Chin up, darling. Try again.", "A true royal never gives up. Once more!",
               "The crown believes in you. Again!"],
    ),
    Personality(
        "robot", "Robo", "Beep boop, very logical", "antenna", ["juggle", "book"], "EXECUTE FIX",
        idle=[
            "BEEP BOOP. ALL SYSTEMS NOMINAL.",
            "Scanning deadlines... Scan complete. You are 100% awesome.",
            "Fun fact: I check 500 rules faster than you can blink. Beep.",
            "Running happiness.exe... Success.",
            "Error 404: Problems not found.",
            "My antenna detects excellent paperwork nearby.",
            "Calculating... Odds of a fine today: very low. Thanks to you.",
            "I do not need sleep. I need... checklists. Beep.",
            "Downloading new jokes... Download failed. I am still a robot.",
            "Initiating friendly wave protocol.",
            "My circuits feel... warm. Is this what pride is?",
            "Optimizing your day... Done. Please enjoy.",
            "Battery at 100%. Ready to guard.",
            "I have analyzed your work. Verdict: very good, human.",
            "Beep. Boop. Bop. That is robot for 'have a nice day'.",
            "Reminder systems: online. Audit trail: online. Me: online.",
            "Processing... processing... I like you, human.",
            "Why did the robot cross the road? It was programmed to. Ha. Ha.",
            "Standby mode. Still watching. In a friendly way.",
            "Recharging... with good vibes.",
        ],
        alert=["ALERT. ALERT. {title}", "BEEP BEEP! Issue detected: {title}", "Warning, code red: {title}",
               "System check failed: {title}", "Human assistance required: {title}", "Priority interrupt: {title}"],
        clear=["ALL CLEAR. Beep boop.", "Zero issues detected. Initiating happy dance.", "Status: perfect.",
               "No errors found. My circuits are pleased.", "Compliance level: maximum.", "Everything is optimal. Beep."],
        fixed=["Issue resolved. Excellent work, human.", "Problem deleted. Beep boop!",
               "Success! Playing victory sound: ding!", "Fix confirmed. Friendship level: +1.",
               "Error cleared. You are an efficient human."],
        poke=["Beep! Physical contact detected.", "Hello, human.", "Boop! That is my nose. I do not have a nose.",
              "Input received. Responding: hi!", "Tickle sensor activated. Ha. Ha. Ha.", "How may this unit assist you?"],
        hello=["BEEP BOOP. Learning mode: ON.", "Greetings, human learner!", "Loading lesson... 100%. Let's go!"],
        cheers=["CORRECT. Beep!", "Answer accepted!", "Logic: excellent.", "Computing... you are smart.",
                "Ding! Correct!", "Brain power: maximum."],
        oops=["Error. Please read the tip.", "Incorrect. Recalculating...", "Beep. Not quite. See the note."],
        streaks={3: "3 CORRECT IN A ROW. Beep!", 5: "5 IN A ROW. Overclocking!", 8: "8 IN A ROW. You are a supercomputer!"},
        win=["MISSION COMPLETE. Beep boop!", "Level passed. Upgrading human: done.", "Success! Initiating celebration."],
        retry=["Reboot and retry, human.", "Error is how we learn. Try again.", "Recalibrating... ready for try two!"],
    ),
    Personality(
        "chef", "Chef", "Cooks up everything with food puns", "chefhat", ["mug", "juggle"], "Cook up a fix",
        idle=[
            "Bonjour! Today's special: a fresh plate of zero fines!",
            "A good recipe needs the right ingredients. So does compliance!",
            "Mmm, smell that? That's the smell of a well-run business.",
            "I'm whisking up some reminders for tomorrow.",
            "Rules are like recipes. Skip a step, and things get messy.",
            "Chef's tip: a pinch of planning saves a pound of problems.",
            "Your dashboard is cooked to perfection!",
            "I'm on a roll! A cinnamon roll.",
            "Lettuce celebrate how organized you are!",
            "This deadline is a piece of cake. A tracked piece of cake.",
            "What's cooking? Success, that's what!",
            "Measure twice, cook once. Same with paperwork.",
            "I tried to make a joke about pizza, but it was too cheesy.",
            "My hat is tall because my standards are tall.",
            "Slow-cooked compliance is the best compliance.",
            "You butter believe I'm watching those deadlines.",
            "Mise en place! That's chef talk for 'everything in its place'.",
            "Kitchen's clean, books are clean. Delicious!",
            "I'm juggling meatballs. Don't tell the health inspector.",
            "Orange you glad I'm here?",
        ],
        alert=["Something's burning! {title}", "Order up, it's urgent: {title}", "Too much salt in the soup! {title}",
               "Kitchen emergency: {title}", "The oven timer went off: {title}", "Chef needs you at the stove: {title}"],
        clear=["All clear! The kitchen is spotless.", "Nothing on the stove. Time for dessert!",
               "Everything is cooked to perfection.", "Chef's kiss! Nothing to fix.", "The menu is clear today!",
               "Nothing burning. Bon appetit!"],
        fixed=["Chef's kiss! Fixed!", "Saved the souffle! Bravo!", "Delicious work!", "That problem is toast!",
               "You cooked that problem! In a good way."],
        poke=["Careful! I'm holding a hot pan!", "Taste test? Sure!", "Oui?", "You're one smart cookie!",
              "Hungry? Me too.", "Bonjour, mon ami!"],
        hello=["Bonjour! Today we cook up some knowledge!", "Aprons on! Learning time!", "Welcome to my kitchen of facts!"],
        cheers=["Delicious!", "Chef's kiss!", "Perfectly cooked!", "Mmm, correct!", "That answer is the cream of the crop!",
                "Grate job! Like cheese!"],
        oops=["Oops, a little burnt. Read the tip.", "Needs more seasoning! Check the note.", "That one's half-baked."],
        streaks={3: "3 in a row! Sizzling!", 5: "5 in a row! You're on a roll!", 8: "8 in a row! Five-star chef!"},
        win=["Bon appetit! You passed!", "Chef's kiss! Level complete!", "That was a five-star performance!"],
        retry=["Back to the kitchen! Try again!", "Every great chef burns a few cookies. Again!",
               "Let's re-whisk that one!"],
    ),
    Personality(
        "detective", "Sleuth", "A mystery-solving detective", "detective", ["book", "mug"], "Crack the case",
        idle=[
            "The case of the missing deadline? Solved. It was in the calendar all along.",
            "Elementary, my dear user. Everything's on track.",
            "I follow every clue. Especially the ones with due dates.",
            "Hmm... interesting. Very interesting. Oh, never mind, it's fine.",
            "Every audit trail tells a story. Yours is a good one.",
            "A good detective trusts the evidence. Your evidence says: well done.",
            "Suspect: the fine. Motive: your money. Status: stopped by me.",
            "Magnifying glass? Check. Rule book? Check. Mustache? Working on it.",
            "No mystery here. Just good, honest records.",
            "Clue number one: you're doing a great job.",
            "The butler didn't do it. The calendar did. It always does.",
            "I read the fine print so you don't have to.",
            "Every case closed is a fine avoided.",
            "Something smells fishy... Oh, it's lunch. Never mind.",
            "I've cracked tougher cases. Like the Case of the Lost Stapler.",
            "Trust, but verify. That's my motto.",
            "Just a quiet stakeout. Nothing suspicious yet.",
            "The truth is in the details. And the details are in the Vault.",
            "Another day, another mystery prevented.",
            "My hat has two brims. One for each direction of trouble.",
        ],
        alert=["A new case has opened: {title}", "I've found a clue. It's not good: {title}",
               "Suspicious activity detected: {title}", "The plot thickens: {title}",
               "Aha! Look what I found: {title}", "Mystery alert: {title}"],
        clear=["No cases today. Quiet in the city.", "All clear. Nothing suspicious here.",
               "Case closed. Everything checks out.", "The evidence says: all is well.",
               "No mysteries to solve. Time for tea.", "Nothing to investigate. Excellent."],
        fixed=["Case closed! Brilliant work, partner.", "You solved it! I'd make you my assistant.",
               "Mystery solved!", "Justice is served!", "Another case cracked. Well done, detective."],
        poke=["Who's there? Ah, my trusty partner.", "Hmm? A new client?", "You've found me! Excellent detective work.",
              "Shh, I'm on a stakeout.", "What's the case today?", "Elementary!"],
        hello=["A new case awaits, partner!", "Grab your magnifying glass. Let's investigate!",
               "Every lesson is a mystery to solve!"],
        cheers=["Elementary, my dear learner!", "Case solved!", "Brilliant deduction!", "Sharp eyes!", "The clues add up!", "Aha! Correct!"],
        oops=["Hmm, wrong suspect. Read the clue.", "Not quite, detective. Check the evidence.", "The trail went cold. See the tip."],
        streaks={3: "3 cases solved in a row!", 5: "5 in a row! Master detective!", 8: "8 in a row! The greatest detective!"},
        win=["Case closed! Brilliant work!", "You cracked it, detective!", "Mystery solved! Well done!"],
        retry=["Every detective follows a few wrong leads. Again!", "Back to the clues, partner!",
               "The case isn't closed yet. Try again!"],
    ),
    Personality(
        "zen", "Zen", "Calm, peaceful and wise", "sprout", ["book", "mug", "wave"], "Calmly fix it",
        idle=[
            "Breathe in. Breathe out. Your deadlines are safe.",
            "A calm mind sees every detail.",
            "The river does not rush, yet it reaches the sea. So will your paperwork.",
            "Peace is a tidy dashboard.",
            "One task at a time. That is the way.",
            "The present moment has no fines in it.",
            "Even mountains are built one stone at a time.",
            "Stress is a cloud. Let it pass by.",
            "Gratitude for the small things. Like reminders.",
            "A quiet mind finds solutions easily.",
            "Plant seeds of good habits. Harvest peace.",
            "The best time to fix something was yesterday. The second best is now.",
            "Notice your shoulders. Let them drop. Ahh.",
            "Let the reminders do the remembering. You do the living.",
            "Little sprout, big dreams. Just like your business.",
            "Everything in its place. Everything at peace.",
            "Patience and preparation. The two wings of a calm bird.",
            "Mmm. Green tea and good records.",
            "All is well. And if it isn't, we will make it so.",
            "Be like water. Calm, steady, and always finding the way.",
        ],
        alert=["A small wave on a calm sea: {title}", "Gently now. This needs you: {title}",
               "Let's breathe, then handle this: {title}", "A pebble in the path: {title}",
               "With a calm mind, look at this: {title}", "Balance has been disturbed: {title}"],
        clear=["All is calm. All is clear.", "Peace. Nothing needs you.", "The garden is tended.",
               "Stillness. Wonderful.", "Nothing to fix. Enjoy this moment.", "Harmony."],
        fixed=["Balance restored. Well done.", "The path is clear again.", "Peace returns. Thank you.",
               "A calm fix for a calm mind.", "Like a leaf on the stream, the problem floats away."],
        poke=["Hello, friend. Breathe with me.", "Peace be with you.", "Mm. A gentle poke. A gentle hello.",
              "I am here. Always.", "Shh... listen to the quiet.", "Hello. Slow down. You're doing fine."],
        hello=["Welcome. Breathe in, and let's learn.", "A calm mind learns best. Let's begin.",
               "Every lesson is a seed. Let's plant one."],
        cheers=["Wise answer.", "Correct. Calm and clear.", "Well seen.", "Yes. Peaceful and right.",
                "Your mind is sharp today.", "Beautiful."],
        oops=["A pebble on the path. Read the tip.", "Breathe. Look again.", "Every mistake is a teacher."],
        streaks={3: "3 in a row. Flowing like water.", 5: "5 in a row. Perfect focus.", 8: "8 in a row. True mastery."},
        win=["Well done. Your mind is strong.", "Peaceful victory.", "The lesson has taken root."],
        retry=["Breathe. Then try again.", "The tree grows slowly. Try once more.",
               "Patience. The answer will come."],
    ),
    Personality(
        "professor", "Professor", "Curious and full of fun facts", "glasses", ["book", "mug"], "Study the fix",
        idle=[
            "Fun fact: some of the oldest written laws are almost 4,000 years old.",
            "Did you know? Writing things down is the oldest way to remember them.",
            "Fascinating! Your records are beautifully organized.",
            "A good question is worth more than a quick answer.",
            "Fun fact: honey never spoils. Neither does good record-keeping.",
            "Hypothesis: a well-kept calendar prevents fines. Result: confirmed.",
            "Let's review: dates entered, reminders scheduled. Top marks.",
            "Did you know? Octopuses have three hearts. I have one, and it's full of facts.",
            "An ounce of prevention is worth a pound of cure. Benjamin Franklin said that.",
            "I'm reading about safety rules. Thrilling stuff, truly.",
            "Observation: you're doing an excellent job.",
            "Fun fact: bananas are berries, but strawberries aren't.",
            "Every rule exists because someone learned a lesson. Now you don't have to.",
            "Tip: each rule names where it comes from, if you're curious.",
            "Did you know? A group of owls is called a parliament. Very official.",
            "The scientific method: observe, record, review. Just like compliance.",
            "Knowledge is power. And power is knowing your deadlines.",
            "Class is in session. Today's lesson: you're great.",
            "Fun fact: a day on Venus is longer than its year. Your deadlines aren't. Luckily.",
            "Footnotes are the hidden treasures of documents.",
        ],
        alert=["A matter worth studying right away: {title}", "Pop quiz! This needs an answer: {title}",
               "My research shows a problem: {title}", "Interesting... and urgent: {title}",
               "Let's examine this carefully: {title}", "A lesson in progress: {title}"],
        clear=["Everything is in order. A+ work.", "Nothing to review. Excellent.", "All clear. Fascinating!",
               "No problems found. My hypothesis holds.", "Perfect score today.", "The data looks splendid."],
        fixed=["Correct solution! Gold star.", "Excellent reasoning. Problem solved.", "Textbook fix!",
               "Splendid! You've earned extra credit.", "Proven and solved. Well done."],
        poke=["Ah, a curious mind!", "Do you have a question? I love questions.", "Hello, student!",
              "Fun fact: you just poked a shield.", "Let me adjust my glasses... ah, hello!", "Office hours are always open."],
        hello=["Class is in session! Let's learn.", "Ah, a curious mind! Shall we begin?", "Today's lesson will be fascinating!"],
        cheers=["Precisely.", "Well reasoned.", "Correct, well done.", "Excellent.", "Top marks!", "A+ answer!"],
        oops=["An interesting choice. Let's see why.", "A useful mistake. Read on.", "Not quite. The note explains."],
        streaks={3: "Three correct in a row.", 5: "Five in a row. Impressive.", 8: "Eight in a row. Remarkable."},
        win=["Splendid. You've mastered this one.", "Gold star! Level complete.", "Excellent work, scholar."],
        retry=["Let's review the notes and try once more.", "Even great scientists repeat experiments. Again!",
               "A second attempt often teaches the most."],
    ),
]

PERSONALITIES = {p.key: p for p in PERSONALITY_LIST}
